### ISSUE TITLE
Unable to run the finetuning sample with transformers==4.36.0 version.

### ISSUE THREAD

**Issue by xiangyang-95** [intel-analytics/BigDL#10009]
Due to the requirements from mixtral that needs transformers==4.36.0, I tried to run the finetuning example but hit into error when I am trying this.

**Comment by xiangyang-95** [comment]
This is the error present: SafetensorError('device xpu is invalid')

**Comment by rnwang04** [comment]
Hi @xiangyang-95 , could you please share us your detailed code and your pip list so that we maybe can reproduce your errors : )

**Comment by rnwang04** [comment]
By the way, based on my experience, if you want to finetune mixtral, it would be better to use transformers==4.36.1 to avoid error in saving checkpoint.

**Comment by xiangyang-95** [comment]
Able to finetune after upgrading to transformers==4.36.1
