### ISSUE TITLE
Scala doc is incomplete?

### ISSUE THREAD

**Issue by xialeizhou** [intel-analytics/BigDL#1005]
scala tutorial is so pool~ 

for example, i've no idea how to use `ParallelTable`, `JoinTable` with `DistriOptimizer`...

If it's a stable project, pls add more tutorials and examples.

we've no time to waste reading your test cases, source code, torch tutorials just to **guess** how to use these elements. 

It is an extremely poor user experience!!!

**Comment by yiheng** [comment]
Hi @xialeizhou 

Thanks for raising this. Documentation is definitely an important recent work. We're preparing a documentation website.

**Comment by yiheng** [comment]
@xialeizhou Some existing documentation

wiki: https://github.com/intel-analytics/BigDL/wiki
scala-doc: https://www.javadoc.io/doc/com.intel.analytics.bigdl/bigdl/0.1.0-doc

**Comment by jason-dai** [comment]
We just make the documentation website for BigDL available  at https://bigdl-project.github.io/; currently most of its contents come from the project wiki; we will add more documents (esp. for APIs) in the coming weeks.

**Comment by xialeizhou** [comment]
thanks for your answer.

**Comment by yiheng** [comment]
The document website has updated. https://bigdl-project.github.io/

If you have any comments, please let us know:)
