### ISSUE TITLE
llama2-7b inference with fp16 precision issue about text generation

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/BigDL#10103]
i installed bigdl-llm=2.5.0b20240205, and inference with fp16 precision, the generation has some issue as below:
model = AutoModelForCausalLM.from_pretrained(model_path,
                                                 load_in_low_bit='fp16',
                                                 device_map = "xpu",
                                                 optimize_model=True,
                                                 trust_remote_code=True,
                                                 use_cache=True)
the output is less than torch_dtype=torch.float16:
![image](https://github.com/intel-analytics/BigDL/assets/99886928/af3ba5f8-e306-4d73-8642-5ffb6d114948)

**Comment by rnwang04** [comment]
Based on below code, the output is normal:
```python
from bigdl.llm.transformers import AutoModelForCausalLM
model_path = 'meta/Llama-2-7b-chat-hf'
model = AutoModelForCausalLM.from_pretrained(model_path,
                                                 load_in_low_bit="fp16",
                                                 torch_dtype=torch.float16,
                                                 optimize_model=True,
                                                 trust_remote_code=True,
                                                 use_cache=True)
```

```bash
[INST] <<SYS>>

<</SYS>>

What is AI? [/INST]  Artificial intelligence (AI) refers to the development of computer systems that can perform tasks that typically require human intelligence, such as learning, problem-sol
```

Hi @Fred-cell , what's your model is and could you please test it again based on above usage ?
If you still meet this issue, could you please share detailed code so that we can reproduce it ?

**Comment by Fred-cell** [comment]
please add guide in each model about precision usage.

**Comment by Fred-cell** [comment]
> Llama-2-7b-

I used llama2-7b-chat-hf:
python generate.py --repo-id-or-model-path ~/LLM/llama-2-7b-hf/ --n-predict 512 --prompt "It is done..."

**Comment by hkvision** [comment]
> please add guide in each model about precision usage.

For the non-chat model, you are recommended to remove the prompt template and directly input the sentence.

**Comment by hkvision** [comment]
Let's add default dtype when load_in_low_bit=fp16. @lalalapotter

**Comment by hkvision** [comment]
Synced with @Fred-cell the problem gets resolved after using the chat model.
And we have add better implementation for fp16. Closing this issue.
