### ISSUE TITLE
What happened to the WebUI?

### ISSUE THREAD

**Issue by opticblu** [intel-analytics/BigDL#10143]
I did a git pull to bring in some of the new updates and it appears that WebUI is gone entirely

Is this being deprecated? If so, is there a suggested replacement?

Thanks

**Comment by jason-dai** [comment]
We plan to move it to a separate repo, which may take some time.

**Comment by opticblu** [comment]
Thanks for the reply

A 16g VRAM card under $300 is very desirable to consumers looking to explore AI, I think an easily deployable webUI like this is a great showcase

BigDL is progressing… uh… bigly! Keep up the great work :)

**Comment by jason-dai** [comment]
We have moved the WebUI support to https://github.com/intel-analytics/text-generation-webui
