### ISSUE TITLE
Can BigDL run on the windows local?

### ISSUE THREAD

**Issue by lawlietAi** [intel-analytics/BigDL#1020]
I'm using IDEA to develop the spark program **on windows local**
so for convenience i also hope to run bigDL program on windows.
but there are some methods missed when i attempt to run the model **Aotuencoder**.
i have added the jars of **spark-2.10-2.11** and download the bigDL's jars from maven.
what had i downloaded the bigDL dependencies from maven is 
**com.intel.analytics.bigdl:bigdl-SPARK_2.1:0.1.1-SNAPSHOT2**
should i download another jars?  
plz help me thank you

**Comment by qiuxin2012** [comment]
Sorry, windows is unsupported right now, but will be supported in the future.
Please use linux or mac, thanks.

**Comment by lawlietAi** [comment]
i see,thanks.await the windows version!

**Comment by yiheng** [comment]
@lawlietAi I have uploaded mkl_win64.jar to maven. You can use the new added profile win64 to use it. Please give a try and let me know if there's any issue.

```bash
mvn clean package -DskipTests -P win64
```

or select the win64 profile in the IDE.
