### ISSUE TITLE
Missing parameter list in python

### ISSUE THREAD

**Issue by 122689305** [intel-analytics/BigDL#1029]
Since some new parameters are added into scala files, the corresponding parameter lists are not appended into python files. For example, the class Linear.

**Comment by shane-huang** [comment]
Missing parameter "squeeze" in python API in following layers. 
1) Sum
2) Mean

What's wierd is, Mean accepts only 2 arguments besides bigdl_type. when I use Mean(2,1,True), it runs without any errors.

**Comment by shane-huang** [comment]
DiceCoefficientCriterion missing default paramter values in python (scala has default values)

**Comment by yangw1234** [comment]
fixed `Linear`, `SpatialConvolution`, `DiceCoefficientCriterion`, `Mean`, `Sum`.
