### ISSUE TITLE
HuatuoGPT-7B need to optimize performance about First token latency (ms) and After token latency (ms/token) 

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#10333]
Hi 

HuatuoGPT-7B need to optimize performance about First token latency (ms) and After token latency (ms/token) 

https://github.com/FreedomIntelligence/HuatuoGPT
and https://huggingface.co/FreedomIntelligence/HuatuoGPT-7B
MTL 155H 32GB 7467MHz
<img width="530" alt="image" src="https://github.com/intel-analytics/BigDL/assets/102839943/87a9127c-059f-4d14-8712-479f737f7bb4">

**Comment by jason-dai** [comment]
This seems to be based on Baichuan architecture @hkvision ?

**Comment by hkvision** [comment]
> This seems to be based on Baichuan architecture @hkvision ?

Check the config and seems it matches our optimizations for Baichuan1 (will optimize attention and rmsnorm).

**Comment by KiwiHana** [comment]
Sorry， we get this performance without plug-in. When device plug-in, the After token latency (ms/token) is about 50~60 ms/token
