### ISSUE TITLE
Baichuan2-7B takes more memory than chatglm3-6B on MTL 16GB device, need to optimize VRAM of Baichuan2-7B

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#10332]
MTL 165H 16GB 6400MHz, GPU Driver: 31.0.101.5124 
<img width="481" alt="image" src="https://github.com/intel-analytics/BigDL/assets/102839943/0fcd7eb4-f5d2-491e-b724-5c3c0aa3b567">

oneapi 2024.0

**Comment by qiuxin2012** [comment]
You can use fp16 model to save more memory, convert model to fp16 before to xpu, like:
```
model = model.half().to('xpu')
```
This can save 700MB for 1024 tokens, 1400MB for 2048 tokens.

**Comment by qiuxin2012** [comment]
If you can change the modeling file, you can empty xpu cache after https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/ea66ced17780ca3db39bc9f8aa601d8463db3da5/modeling_baichuan.py#L698
Like:
```
if hidden_states.device.type == "xpu" and hidden_states.size(1) != 1:
    torch.xpu.empty_cache()
```
https://github.com/intel-analytics/BigDL/pull/10317 is working on the empty, but it's still testing. This can decrease the peak memory about 600MB.

Another unused memory is the sin_cache and cos_cache in https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/main/modeling_baichuan.py#L109, about 153MB cached on cpu. You can remove them.

**Comment by biyuehuang** [comment]
It work, thanks!
<img width="464" alt="image" src="https://github.com/intel-analytics/BigDL/assets/31006098/b0636d17-055e-41d1-9d19-22d01d0a5749">

**Comment by KiwiHana** [comment]
Thanks Qiu,Xin!
