### ISSUE TITLE
Running minicpm failed

### ISSUE THREAD

**Issue by zkh2016** [intel-analytics/BigDL#10342]
Hello, I want to use Bigdl to run Minicpm, but I encountered some issues. Here is my test code and environment information. Could you please help me check this error message.

**code:**
```
from transformers import LlamaTokenizerFast, LlamaForCausalLM
from bigdl.llm import optimize_model

import torch
torch.manual_seed(0)

model_path = "openbmb/MiniCPM-2B-dpo-bf16-llama-format"
tokenizer = LlamaTokenizerFast.from_pretrained(model_path)


model = LlamaForCausalLM.from_pretrained(model_path, torch_dtype='auto', low_cpu_mem_usage=True)
model = optimize_model(model) # With only one line to enable BigDL-LLM INT4 optimization
model = model.to('xpu') # Important after obtaining the optimized model

prompt="Now you act like a terminal situated within a beginner's C++ practice repository folder, please provide the output for the command: `ls -l`"
input_ids = tokenizer.encode("<用户>{}<AI>".format(prompt), return_tensors='pt', add_special_tokens=True)
input_ids = input_ids.to('xpu')
responds = model.generate(input_ids, temperature=0.3, top_p=0.8, repetition_penalty=1.02, max_length=1024)
responds = tokenizer.decode(responds[0], skip_special_tokens=True)
print(responds)

```

**error:**
![image](https://github.com/intel-analytics/BigDL/assets/24504497/c2432bf5-92f0-473c-9fc0-7920264317d4)

**env:**
1. Python 3.9.18
2. transformers 4.31.0
3. windows11
4. Intel(R) Core(TM) Ultra 7 155H   1.40 GHz

**Comment by MeouSker77** [comment]
Could you check whether this file `"C:\Program Files (x86)\Intel\oneAPI\compiler\latest\bin\libsycl-fallback-bfloat16.spv"` exists?

And make sure you have executed `call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"` before running your python script

**Comment by zkh2016** [comment]
> Could you check whether this file `"C:\Program Files (x86)\Intel\oneAPI\compiler\latest\bin\libsycl-fallback-bfloat16.spv"` exists?

 I checked and found that this file exists

> And make sure you have executed `call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"` before running your python script
Yes，I have executed this command.

**Comment by MeouSker77** [comment]
we'll fix this issue as soon as possible, for now, you can executed this command 
`set BIGDL_QUANTIZE_KV_CACHE=1` before running your python script to work around this error

**Comment by zkh2016** [comment]
> we'll fix this issue as soon as possible, for now, you can executed this command `set BIGDL_QUANTIZE_KV_CACHE=0` before running your python script to work around this error

ok, thanks.
