### ISSUE TITLE
python api only supports ndarray or list of ndarry; it does not support nested data type. 

### ISSUE THREAD

**Issue by JerryYanWan** [intel-analytics/BigDL#1036]
In MixtureTable layer, the input format is:
input = Table(Tensor, Table(Tensor, Tensor, Tensor))
There is no corresponding datatype in python api.

Should we flatten these input to Table(Tensor, Tensor, Tensor, Tensor) in scala code?

**Comment by zhichao-li** [comment]
In keras, the input for forward is either a ndarray or list of ndarray. I think we should follow that style and get rid of `Table` in the end. Ideally, we should only allow tensor or list of tensor in BigDL.

**Comment by zhichao-li** [comment]
cc @shane-huang

**Comment by SeaOfOcean** [comment]
In FlattenTable, the input is a nested table with any depths, seems cannot be support in python

```
module = FlattenTable()
t1 = np.random.randn(3)
t2 = np.random.randn(3)
t3 = np.random.randn(3)
input = [t1, [t2, [t3]]]
module.forward(input)
```

This nested table can be generated by a nested ConcatTable

**Comment by SeaOfOcean** [comment]
As suggested by @zhichao-li , we can test the python layer with nested table input by making use of some containers. i.e. generate table from some other layers.

For example,

```python
module = Sequential()
nested = ConcatTable().add(Identity()).add(Identity())
module.add(nested).add(ModuleYouWantToTest)
```
