### ISSUE TITLE
Lack create method in python layers

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#1040]
Lack create method in python layers such as 

```
class Const(Model)
class Fill(Model)
class Pack(Model)
class Shape(Model)
class SplitAndSelect(Model)
class StrideSlice(Model)
```

**Comment by zhichao-li** [comment]
have you upgrade to latest code? just checkthose layers have been added into master branch.

**Comment by zhichao-li** [comment]
https://github.com/intel-analytics/BigDL/pull/957  we need to add unittest for those new added layers and also change the base class from ```Model``` to ```Layer```
