### ISSUE TITLE
qwen1.5模型使用bigdl量化之后，模型推理效果非常差，并且模型如果迁移到cuda，就会报错：段错误（核心已转储)

### ISSUE THREAD

**Issue by lishu2006ll** [intel-analytics/BigDL#10428]
测试代码如下:
<img width="833" alt="image" src="https://github.com/intel-analytics/BigDL/assets/3477402/50baa958-d065-4f3b-ba06-18045f16533a">
<img width="964" alt="image" src="https://github.com/intel-analytics/BigDL/assets/3477402/7074787a-277d-40e3-bcb5-f0c1c782d5fd">

**Comment by Uxito-Ada** [comment]
Hi @lishu2006ll , bigdl-llm is towards Intel hardware and does not support CUDA. As for the performance issue, which platform did your run it on, and any detail data about the latency?

**Comment by lishu2006ll** [comment]
> Hi @lishu2006ll , bigdl-llm is towards Intel hardware and does not support CUDA. As for the performance issue, which platform did your run it on, and any detail about the latency and output?

If I use BigDL.LLM to load the Qwen model through quantization, it will either throw an error for the Q&A issue, or not respond with any content, when I use cpu ,
can test it!

**Comment by Uxito-Ada** [comment]
> > Hi @lishu2006ll , bigdl-llm is towards Intel hardware and does not support CUDA. As for the performance issue, which platform did your run it on, and any detail about the latency and output?
> 
> If I use BigDL.LLM to load the Qwen model through quantization, it will either throw an error for the Q&A issue, or not respond with any content, when I use cpu , can test it!


Hi, @lishu2006ll , it is found that no `load_in_low_bit`/`load_in_4_bit`/`optimize_model` is set when `from_pretrained` in your codes, and in that way you are using the native huggingface transformers without any quantization or optimization.


With codes [here](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/CPU/HF-Transformers-AutoModels/Model/qwen1.5#qwen15), where `load_in_4_bit=True` and `max_new_tokens` set to 512, I got the below output:
```bash
-------------------- Prompt --------------------
给出一段hive的sql脚本，计算学生总成绩！
-------------------- Output --------------------
假设我们有一个名为"students"的表，其中包含字段"student_id", "subject1_score", "subject2_score", "subject3_score"（每个学生有三个科目），我们可以使用SUM函数来计算每个学生的总成绩。以下是一个简单的Hive SQL脚本：

SELECT student_id, SUM(subject1_score + subject2_score + subject3_score) as total_score
FROM students
GROUP BY student_id;

这个脚本首先将每个学生的三个科目的分数相加，然后通过GROUP BY语句按学生ID分组，这样每个学生的总成绩就会单独列出来。

如果你的表结构不同，你需要根据你的实际情况调整这个查询，例如，如果科目分数存储在一个单独的表中，或者分数是通过JOIN操作获取的，那么查询可能会更复杂。
```


After removing `load_in_4_bit=True`, and setting `torch_dtype="auto"` and `device_map="auto"`, native huggingface outputs the below:
```bash
-------------------- Prompt --------------------
给出一段hive的sql脚本，计算学生总成绩！
-------------------- Output --------------------
假设我们有一个名为"students"的表，其中包含以下字段：student_id（学生ID），subject1_score（第一门课成绩），subject2_score（第二门课成绩），subject3_score（第三门课成绩）。你可以使用以下Hive SQL脚本来计算每个学生的总成绩：

SELECT student_id, (subject1_score + subject2_score + subject3_score) AS total_grade
FROM students;

这个查询会返回一个表，其中每一行包含一个学生ID和他们的总成绩。

如果你的表结构不同，你需要根据你的实际字段来调整这个查询。例如，如果你的科目分数存储在一个名为"grades"的表中，那么查询可能看起来像这样：

SELECT s.student_id, g.subject_score * 3 AS total_grade
FROM students s
JOIN grades g ON s.student_id = g.student_id;

这里假设每个科目有3分，如果你的分数不是3的倍数，你可能需要进行一些额外的计算来确保总分正确。
```


Thus, which version of torch/transformers/bigdl-llm/intel_extension_for_pytorch is used in your environment? I recommend to follow the document [here](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/CPU/HF-Transformers-AutoModels/Model/qwen1.5#qwen15) to launch a validation.
