### ISSUE TITLE
init_orca_context failed because of wrong spark-submit args

### ISSUE THREAD

**Issue by piekill** [intel-analytics/BigDL#10431]
https://github.com/intel-analytics/BigDL/blob/77e9ef1221e175e858340f03fe67c4d90327d2c6/python/dllib/src/bigdl/dllib/nncontext.py#L770

Looks to me that we need a white space here:

`os.environ["BIGDL_JARS"] + ' ' + submit_args[start:]`

otherwise we will get "Error: Missing application resource"

**Comment by hkvision** [comment]
Correct, thanks for pointing out! Will fix it.
