### ISSUE TITLE
use "pip install --pre --upgrade bigdl-llm[xpu]" problems

### ISSUE THREAD

**Issue by aoke79** [intel-analytics/BigDL#10443]
Dear,
when I used command "pip install --pre --upgrade bigdl-llm[xpu]" to update bigdl environments with PRC mirror, it will download many version of bigdl, not sure why. Might you please help check that? I've attached the capture.
thanks a lot,
![Screenshot 2024-03-18 101727](https://github.com/intel-analytics/BigDL/assets/7357656/1fe4892f-13f9-4005-8f76-97c7055927b7)

**Comment by hkvision** [comment]
Same issue as https://github.com/intel-analytics/BigDL/issues/9522
Please check this page for more details: https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#id3
