### ISSUE TITLE
Parameters differ between python and scala API in SpatialConvolution and SpatialFullConvolution

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1056]
Below issue exists for SpatialConvolution and SpatialFullConvolution. 

- initGradWeight, initGradBias does not exist in python API. 
- initBias, initWeight are seperated but python API uses only init_method. 
- wRegularizer, bRegularizer does not exist in python API

```scala
val m = SpatialConvolution[Double](nInputPlane,nOutputPlane,kernelW,kernelH,strideW,strideH,padW,padH,nGroup,propagateBack,wRegularizer,bRegularizer,initWeight, initBias, initGradWeight, initGradBias) 
```

```python
m = SpatialConvolution(n_input_plane,n_output_plane,kernel_w,kernel_h,stride_w=1,stride_h=1,pad_w=0,pad_h=0,n_group=1,propagate_back=True,init_method="default")
```

**Comment by yangw1234** [comment]
I can remove the `init_method` parameter from the python constructor to be compatible with scala api (using the `set_init_method` only ).

As for  `initWeight`, `initBias`, `initGradWeight` and `initGradBias`, they are introduced to enable weight sharing in Graph. Not really sure whether they should go into the python api. @yiheng what do you think?

 And pr #1008 has already fixed the python regularizer issue.
