### ISSUE TITLE
SpatialShareConvolution lack of api docs and unit test

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1062]
API docs (both scala and python) and unit test (scala) are missing for SpatialShareConvolution.

**Comment by JerryYanWan** [comment]
API docs include the Scala and python examples for SpatialShareConvolution

**Comment by JerryYanWan** [comment]
The Unit tests are included in bigdl

**Comment by qiuxin2012** [comment]
fixed in #1144
