### ISSUE TITLE
API DOC: The name `Merge Layer` in doc is a little confused. Add additional Table layer? 

### ISSUE THREAD

**Issue by psyyz10** [intel-analytics/BigDL#1090]
I cannot catch the idea of `Merge Layer`, does it mean every combining? such as Add, CAdd, CMult, Concat, JoinTable and so on. If the idea is like that, do we need a `Split Layer` too? I know there is a merge layer category in Keras, however keras's api is very different from ours. For example `Concat` can be classified into both `Container Layer` and `Merge Layer`.

Additionally we have table layers, so do we need a new category `Table Layers`?

**Comment by shane-huang** [comment]
In my understanding, Concat just concats several  without aggregation. Actually you still can use Select to split the result back into original input if you like.  However,  Merge operations is usually not reversable from output. e.g. if you add A+B = C, you don't know A and B from only C.

**Comment by shane-huang** [comment]
AFAIK, Table layers are just those layers which accept table input (or output a table?). Some layers may accept table as input but does not have table in the name. Do we really need a seperate layer category for that?

**Comment by shane-huang** [comment]
For now, I think we can just put any layer that inherits the Container in the Container folder.

**Comment by shane-huang** [comment]
I created a Merge / Split layers for those merge several intput (table) into one or split inputs into tables. And for those that inherits Container (which means they can add layers), I will put them into Container folder. 

Are you okay with that?

**Comment by shane-huang** [comment]
categories are now confirmed. close this issue.
