### ISSUE TITLE
need implicit conversion from Double to Float in Tensor/Storage interfaces

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1123]
Use `val target = Tensor(Storage(Array(2.0, 1.0)))` in below example code throws error - 2.0 should be written as 2.0f. It is a little bit inconvinient. If we expect user to use Float type by default, we should make it more convinient for user to create Float data structure. Similiar issue exists with Tensor.fill. 

```scala
import com.intel.analytics.bigdl.tensor.TensorNumericMath.TensorNumeric.NumericFloat
import com.intel.analytics.bigdl.nn._
import com.intel.analytics.bigdl.tensor._
import com.intel.analytics.bigdl.tensor.Storage

val input = Tensor(2).randn()
val target = Tensor(Storage(Array(2.0f, 1.0f)))
val loss = DistKLDivCriterion()
val output = loss.forward(input,target)
val grad = loss.backward(input,target)
```

**Comment by yiheng** [comment]
You can init the tensor like this
```scala
val target = Tensor(T(2.0f, 1.0f))
```

I think it's doable to init a **float** tensor with
```scala
val target = Tensor(T(2.0, 1.0))
```

We can convert it in the constructor.
