### ISSUE TITLE
Support run BigDL-Tutorials with pip install BigDL

### ISSUE THREAD

**Issue by dding3** [intel-analytics/BigDL#1135]
After using pip to install BigDL, current BigDL-Tutorials guidance cannot work for running notebooks in juptor. We need find a way to resolve that and update the guidance.

**Comment by zhichao-li** [comment]
We need to update BigDL-Tutorial master branch to support BigDL 0.2.0 as well

**Comment by zhichao-li** [comment]
Here's how to launch jupyter locally after the pip install.
export SPARK_HOME= path to spark 2.x
 
pip install BigDL==0.1.1rc0
 
jupyter notebook --notebook-dir=./  --ip=* --no-browser
 
NOTE:
1) you might need to create spark context by yourself as we doesn’t start jupyter via pyspark in the previous steps
2) pip install is for local mode only.
 
from bigdl.util.common import *
sc = get_spark_context()

**Comment by Lowpassfilter** [comment]
I have finished the new tutorial, and it may take some time to upload it. What's the problem? Maybe I can solve it now.

**Comment by helenlly** [comment]
need add docs
