### ISSUE TITLE
TimeDistributed should inherit Container interface

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1153]
By definition, it contains another layers and applies the contained layer to each input slice.  Looks like it should be a Container type.

**Comment by JerryYanWan** [comment]
There are two differences.
1. The container will use add method to include the contained layer. TimeDistributed layer will use constructor to include layer. 
2. The container can add more than 1 layer. TimeDistributed layer will only accept 1 layer.

**Comment by shane-huang** [comment]
Comments accepted.
