### ISSUE TITLE
Support both deep and shallow copy in cloneModule()

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#1173]
We should make sure that user always use Support both deep and shallow copy in cloneModule()

**Comment by wzhongyuan** [comment]
@jason-dai   Just to clarify, does "shallow" mean for weight and bias, we don't copy, just use original module ones ?  Besides these, all other data are done with deep copy ?

**Comment by jason-dai** [comment]
Yes - shallow means sharing weight & bias.

**Comment by wzhongyuan** [comment]
@jason-dai  This could be implemented based on my current serialization approach. 
the basic idea is to change the serialization related interfaces to add a flag say 'copyWeightAndBIas' , which has a default value as true to make it transparent to normal model serialization/deserialization.

trait Loadable {

  def loadModule[T: ClassTag](model : BigDLModule, copyWeightAndBias : Boolean = true)
                             (implicit ev: TensorNumeric[T]) : ModuleData[T]
}
trait Savable {

  def serializeModule[T: ClassTag](module : ModuleData[T], copyWeightAndBias : Boolean = true)
                                  (implicit ev: TensorNumeric[T]) : BigDLModule
}

And inside the cloneModule(),  use protobuf format as inter-media to get a copy without weight and bias copied. then re-assign the weight and bias storage references to original ones using parameter tables.

I'll give it a try today.
