### ISSUE TITLE
For the Convolutions Python API,  the `initMethod` attributes may need to be removed.

### ISSUE THREAD

**Issue by psyyz10** [intel-analytics/BigDL#1183]
For all the Convolutions Python API,  the `initMethod` attributes may need to be removed, as well as `create**Convolution**()` methods. I did not find anywhere it was used.

**Comment by yangw1234** [comment]
Does master branch still have this problem? It's supposed to be fixed already.

**Comment by yiheng** [comment]
then please close it.

**Comment by yangw1234** [comment]
checked again, master does not have this problem. Closing it.
