### ISSUE TITLE
No bigdl.sh file after building

### ISSUE THREAD

**Issue by hausofliufeng** [intel-analytics/BigDL#1197]
I've tried several times using different versions of spark and scala, I just can't see the bigdl.sh file in /dist/bin folder after buiding. Then a friend of mine suggests I use the branch-0.1 instead of master when cloning repository. It worked out. 
I thought maybe mentioning this in the README.md file isn't a bad idea.
PS: When you can't see the /dist/bin/bigdl.sh script, use a different branch.

**Comment by yiheng** [comment]
Hi, @hausofliufeng. The bigdl.sh is no needn't in the master. It only takes effect in the older version.

I think the documents on wiki has removed all bigdl.sh references.
