### ISSUE TITLE
Missing md docs for Module

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1203]
Describe below functionalities. 
- load
- save
- predict
- evalute
- etc.

Update docs/docs/APIdocs/Model/ModuleAPI.md

**Comment by shane-huang** [comment]
Python is Layer instead of Module in Scala. Do we need to make them sync?

**Comment by wzhongyuan** [comment]
@shane-huang  sure, I will add a MD doc for this one. Currently I am working on the new serialization method, I will create one based on current master and refine it in future if needed once my change is in.
