### ISSUE TITLE
Cannot use gpu

### ISSUE THREAD

**Issue by yuyalun-allen** [intel-analytics/BigDL#12152]
Hello developers! I'm trying to run ollama on my intel iGPU, and I set up the environment as follows, but ollama still runs on CPU.

1. Update GPU driver from intel
![image](https://github.com/user-attachments/assets/d49acefc-5272-48bb-9f62-adfe5fde98a3)
2. (suggested by [intel](https://www.intel.com.tw/content/www/tw/zh/content-details/826081/running-ollama-with-open-webui-on-intel-hardware-platform.html) )install oneAPI toolkit
3. create venv and install ipex-llm[cpp]
![image](https://github.com/user-attachments/assets/bd894f87-970b-48cf-8544-b8308053e235)
4. initialize it with init-ollama
![image](https://github.com/user-attachments/assets/d1b00cee-752c-4721-a30e-cd1952fd5169)
5. run it with following env
![image](https://github.com/user-attachments/assets/ac783593-c570-4268-b75e-914230c9bb28)

but it turned out still run ollama on CPU if I understand the output correctly.
![image](https://github.com/user-attachments/assets/c0149caa-7374-4fed-9cc1-41d88ae78f40)

How to solve this?

**Comment by user7z** [comment]
@yuyalun-allen that does not mean it runs on cpu , it will always use cpu , but just the serving service i.e ollama serve , to know if it runs on gpu you have to first run a model.and go ro task manager to see if the igpu is  bieng used , that if the model runs witbout any issue

**Comment by yuyalun-allen** [comment]
Okay, then it seems that I ran into another problem.
When I run the system ollama, it works fine, but on cpu, rather than gpu.
![image](https://github.com/user-attachments/assets/87a88566-2344-479b-aed4-23116b964b5b)

then when I use ollama.exe in generated by ipex-llm, then the program crash (It seems that some dll file is missing).
![image](https://github.com/user-attachments/assets/013092c0-8956-4524-b546-27847e01309a)

**Comment by user7z** [comment]
@yuyalun-allen you need to understand that ollama well always run on cpu , but when you run a model , the ollama that is runing on the cpu well use the gpu for the model , that what accelersting ollama by thr gpu means , how to know if the gpu is utiliezed or know , you should see task manager.

Did you follow the guide correctlly ?

**Comment by yuyalun-allen** [comment]
alright I got to know that ollama will always use cpu and use gpu to accelerate. And I am still not clear with what ` init-ollama.bat` do to generate a `ollama.exe` file under current directory, since the guide says on windows we should still run `ollama serve` rather than `.\ollama.exe serve` (and those 2 command have exactly different effects, the latter one cause ollama to crash).  So if we just call system ollama then why do we need `init-ollama.bat`? Thanks for your help!

**Comment by user7z** [comment]
Every thing that uses the gpu well use also cpu , you cant skip the cpu entirelly.
Yeah those guys here really have slpit docs there & there there not orgnized in friendlly way , iam glad it helped , have a nice day
