### ISSUE TITLE
How to save model in BigDL with python?

### ISSUE THREAD

**Issue by zhpmatrix** [intel-analytics/BigDL#1223]
I have try joblib and pickle in sklearn, but they don't work! And I check code to find the API as loadWeights(), but are there some functions to save/load model in BigDL with python?if not, how to package the code with Scala to use in python?

**Comment by qiuxin2012** [comment]
I find some test code for you. @zhpmatrix 
```
        fc1 = Linear(4, 2)
        fc1.set_weights([np.ones((4, 2)), np.ones((2, ))])
        tmp_path = tempfile.mktemp()
        fc1.save(tmp_path, True)
        fc1_loaded = Model.load(tmp_path)
```

**Comment by zhpmatrix** [comment]
TKS! @qiuxin2012  But I haven't solve my problem.

I have read the code in repo, in current version, the class Linear extends from class Layer which has method as save(). but in Python3.5 environment, I can't find the class Layer, as the code shows, class Layer maybe has been changed to class Model without method as save(). 

So I add the save() method from the class Layer to the class Model in Python3.5, but I got the error as follows:

py4j.protocol.Py4JError: An error occurred while calling o45.modelSave. Trace:
py4j.Py4JException: Method modelSave([class com.intel.analytics.bigdl.nn.Sequential, class java.lang.String, class java.lang.Boolean]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:272)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:128)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:211)
	at java.lang.Thread.run(Thread.java:748)

How to add this function to save model?(it's really sad!!!)

**Comment by qiuxin2012** [comment]
@zhichao-li Please help.

**Comment by jason-dai** [comment]
Are you running BigDL 0.1 release or the master (0.2-snapshot) code? The save method is newly added in the master (0.2-snapshot).

Instead of explicitly saving the mode, you can actually checkpoint the model periodically during training; see https://bigdl-project.github.io/latest/#getting-started/#stop-and-resume-a-training
