### ISSUE TITLE
I met a problem when building the BigDL

### ISSUE THREAD

**Issue by Mr-quan** [intel-analytics/BigDL#1240]
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] compiler plugin: BasicArtifact(org.scalamacros,paradise_2.10.5,2.0.1,null)
[INFO] Compiling 6 Java sources to /root/BigDL/BigDL/target/classes...
[ERROR] /root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/DecorationUtils.java:22: error: package org.codehaus.plexus.util does not exist
[ERROR] import org.codehaus.plexus.util.StringUtils;
[ERROR]                                ^
[ERROR] /root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/inheritance/DecorationModelInheritanceAssembler.java:22: error: cannot find symbol
[ERROR] import org.apache.maven.doxia.site.decoration.DecorationModel;
[ERROR]                                              ^
[ERROR]   symbol:   class DecorationModel
[ERROR]   location: package org.apache.maven.doxia.site.decoration
[ERROR] /root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/inheritance/DecorationModelInheritanceAssembler.java:56: error: cannot find symbol
[ERROR]     void assembleModelInheritance( String name, DecorationModel child, DecorationModel parent,
[ERROR]                                                 ^
[ERROR]   symbol:   class DecorationModel
[ERROR]   location: interface DecorationModelInheritanceAssembler
[ERROR] /root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/inheritance/DecorationModelInheritanceAssembler.java:56: error: cannot find symbol
…………
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project bigdl-parent: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile failed.: CompileFailed -> [Help 1]

something like that
Did anyone meet this problem?

**Comment by yiheng** [comment]
/root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/DecorationUtils.java

is this your own file?

**Comment by Mr-quan** [comment]
No. I downloaded it online 
发自网易邮箱大师
On 07/17/2017 10:56, Ian Wong wrote: /root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/DecorationUtils.java
is this your own file?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/intel-analytics/BigDL","title":"intel-analytics/BigDL","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/intel-analytics/BigDL"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yiheng in #1240:  /root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/DecorationUtils.java\r\n\r\nis this your own file?"}],"action":{"name":"View Issue","url":"https://github.com/intel-analytics/BigDL/issues/1240#issuecomment-315659446"}}}

**Comment by yiheng** [comment]
In BigDL, there's no such file. Where do you download it?

/root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/DecorationUtils.java

**Comment by Mr-quan** [comment]
When I built BigDL, it appeared a error "can't find a file xxxx". Then I search that and download it.
发自网易邮箱大师
On 07/17/2017 11:02, Ian Wong wrote: In BigDL, there's no such file. Where do you download it?
/root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/DecorationUtils.java

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/intel-analytics/BigDL","title":"intel-analytics/BigDL","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/intel-analytics/BigDL"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yiheng in #1240: In BigDL, there's no such file. Where do you download it?\r\n\r\n/root/BigDL/BigDL/src/main/java/org/apache/maven/doxia/site/decoration/DecorationUtils.java"}],"action":{"name":"View Issue","url":"https://github.com/intel-analytics/BigDL/issues/1240#issuecomment-315659877"}}}

**Comment by yiheng** [comment]
I don't think you need to download extra java files. What's the specific error message for the
> When I built BigDL, it appeared a error "can't find a file xxxx"

**Comment by Mr-quan** [comment]
oh～get it. I try to download BigDL again
发自网易邮箱大师
On 07/17/2017 11:40, Ian Wong wrote: I don't think you need to download extra java files. What's the specific error message for the

When I built BigDL, it appeared a error "can't find a file xxxx"


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/intel-analytics/BigDL","title":"intel-analytics/BigDL","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/intel-analytics/BigDL"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yiheng in #1240: I don't think you need to download extra java files. What's the specific error message for the\r\n\u003e When I built BigDL, it appeared a error \"can't find a file xxxx\""}],"action":{"name":"View Issue","url":"https://github.com/intel-analytics/BigDL/issues/1240#issuecomment-315662702"}}}
