### ISSUE TITLE
Update python document

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#1259]
Install (https://github.com/intel-analytics/BigDL/blob/master/docs/docs/PythonSupport/python-install.md): need to specify how to get Spark and how to set the ENV variables

Run (https://github.com/intel-analytics/BigDL/blob/master/docs/docs/PythonSupport/python-run.md): please update (e.g., no bigdl.sh)

**Comment by shane-huang** [comment]
Need also specify the limitations of pip install:
- pip only supports certain version
- pip install can not be on cluster deployment

**Comment by shane-huang** [comment]
Python examples also needs to update to use 2.0 API. 
`optim_method="Adagrad"` should became `optim_method=Adagrad ()`
```
optimizer = Optimizer(
    model=build_model(news20.CLASS_NUM),
    training_rdd=train_rdd,
    criterion=ClassNLLCriterion(),
    end_trigger=MaxEpoch(max_epoch),
    batch_size=batch_size,
    optim_method="Adagrad",
    state=state)
...
train_model = optimizer.optimize()
```

**Comment by shane-huang** [comment]
Maybe also revise the navigation layout

**Comment by jason-dai** [comment]
And update how to pack python dependency for YARN

**Comment by JerryYanWan** [comment]
https://bigdl-project.github.io/latest/#PythonSupport/python-install/
In "Install BigDL-0.2.0-snapshot", command typo:
should be
`wget https://d3kbcqa49mib13.cloudfront.net/spark-1.6.3-bin-hadoop2.6.tgz`
