### ISSUE TITLE
Can't find bigdl.sh

### ISSUE THREAD

**Issue by bigdataexplorer** [intel-analytics/BigDL#1278]
When I tried to run the bootstrap.sh script, it complained about not finding https://raw.githubusercontent.com/intel-analytics/BigDL/master/scripts/bigdl.sh 
I checked the repo but can't find the bigdl.sh script

**Comment by qiuxin2012** [comment]
We have removed bigdl.sh in the latest code. The default mkl environment variable will be set while loading BigDL-core.
