### ISSUE TITLE
BigDL model Download link is wrong

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#1288]
Currently BigDL model Download link is wrong for all spark versions.

https://oss.sonatype.org/content/groups/public/com/intel/analytics/bigdl/dist-spark-1.5.1-scala-2.10.5-linux64/0.2.0-SNAPSHOT/

should be

https://oss.sonatype.org/content/groups/public/com/intel/analytics/bigdl/bigdl-SPARK_1.5/0.2.0-SNAPSHOT/

**Comment by yiheng** [comment]
it's not wrong. Download zip package is not artifacts
