### ISSUE TITLE
Link error in python doc Example link

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/BigDL#1294]
The examples in the python document should not point to the master branch(should use the release branch) since the master branch will keep evolving.

https://bigdl-project.github.io/master/#PythonSupport/python-examples/

This tutorial describes the textclassifier example written...

The link for textclassifier is wrong, it should be https://github.com/intel-analytics/BigDL/tree/master/pyspark/bigdl/models/textclassifier while it's using the old link (https://github.com/intel-analytics/BigDL/tree/master/pyspark/bigdl/models/textclassifier)

**Comment by jenniew** [comment]
On https://bigdl-project.github.io/master/#PythonSupport/python-resources/, the links for lenet, textclassifier and Jupyter notebook tutorial are wrong too. They are pointing to old "dl" package not "bigdl" package.
