### ISSUE TITLE
Buid BigDL to dist on Windows

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1296]
Currently we can only use maven to build, it cannot create dist folder under ${BigDL_HOME}. The built jar and zip are under spark\dist\target\bigdl-version-spark-version-scala-version-win64-dist.  To be consistent with other platform, can we create some script like make-dist.cmd to work just as similar as build in Unix?

**Comment by yiheng** [comment]
I don't think we need it.

**Comment by yiheng** [comment]
Have mentioned this in the build page. https://bigdl-project.github.io/master/#UserGuide/install-build-src/#build-for-windows

**Comment by jenniew** [comment]
Make it consistent can help user run example in the same directories structure as ReadMe mentioned on, cos in ReadMe we don't mention on Windows we have different directory of jar and zip file.
