### ISSUE TITLE
Could not locate executable null\bin\winutils.exe in the Hadoop binaries on Windows

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1297]
When running BigDL program on Windows, it get "java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries". 
Need to download winutils.exe manually and put to some_folder\bin and set HADOOP_HOME or System property “hadoop.home.dir" to full path to some_folder. We need to document it in user guide.

**Comment by yiheng** [comment]
You need to set hadoop binaries on windows platform.

**Comment by yiheng** [comment]
Please google the error msg. There're tons of pages.

**Comment by yiheng** [comment]
https://stackoverflow.com/questions/35652665/java-io-ioexception-could-not-locate-executable-null-bin-winutils-exe-in-the-ha

**Comment by jenniew** [comment]
I know how to resolve it. I just mean we can add this information in document, so user would not meet this problem.

**Comment by jason-dai** [comment]
Please update the run page in the user guide for windows support.

**Comment by yiheng** [comment]
Add the doc to both known-issue and run page
