### ISSUE TITLE
ERROR while running a BigDL program with Interactive Spark shell

### ISSUE THREAD

**Issue by Mr-quan** [intel-analytics/BigDL#1300]
**# I run spark-shell on TH-2,and meet a problem**

cat: /master: No such file or directory
Execute parameters: --executor-memory 4G --total-executor-cores 2 --executor-cores 2 --master spark://:7077
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's repl log4j profile: org/apache/spark/log4j-defaults-repl.properties
To adjust logging level use sc.setLogLevel("INFO")
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.5.1
      /_/

Using Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_71)
Type in expressions to have them evaluated.
Type :help for more information.
17/07/20 02:05:48 WARN SparkConf: 
SPARK_WORKER_INSTANCES was detected (set to '2').
This is deprecated in Spark 1.0+.

Please instead use:
 - ./spark-submit with --num-executors to specify the number of executors
 - Or set SPARK_EXECUTOR_INSTANCES
 - spark.executor.instances to configure the number of instances in the spark config.
        
17/07/20 02:05:50 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
17/07/20 02:05:50 ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: Invalid master URL: spark://:7077

**Comment by yiheng** [comment]
In your command:
Execute parameters: --executor-memory 4G --total-executor-cores 2 --executor-cores 2 --master spark://:7077

the master is wrong. What is spark://:7077?
