### ISSUE TITLE
'LookupTable' object has no attribute 'set_weights'

### ISSUE THREAD

**Issue by Mathstao** [intel-analytics/BigDL#1301]
python: 2.7.10
spark: 1.5.2
scala: 2.10.6

When running the tutorial demo code (given by the Intel PAC-HPC competition) ,which is about segement analysis on IMDB dataset, it throw an Error: 'LookupTable' object has no attribute 'set_weights'.
And I cannot find the 'set_weights' funcition in 'LookupTable' class.

**Comment by yiheng** [comment]
where do you get BigDL? I think you may use the latest BigDL code to run that demo. @psyyz10

**Comment by psyyz10** [comment]
For python, `set_weights` method is defined in `Layer` class, any layer should have this method. Please try the latest code.
