### ISSUE TITLE
missing tests for load/save model (bigdl/caffe/)

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1307]
Below is the status of model load/save support from different sources. The items marked `N/A`  missed unit tests.  

 ---  | Local FS (`Scala`) | Local FS (`Python`) | hdfs (`Scala`) | hdfs (`Python`) | s3 (`Scala`) | s3 (`Python`)
------------ | -------------| ---------------| ----------| ------------| ----------| -----------
BigDL | Y | Y | Y | N/A | Y | N/A
Caffe | Y | Y | Y | Y | Y | Y
Tensorflow |  Y | N/A | N| N| N| N|

**Comment by wzhongyuan** [comment]
@shane-huang   All the tests have now been added for different data sources, closing this issue
