### ISSUE TITLE
python textclassifier doc needs update for pip install

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/BigDL#1331]
https://github.com/intel-analytics/BigDL/tree/master/pyspark/bigdl/models/textclassifier

only provide instructions for the manually installation users
```
        BigDL_HOME=...
        SPARK_HOME=...
        MASTER=...
        PYTHON_API_ZIP_PATH=${BigDL_HOME}/dist/lib/bigdl-VERSION-python-api.zip
        BigDL_JAR_PATH=${BigDL_HOME}/dist/lib/bigdl-VERSION-jar-with-dependencies.jar
```
I assume pip install users will not know where to find the bigdl home and jar files.

**Comment by zhichao-li** [comment]
added db8b0f8
