### ISSUE TITLE
Training Resnet not support HDFS file dir

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-analytics/BigDL#1333]
`spark-submit --class com.intel.analytics.bigdl.models.resnet.Train --master spark://hsx-node1:7077 --driver-memory=30g --executor-cores=28 --num-executors=8 --total-executor-cores=224 --executor-memory=220g --driver-java-options="-Dlog4j.configuration=/opt/package/BigDL_713_2/log4j.conf" /opt/package/BigDL_713_2/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar --batchSize 896 -f hdfs:///user/root/cifar-10 --optnet true --depth 20 --classes 10 --shortcutType A --nEpochs 1 --learningRate 0.1`
It reports:
`Exception in thread "main" java.nio.file.NoSuchFileException: hdfs:/user/root/cifar-10/data_batch_1.bin `

It can train after changing to cifar-10 local dir.

**Comment by helenlly** [comment]
@JerryYanWan  pls have a look

**Comment by yiheng** [comment]
cifar10 is too small. we need not put it on hdfs...

**Comment by ibingoogle** [comment]
straightforward solution: 
First, replace three functions loadTrain loadTest load in resnet/Utils.scala with counterparts in vgg/Utils.scala
Then, recompile bigdl
Works for both local file and hdfs

**Comment by yiheng** [comment]
@ibingoogle thanks for providing the solution. I will look at your PR
