### ISSUE TITLE
A problem about set_validation

### ISSUE THREAD

**Issue by zzuzayu** [intel-analytics/BigDL#1353]
Can only one dimension?
If I coding the following:

```
import numpy as np
from bigdl.optim.optimizer import *
from bigdl.nn.criterion import *
from bigdl.nn.layer import *
from bigdl.util.common import *
import itertools


model = Linear(2, 2)
samples = [
  Sample.from_ndarray(np.array([5, 5]), np.array([2.0,1.0])),
  Sample.from_ndarray(np.array([-5, -5]), np.array([-2.0,1.1])),
  Sample.from_ndarray(np.array([-2, 5]), np.array([1.3,1.2])),
  Sample.from_ndarray(np.array([-5, 2]), np.array([0.1,1.1])),
  Sample.from_ndarray(np.array([5, -2]), np.array([-0.1,-0.4])),
  Sample.from_ndarray(np.array([2, -5]), np.array([-1.3,-0.3]))
]
samples_test = [
    Sample.from_ndarray(np.array([5, -5]), np.array([1.0]))
]
train_data = sc.parallelize(samples, 2)
test_data=sc.parallelize(samples_test, 2)
init_engine()
optimizer = Optimizer(model, train_data, MSECriterion(), MaxIteration(100), 4)
optimizer.set_validation(
        batch_size=4,
        val_rdd=test_data,
        trigger=EveryEpoch(),
        val_method=[Top1Accuracy()])
train_model=optimizer.optimize()
model.get_weights()[0]

predictions = train_model.predict(train_data)

def map_predict_label(l):
    print l
def map_groundtruth_label(l):
    return l[0]

for s in predictions.collect():
    map_predict_label(s)
print test_data.collect()[0]
print train_data.collect()[0]
print samples[0]
print samples_test[0]

```
I got the following result:

> creating: createLinear
> creating: createMSECriterion
> creating: createMaxIteration
> creating: createDefault
> creating: createSGD
> creating: createOptimizer
> creating: createEveryEpoch
> creating: createTop1Accuracy
> [ 1.9036479   0.11492476]
> [-1.81120682  1.04498386]
> [ 0.61473751  1.31026411]
> [-0.4997189  1.5892818]
> [ 0.59215999 -0.4293732 ]
> [-0.52229643 -0.15035546]
> features: [ 5. -5.], label: [ 1.],
> features: [ 5.  5.], label: [ 2.  1.],
> features: [ 5.  5.], label: [ 2.  1.],
> features: [ 5. -5.], label: [ 1.],

But if I turn
 ```
samples_test = [
    Sample.from_ndarray(np.array([5, -5]), np.array([1.0]))
] 
```
into 
```
samples_test = [
    Sample.from_ndarray(np.array([5, -5]), np.array([1.0,0]))
]
```
I got a error:

> Py4JJavaError: An error occurred while calling o627.optimize.
> : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2517.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2517.0 (TID 1249, localhost):java.lang.IllegalArgumentException: requirement failed: inconsistent tensor size: 1 == 2

Who can tell me ,why????What should I do?

**Comment by dding3** [comment]
Top1Accuracy is used to caculate the percentage that output's max probability index equals target. In your scenario if you want to use top1Accuracy, your target size has to be 1. Else please change to other validation method (eg. Loss(MSECriterion)), it fits more in your scenario.
