### ISSUE TITLE
Epoch stopping criterion is non-sensical

### ISSUE THREAD

**Issue by sethah** [intel-analytics/BigDL#1354]
In the distributed optimizer, an epoch ends based on the following line:

````scala
if (accumulateCount >= dataset.size()) {
  ...
}
````

This does not make sense to me. `accumulateCount` is a var that is reset every epoch, and is updated via `accumulateCount += recordsNum.value`. Here, `recordsNum` is an accumulator which keeps track of the number of **training samples** that were used to train in each _iteration_. So, the stopping criterion above is comparing something with units of samples, to something with units of batches. 

Take a case where you have a batch size of 256, and your distributed dataset has 1000 minibatches in total. In this case, each epoch will consist of training on only four minibatches out of 1000, since `256 * 4 > 1000`. However, most of the time an epoch is defined as making a single pass through all of the mini-batches. 

One problem is that there doesn't seem to be any documentation on what the intended behavior is, but I'm fairly confident this is not it.

**Comment by sethah** [comment]
BTW, I have a pr pretty much ready for this. I'm happy to submit it, but wanted to raise the issue to make sure of what the intended behavior really is.

**Comment by dding3** [comment]
It's correct that accumulateCount is used to keep track of the number of trained samples, however dataset.size() is actually the total number of samples, so the stopping criterion is comparing units of trained samples with total samples. It should be correct to mark an epoch as finished if accumulateCount >= dataset.size as all the samples has been made a pass.

**Comment by sethah** [comment]
In the `DistriOptimizer`, the dataset is type ` DistributedDataSet[MiniBatch[T]]`. `dataset.size()` calls `dataset.count`, defined as follows

````scala
buffer.mapPartitions(iter => {
    require(iter.hasNext)
    val array = iter.next()
    require(!iter.hasNext)
    Iterator.single(array.length)
  }).reduce(_ + _)
````

`buffer` here, is of type `RDD[Array[Minibatch[T]]]`, so `iter.next()` will produce `Array[Minibatch[T]]`. The length of that array will be the number of minibatches in that partition, and the sum of that across partitions will be the total number of minibatches in the dataset, not the total number of samples contained in all those minibatches.

Please also see `DistriOptimizerSpec` for further evidence, where the dataset used for tests defines the size method to be `256 * nodeNumber` which is the number of _minibatches_ in the dataset. There are 1024 minibatches in that dataset, but if you run the tests you will see that it only processes 32 minibatches per epoch, instead of 1024. It prints 

````
2017-07-24 08:24:31 INFO  DistriOptimizer$:295 - [Epoch 3 32/1024][Iteration 66][Wall Clock 3.874609356s] Train 32 in 0.045870153seconds.
````

But 32 is the number of _samples_ (accumulateCount), and 1024 is the number of _minibatches_ (dataset.size()). I ran into this issue because it also happened to me when I was running a normal training workload. The code used there is:

````scala
val trainRDD: RDD[MiniBatch[Float]] = ...
val train = DataSet.rdd(trainRDD)
val optimizer = Optimizer(model, train, new ClassNLLCriterion[Float]())
````

This produces the same problem of not processing all minibatches.

**Comment by dding3** [comment]
dataset.size() should be sample size. @qiuxin2012 , could you give more explanation here?

**Comment by qiuxin2012** [comment]
Aha, you are creating `RDD[MiniBatch[Float]]` directly. This is much different from our existing examples. @sethah 

In our examples, we create DataSet with raw-data RDD, like `RDD[ByteRecord]` or `RDD[Sample]`. And, we use some transform to transform the raw data to a MiniBatch. So, in our examples, the `dataset.size()` means number of samples, `mini batch size` means number of training samples in each iteration.
Like the lenet example:
```scala
      val trainSet = DataSet.array(load(trainData, trainLabel), sc) ->
        BytesToGreyImg(28, 28) -> GreyImgNormalizer(trainMean, trainStd) -> GreyImgToBatch(
        param.batchSize)
```


But, in your case, you create `DataSet` with `RDD[MiniBatch]` directly. Then your `dataset.size()` is number of MiniBatchs. In each iteration, `DistriOptimizer` will fetch `node number * MiniBatch` for training. The `accumulateCount += nodeNumber * MiniBatch.size()`, is really a bug here, the counting doesn't match. We will fix this.

So, before our fixing, could you try to construct `RDD[Sample]` instead of `RDD[MiniBatch]`? In our latest 0.2.0 release, you can use `RDD[Sample]` to create a optimizer with
```scala
  def apply[T: ClassTag](
      model: Module[T],
      sampleRDD: RDD[Sample[T]],
      criterion: Criterion[T],
      batchSize: Int
      )(implicit ev: TensorNumeric[T]): Optimizer[T, MiniBatch[T]] = {
    new DistriOptimizer[T](
      _model = model,
      dataset = (DataSet.rdd(sampleRDD) -> SampleToMiniBatch(batchSize))
        .asInstanceOf[DistributedDataSet[MiniBatch[T]]],
      criterion = criterion
    ).asInstanceOf[Optimizer[T, MiniBatch[T]]]
  }
```

**Comment by sethah** [comment]
Ok, I see what is going on now, but I do think it is a real problem.

From the compiler's perspective, `DistriOptimizer.optimize` requires a `dataset: DistributedDataset[MiniBatch[T]]`. However, what you're pointing out is that what has to be passed in is not just any `DistributedDataset[MiniBatch[T]]`, but a dataset that has been "transformed" from a `DistributedDataset[Sample[T]]` or something at a per sample basis. This is because when transformations are applied via `Dataset.transform`, the size method simply references `preDataset.size()`. So the "size" of a distributed dataset is the size of whatever dataset originally created it. 

I would argue that this is highly deceiving. But regardless, there is a problem since users can pass in a completely valid dataset to the optimize function and get incorrect behavior. If you are not supposed to be allowed to create your own minibatch dataset, then APIs to do so must be made private or we would need more robust type checking on the optimization functions.

I guess this begs the question of what is a "DataSet" in BigDL exactly? Right now, the "size" of a dataset is simply whatever the number of elements in the original Dataset were, even if I perform arbitrary transformations on it. How should anyone know that the size will trace back to the original dataset in the lineage? The documentation for it is:

````scala
/**
   * Total size of the data set
   * @return
   */
  def size(): Long
````

This is basically incorrect. The doc should say something like "The number of elements in the dataset, or in the very first dataset in the lineage if this dataset is the result of transformations." 

I would propose to solve this particular issue by changing `DistriOptimizer` to not use `dataset.size()`, since it's unpredictable in its output. Instead, you could just count the number of elements in each minibatch by using:

````scala
val totalSamples = dataset.data(train = false).map(_.getTarget().toTensor.size().head).reduce(_ + _)
````

Then, we can correct the tests to produce the correct behavior and also add unit tests to verify this explicitly. What do you think?

**Comment by qiuxin2012** [comment]
I think it's better to use `MiniBatch's size()`:
```val totalSamples = dataset.data(train = false).map(_.size()).reduce(_ + _)```
