### ISSUE TITLE
Variational Auto Encoder (VAE) Request

### ISSUE THREAD

**Issue by volkanagun** [intel-analytics/BigDL#1416]
Variational Auto Encoder is requested... KL Loss criteria and Gaussian sampling layer must be implemented for this new feature.

**Comment by zhangxiaoli73** [comment]
https://github.com/intel-analytics/BigDL/pull/1432
Hi, @volkanagun I have add a pr to support your request. Please help review the pr, and do comments for any question.

**Comment by volkanagun** [comment]
I am not an expert though. How about the tests of convergence in MNIST....

**Comment by zhangxiaoli73** [comment]
I just use a criterion to optimize the loss, and after training, use decoder to reconstruct a gaussian sample to a digit to verify the model.
