### ISSUE TITLE
BigDL init_engine() Py4JJavaError  error running SSD model using pipeline-0.1-SNAPSHOT-jar-with-

### ISSUE THREAD

**Issue by Rashimk** [intel-analytics/BigDL#1426]
I am trying to run the SSD model using the ssd example with the pipeline-0.1-SNAPSHOT-jar-with-dependencies.jar, bigdl_ssd_vgg_300x300_voc.model. I am running this on Mac and read me does say that the example is being run on Linux. Is the jar file only compatible with linux? What can I do to get it running on mac. I can run other examples using the normal prebuilt bigdl 0.2.0. 
<img width="1118" alt="screenshot 2017-08-03 11 06 20" src="https://user-images.githubusercontent.com/23042079/28936197-d1000ed8-783b-11e7-8389-389e3a771fd3.png">

Thanks

**Comment by SeaOfOcean** [comment]
Hi, pipeline-0.1-SNAPSHOT-jar-with-dependencies.jar is build for linux,
If you want to try in mac, download the mac jar here
https://drive.google.com/uc?id=0B7vkTZblCs9hcDZzc2NuajNTUjA&export=download

just replace pipeline-0.1-SNAPSHOT-jar-with-dependencies.jar with pipeline-0.1-SNAPSHOT-jar-with-dependencies-mac.jar, it should work in mac
