### ISSUE TITLE
add documentation for customizing layers and criterions

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#1445]

**Comment by lseffer** [comment]
Until these documentations are available, could you provide a minimal example of how to adding a custom layer and criterion? Using pyspark would it be enough to extend the Python classes?

**Comment by yiheng** [comment]
@lseffer Currently, we do not support add customized layer by extending the Python classes. You need to extend the scala classes and wrapper it as Python class...

You need to extend ```AbstractModule``` class to define your own Layer. 
Here's an example of a layer which add a scalar to the input tensor.(Just need to look at the ```updateOutput``` and ```updateGradInput``` methods, they forward and backward the data)
https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/AddConstant.scala


To define your own loss function, you need to extend the ```AbstractCriterion``` class.
Here's an example of use avg of absolute value of the element-wise difference as loss
https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/AbsCriterion.scala
