### ISSUE TITLE
build failed after "git checkout branch-0.2"

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-analytics/BigDL#1448]
```
git checkout branch-0.2
bash make-dist.sh -P spark-2.x
```
Failure information:
Failed to execute goal on project bigdl: Could not resolve dependencies for project com.intel.analytics.bigdl:bigdl:jar:0.2.1-SNAPSHOT: Failure to find com.intel.analytics.bigdl.native:mkl-java:jar:0.2.1-SNAPSHOT in https://oss.sonatype.org/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype has elapsed or updates are forced -> [Help 1]

**Comment by yiheng** [comment]
We have not upload bigdl 0.2.1 to sonatype. I suggest checkout the 0.2.0 version instead of branch-0.2, which is actual 0.2.1-SNAPSHOT.

You can checkout the 0.2.0 version code by running command like this
```
git checkout tags/v0.2.0 -b v0.2.0
```

**Comment by ZeweiChen11** [comment]
Thanks Yiheng, the command works.
