### ISSUE TITLE
BigDL optimization throw exception on Spark 2.2.0

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#1461]
Here's the error stack

```
Py4JJavaError: An error occurred while calling o133.optimize.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 9.0 failed 4 times, most recent failure: Lost task 0.3 in stage 9.0 (TID 35, bigdl-w-1.c.internal, executor 2): java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.spark.storage.BlockInfoManager.unlock(Lorg/apache/spark/storage/BlockId;)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
```

Looks like we need to wrap the BlockManager.unlock method with reflection.

Why is this not caught in the unit test?

We also need to set a verify job for spark 2.2 in our Jenkins job configuration.

Currently, the work around of this issue is to build with ```-Dspark.version=2.2.0```

**Comment by srowen** [comment]
Yeah, it's this change, which is going to appear in several branches: 
https://github.com/apache/spark/commit/ee9d5975e6dbc5cb1dfe498870f94b1d760098db#diff-eb44ea906b13bb8223654ce70fbfff79R289

It should be safe to pass "None" for the second arg when there is a second arg.
