### ISSUE TITLE
Make the jar file and python zip file name with consistent version in BigDL release

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1500]
In the documentation of running local mode without pip install: https://bigdl-project.github.io/master/#PythonUserGuide/run-without-pip/#a-quick-launch-for-local-mode

cd $BIGDL_HOME/dist/lib 
BIGDL_VERSION=...
${SPARK_HOME}/bin/pyspark --master local[4] \
--conf spark.driver.extraClassPath=bigdl-${BIGDL_VERSION}-jar-with-dependencies.jar \
--py-files bigdl-${BIGDL_VERSION}-python-api.zip \
--properties-file ../conf/spark-bigdl.conf 

If a user install BigDL by downloading release, replacing BIGDL_VERSION is not working for both jar file and python zip file. I.E. jar is: bigdl-SPARK_1.6-0.2.0-jar-with-dependencies.jar, python zip is: bigdl-0.2.0-python-api.zip.
We need to make the jar and zip file name consistent in release.

**Comment by yiheng** [comment]
I think it's the document problem instead of the version problem.

@zhichao-li @jason-dai  The python start command is too complex and error prone. Should we refactor them by providing some script?

See https://github.com/intel-analytics/BigDL-Tutorials/blob/master/start_notebook.sh
