### ISSUE TITLE
Provide a way to print BigDL debug log without modifying code

### ISSUE THREAD

**Issue by dding3** [intel-analytics/BigDL#1521]
Some debug log is helpful to investigate issue. eg. 
========== Metrics Summary ==========
get weights average : 
computing time average : 
send weights average : 
xxxxx

For existing examples, eg. googlenet, by default they are turn off. and currently if we want to get above log, we have to edit the code, changing logger.debug to logger.info or update log level in train.scala. It's not very convenient as some users have build bigdl into a image and if they want to get the debug log, they have to edit code, recompile it and rebuild a image. It would be better if we can provide a way to show these logs without modifying the code.

**Comment by yiheng** [comment]
@lopelopelope  please take a look at this

**Comment by dding3** [comment]
I tried latest code and use the log4j config in the optimization.md, it can work. However, 2017-10-13 13:55:30 INFO  DistriOptimizer$:330 - [Epoch 1 576/60000][Iteration 36][Wall Clock 6.086943943s] Trained 16 records in xxx seconds. Throughput is xxx records/second. Loss is 1.9541306. Current learning rate is 0.05. Current dampening is 1.7976931348623157E308. 
will print twice. After i remove "myappender" from  "log4j.logger.com.intel.analytics.bigdl.optim=DEBUG,myappender" in log4j, looks like the log is expected.

Update the optimization.md?
