### ISSUE TITLE
Python documentation of loading Caffe Model Weights is not correct

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1552]
In the documentation https://bigdl-project.github.io/0.2.0/#ProgrammingGuide/caffe-support/, the python example of "Load Caffe Model Weights to Predefined BigDL Model" is not correct, the API is Model.load_caffe(bigdlModel, caffe.prototxt, caffe.model, match_all=True), not Model.load_caffe_model(bigdlModel, caffe.prototxt, caffe.model, match_all=True).

**Comment by jason-dai** [comment]
Please send a PR

**Comment by wzhongyuan** [comment]
I will send out a PR shortly

**Comment by wzhongyuan** [comment]
@jenniew  updated the doc in https://github.com/intel-analytics/BigDL/pull/1557

**Comment by wzhongyuan** [comment]
Merging it given it's minor doc change ~
