### ISSUE TITLE
save bigdl model to caffe model error

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1584]
Load a caffe googlenet model to bigdl model, fine tune the model, and save back to caffe mode, and get error.
Code:
model.saveCaffe("/model/front_story_40/a.prototxt", "/model/front_story_40/a.caffemodel")

Log:
[test_story.txt](https://github.com/intel-analytics/BigDL/files/1323636/test_story.txt)

**Comment by yiheng** [comment]
I think caffe model save only support graph model. @wzhongyuan

**Comment by wzhongyuan** [comment]
@yiheng  yes, but seems this loaded model is a Graph, I will take a look

**Comment by yiheng** [comment]
@wzhongyuan I see a sequential container in the error message.

**Comment by wzhongyuan** [comment]
@jenniew  

I did try and ran below code successfully
```scala
    val model = CaffeLoader.loadCaffe[Float]("/home/jerry/lab/data/caffe/googlenet/deploy.prototxt",
      "/home/jerry/lab/data/caffe/googlenet/bvlc_googlenet.caffemodel", null)
      ._1.asInstanceOf[Graph[Float]]

    CaffePersister.persist[Float]("/tmp/gle.prototxt", "/tmp/gle.caffemodel", model, true, true)
```
did you modify the model ?

**Comment by jenniew** [comment]
val newModel = Inception_v1_NoAuxClassifier(param.classNumber)
val model = Module.loadCaffe(newModel, param.prototxt, param.modelSnapshot, matchAll = false)
After trained, cannot save to caffe model or bigdl model.  I used pretrained place-365 googlenet model from https://github.com/CSAILVision/places365

**Comment by yiheng** [comment]
can we close the issue now? @wzhongyuan @jenniew

**Comment by yiheng** [comment]
@wzhongyuan any update of this?

**Comment by wzhongyuan** [comment]
@yiheng  I did try with above code without any issue, I think it's sequential issue, we can close it for now
