### ISSUE TITLE
Save bigdl model to torch model error

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1585]
Load a caffe googlenet model to bigdl model, fine tune the model, and save back to torch mode, and get error.
Code:
model.saveTorch("/model/front_story_40/b.torchmodel", overWrite = true)
Log:
[test_story.txt](https://github.com/intel-analytics/BigDL/files/1323660/test_story.txt)

**Comment by yiheng** [comment]
I think the error message is very clean. You model contains SpatialCrossMapLRN, but currently we havn't implent a saver for that kind of layer

**Comment by jenniew** [comment]
Could we add this support? As this layer is common layer in googlenet.
