### ISSUE TITLE
Inception V1 converted from tf runs slowly

### ISSUE THREAD

**Issue by i8run** [intel-analytics/BigDL#1602]
Branch: master, 2017.09.28
InceptionV1 model: http://download.tensorflow.org/models/inception_v1_2016_08_28.tar.gz

The first forward takes 2x time of original BigDL Inception V1 model. The second and last forwards take 100x time.

Progress:

1. freeze the model
2. load with `Module.loadTF`
3. create a tensor [4, 224, 224, 3]
4. do forward

**Comment by yiheng** [comment]
fixed in https://github.com/intel-analytics/BigDL/pull/1607
