### ISSUE TITLE
Format problem on website documentation

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#1604]
https://bigdl-project.github.io/master/#PythonUserGuide/run-without-pip/#faq
https://bigdl-project.github.io/master/#PythonUserGuide/run-from-pip/#bigdl-configuration

Nested lists are not shown properly on the website. 
Quite strange that they are displayed correctly on GitHub page but somehow there's format problem when viewing on the website [Nested lists are shown as a single list, which seems not that elegant.].

**Comment by yiheng** [comment]
the section list of doc page is only expanded when you click it
