### ISSUE TITLE
Python documentation of model test is not correct

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1627]
In python documentation of model test (https://bigdl-project.github.io/0.2.0/#APIGuide/Module/ and https://bigdl-project.github.io/master/#APIGuide/Module/), the API example is not correct. The original example code is: evaluateResult = model.test(testSet, 1, [Top1Accuracy]). It should be evaluateResult = model.test(testSet, 1, [Top1Accuracy()]).

**Comment by hkvision** [comment]
I fixed this problem in PR #1588 but this PR hasn't been merged to master yet.

**Comment by hkvision** [comment]
#1588 merged. Fixed this issue.

**Comment by hkvision** [comment]
Fix typo in branch-0.2 in pr #1638

**Comment by hkvision** [comment]
Fix typo in master branch in pr #1641 and merged.
