### ISSUE TITLE
Support python3.6

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#1665]
Currently we only test against python2.5 and python3.5.

1. Refactor code to support python3.6
2. Add python3.6 into jenkins test.

**Comment by zhichao-li** [comment]
https://github.com/intel-analytics/BigDL/issues/1293

As the jira suggested, python3.6 only works with Spark 1.6.4, 2.0.3, 2.1.1, 2.2.0. We need to upgrade Spark version in Jenkins if we want to add python3.6 into the workflow.

**Comment by hkvision** [comment]
Syntax error for `print` in `diff.py` with python 3.6

**Comment by hkvision** [comment]
Lenet example passed for bigdl 0.3.0 with pyspark 2.2.0

**Comment by zhichao-li** [comment]
cc @glorysdj
