### ISSUE TITLE
Release 0.2.1 seems to be missing

### ISSUE THREAD

**Issue by dnielsen** [intel-analytics/BigDL#1671]
Take a look.  0.2.1 download files seems to be missing: https://bigdl-project.github.io/0.2.0/#release-download/#release-021-snapshot

Dave

<img width="851" alt="release-021-snapshot" src="https://user-images.githubusercontent.com/392292/31689223-9a563108-b343-11e7-9840-09318458449d.png">

**Comment by jason-dai** [comment]
0.2.1 is never released; can you try 0.3.0-snapshot?
