### ISSUE TITLE
[0.3 Release QA] BigDL 0.3 release test: Loading Caffe models

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/BigDL#1711]
List the models that has been tested, and track the issues here.

Model tested (load successfully):

1. AlexNet-Imagenet
    https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet 

2. GoogleNet-Imagenet
    https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet

3. ResNet152-ImageNet
    https://github.com/KaimingHe/deep-residual-networks

4. vgg19-ImageNet
    https://gist.github.com/ksimonyan/3785162f95cd2d5fee77#file-readme-md 

5. GoogleNet-Places205
   http://places.csail.mit.edu/model/googlenet_places205.tar.gz

6. DeepBit32
   https://github.com/kevinlin311tw/cvpr16-deepbit

Issue found: 
* Error loading DenseNet: 
    `Error Input contains unknown fields and/or extensions:  54:5:	caffe.PoolingParameter.ceil_mode`
    I thought there was no issue but thanks for the reminder from @wzhongyuan, I actually removed the ceil_mode option from prototxt and the model can be loaded. But with the `ceil_mode: false`, there's still the error as shown.

* HybridCNN 
    http://places.csail.mit.edu/model/hybridCNN.tar.gz
```
  Exception in thread "main" java.lang.UnsupportedOperationException: NONE is not supported in BigDL for now
	at com.intel.analytics.bigdl.utils.caffe.Converter.tryCustomizedConverter(Converter.scala:64)
	at com.intel.analytics.bigdl.utils.caffe.Converter.convertLayerFromCaffe(Converter.scala:74)
```

* FCN 
  https://github.com/shelhamer/fcn.berkeleyvision.org
```
Exception in thread "main" java.lang.UnsupportedOperationException: DECONVOLUTION is not supported in BigDL for now
	at com.intel.analytics.bigdl.utils.caffe.Converter.tryCustomizedConverter(Converter.scala:64)
	at com.intel.analytics.bigdl.utils.caffe.Converter.convertLayerFromCaffe(Converter.scala:74)
```

* VGG16_faster_rcnn
https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/scripts/fetch_faster_rcnn_models.sh

```
2017-10-24 23:27:44 INFO  CaffeLoader:115 - load caffe model done
Exception in thread "main" java.lang.UnsupportedOperationException: ROIPOOLING is not supported in BigDL for now
	at com.intel.analytics.bigdl.utils.caffe.Converter.tryCustomizedConverter(Converter.scala:64)
	at com.intel.analytics.bigdl.utils.caffe.Converter.convertLayerFromCaffe(Converter.scala:74)
```

I'll close this once all the issues are resolved.

**Comment by wzhongyuan** [comment]
@hhbyyh 
For densenet, `ceil_mode ` in pooling is not in standard caffe definition thus we should ignore this for now

**Comment by wzhongyuan** [comment]
@hhbyyh   I checked the hybridcnn issue, it was becase the deprecated 'V1LayerParameter' contains nested 'V0LayerParameter' which is even older version than `V1LayerParameter`, both are not recommended in Caffe.
layers {
  layer {
    name: "prob"
    type: "SOFTMAX"
  }
  bottom: "fc8"
  top: "prob"
}

we have now supported 'LayerParameter' (recommended) and 'V1LayerParameter' (deprecated as well), but we don't support nested 'V0LayerParameter'

@jason-dai   The deprecated 'V0LayerParameter'  representation in Caffe is in a quite different way, Do we need to support this for now?

**Comment by hhbyyh** [comment]
For DenseNet, does it make sense if we just ignore the ceil_mode specifically in the code? 

And for the error message, if ceil_mode is not standard caffe field, we should let users know it's not our fault. And perhaps give some hint message about the possible work-around.

**Comment by wzhongyuan** [comment]
@hhbyyh   we cannot ignore it otherwise the behaviour should be different.
we already have an issue opened for promoting more meaningful messages to users for any incompatible issues

**Comment by wzhongyuan** [comment]
@hhbyyh    For densenet, the exception happened from the protobuf library where we map the binary to generated object, basically it's an protobuf incompatible issue (use old version-ed caffe to load a new and not standard caffe) which we cannot handle in our logic.

**Comment by hhbyyh** [comment]
@wzhongyuan I'm done with the tests. Please check the latest update ( which should be by design).

Also, from your comments, both densenet and HybridCNN don't need a fix. Please confirm.

**Comment by wzhongyuan** [comment]
@hhbyyh  Thanks for the update. Yes, For densenet, the param is not in standard caffe, for hybridcnn we will see if we have to support deprecated V0.

**Comment by wzhongyuan** [comment]
@hhbyyh Thanks for the update. Yes, For densenet, the param is not in standard caffe, for hybridcnn we will see if we have to support deprecated V0 after the release
