### ISSUE TITLE
[0.3 release test] Run python example on Windows get two unmatched spark sources exception

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1713]
Run Lenet example in Python( 2.7 and 3.5) on Windows, get two unmatched spark sources exception. 
I didn't set SPARK_HOME in environment, but in __prepare_spark_env(), when call os.environ.get('SPARK_HOME', None), still get the spark home. 

Traceback (most recent call last):
  File "C:/git/BigDL/pyspark/bigdl/models/lenet/lenet5.py", line 18, in <module>

    from bigdl.dataset import mnist
  File "C:\git\BigDL\spark\dist\target\bigdl-0.3.0-SNAPSHOT-spark-1.5.1-scala-2.
10.5-win64-dist\lib\bigdl-0.3.0-SNAPSHOT-python-api.zip\bigdl\__init__.py", line
 18, in <module>

  File "C:\git\BigDL\spark\dist\target\bigdl-0.3.0-SNAPSHOT-spark-1.5.1-scala-2.
10.5-win64-dist\lib\bigdl-0.3.0-SNAPSHOT-python-api.zip\bigdl\util\engine.py", l
ine 128, in prepare_env
  File "C:\git\BigDL\spark\dist\target\bigdl-0.3.0-SNAPSHOT-spark-1.5.1-scala-2.
10.5-win64-dist\lib\bigdl-0.3.0-SNAPSHOT-python-api.zip\bigdl\util\engine.py", l
ine 37, in __prepare_spark_env
Exception: Find two unmatched spark sources. pyspark is found in C:\tools\spark-
1.6.0-bin-hadoop2.6\python\lib\pyspark.zip\pyspark\__init__.py, while SPARK_HOME
 env is set to C:\tools\spark-1.6.0-bin-hadoop2.6\bin\... Please use one spark s
ource only. For example, you can unset SPARK_HOME and use pyspark only.

**Comment by hkvision** [comment]
The logic is:
       get spark_home if set
       if pyspark package installed:    //use pyspark in this case
              if pyspark path and spark_home are not consistent  then raise the forementioned exception
       else:
              //use spark_home in this case

**Comment by hkvision** [comment]
Can you print out spark_home and pyspark.__file__ for the comparison?

**Comment by hkvision** [comment]
Exception: Find two unmatched spark sources. pyspark is found in C:\tools\spark-
1.6.0-bin-hadoop2.6\python\lib\pyspark.zip\pyspark_init.py, while SPARK_HOME
env is set to C:\tools\spark-1.6.0-bin-hadoop2.6\bin... Please use one spark s
ource only. For example, you can unset SPARK_HOME and use pyspark only.

-----
It seems that you already set spark_home to `C:\tools\spark-1.6.0-bin-hadoop2.6\bin...`?
