### ISSUE TITLE
[0.3 release test] scala: ML pipeline: need update jar name in readme

### ISSUE THREAD

**Issue by zhangxiaoli73** [intel-analytics/BigDL#1726]
The jar name is bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar, actually it should be bigdl-VERSION-SNAPSHOT-jar-with-dependencies.jar

**Comment by hhbyyh** [comment]
Hi @zhangxiaoli73 anyone is working on this? If no I can send a PR.

**Comment by zhangxiaoli73** [comment]
yeah. I will fix it with other changes together.
