### ISSUE TITLE
[0.3.0-test] Could not find https://bigdl-project.github.io/master/#UserGuide/install-build-src/ in navigator

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#1757]
Could not find https://bigdl-project.github.io/master/#UserGuide/install-build-src/ in navigator

**Comment by qiuxin2012** [comment]
Find in another link in navigator, https://bigdl-project.github.io/master/#ScalaUserGuide/install-build-src/

**Comment by helenlly** [comment]
should we remove the wiki pages ?

**Comment by helenlly** [comment]
removed wiki pages
