### ISSUE TITLE
[0.3 release test] Run Lenet on Windows get Permission denied error

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1764]
When run lenet example on windows, get Permission denied error as below. The default download folder is /tmp/mnist.  Because windows user can not create /tmp/mnist folder. Can we provide an option in command line to let user specify a downloaded folder on which he has permission?
('Downloading data from', 'http://yann.lecun.com/exdb/mnist/train-images-idx3-ub
yte.gz')
Traceback (most recent call last):
  File "C:/git/BigDL/pyspark/bigdl/models/lenet/lenet5.py", line 83, in <module>

    train_data = get_mnist(sc, "train")\
  File "C:/git/BigDL/pyspark/bigdl/models/lenet/lenet5.py", line 53, in get_mnis
t
    (images, labels) = mnist.read_data_sets(location, data_type)
  File "C:\git\BigDL\spark\dist\target\bigdl-0.3.0-SNAPSHOT-spark-1.5.1-scala-2.
10.5-win64-dist\lib\bigdl-0.3.0-SNAPSHOT-python-api.zip\bigdl\dataset\mnist.py",
 line 100, in read_data_sets
  File "C:\git\BigDL\spark\dist\target\bigdl-0.3.0-SNAPSHOT-spark-1.5.1-scala-2.
10.5-win64-dist\lib\bigdl-0.3.0-SNAPSHOT-python-api.zip\bigdl\dataset\base.py",
line 194, in maybe_download
  File "C:\git\BigDL\spark\dist\target\bigdl-0.3.0-SNAPSHOT-spark-1.5.1-scala-2.
10.5-win64-dist\lib\bigdl-0.3.0-SNAPSHOT-python-api.zip\bigdl\dataset\base.py",
line 169, in urlretrieve
IOError: [Errno 13] Permission denied: 'c:\\users\\jiaowang\\appdata\\local\\tem
p\\tmptjwzpg'

**Comment by yiheng** [comment]
Use temp folder is fine but should not hard code to /tmp/

**Comment by yiheng** [comment]
A lot of test code also have this problem

**Comment by hkvision** [comment]
I got the same problem when trying to run on windows.
Even if I use `icacls "C:\Users\kaihuang\AppData\Local\Temp" /q /c /t /grant Users:F` to give full permissions, the download still can't be finished.
