### ISSUE TITLE
Run as a local scala program documentation is not updated.

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#1799]
https://bigdl-project.github.io/master/#ScalaUserGuide/run/#run-as-a-local-javascala-program
The documentation is not updated.
I suppose `java -cp` should be changed to `scala -cp`
In Jennie's PR, https://github.com/intel-analytics/BigDL/pull/1780/files
only README in localLenet folder is updated.

**Comment by jason-dai** [comment]
@hkvision please send a PR for that.

**Comment by hkvision** [comment]
ok I will do that.

**Comment by hkvision** [comment]
Updated both on master and branch-0.3 #1800 #1801
