### ISSUE TITLE
sbt has problem reading the artifactId ${mkl-java-os-version} in pom

### ISSUE THREAD

**Issue by weiguanghuang** [intel-analytics/BigDL#1817]
sbt may have problem reading the <artifactId>${mkl-java-os-version}</artifactId> variable in the pom file.
https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/native/mkl-java-mac/0.4.0-SNAPSHOT/mkl-java-mac-0.4.0-20171031.032222-1.pom

build.sbt
scalaVersion := "2.11.8"

resolvers += "ossrh repository" at "https://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies ++= Seq(
  "org.apache.predictionio" %% "apache-predictionio-core" % "0.11.0-incubating" % "provided" withSources(),
    "org.apache.spark"        %% "spark-core"               % "2.1.1" % "provided" withSources(),
    "org.apache.spark"        %% "spark-mllib"              % "2.1.1" % "provided" withSources(),
    "org.apache.spark"        %% "spark-sql"                % "2.1.1" % "provided" withSources(),
    "org.apache.lucene"        % "lucene-core"              % "6.5.1" % "provided",
    "com.intel.analytics.bigdl" % "bigdl-SPARK_2.1" 		% "0.3.0-SNAPSHOT"
    )
...
run $sbt compile
[error]         ossrh repository: bad module name found in https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/native/mkl-java-mac/0.3.0-SNAPSHOT/mkl-java-mac-0.3.0-20170930.061843-3.pom: expected='mkl-java-mac found='mkl-java'
[error]         ossrh repository: bad module name found in https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/bigquant/bigquant-java-mac/0.3.0-SNAPSHOT/bigquant-java-mac-0.3.0-20171019.113244-2.pom: expected='bigquant-java-mac found='bigquant-java'
[error]         ossrh repository: bad module name found in https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/native/mkl-java-win64/0.3.0-SNAPSHOT/mkl-java-win64-0.3.0-20170818.061623-2.pom: expected='mkl-java-win64 found='mkl-java'
[error]         ossrh repository: bad module name found in https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/bigquant/bigquant-java-win64/0.3.0-SNAPSHOT/bigquant-java-win64-0.3.0-20171019.075635-1.pom: expected='bigquant-java-win64 found='bigquant-java'

It looks like sbt has problem reading the <artifactId> variable in the pom.
I temperately excluded the two modules to pass the sbt compile.

**Comment by jason-dai** [comment]
Is there a fix or workaround?

**Comment by jason-dai** [comment]
@i8run

**Comment by i8run** [comment]
It has been fixed on 0.4.0-SNAPSHOT and had a workaround on 0.3.0.
