### ISSUE TITLE
A bug in expanded tensor

### ISSUE THREAD

**Issue by frankfzw** [intel-analytics/BigDL#1824]
For a expanded tensor, when the `mul` method is called, each element in this tensor while be multiplied many times (depends on how many times it is expanded)
e.g.
```
val x = Tensor[Double](3, 1)
    var i = 0
    x.apply1(e => {
      i += 1;
      i
    })
val result = x.expand(Array(3, 2))
result.mul(2)
```

The value inside the `result` will be [[4, 8, 12], [4, 8, 12]] instead of [[2, 4, 6], [2, 4, 6]]

**Comment by frankfzw** [comment]
@yiheng Please take a look at this issue.

**Comment by yiheng** [comment]
This should be an expected behavior...
