### ISSUE TITLE
model API document issue

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#1836]
In https://bigdl-project.github.io/master/#APIGuide/Module/#model-evaluation
```scala
val evaluateResult = model.evaluate(testSet, Array(new Top1Accuracy))
```
should be changed to
```scala
val evaluateResult = model.evaluate(testSet, Array(new Top1Accuracy), None)
```

As the third argument, which is optional, doesn't work because of a new added API.

In https://bigdl-project.github.io/master/#APIGuide/Module/#model-prediction, change the 
```scala
val predictSample = Sample(feature, label)
```

to

```scala
val predictSample = Sample(feature)
```

**Comment by mhddenno** [comment]
That is what I am using:    
    scala.version > 2.11.8
    scala.tools.version > 2.11
    scala.binary.version > 2.11
    spark.version > 2.0.0
    BIGDL_VERSION > 0.1.0
Eclipse as a development IDE and when I use evaluate method I get always this error:
no arguments allowed for nullary method

**Comment by zhichao-li** [comment]
`val evaluateResult = model.evaluate(testSet, Array(new Top1Accuracy), None)
`
None is ugly here? maybe we can hide that from the user in the next release.

**Comment by jason-dai** [comment]
I think it's None by default, no? So model.evaluate(testSet, Array(new Top1Accuracy) should do?

**Comment by yiheng** [comment]
@jason-dai It's None by default. But it doesn't work.

**Comment by jason-dai** [comment]
This is strange. @zhangxiaoli73 please take a look.

**Comment by zhangxiaoli73** [comment]
ok

**Comment by zhangxiaoli73** [comment]
yeah，I have do some test, and find:
if you set val evaluateResult = model.evaluate(testSet, Array(new Top1Accuracy)), then you will meet error: too many arguments, besides, there will be another warning: type mismatch, expected Array[ValidationMethod[Float]], acutally get Array[Top1Accuracy[Float]]. 

Chang to "val evaluateResult = model.evaluate(testSet, Array(new Top1Accuracy.asInstanceof[ValidationMethod[Float]]))" will be ok.

**Comment by zhangxiaoli73** [comment]
If you set "val evaluateResult = model.evaluate(testSet, Array(new Top1Accuracy, new Top5Accuracy))", there will be no type mismatch error.

**Comment by zhangxiaoli73** [comment]
Maybe we can add some objects to return same type
