### ISSUE TITLE
BigDL Release 0.3.0 is missing on maven central

### ISSUE THREAD

**Issue by mhddenno** [intel-analytics/BigDL#1837]
I am trying to linking the newest BigDL release which is (0.3.0) - after using (0.1.0) for six months - to my project. However, it appeared to be existed here [https://bigdl-project.github.io/0.3.0/#release-download/](url) but not on maven central! so is it uploaded somewhere else?

**Comment by yiheng** [comment]
Please append a suffix to the module name.

Here's for maven
```xml
<dependency>
    <groupId>com.intel.analytics.bigdl</groupId>
    <artifactId>bigdl-[SPARK_1.5|SPARK_1.6|SPARK_2.1|SPARK_2.2]</artifactId>
    <version>0.3.0</version>
</dependency>
```
For example, if you're using Spark 2.2
```xml
<dependency>
    <groupId>com.intel.analytics.bigdl</groupId>
    <artifactId>bigdl-SPARK_2.2</artifactId>
    <version>0.3.0</version>
</dependency>
```
