### ISSUE TITLE
Support other activation in recurrent layers.

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#1901]
Currently in recurrent layers including SimpleRNN, LSTM, GRU and ConvLSTM, we hard code the activation to be `Tanh`, and inner_activation to be `Sigmoid`.
In Keras, users can pass in activation and inner_activation as parameters. Moreover, inner_activation is set to `hard_sigmoid` by default. Usually it turns out that when users add a recurrent layer, they won't specify the activation, namely they will use `hard_sigmoid` as inner_activation but we don't support it.
Maybe we can consider adding activation parameters in these layers.

**Comment by zhichao-li** [comment]
cc @jason-dai @psyyz10 @yiheng  any thoughts?
