### ISSUE TITLE
Can I use multiple CPUs to make predictions?

### ISSUE THREAD

**Issue by zzuzayu** [intel-analytics/BigDL#1903]
When I load a model to predict,I find it only use one cpu.
The %Cpu(s) only 100.0.
I set the Spark is local[8].
Can I use multiple CPUs to make predictions?
What should I do?

**Comment by yiheng** [comment]
How many partitions of your data? Can you show me the code for prediction?

**Comment by zzuzayu** [comment]
@yiheng I only use the`predictions = model1.predict(test_rdd)`
`model1` is load a model.
The test_rdd is `test_rdd = sc.parallelize(zip(test_x, test_y), 2).map(lambda (x, y): to_sample(x, y))` 
the `test_x` has thousands of data.Why the `model1.predict() ` dont have batch_size?

**Comment by zzuzayu** [comment]
@yiheng Oh,I think i know... I should in the `sc.parallelize(zip(test_x, test_y), 2)` change the 2 to the number of cpus.Thanks.
