### ISSUE TITLE
Graph schedule takes too much time for small model or small batchsize

### ISSUE THREAD

**Issue by zhangxiaoli73** [intel-analytics/BigDL#1923]
When testing deepspeech model inference, found:
for deepspeech model with batchsize=1, graph process (not including nodes forward time) time takes about 10% of whole model time cost.
use another lenet model with batchsize=1, graph process (not including nodes forward time) time takes about 32% of whole model time cost. Increasing batchsize=32, it takes about 6%.

As in graph forward, schedule operations are fixed for a model. So when batchsize is small, nodes forward time will be less, but graph process time will not be reduced.

**Comment by jason-dai** [comment]
Maybe we should implement a subclass of Graph to support control nodes, while the base Graph is used to support normal nodes?
