### ISSUE TITLE
ModuleSerializerSpec should create tmp file using java.io.File.createTempFile

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#1995]
ModuleSerializerSpec should create tmp file using  java.io.File.createTempFile, not "/tmp/xxx"

Operation system like windows doesn't have a folder named /tmp

**Comment by wzhongyuan** [comment]
@qiuxin2012   The refinement in my current repo has already done so, thanks

**Comment by qiuxin2012** [comment]
@wzhongyuan Great!
