### ISSUE TITLE
Jenkins caffe-keras is slow

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#2018]
Caffe-Keras with 5 nodes if run on both spark 2.1.1 and 2.2.0 with python versions 2.7, 3.5 and 3.6, the running time is long and will cause time out since the jobs aren't running in parallel.

**Comment by hkvision** [comment]
Only running spark 2.2.0 for now. #2006 to track whether parallelization will speed up the process.

**Comment by yiheng** [comment]
don't open such issue in this.

**Comment by hkvision** [comment]
@yiheng ..... @zhichao-li asked me to open a issue to trace.....

**Comment by jason-dai** [comment]
Track it at Arda project instead. @glorysdj
