### ISSUE TITLE
Cannot use Tensor or AbstractModule as key in HashMap or HashSet

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#2146]
Currently, the `hashCode()` method in `Tensor` and `AbstractModule` is implemented using their own mutable states. 
If we put an `AbstractModule`  in a HashSet, and call forward on `AbstractModule`, then we may not find
the `AbstractModule` in the HashSet it was put in.

 For example, the following test will fail:
```scala
  "HashSet " should "work" in {
    val layer1 = Linear(4, 4)
    val hashSet = mutable.HashSet[Module[Float]]()
    hashSet.add(layer1)
    val data = Tensor[Float](4, 4).rand()
    layer1.forward(data)
    hashSet.contains(layer1) should be (true)
  }
```

**Comment by yiheng** [comment]
You should not use a mutable object as key of hashmap/hashset... In graph, maybe use the name of the layer?

**Comment by yangw1234** [comment]
@yiheng  I used the System.identityHashCode(n.element) as key.
Use name may not work, because user may accidentally set two unrelated layer to the same name and a layer's name can also be changed.

**Comment by yiheng** [comment]
In the graph, the name is unique, or the graph can't be built...

**Comment by yangw1234** [comment]
@yiheng the name field is mutable, it can be changed after the graph is built.
