### ISSUE TITLE
Error when creating a model with Replicate and a recurrent layer

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#2153]
When I run the following code:
```
import numpy as np
from bigdl.nn.layer import Sequential, Replicate, RnnCell, Recurrent, Tanh
bmodel = Sequential()
bmodel.add(Replicate(2, 1, 1))
rec = Recurrent()
rec.add(RnnCell(1, 1, Tanh(), isInputWithBias=False))
bmodel.add(rec)
bmodel.set_weights([np.array([[0.1]]), np.array([[-1.2]]), np.array([0.0])])
input_data = np.array([[0.2]])
bmodel.forward(input_data)
```
I get the result, which is WRONG...:
```
array([[[ 0.],
            [ 0.]]], dtype=float32)
```

However, if I run the following:
```
import numpy as np
from bigdl.nn.layer import Sequential, RnnCell, Recurrent, Tanh
bmodel = Sequential()
rec = Recurrent()
rec.add(RnnCell(1, 1, Tanh(), isInputWithBias=False))
bmodel.add(rec)
bmodel.set_weights([np.array([[0.1]]), np.array([[-1.2]]), np.array([0.0])])
input_data = np.array([[[0.2], [0.2]]])
bmodel.forward(input_data)
```
I get the result and this should be correct:
```
array([[[ 0.01999734],
            [-0.00399678]]], dtype=float32)
```

But basically, after forwarding by the `Replicate(2, 1, 1)` layer, the input `[[0.2]]` should be `[[[0.2], [0.2]]]`, so the above two code blocks should generate the same output?

**Comment by zhangxiaoli73** [comment]
output of Replicate layer is a noncontiguous tensor (storagesize <  totalsize).
But when doing resize in Recurrent, resize operation will expand storagesize to totalsize, and then original data in storage will be replaced with 0.

**Comment by zhangxiaoli73** [comment]
Here you should not use Replicate layer, which will not expand storage.
