### ISSUE TITLE
The type of return model by optimizer.optimze() will change to StaticGraph.

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#2168]
The type of return model by optimizer.optimze() will change to StaticGraph, if I put a graph model to the optimizer.
As StaticGraph's type is a layer not a Model, I couldn't call `.save_graph_topology` method.

**Comment by zhichao-li** [comment]
We need to check and wrap the a concrete type(Model, Sequential or Layer) according to the type of `jmodel`
```   
 def optimize(self):
        """
        Do an optimization.
        """
        jmodel = callJavaFunc(get_spark_context(), self.value.optimize)
        from bigdl.nn.layer import Layer
        return Layer.of(jmodel)
```
