### ISSUE TITLE
Support multi-OptimMethod in one model.

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#2171]
For model like wide&deep can use more than one OptimMethods in model's different parts. Like wide&deep model,  ftrl for wide part, adagrad for deep part.

**Comment by kiminh** [comment]
Hi,I'm very interested on this topic.Is there a scheduled timeline?

**Comment by qiuxin2012** [comment]
@kiminh Yes, I'm working on this issue. May I ask why you are interested on this feature?  Which kinds of case will you use?

**Comment by kiminh** [comment]
1. As you mentioned above, using ftrl to train wide part, and other methods for deep part in wide and deep model. Just like tensorflow wdl example.  
2. Use ftrl for some other models, like factorization machine widely used in ctr, recommendation.
