### ISSUE TITLE
can't install BigDL version 0.5.0.dev0 via pip3

### ISSUE THREAD

**Issue by dummr** [intel-analytics/BigDL#2209]
I have pip version 9.0.1 and python version 3.6.0. I cannot install BigDL on my mac. When I try:
`pip3 install BigDL==0.5.0.dev0`
as written in https://bigdl-project.github.io/master/#PythonUserGuide/install-from-pip/
I get this error:

> Could not find a version that satisfies the requirement BigDL==0.5.0.dev0 (from versions: 0.1.2, 0.2.0, 0.3.0, 0.4.0.dev0, 0.4.0.dev51, 0.4.0.dev511, 0.4.0)
No matching distribution found for BigDL==0.5.0.dev0

**Comment by yiheng** [comment]
0.5.0.dev0 is for internal test. Currently, we only publish 0.4.0. please refer:
https://bigdl-project.github.io/0.4.0/#PythonUserGuide/install-from-pip/

@helenlly @zhichao-li  should we change the default version of our doc website from master to the latest released version?

**Comment by dummr** [comment]
Thanks! Good to know!

**Comment by hkvision** [comment]
After the modification, it seems that the layout is not user-friendly.... @helenlly @yiheng
