### ISSUE TITLE
on Azure VM Ubuntu 16.04 LTS, python 2.7 package 'six' is not installed

### ISSUE THREAD

**Issue by sermolin** [intel-analytics/BigDL#2239]
Standard "without pip" instructions
https://bigdl-project.github.io/master/#PythonUserGuide/install-without-pip/
and
https://bigdl-project.github.io/master/#PythonUserGuide/run-without-pip/
fail upon executing 
from bigdl.nn.layer import *
![image](https://user-images.githubusercontent.com/25041537/35463518-e0f12396-02a5-11e8-9e78-6397a3dbf80e.png)

The issue is fixed by installing 'six':
$sudo apt-get install python-six
after which the command below executes successfully:
$bin/spark-submit-with-bigdl.sh --master local[4] lenet5.py

Python version:
bigdlazrmktplc@bigdl-v04b:~/BigDL$ python --version
Python 2.7.12
bigdlazrmktplc@bigdl-v04b:~/BigDL$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by hkvision** [comment]
LeNet needs package `six`. We only add the dependency for install-from-pip. We need to update install-without-pip page for this dependency? cc @zhichao-li related pr #1996 
Thanks for pointing out! @sermolin 👍

**Comment by hkvision** [comment]
@sermolin We have updated the doc page to add the dependency of `six`. Issue closed. Thanks!
