### ISSUE TITLE
Some code need to be refactor for keras implementation

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#2281]
- Change the default value of isCompatibleWithKeras to be false and override it if needed.
- Change the outputShape from Array[Shape] to be Shape.
- seq.add(dense), check if the outputShape of seq equals to the manually specified inputShape of dense or not. // and also seq.add(linear). // if there's getInputShape then we would trigger such checking? or check the isBuilt?
- `linear -> seq -> linear` can be put into a KModel for now. we need to iterate the whole graph on the constructing stage to see if all of the node is compatible with keras or vice versus.
- final `getInputShape` and `getOutputShape` as we do not go through building process while reload model from file. `InputShapeValue` and `outputShapeValue` is the final answer.

**Comment by hkvision** [comment]
We need to validate outputshape all entries >0 after building and calculation.
