### ISSUE TITLE
Save/Load module should not use getParameterTable method

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#2292]
As the getParameterTable will mix weight and gradients together, there's no way to distinguish them. Currently the save/load method only save parameter with name "weight" and "bias", which is wrong as there's no restrict to the name and one layer may have more than three weights parameter with a different name.

**Comment by wzhongyuan** [comment]
@yiheng   Previously  there was not layer breaking this convention and i saw other utility uses this way as well, also this API is much friendly to use

Currently there are couple of APIs in `AbstractModule` like `parameters` `getParameters` `setWeightsAndBias` , `setWeights`, etc. we should also open an issue to consolidate them to avoid confusion, it's kind of messed up...
