### ISSUE TITLE
Resnet Visualization for Graph Topology and biases

### ISSUE THREAD

**Issue by SnehalA** [intel-analytics/BigDL#2310]
How to view the topology and parameters visualization.
1. Integration of model.saveGraphTopology("logpath") with Resnet model - [DONE]
2. Viewing “weights”, “bias”, “gradientWeights” and “gradientBias” under the DISTRIBUTIONS and HISTOGRAMS tabs .

Only able to integrate the training and validation summaries

**Comment by jason-dai** [comment]
I believe you need to look at the GRAPH tab for viewing the topology.

**Comment by zhangxiaoli73** [comment]
default model in resenet/Train.scala is non-graph resnet, if you want to use graph model, you can add "--graphModel" to get graph model.

**Comment by SnehalA** [comment]
I have tried -g option, but it isn't working. Can the topology and parameters for Resnet/Inception models be viewed under tensorboard? Thanks.

**Comment by zhangxiaoli73** [comment]
If you have set -g, please try "model.asInstanceOf[Graph[Float]].saveGraphTopology("logpath")" to save topology. @SnehalA

**Comment by SnehalA** [comment]
Any tips for viewing “weights”, “bias”, “gradientWeights” and “gradientBias” under the DISTRIBUTIONS and HISTOGRAMS tabs  ?

**Comment by qiuxin2012** [comment]
@SnehalA 
I think you have known how to [create TrainSummary](https://bigdl-project.github.io/0.4.0/#ProgrammingGuide/visualization/).
Add a SummaryTrigger for TrainSummary like following code:
```
val optimizer = Optimizer(...)
...
val logdir = "mylogdir"
val appName = "myapp"
val trainSummary = TrainSummary(logdir, appName)
trainSummary.setSummaryTrigger("Parameters", Trigger.severalIteration(10))  // enable collecting “weights”, “bias”, “gradientWeights” and “gradientBias”
val validationSummary = ValidationSummary(logdir, appName)
optimizer.setTrainSummary(trainSummary)
optimizer.setValidationSummary(validationSummary)
...
val trained_model = optimizer.optimize()
```

**Comment by SnehalA** [comment]
Thank you, closing this issue.
