### ISSUE TITLE
Failed to install BigDL by pip under Windows

### ISSUE THREAD

**Issue by sperlingxx** [intel-analytics/BigDL#2317]
As mentioned, I have tried a lot of time `pip install BigDL==0.4.0`, and I have also tried BigDL==0.3.0, but it just returned same thing as below:

>   Could not find a version that satisfies the requirement BigDL==0.4.0 (from versions: )
No matching distribution found for BigDL==0.4.0

My system is Windows 7.
My pip version is 9.0.1, and my python version is 2.7.14.

**Comment by hkvision** [comment]
https://bigdl-project.github.io/master/#PythonUserGuide/install-from-pip/ We have stated here that pip install only supports Linux and Mac platforms. Sorry that pip install is currently not supported for windows.
Alternately, you can try to build the project on Windows. @sperlingxx

**Comment by sperlingxx** [comment]
@hkvision  thanks, I've installed it manually.
