### ISSUE TITLE
Python example of using BigDL with dataframe

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#2343]
Need python example of using BigDL in dataframe, like python version of MLPipeline, etc.

**Comment by jason-dai** [comment]
See https://github.com/intel-analytics/analytics-zoo/tree/master/apps/feature

**Comment by jenniew** [comment]
That example is for python ImageFrame. We need python example for training/evaluation/inference on spark dataframe instead of RDD. I think this one would work: https://github.com/intel-analytics/analytics-zoo/tree/master/apps/fraudDetection
