### ISSUE TITLE
jupyter launch script needs to be extended to support adding extra jars and python zip

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#2350]
juptyer-with-bigdl.sh should support adding extra jars and python zip (user-defined). Or it's not possible to add extra jars after SparkContext is created. 

specifically, the configurations needs to change as below:
```
       --py-files ${PYTHON_API_ZIP_PATH},${user_PYTHON_API_ZIP_PATH} \
       --jars ${BigDL_JAR_PATH},${user_JAR_PATH} \
       --conf spark.driver.extraClassPath=${BigDL_JAR_PATH}:${user_JAR_PATH} \
       --conf spark.executor.extraClassPath=bigdl-${BigDL_lib_version}-jar-with-dependencies.jar:${user_JAR_PATH}
```

**Comment by hkvision** [comment]
I tried adding `--jars --py-files` when starting the script and it works. Jupyter launching scripts in this way should be able to add configurations as normal. I will update the run-without-pip doc to point out this. cc @yiheng @shane-huang

**Comment by hkvision** [comment]
Updated docs here: https://github.com/intel-analytics/BigDL/pull/2358/files#diff-ddd31288395e39dc7e89f92bf41bf453R64
