### ISSUE TITLE
Categorical_Crossentropy (LogSoftMax + ClassNLL) is not the same as Keras

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#2385]
Categorical_Crossentropy in BigDL is  LogSoftMax + ClassNLL
Keras is ClassNLL with one hot as input
They are not the same in theory.

**Comment by hkvision** [comment]
`ClassNLLCriterion[Float](logProbAsInput = false))` should be equivalent to `sparse_categorical_crossentropy`.
For `categorical_crossentropy`, it is added by @yiheng and compared results with Keras.

**Comment by zhichao-li** [comment]
Let's keep track of this as the implementation of `CategoricalCrossEntropy` has combined "LogSoftMax" + "ClassNLL".
