### ISSUE TITLE
pip install command installs Spark 2.3.0 by default.

### ISSUE THREAD

**Issue by sermolin** [intel-analytics/BigDL#2503]
instructions: https://bigdl-project.github.io/0.5.0/#PythonUserGuide/install-from-pip/
$spark-submit --version 
    returns version 2.3.0

**Comment by hkvision** [comment]
I suppose this is because pip install dependencies require `pyspark>=2.2.0` while the latest version of pyspark (2.3.0) is installed by default. Will this be an issue?

**Comment by yiheng** [comment]
The risk is when Spark release a new version, we may not test BigDL on it yet, and it may potentially fail. Currently, we haven't seen such issue. So le's close it first.
