### ISSUE TITLE
Python ChannelNormalize have different parameter order with scala ChannelNormalize 

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#2544]
Python ChannelNormalize initializer:
def __init__(self, mean_r, mean_b, mean_g, std_r=1.0, std_g=1.0, std_b=1.0, bigdl_type="float"):
        super(ChannelNormalize, self).__init__(bigdl_type, mean_r, mean_g, mean_b, std_r, std_g, std_b)
The order is: mean_r, mean_b, mean_g, std_r, std_g, std_b
Scala ChannelNormalize initializer:
def apply(meanR: Float, meanG: Float, meanB: Float,
    stdR: Float = 1, stdG: Float = 1, stdB: Float = 1)
The order is: meanR, meanG, meanB, stdR, stdG, stdB

**Comment by jenniew** [comment]
Yes

**Comment by wzhongyuan** [comment]
@jenniew 

yes, the order is different....  not sure why it's done like this...

I will run another with this fixed to see if we have a better result once there is available cluster resource
