### ISSUE TITLE
Add probability prediction to Spark dataframe

### ISSUE THREAD

**Issue by sethah** [intel-analytics/BigDL#2551]
I am training a simple binary classification module. Once trained, I want to use it to generate predictions on a Spark dataframe. I see that there is the `DLClassifierModel` which serves this purpose, but I don't see a way to generate the actual probability from the model, just the class prediction. Is this possible? I'm using the Python API.

If not, what is the correct way to generate (feature, label, probability, prediction) tuples using the Python API (RDD or DF)?

**Comment by yiheng** [comment]
The purpose of `DLClassiferModel` is to let the user don't need to write code to convert probability to classification.

If you want to get the raw probability, please try `DLModel/DLEstimator`. It will output the model raw output(e.g. if the last layer is logsoftmax, it is log(probability)).

Please find the example in our document website(it's not a pure DLModel example but you know DLEstimator generate DLModel)
https://bigdl-project.github.io/0.5.0/#APIGuide/DLFrames/DLEstimator_DLClassifier/#dlestimator
