### ISSUE TITLE
几个问题：1. 支持sparse-dnn训练吗，现在实测能够支持sparse多大维度，看到paper里好像都是图片的 2. allreduce怎么支持的，是数据分成N片后，然后发到对应的N台机器，再循环分发吗

### ISSUE THREAD

**Issue by qiquanchang** [intel-analytics/BigDL#2554]

**Comment by jason-dai** [comment]
We do provide support for various sparse layers (https://bigdl-project.github.io/master/#APIGuide/Layers/Sparse-Layers/); an example is at https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/recommendation/WideAndDeepExample.scala.

For a quick overview of allreduce implementation, please see our tech report at https://bigdl-project.github.io/master/#whitepaper/
