### ISSUE TITLE
[bug] StaticGraph.backward doesn't respect the parameter `input`

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#2575]
i.e 
`input` is useless here< `graph.backward(input, gradoutput)` > as within the implementation it would only use the `cached` output as input instead of the `input` passed through function.

details can be found:

  private def backwardExecution( **input: Activity** , gradOutput: Activity,
    executeBackward: Boolean): Activity = {
    dummyOutputGrad.element.gradInput = gradOutput
    var i = 0
    while (i < backwardExecution.length - 1) {  // do not execute the dummy backward end
      val curNode = backwardExecution(i)
      val curGradOutput = findGradOutput(curNode, gradOutput)
      gradOutputCache(i) = curGradOutput
      val curInput = inputCache(backId2ForwardId(i))
      if (!isStopGradient(curNode.element)) {
        if (executeBackward) {
          curNode.element.backward(**curInput**, curGradOutput)

**Comment by i8run** [comment]
This is correct. We must do `forward` first than do `backward` for `Container`. Graph is a `Container`.
Although we have `input` for `graph.backward`, but it's only for the first layer/op. The input of others' layer/op should be computed first.
