### ISSUE TITLE
load tensorflow model doesn't support infer reshape

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#2576]
When trying to load the tensorflow model: https://github.com/intel-analytics/analytics-zoo/blob/master/zoo/src/test/resources/tfnet/frozen_inference_graph.pb
It will throw the following error:
```
Layer info: GraphNet[c98d25c1]/ReshapeLoadTF[LeNet/Flatten/flatten/Reshape]/Reshape[137d4f87](4x-1)
java.lang.IllegalArgumentException: requirement failed: element number must match Reshape size. But In Reshape137d4f87 : element number is: 12544 , reshape size is: -4
```
Reshape(4, -1) is used in tensorflow to infer the last dimension is not supported.

FYI, in Keras Reshape, I have added infer reshape. Not sure it can be used for this.

**Comment by megaSpoon** [comment]
@hkvision  After a lot of trials, I managed to load this protobuf in this way without getting exceptions. I changed the input node names and output node names based what I found in the .json file.
```
from bigdl.nn.layer import *
model_def = "/path/to/the/tf/model/frozen_inference_graph.pb"
inputs = ["batch:0"]
outputs = ["LeNet/fc4/BiasAdd"]
model = Model.load_tensorflow(model_def, inputs, outputs, byte_order = "little_endian", bigdl_type="float")
model
```

>Output:  <bigdl.nn.layer.Model at 0x7ff8a1f91790>

**Comment by megaSpoon** [comment]
@hkvision I checked the TFNet developed from the analytic-zoo. Is this the new tensorflow loader API?

**Comment by hkvision** [comment]
TFNet uses tensorflow as backend to do the inference and training. :)

**Comment by hkvision** [comment]
Using load_tensorflow() for this model can get a BigDL model, but when you call `forward`, it will throw the exception I mentioned above. @megaSpoon

**Comment by jason-dai** [comment]
I think we can just use this workaround.
