### ISSUE TITLE
Can we add a flag to turn on/off the shuffle behavior?

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#2594]
We are trying to implement a `rank_hinge_loss` which expect the shuffle to be off.

**Comment by yiheng** [comment]
I think it's doable. But normally train on dataset without shuffle model will get a very bad result, are you sure to do this?

There's a global shuffle at the very beginning and local shuffle for each epoch. Do you want to disable both or just the local shuffle?
