### ISSUE TITLE
Integrate DLModel with Spark ML's ImageSchema.readImages()

### ISSUE THREAD

**Issue by lucashu1** [intel-analytics/BigDL#2600]
As of [a few months ago](https://issues.apache.org/jira/browse/SPARK-21866), it looks like now Spark has [native support](https://blogs.technet.microsoft.com/machinelearning/2018/03/05/image-data-support-in-apache-spark/) for reading directories of images into a Spark Dataframe. Specifically, the `pyspark.ml.image.ImageSchema.readImages(path_to_img_folder)` function returns a DataFrame that has the schema:
```
root
 |-- image: struct (nullable = true)
 |    |-- origin: string (nullable = true)
 |    |-- height: integer (nullable = false)
 |    |-- width: integer (nullable = false)
 |    |-- nChannels: integer (nullable = false)
 |    |-- mode: integer (nullable = false)
 |    |-- data: binary (nullable = false)
```

Now that this image DataFrame functionality exists, has anyone tried to create a Spark ML Pipeline that starts with `ImageSchema.readImages()`, converts the image binary data to `Arrays` (or `mlllib` `Vector/Matrix`), and then uses a BigDL model to perform image featurization using a pre-trained `DLModel`? 

My goal is to implement a Spark Pipeline like: `Image URIs --> ImageSchema.readImages(), get a DataFrame with binary image data --> Reshape image data to Multi-dimensional arrays --> Transform DataFrame using pre-trained DLModel (e.g. ResNet50 featurizer) --> Ouptut n-dim Feature Vectors`.

This [house similarities](https://software.intel.com/en-us/articles/using-bigdl-to-build-image-similarity-based-house-recommendations) article is the closest snippet I could find to a code sample where a `DLClassifier` is applied to a DataFrame with image data (in the form of `Arrays`), but I haven't yet found any way to integrate this with Spark's new `ImageSchema` functionality.

Anyone have recommendations on what the best way to proceed with such an image featurization pipeline would be, or have links to any code samples that accomplish something like this? I'd like to keep as much computation within the same Spark ML pipeline as possible.

Thanks in advance!

**Comment by jason-dai** [comment]
See https://github.com/intel-analytics/analytics-zoo/tree/master/apps/image-similarity

**Comment by hkvision** [comment]
We haven't tested Analytics Zoo with Spark 2.3 yet but it is work in progress. @lucashu1

**Comment by lucashu1** [comment]
Got it @hkvision. 

On a related note, is there any way to normalize image values to between 0-1 in `ChainedPreprocessing`? I'm seeing an `ImageChannelNormalize()` function, but that seems to be used primarily for zero-centering each channel, rather than for 0-1 normalizing.

**Comment by jason-dai** [comment]
@lucashu1 maybe you can open an issue at https://github.com/intel-analytics/zoo/issues

**Comment by lucashu1** [comment]
Will do, @jason-dai -- that's probably a more fitting place to ask. Thanks for the help.
