### ISSUE TITLE
No `bigdl.dlframes` package after pip install bigdl

### ISSUE THREAD

**Issue by megaSpoon** [intel-analytics/BigDL#2601]
If we use `pip instal bigdl=0.x.0` to install BigDL, the `dlframes` package cannot be not found . i.e:

run `import bigdl.dlframes` in python shell after `pip install`

Output:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named 'bigdl.dlframes

**Comment by yiheng** [comment]
This is a duplicated ticket and the issue has already been fixed in https://github.com/intel-analytics/BigDL/pull/2588, which is available in 0.7.0-SNAPSHOT
