### ISSUE TITLE
Use a factory for model broadcast (instead of hard coding)

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#2604]
Instead of hard coding how to broadcast model (`ModelBroadcast`), use a factory that can be customized by the users (e.g., see broadcast in Spark https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/broadcast/BroadcastManager.scala)

**Comment by yiheng** [comment]
We'll look into it.
