### ISSUE TITLE
error when running examples in compilation

### ISSUE THREAD

**Issue by yy1987oo** [intel-analytics/BigDL#2614]
Error:scalac: '-deprecation' does not accept multiple arguments
Error:scalac: bad option: '-deprecation:false'

in my pom I also got a red error:
              <dependency>
                <groupId>com.intel.analytics.bigdl.core.dist</groupId>
                <artifactId>${os-flag}</artifactId>
                <version>0.7.0-SNAPSHOT</version>
                <type>pom</type>
              </dependency>

my JDK is 1.8 and scala is 2.12. maven is 3.0 how to fix it?

**Comment by yiheng** [comment]
How do you compile? Do you follow https://bigdl-project.github.io/0.6.0/#ScalaUserGuide/install-build-src/?
