### ISSUE TITLE
Failed to build BigDL，I expect to get some help.

### ISSUE THREAD

**Issue by Curry1201** [intel-analytics/BigDL#2633]
The bigdl.sh file is missing from the process of building BigDL by following the tutorial below.
tutorial：https://software.intel.com/en-us/articles/bigdl-distributed-deep-learning-on-apache-spark  
My laptop is dual system, I configure BigDL with Ubuntu system.I am using jdk-8u181-linux-x64.tar.gz，spark-2.3.1-bin-hadoop2.7.tgz and scala-2.13.0-M1.deb. But when I executed the command $ bash make-dist.sh, I found that the dist/bin/bigdl.sh. in the tutorial does not exist. There are only spark-shell-with-bigdl.sh, spark-submit-with-bigdl.sh, jupyter-with-bigdl.sh and pyspark-with-bigdl.sh. When I am going to start **Set Environment Variables** in the **Getting Started section** of the tutorial, I execute the command $ source PATH_To_BigDL/scripts/bigdl.sh, I can't proceed because there is no bigdl.sh under the folder BigDL/scripts.

**Comment by jason-dai** [comment]
@Curry1201 the article there is for an old version of bigdl; maybe you can try some high level notebooks (e.g., https://github.com/intel-analytics/analytics-zoo/tree/master/apps/anomaly-detection) as a starting point?

**Comment by Curry1201** [comment]
> @Curry1201 the article there is for an old version of bigdl; maybe you can try some high level notebooks (e.g., https://github.com/intel-analytics/analytics-zoo/tree/master/apps/anomaly-detection) as a starting point?

Thanks to teacher Jason for kind response. In fact, I read your speech at the 2018 China Artificial Intelligence Conference and your article 《BigDL: A Distributed Deep Learning Framework for Big Data》. I used to utilize the caffe to implement the SSD. Due to limited lab resources, I was unable to install the caffe on my laptop, so I wanted to use BigDL. Thanks again for your answer, I will try the analytics-zoo you just mentioned.
