### ISSUE TITLE
how can I get an AUC score to validate the classification model

### ISSUE THREAD

**Issue by land1725** [intel-analytics/BigDL#2692]
@zhangxiaoli73 Hello,do we have a method to get an AUC score to validate the classification model?
We may need implement a AUC score to validate the classification model.
https://en.wikipedia.org/wiki/Receiver_operating_characteristicg

**Comment by land1725** [comment]
@jason-dai hello thanks a lot to your reply.
I met another questions.
my label is 0 and 1,but bigDL need label start from 1.0 so I change my label to 1.0 and 2.0

but when I use AUC it report another problem like below.
Shoud I try to change my label to 1 and 0?
I am a beginner on bigDL,do you have some demos on how to use AUC?
ResultStage 845 (reduce at AbstractOptimizer.scala:146) failed in 0.393 s due to Job aborted due to stage failure: Task 2 in stage 845.0 failed 4 times, most recent failure: Lost task 2.3 in stage 845.0 (TID 3709, bigdata.node3, executor 3): java.lang.IllegalArgumentException: requirement failed: output dimension must be the same with target!!out dimension is: 2, target dimension is: 1

Engine.init

    val weightInitMethod = Xavier
    val biasInitMethod = Xavier
    val hidden_1 = Linear(inputNumber, 512)
    hidden_1.setInitMethod(weightInitMethod, biasInitMethod)
    val hidden_2 = Linear(512, 2)
    hidden_2.setInitMethod(weightInitMethod, biasInitMethod)

    val model = Sequential()
      .add(hidden_1)
      .add(ReLU())
      .add(hidden_2)
      .add(LogSoftMax())


    val criterion = ClassNLLCriterion()
    val estimator = new DLClassifier(model, criterion, Array(inputNumber))
      .setFeaturesCol("features")
      .setLabelCol("label")
      .setBatchSize(2048)
      .setOptimMethod(new Adam())
      .setValidation(Trigger.everyEpoch,testInput,Array(new AUC()),2048)
    val dlModel = estimator.fit(trainInput)
    val testRank = dlModel.transform(testInput)

**Comment by jason-dai** [comment]
You may open an issue at https://github.com/intel-analytics/analytics-zoo/issues and then we can take a look.

**Comment by land1725** [comment]
I solved the problem like this:
   val estimator = new DLClassifier(model, criterion, Array(inputNumber))
      .setFeaturesCol("features")
      .setLabelCol("label")
      .setBatchSize(2048)
      .setOptimMethod(new Adam())
      .setValidation(Trigger.everyEpoch, testInput, Array(new AUC()), 2048)
