### ISSUE TITLE
JavaPackage object is not callable

### ISSUE THREAD

**Issue by Alireza-cman** [intel-analytics/BigDL#2717]
Hi, 
I've installed BigDL version 0.7.0 via pip install procedure. I didnt set any ``BIGDL_JAR`` environment based on pip installation composed on the document. the Spark version is 2.4, OS is Ubuntu 16.04 and I am using python 2.7.
when I run the ``pyspark`` to check validation of my installation via this code, it will through the `` JavaPackage Object is not Callable``
```sh
from bigdl.util.common import *
from pyspark import SparkContext
from bigdl.nn.layer import *
import bigdl.version

# create sparkcontext with bigdl configuration
sc = SparkContext.getOrCreate(conf=create_spark_conf().setMaster("local[*]"))
init_engine() # prepare the bigdl environment 
bigdl.version.__version__ # Get the current BigDL version
linear = Linear(2, 3) # Try to create a Linear layer
``` 
by the way, when start the above program with python (without ``pyspark`` or ``spark-submit`` command) it will work nice and clear. Although I've cope up with the FAQ and set ``BIGDL_JAR`` by downloading the project and set this env (actually there is no any JAR file when you use pip installation). but unfortunetly, I still encounter with JavaPackage error when I use ``pyspark``/``spark-submit`` command. 
could you plz help me to get though this ?

**Comment by wzhongyuan** [comment]
it's an unknown issue where you want to use pip installed BigDL with pyspark. the root cause is the pyspark will overwrite the classpath when initialization so the BigDL python API cannot load BigDL jar correctly. we will try to see how to fix it. in the mean time, you can use --jars option to resolve this issue when using pyspark by:

```shell
sudo pyspark --jars /path/to/bigdl/jar
```

**Comment by Alireza-cman** [comment]
I actually solve the problem by setting the `BIGDL_JAR` variable as a system environment variable. it was interesting to me that when I set the BIGDL_JAR on `.bashrc` file in home directory, it doesn't work at all. I just set it in ``/etc/environment`` which is system environment variable.

**Comment by yeamusic21** [comment]
What did you set BIGDL_JAR to exactly?  I can't seem to find the necessary jar files?  Did you grab them by  downloading the project?

**Comment by Alireza-cman** [comment]
did you install BigDL via pip install ? 
by the way, download the latest release of BigDL from [here](https://bigdl-project.github.io/0.7.0/#release-download/), after extraction of this compressed file, you will find the jar file on `lib` directory. 
just pass the jar file path when you are trying to run your file with spark-submit

**Comment by yeamusic21** [comment]
Yes, we installed BigDL via pip install.

Given my answer is 'yes', should I still "download the latest release of BigDL" as you mentioned in order to get the jar files I need?

Thanks again :)

**Comment by Alireza-cman** [comment]
Yeap, you shoud download it even you have install the BigDL with pip.

**Comment by yeamusic21** [comment]
Excellent, thanks so much Alireza-cman!! :-D

**Comment by yeamusic21** [comment]
This is still not working for me

script:

`from bigdl.util.common import *
from pyspark import SparkContext
from bigdl.nn.layer import *
import bigdl.version

# create sparkcontext with bigdl configuration
sc = SparkContext.getOrCreate(conf=create_spark_conf().setMaster("local[*]"))
init_engine() # prepare the bigdl environment 
bigdl.version.__version__ # Get the current BigDL version
linear = Linear(2, 3) # Try to create a Linear layer`

Commands:
`export PYSPARK_PYTHON="/opt/datascience/anaconda/bin/python"
export SPARK_DRIVER_MEMORY=20g
export JAVA_HOME="/usr/jdk64/jdk1.8.0_40/"
export PATH="$JAVA_HOME/jre/bin/:$PATH"
PATH=/usr/jdk64/jdk1.8.0_40/jre/bin/:$PATH
export BIGDL_JARS="/installs/update/analytics-zoo-bigdl_0.7.2-spark_2.3.1-0.4.0-dist-all/lib"
export BIGDL_PACKAGES="/installs/update/analytics-zoo-bigdl_0.7.2-spark_2.3.1-0.4.0-dist-all"

USER="uswe8vk"
PASSWORD='DxCClstNov19!'

spark-submit \
--master yarn \
--conf spark.driver.memory=5G \
--queue spark \
--num-executors 8 \
--executor-memory 5G \
--executor-cores 4 \
Test/BigDL_Test.py > Test/BigDL_Test_Output.txt`

Output:

'Adding /opt/datascience/anaconda/lib/python2.7/site-packages/bigdl/share/lib/bigdl-0.7.2-jar-with-dependencies.jar to BIGDL_JARS
Prepending /opt/datascience/anaconda/lib/python2.7/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Prepending /farmers_installs/update/analytics-zoo-bigdl_0.7.2-spark_2.3.1-0.4.0-dist-all to sys.path
Traceback (most recent call last):
  File "/home/uswe8vk/Rec_Sys_Test/Matt_Yates_BigDL_Test.py", line 12, in <module>
    init_engine() # prepare the bigdl environment 
  File "/opt/datascience/anaconda/lib/python2.7/site-packages/bigdl/util/common.py", line 417, in init_engine
    callBigDlFunc(bigdl_type, "initEngine")
  File "/opt/datascience/anaconda/lib/python2.7/site-packages/bigdl/util/common.py", line 579, in callBigDlFunc
    for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:
  File "/opt/datascience/anaconda/lib/python2.7/site-packages/bigdl/util/common.py", line 56, in instance
    cls._instance = cls(bigdl_type, *args)
  File "/opt/datascience/anaconda/lib/python2.7/site-packages/bigdl/util/common.py", line 93, in __init__
    self.value.append(getattr(jclass, "ofFloat")())
TypeError: 'JavaPackage' object is not callable'

Running PySpark 2.3.2

:(

**Comment by yeamusic21** [comment]
I think this answers my question

https://groups.google.com/forum/#!msg/bigdl-user-group/xIzBGfHmn-A/PREWlj_HCgAJ

if installing from pip you use `python` command not `spark-submit`.  

> You can use `python` to start a REPL and call `from zoo.common.nncontext import *`&`sc = init_nncontext()` to create a SparkContext.

Would be interesting if I understand this correctly.

Thanks :)
