### ISSUE TITLE
slave workers do throw lots of error on their backend

### ISSUE THREAD

**Issue by Alireza-cman** [intel-analytics/BigDL#2722]
many tnx, I got what you mean. 
there is an another issue in cluster mode that I encounter with. I have setup a spark cluster which is consisted of 3 node (1 master / 2 worker) with Virtual box. I config the its topology in such a way that only those two worker node should be considered as slave. by the way, when I run my code locally whether by installing the BigDL framework via pip or without pip there is not any kind of problem and everything goes very well. but the problem is that when I change mode to the spark cluster, the code will be freezing after compiling the Keras-style code, when it will print out 
`` DistriOptimizer$ 731 - caching training rdd ... ``
I waited for a long time, but there is no any kind of progress after this info. 
I have installed Numpy and six packages in slaves nodes. 
I have sort of question that may solve this issue, 
1- should I change my train & test samples from Numpy array to RDD format to be executed in cluster mode ? 
2- Is it necessary to install BigDL on slave nodes ? 
Moreover, there are a lot of executor summary in my spark terminal in which a lots of jobs were failed

_Originally posted by @Alireza-cman in https://github.com/intel-analytics/BigDL/issues/2720#issuecomment-455868273_

**Comment by wzhongyuan** [comment]
Hi, replied in your original issue, we can follow up from there, closing this one
