### ISSUE TITLE
BigDL engine specifying the executors and cores

### ISSUE THREAD

**Issue by moyanojv** [intel-analytics/BigDL#2725]
Hi all.

As I understand training with BigDL (autoencoder) requires certain conditions (please correct me if I'm wrong):

1. The batch size must be a multiple of the total number of cores.

2. The batch size must be less than the total number of elements in the training dataset.

If the above is correct I would like to comment with you a use case that can cause certain problems.

We have a process that requires training N models on N datasets. One of the datasets is extremely small compared to the others.

If we configure the number of executors and cores to optimize the calculation of the model with the largest dataset we find that the total number of cores exceeds the smallest dataset which causes an error.

Similarly, if we configure executors and cores to work with the smallest dataset, we lose performance in time when calculating the model for larger datasets.

I understand that the correct way to proceed is to launch N executions. One for each model with an optimal configuration of executors and cores. Still, I would like to ask:

Is there a way to initialize the BigDL engine specifying the executors and cores that it should use?

Thanks in advance.

**Comment by wzhongyuan** [comment]
A bit little confused here.  what's the relationship among the N models ? you want to train all models in one application ? why not training N models with N spark application?

**Comment by moyanojv** [comment]
I see your point @wzhongyuan: 

> I understand that the correct way to proceed is to launch N executions. One for each model with an optimal configuration of executors and cores.

> 
But, let me explain another example:

We can imagine a process just for train one model. This process needs a lot of data manipulation and for this pourposes we add a lot of resources (executors and cores). If the resultant dataset have less rows than the number of cores used will cause the same situacion. So i think my question still have sense:

Is there a way to initialize the BigDL engine specifying the executors and cores that it should use?

**Comment by zhangxiaoli73** [comment]
HI, @moyanojv yeah, you have a good understanding about how to set batchSize.
From your example, you mean you have more cores than dataset rows, and want to init Engine with less cores, right?
Now, we initialize Engine automatically from submit command, and if you want to set by hand, you may try Engine.init(nExecutor: Int, executorCores: Int, onSpark: Boolean). Hope it can fix your issue.

Thanks,
Cherry

**Comment by moyanojv** [comment]
Good to know that that we still have this possibility.

Many thanks @zhangxiaoli73
