### ISSUE TITLE
Refine a model, loss=MSE out of control 

### ISSUE THREAD

**Issue by hxfcalf** [intel-analytics/BigDL#2726]
Hi, Jason Dai 
With BigDL ver 0.7, I create a multi-element nowcasting model using 2016--2018 datas after epoch=40 training.
I use the model for my forecast work in 2019. after 2 hours , there are predicts/real pairs, I need refine the model. Based on the old model to fit the 2016--2019 datas the loss=MSE out of control after epoch=3. 
So I must recreate the model using epoch=40, this time it takes more times and the semi on-line training task failure.
I notes BigDL ver 0.8 ,add reserve optimum Method, may help me solve the  problem. 
Could you give me more advice?

**Comment by zhangxiaoli73** [comment]
Hi, from your description, it seems that you want to resume training your model with previous optim method, right?
For reserve optim Method api, it means you can call multi optimizer and next one will use optimMethods from previous one.
If you just loaded trained model from local file and do resume training, reserve optim Method is not suitable for you. Do you have saved your optim method after training? If saved, you can load optim method by OptimMethod.load[Float](path) and set it to optimizer.

**Comment by zhangxiaoli73** [comment]
Ok, if you don't have any other questions, I will close this issue. 
But You can reopen it if you still have such issue.
