### ISSUE TITLE
Spark2.3.2 Compatible

### ISSUE THREAD

**Issue by yeamusic21** [intel-analytics/BigDL#2735]
https://bigdl-project.github.io/0.7.0/#release-download/

We can see that BigDL has releases under 0.7.0 for Spark 2.3.1, but we're running on Spark 2.3.2.  Would BigDL version 0.7.2 only work under Spark 2.3.1, or should it also work under 2.3.2.  We did a pip install and we're having trouble getting init_engine() to run for PySpark.  init_engine runs if we just call 'python' but if we do 'spark-submit' or 'pyspark' we get "TypeError: 'JavaPackage' object is not callable".  Any help would be greatly appreciated!

Thanks :)

**Comment by wzhongyuan** [comment]
For most cases, it should be compatible to run BigDL under 2.3.2 as well, you can give it a try.

For your issue,  please check https://github.com/intel-analytics/BigDL/issues/2717

**Comment by yeamusic21** [comment]
Excellent!  Thank you!  (I think we can close this issue).
