### ISSUE TITLE
branch-0.6 maven can not find ...dist:all:jar:0.6.1-SNAPSHOT in https://oss.sonatype.org

### ISSUE THREAD

**Issue by byuegv** [intel-analytics/BigDL#2784]
[ERROR] Failed to execute goal on project bigdl: Could not resolve dependencies for project com.intel.analytics.bigdl:bigdl:jar:0.6.1-SNAPSHOT: Failure to find com.intel.analytics.bigdl.core.dist:all:jar:0.6.1-SNAPSHOT in https://oss.sonatype.org/content/groups/public/

**Comment by wzhongyuan** [comment]
we don't have minor release 0.6.1, can you check your dependency configure and try with 0.6.0 ?
