### ISSUE TITLE
Wrong log in BCECriterion

### ISSUE THREAD

**Issue by yaochitc** [intel-analytics/BigDL#2797]
The code below compared the input and the target, but the log output the input size twice.

`require(input.size().sameElements(target.size()),
      s"input size should be equal to target size, but got input size: ${input.size().toList}," +
        s" target size: ${input.size().toList}")`

**Comment by wzhongyuan** [comment]
Thank for pointing out , we will get it fixed soon, also you could raise a PR to fix it as well if you want :)

**Comment by yaochitc** [comment]
> Thank for pointing out , we will get it fixed soon, also you could raise a PR to fix it as well if you want :)

ok

**Comment by wzhongyuan** [comment]
fixed with https://github.com/intel-analytics/BigDL/pull/2800
