### ISSUE TITLE
ResNet50 inference RandomCropper can be replaced by CenterCrop

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#2811]
The accuracy will remain unchanged and the speed will be much faster.
Please confirm this :).

**Comment by wzhongyuan** [comment]
Thanks, will take a look

**Comment by hkvision** [comment]
Also, RandomResize can be replaced by Resize (mainly for avoid ambiguity).

**Comment by wzhongyuan** [comment]
CenterCrop has the same result as the RandomCropper for validation while RandomResize does not with Resize
