### ISSUE TITLE
ResNet50 MKLDNN accuracy issue

### ISSUE THREAD

**Issue by Litchilitchy** [intel-analytics/BigDL#2812]
Analytics-zoo model (converted from caffe) could be directly load by `loadModule`, but the accuracy gets bad(**top1/5 55%/77%** compared to bigdl model **top1/5 75%/92%**)

The model used is resnet50 pretrained one, using mkldnn as backend

However there is no error raised, seems the weights and bias are loaded correctly. What happens?

**Comment by zhangxiaoli73** [comment]
@Litchilitchy Hi, I use examples in zoo to test model (converted from caffe) accuracy.
**With MKLDNN and MKLBLAS backend, I got same accuracy for Imagenet validation dataset.**
Top1Accuracy is Accuracy(correct: 36433, count: 50000, accuracy: 0.72866)
Top5Accuracy is Accuracy(correct: 45571, count: 50000, accuracy: 0.91142)

So please check your test code. Please let me know if there is still accuracy inconsistent.
