### ISSUE TITLE
mkldnn backend set coreNumber to 1 may be confusing for LocalPredictor in local mode

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#2820]
If we use localMode with mkldnn backend, the property "bigdl.coreNumber" will always be set to 1 and not user configurable.
Thus when using LocalPredictor, default batchPerCore is 4, thus if we don't change this, the total batch is 4 *1 *1=4, which is too small.

**Comment by hkvision** [comment]
For Distributed Predictor, you calculate the total batch size according to the __original__ RDD partition and batchPerPartition, and then coalecse to partition=1 (for single node). But for LocalPredictor, you are always forcing coreNumber=1. This may be a bit confusing.

**Comment by jason-dai** [comment]
just call init_nncontext to walk around it
