### ISSUE TITLE
make-dist.sh build script failing for Java 10+

### ISSUE THREAD

**Issue by 0xcfe4f1** [intel-analytics/BigDL#2829]
The build script doesn't account for Java 10+, as the version check looks to be expecting strings like "1.7", "1.8", etc. instead of "10", "11", "12", etc. 

https://github.com/intel-analytics/BigDL/blob/32e61c75be434371dd16819f4d7961376c706d66/make-dist.sh#L37

**Comment by wzhongyuan** [comment]
Yes, currently only 1.7 and 1.8 are supported

**Comment by 0xcfe4f1** [comment]
Thanks for getting back to me on this -- are there plans to support Java 10+ or Spark 2.4+ in the future?
