### ISSUE TITLE
Problematic inferred output shape for sparse embedding

### ISSUE THREAD

**Issue by yaochitc** [intel-analytics/BigDL#2833]
Here is the returned value of the computeOutputShape method in SparseEmbedding:

` Shape(input(0), input(1), outputDim)`

As the second dimension will be aggregated by the combiner, should it be change to  `Shape(input(0), outputDim)` ?

**Comment by benjamim93** [comment]
Looks like in nn.keras.Embedding the output ought to be 3D. Could you please state the meaning of combiner?

**Comment by yaochitc** [comment]
> Looks like in nn.keras.Embedding the output ought to be 3D. Could you please state the meaning of combiner?

The combiner used in the SparseEmbedding works as a aggregator which aggregate through the input(1) dimension.

**Comment by benjamim93** [comment]
In computeOutputShape() the shape of input is required to be in 2D. Thus the total number of elements should be input(0) * input(1). The embedding layer expands the integer indices into dimension of outputDim. In this way, the output shape becomes (input(0), input(1), outputDim). Am I correct?

Could you please indicate the path to find SparseEmbedding? I cannot find Embedding layer specially designed for sparse tensor. Only nn.keras.Embedding.

**Comment by yaochitc** [comment]
You are right, that's the logic in Embedding layer. But in SparseEmbedding, an aggregator is applied, so the input(1) dimension is aggregated.

The SparseEmbedding layer is in the analytics-zoo, and the full package name is com.intel.analytics.zoo.pipeline.api.keras.layers. Seems I should open an issue in that project.
