### ISSUE TITLE
bigdl-SPARK_2.3 package error

### ISSUE THREAD

**Issue by bjuthjliu** [intel-analytics/BigDL#2851]
Hello, as shown in the title,  I am using BigDL, the sbt is like:
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.3.0" withSources(),
  "org.apache.spark" %% "spark-sql" % "2.3.0" withSources(),
  "com.intel.analytics.bigdl" % "bigdl-SPARK_2.3" % "0.8.0"
)

and the scala code is the example of DLClassifierLogisticRegression:
when I use "sbt clean package", the error showed that
[error] missing or invalid dependency detected while loading class file 'DLEstimatorBase.class'.
[error] Could not access term param in package org.apache.spark.ml,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'DLEstimatorBase.class' was compiled against an incompatible version of org.apache.spark.ml.
[error] missing or invalid dependency detected while loading class file 'DLEstimatorBase.class'.
[error] Could not access type Estimator in package org.apache.spark.ml,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'DLEstimatorBase.class' was compiled against an incompatible version of org.apache.spark.ml.
[error] missing or invalid dependency detected while loading class file 'DLEstimatorBase.class'.
[error] Could not access type HasLabelCol in value org.apache.spark.ml.shared,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'DLEstimatorBase.class' was compiled against an incompatible version of org.apache.spark.ml.shared.
[error] missing or invalid dependency detected while loading class file 'HasFeaturesCol.class'.
[error] Could not access term param in package org.apache.spark.ml,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'HasFeaturesCol.class' was compiled against an incompatible version of org.apache.spark.ml.
[error] missing or invalid dependency detected while loading class file 'HasFeaturesCol.class'.
[error] Could not access type HasFeaturesCol in value org.apache.spark.ml.shared,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'HasFeaturesCol.class' was compiled against an incompatible version of org.apache.spark.ml.shared.
[error] missing or invalid dependency detected while loading class file 'HasPredictionCol.class'.
[error] Could not access term param in package org.apache.spark.ml,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'HasPredictionCol.class' was compiled against an incompatible version of org.apache.spark.ml.
[error] missing or invalid dependency detected while loading class file 'HasPredictionCol.class'.
[error] Could not access type HasPredictionCol in value org.apache.spark.ml.shared,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'HasPredictionCol.class' was compiled against an incompatible version of org.apache.spark.ml.shared.
[error] missing or invalid dependency detected while loading class file 'HasBatchSize.class'.
[error] Could not access type Params in value org.apache.spark.ml.param,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'HasBatchSize.class' was compiled against an incompatible version of org.apache.spark.ml.param.
[error] missing or invalid dependency detected while loading class file 'DLTransformerBase.class'.
[error] Could not access type Model in package org.apache.spark.ml,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'DLTransformerBase.class' was compiled against an incompatible version of org.apache.spark.ml.
[error] 9 errors found
[error] (compile:compileIncremental) Compilation failed

**Comment by Menooker** [comment]
Please try to add "org.apache.spark" %% "spark-mllib" % "2.3.0" to sbt dependency. Should be ok after adding mllib.

**Comment by bjuthjliu** [comment]
ok, the problem is fixed. thanks
