### ISSUE TITLE
When I performed the quantification,  inference speeddown

### ISSUE THREAD

**Issue by suhong1** [intel-analytics/BigDL#2875]
quantizedModel = model.quantize()
quantizedModel.predict(net_input_data)

Do I still need other settings?

**Comment by wzhongyuan** [comment]
did you run under MKL-BLAS or MKL-DNN ?

**Comment by suhong1** [comment]
I build a bigdl:default image:
sudo docker build --rm -t bigdl/bigdl:default .
my cpu is: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
How should I set it up?

**Comment by suhong1** [comment]
I have installed MKL-DNN

**Comment by wzhongyuan** [comment]
could you please share your model definition and also command/script you ran ?

**Comment by suhong1** [comment]
i use python
my model is resnet50
how and when to enable MKLDNN

**Comment by i8run** [comment]
Hi suhong. The MKL-DNN can be enabled by Java property `bigdl.engineType=mkldnn`. You can try to set the property. BigDL will run the MKL-DNN backend after that. If you set to `bigdl.engineType=mklblas`. It will run with original backend.

**Comment by suhong1** [comment]
If I load a tf model, can it be accelerated after quantification?

**Comment by suhong1** [comment]
i set bigdl.engineType=mkldnn,But it did not take effect

${SPARK_HOME}/bin/spark-submit \
  --master local[4] \
  --driver-memory ${DRIVER_MEMORY} \
  --conf "spark.serializer=org.apache.spark.serializer.JavaSerializer" \
  --conf "spark.network.timeout=1000000" \
  --executor-memory ${EXECUTOR_MEMORY} \
  --executor-cores ${EXECUTOR_CORES} \
  --num-executors ${EXECUTOR_NUMBER} \
  --total-executor-cores ${TOTAL_EXECUTOR_CORES} \
  --py-files /opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-0.10.0-SNAPSHOT-python-api.zip,1.py \
  --jars  /opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-SPARK_2.1-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
  --conf spark.driver.extraClassPath=/opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-SPARK_2.1-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
  --conf spark.executor.extraClassPath=/opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-SPARK_2.1-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
  --conf "spark.driver.extraJavaOptions=-Dbigdl.engineType=mkldnn -Dbigdl.mkldnn.fusion=true " \
  --conf "spark.executor.extraJavaOptions=-Dbigdl.engineType=mkldnn -Dbigdl.mkldnn.fusion=true" \
  test.py

**Comment by suhong1** [comment]
i set bigdl.engineType=mkldnn,But it did not take effect

${SPARK_HOME}/bin/spark-submit \
  --master local[4] \
  --driver-memory ${DRIVER_MEMORY} \
  --conf "spark.serializer=org.apache.spark.serializer.JavaSerializer" \
  --conf "spark.network.timeout=1000000" \
  --executor-memory ${EXECUTOR_MEMORY} \
  --executor-cores ${EXECUTOR_CORES} \
  --num-executors ${EXECUTOR_NUMBER} \
  --total-executor-cores ${TOTAL_EXECUTOR_CORES} \
  --py-files /opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-0.10.0-SNAPSHOT-python-api.zip,test.py \
  --jars  /opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-SPARK_2.1-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
  --conf spark.driver.extraClassPath=/opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-SPARK_2.1-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
  --conf spark.executor.extraClassPath=/opt/work/bigdl-0.10.0-SNAPSHOT/lib/bigdl-SPARK_2.1-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
  --conf "spark.driver.extraJavaOptions=-Dbigdl.engineType=mkldnn -Dbigdl.mkldnn.fusion=true " \
  --conf "spark.executor.extraJavaOptions=-Dbigdl.engineType=mkldnn -Dbigdl.mkldnn.fusion=true " \
  test.py

**Comment by i8run** [comment]
> If I load a tf model, can it be accelerated after quantification?

if you can load tf model successfully, then you can quantize it as normal.

Another question is, what's the CPU/platform you use ? Could you attach the Model Name of `lscpu` command ?

**Comment by suhong1** [comment]
root@3bd1a1fc7292:/opt/work#  lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Stepping:              1
CPU MHz:               1200.843
BogoMIPS:              4801.33
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55

**Comment by i8run** [comment]
OK. I found the root cause. Your CPU is Broadwell microarchitecture, which only supports the AVX2. But Int8 version of MKL-DNN mainly optimized with AVX-512. So the performance will downgrade when you use int8 inference compared with Float version. If you use Skylake, you will see the performance upgrade and Cascade Lake has more improvement.

**Comment by suhong1** [comment]
I changed a cpu, still the same problem
my cpu info:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                80
On-line CPU(s) list:   0-79
Thread(s) per core:    2
Core(s) per socket:    20
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Stepping:              4
CPU MHz:               1699.843
BogoMIPS:              3992.06
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              28160K
NUMA node0 CPU(s):     0-19,40-59
NUMA node1 CPU(s):     20-39,60-79


I see the log does not seem to use mkldnn：
Converting model now
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.loadRuntime ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.FCKernelDescInit ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.FCKernelLoadFromModel ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.FreeMemory ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.ConvKernelDescInit ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.ConvKernelLoadFromModel ... JNI]
Converting model successfully
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.ConvDataDescInit ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.ConvDataInit ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.MixPrecisionGEMM ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.FCDataDescInit ... JNI]
[Dynamic-linking native method com.intel.analytics.bigdl.bigquant.BigQuant.FCDataInit ... JNI]

**Comment by zhangxiaoli73** [comment]
@suhong1 it is weird. Can you share a piece of code to help us recur  this issue? Thanks.

**Comment by suhong1** [comment]
from bigdl.nn.layer import *
from timeit import default_timer as timer
from bigdl.nn.layer import *
from bigdl.util.common import *
from pyspark import SparkContext
from bigdl.util.common import Sample

sc = SparkContext.getOrCreate(conf=create_spark_conf())
init_engine()
model_def = "/home/resnet50_v2.pb"
inputs = ["net_input"]
outputs = ["net_output"]
image_u = np.ones((1,224,224,3), dtype=np.uint8)
label = np.array(1)
sample_u = Sample.from_ndarray(image_u, label)
predictSet = sc.parallelize([sample_u])
model = Model.load_tensorflow(model_def, inputs, outputs, byte_order = "little_endian",generated_backward=False, bigdl_type="float")
quantizedModel = model.quantize()
quantizedModel.predict(predictSet)

**Comment by zhangxiaoli73** [comment]
@suhong1 Sorry to inform you that we have not supported NHWC format with MKLDNN backend. So you can not enable tensorflow model with MKLDNN.
The issue is created https://github.com/intel-analytics/BigDL/issues/2901
You can follow up it and we will fix it in the future. Thanks.

**Comment by suhong1** [comment]
I changed a model,it's ok. thanks.
