### ISSUE TITLE
请问这个社区还有人维护么？

### ISSUE THREAD

**Issue by land1725** [intel-analytics/BigDL#2890]
麻烦问下，这个社区还有人维护么？真的是很喜欢bigdl的设计思想，分布式，cpu，但是提了问题，已经一周了，也没人回复我啊，这个怎么商用呢？我现在搞了bigdl，在商用系统，但是遇到问题了，连个回复的人都没有，我日报都写不出来，话说这个东西怎么普及呢？真诚的希望各位大佬看下github，回复一下我的问题，要不这个就只能被领导废弃使用了，解决问题的速度太慢了，跟不上项目进度

**Comment by wzhongyuan** [comment]
we are looking into them and will get back to you soon
