### ISSUE TITLE
when I use OpencvMat provided by BigDL， it occurs“java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat()”

### ISSUE THREAD

**Issue by linjiaqin** [intel-analytics/BigDL#2915]
**code：**
public class bigdlopencv {
    public static void main(String[] args) {
        OpenCVMat mat = new OpenCVMat();
        mat.create(224, 224, CvType.CV_8UC(3));
        mat.put(0, 0);
    }
}
**error information：**
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat()J
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:24)
	at com.intel.analytics.bigdl.transform.vision.image.opencv.OpenCVMat.<init>(OpenCVMat.scala:32)
	at com.flink.bigdlopoencv$.main(bigdlopoencv.scala:15)
	at com.flink.bigdlopoencv.main(bigdlopoencv.scala)

Do I need to install opencv locally or import any opencv jar in maven？

**Comment by benjamim93** [comment]
Hi , we are looking into this problem.

**Comment by benjamim93** [comment]
@i8run says adding com.intel.analytics.bigdl.opencv.OpenCV.isOpenCVLoaded() to your code like
'import com.intel.analytics.bigdl.opencv.OpenCV
OpenCV.isOpenCVLoaded();
OpenCVMat mat = new OpenCVMat();`

Please let me know if it works for you.

**Comment by linjiaqin** [comment]
> @i8run says adding com.intel.analytics.bigdl.opencv.OpenCV.isOpenCVLoaded() to your code like
> 'import com.intel.analytics.bigdl.opencv.OpenCV
> OpenCV.isOpenCVLoaded();
> OpenCVMat mat = new OpenCVMat();`
> 
> Please let me know if it works for you.

Ok, it works, thank you very much.

**Comment by linjiaqin** [comment]
@benjamim93 
Ok, it works, thank you very much.
