### ISSUE TITLE
Unable to adjust warmupEpoch for ResNet on CIFAR10

### ISSUE THREAD

**Issue by Blickwinkel1107** [intel-analytics/BigDL#2919]
No matter how I set the warmupEpoch for CIFAR10 training configuration, the "WarmupIteration" constantly reads 200.
It seems that warmup options does not appear in the source code "TrainCIFAR10.scala"

**Comment by i8run** [comment]
Yes. There's no warmup configuration for CIFAR10.

**Comment by Blickwinkel1107** [comment]
Is there any possibility to see it get fixed?

**Comment by i8run** [comment]
In fact, the `warmupEpoch` is just for training ResNet-50 on ImageNet. If you want to this param working on TrainingCIFAR10, you need to change the [code](https://github.com/intel-analytics/BigDL/blob/6f90aed993f6a07210ecc4749ddd1f492857e7d4/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/resnet/TrainCIFAR10.scala#L79) based on the [TrainImageNet](https://github.com/intel-analytics/BigDL/blob/6f90aed993f6a07210ecc4749ddd1f492857e7d4/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/resnet/TrainImageNet.scala#L102).

**Comment by Blickwinkel1107** [comment]
Got it, thanks

**Comment by i8run** [comment]
I'll close this issue, if you have more issues on this please feel free to reopen it.
