### ISSUE TITLE
Python TimeDistributedCriterion() lack of parameter of dimension

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#2922]
TimeDistributedCriterion constructor in Python lacks of dimension parameter. It cannot specify the dimension if the dimension parameter is not default(2).
In Scala API:
TimeDistributedCriterion(
    critrn: TensorCriterion[T] = null, sizeAverage: Boolean = false, dimension: Int = 2)
But Python API:
def __init__(self, criterion, size_average=False, bigdl_type="float")

**Comment by wzhongyuan** [comment]
@jenniew  thanks, will take a look

**Comment by wzhongyuan** [comment]
@lingxiao1989  Please add your related PR link here

**Comment by lingxiao1989** [comment]
PR link:
https://github.com/intel-analytics/BigDL/pull/2940
