### ISSUE TITLE
What this message about mkl means in BigDL?

### ISSUE THREAD

**Issue by Zarca** [intel-analytics/BigDL#2988]
Hello, I'm using BigDL in my nlp projects  in CentOS 7 recently.However, I found it that my bigdl program appers to  be a bit slower than Tensorflow(CPU) in deep learning stage.
So I'm not sure whether my bigdl program have take advantages of mkl library to get better performance...
What this message about mkl means while my program running?Dose it means that my CentOS already have the mkl library  and it is already in use?
![bigdl issue](https://user-images.githubusercontent.com/24642659/71235674-cd22ba00-2337-11ea-9c51-c249f328453b.png)

**Comment by Zarca** [comment]
And I also notice that my bigdl program is slower than tensorflow(cpu version) in the same test environment even after optimization over the Spark configuration, so  how can I get a better performance compared with tensforflow on cpu?

**Comment by zhangxiaoli73** [comment]
Hi, please try to set bigdl.engineType=mkldnn. Hope those can help you. Thanks.
