### ISSUE TITLE
Enable DistriOptimizerV2

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#2999]
- [x] Create `DistriOptimizerV2` in factory method (per user-specified argument)
- [x] Enabled `DistriOptimizerV2` in Scala and Python examples (per user-specified argument)
- [x] Test performance and convergence using `DistriOptimizerV2`

**Comment by qiuxin2012** [comment]
For the factory method, shall we use a DistriOptimizerFactory like this [ModelBroadcastFactory](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcastFactory.scala) in [ModelBroadcast](https://github.com/intel-analytics/BigDL/blob/4fe75f5f5f20cfeafde46afd4f1dbafbee4c540f/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala#L75). And set the default value to DistriOptimizerV2. @jason-dai

**Comment by jason-dai** [comment]
> For the factory method, shall we use a DistriOptimizerFactory like this [ModelBroadcastFactory](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcastFactory.scala) in [ModelBroadcast](https://github.com/intel-analytics/BigDL/blob/4fe75f5f5f20cfeafde46afd4f1dbafbee4c540f/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala#L75). And set the default value to DistriOptimizerV2. @jason-dai

I was referring to `Optimizer.apply`; we can add an argument (e.g., `V2`) which default to false.

**Comment by qiuxin2012** [comment]
> > For the factory method, shall we use a DistriOptimizerFactory like this [ModelBroadcastFactory](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcastFactory.scala) in [ModelBroadcast](https://github.com/intel-analytics/BigDL/blob/4fe75f5f5f20cfeafde46afd4f1dbafbee4c540f/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala#L75). And set the default value to DistriOptimizerV2. @jason-dai
> 
> I was referring to `Optimizer.apply`; we can add an argument (e.g., `V2`) in this method which default to false.

There is 3 `Optimizer.apply` function, add a optional argument will lead to "multiple overloaded alternatives of method apply define default arguments". If we add a general arguments, the API will be not compatible with old code.

**Comment by jason-dai** [comment]
> > > For the factory method, shall we use a DistriOptimizerFactory like this [ModelBroadcastFactory](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcastFactory.scala) in [ModelBroadcast](https://github.com/intel-analytics/BigDL/blob/4fe75f5f5f20cfeafde46afd4f1dbafbee4c540f/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala#L75). And set the default value to DistriOptimizerV2. @jason-dai
> > 
> > 
> > I was referring to `Optimizer.apply`; we can add an argument (e.g., `V2`) in this method which default to false.
> 
> There is 3 `Optimizer.apply` function, add a optional argument will lead to "multiple overloaded alternatives of method apply define default arguments". If we add a general arguments, the API will be not compatible with old code.

Then maybe add an variable in `Engine`, and change `new DistriOptimizer[T](...)` to `DistriOptimizer.apply()` which checks that variable internally?

**Comment by Le-Zheng** [comment]
> > > > For the factory method, shall we use a DistriOptimizerFactory like this [ModelBroadcastFactory](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcastFactory.scala) in [ModelBroadcast](https://github.com/intel-analytics/BigDL/blob/4fe75f5f5f20cfeafde46afd4f1dbafbee4c540f/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala#L75). And set the default value to DistriOptimizerV2. @jason-dai
> > > 
> > > 
> > > I was referring to `Optimizer.apply`; we can add an argument (e.g., `V2`) in this method which default to false.
> > 
> > 
> > There is 3 `Optimizer.apply` function, add a optional argument will lead to "multiple overloaded alternatives of method apply define default arguments". If we add a general arguments, the API will be not compatible with old code.
> 
> Then maybe add an variable in `Engine`, and change `new DistriOptimizer[T](...)` to `DistriOptimizer.apply()` which checks that variable internally?

Many thanks. I will have a try.
