### ISSUE TITLE
Select() Layer

### ISSUE THREAD

**Issue by m-developer96** [intel-analytics/BigDL#3018]
Hi everyone!

I can't figure out exactly what this function does! And also in its documentation, it's noted that the dimension and index start from 1 but in this example index set to -1.
Could anyone explain this function, please?

` model.add(Recurrent().add(LSTM(embedding_dim, 128, p)))
`
`  model.add(Select(2, -1))`

Thanks :)

**Comment by yangw1234** [comment]
I think `Select(2, -1)` means "selecting" the last (-1) slice of second (2) dimension of the tensor. E.g. the input to `Select` has shape [4, 3, 2, 1], then Select(2, -1) will return a tensor of shape [4, 2, 1].
