### ISSUE TITLE
How can I update word embeddings during training?

### ISSUE THREAD

**Issue by m-developer96** [intel-analytics/BigDL#3044]
Hi everyone :)

I'm working on sentiment analysis and I want to implement an embedding layer like Keras `Embedding()` layer that my word embeddings get updated during the training.
I set up my model with `GRU` and test it but my inputs didn't get updated. 
So I searched for an embedding layer like Keras and I found `LookupTable()` (I don't know that if this layer does the same work as Keras embedding layer). But in the official documentation, it was not explained parameters of this layer and I couldn't understand them. And also I searched for an example of using that but I couldn't find anything.
Could anyone guide me about this layer and the way of its work plz?

Thanks.

**Comment by hkvision** [comment]
LookupTable is equivalent to use Embedding, but the index labels are suppose to start from 1.

I highly recommend you to switch to the Keras style API provided by Analytics Zoo: https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/pipeline/api/keras 
Jason also suggested you in the previous post: https://github.com/intel-analytics/BigDL/issues/3039
Please take our advice.

If you use the Keras style API, we can better support you and you won't have so much pain in understanding the layer meanings and encounter bugs from time to time.

**Comment by m-developer96** [comment]
I tried to use it but I got errors at first and I couldn't solve it. I'm using standalone cluster mode in Jupyter and in `Analytics Zoo` I didn't know how to set master URL and my spark conf.
Could you guide me plz?
How should I start engine?

**Comment by m-developer96** [comment]
@hkvision 
I used this method `init_spark_standalone()` but I got this error:

`name 'init_spark_standalone' is not defined`

**Comment by hkvision** [comment]
init_spark_standalone is still work in progress and not available in the release package yet.
https://analytics-zoo.github.io/master/#PythonUserGuide/run/#run-with-jupyter-notebook You can refer to here, change master address to your standalone master URL.
You can also find some useful documentation in the website. Please take some time to get familiar.

**Comment by m-developer96** [comment]
Thanks!
Isn't it possible to set spark conf in `init_nncontext()` ?
I set this conf:
```
conf=SparkConf()
conf.set("spark.app.name","sentiment")
conf.set("spark.driver.memory", "23400m")
conf.set("spark.cores.max", "16")
conf.set("spark.executor.memory", "11700m")
conf.set("spark.executor.cores", "8")
conf.set("spark.executor.instances", "16")
conf.set("spark.rpc.message.maxSize","1024")
conf.set("spark.driver.extraJavaOptions","-Djava.io.tmpdir=~/workTable/temp/")
conf.set("spark.executor.extraJavaOptions","-Djava.io.tmpdir=~/workTable/temp/")
```
But when I execute `init_nncontext(conf=conf)`, it says to me :
`requirement failed: Engine.init: Can't find executor core number, do you submit with --executor-cores option`

Do I have to set all conf like `executor-cores` via command?

**Comment by hkvision** [comment]
In the spark-submit settings, the sc is created at the submit time and thus the conf you set after creating the sc won't take effect. You are recommended to specify executor cores at submit time.

**Comment by m-developer96** [comment]
@hkvision 
Thanks!

**Comment by hkvision** [comment]
You are welcome!
