### ISSUE TITLE
什么时候解决刷star的bug? When you fix the bug that you buy stars?

### ISSUE THREAD

**Issue by Asshasahole** [intel-analytics/BigDL#3050]

**Comment by PragmaTwice** [comment]
@helenlly You shouldn't close it without explaining.

ref to https://www.v2ex.com/t/699097

**Comment by jason-dai** [comment]
Thanks for the information; we'll definitely look into this.

**Comment by jason-dai** [comment]
@Asshasahole @PragmaTwice Thanks a lot for raising the issue; we certainly do not agree with this type of activity and have discouraged it. On the other hand, we cannot confirm it is directly affiliated or related to the project at this moment, and so I’m closing the issue for now. Feel free to reopen it if you have additional information.
