### ISSUE TITLE
Getting compilation errors in make_dist.sh

### ISSUE THREAD

**Issue by shadyonfire** [intel-analytics/BigDL#3058]
I have been trying to compile the code but i have been getting compilation errors.
I think it is pom.xml issue. 
Can someone provide me a pom.xml for spark 2.3.1 and scala 2.11 and maven 3.
Thanks.need it asap.

**Comment by Le-Zheng** [comment]
Hi @shadyonfire 
If you have cloned this repo, you can compile with `./make-dist.sh -P spark_2.x` at the top level of this repo folder.

**Comment by Le-Zheng** [comment]
Or compile with specifying spark version  `./make-dist.sh -P spark_2.x -Dspark.version=2.3.1`

**Comment by shadyonfire** [comment]
Thanks, that helped.
