### ISSUE TITLE
python support version is not clear in BigDL doc website

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/BigDL#3059]
https://bigdl-project.github.io/master/#PythonUserGuide/run-without-pip/#remark

“Remark
Only Python 2.7, Python 3.5 and Python 3.6 are supported for now.
Note that Python 3.6 is only compatible with Spark 1.6.4, 2.0.3, 2.1.1, 2.2 and 2.3. See this issue for more discussion.”

**Comment by hkvision** [comment]
Just follow the doc of analytics-zoo: https://analytics-zoo.github.io/master/#PythonUserGuide/install/
This is clear.
