### ISSUE TITLE
UT: optim test failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/BigDL#3084]
Regression
com.intel.analytics.bigdl.optim.PredictionServiceSpec.PredictionService should work properly with concurrent calls

Error Message
false did not equal true

jenkins link:
http://10.239.47.210:18080/job/BigDL-NB-scalatest-optim-Spark-2.4/730/

**Comment by Le-Zheng** [comment]
This is a random error.  
Error info: PredictionService-should work properly with concurrent calls *** FAILED *** false did not equal true (PredictionServiceSpec.scala:146) https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/test/scala/com/intel/analytics/bigdl/optim/PredictionServiceSpec.scala#L146
This line just checks the output length. It doesn't reproduce the exact error on local testing. 
@qiuxin2012 could you help to have a look?
