### ISSUE TITLE
make-dist failed on openjdk-11

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/BigDL#3086]
```
+ MVN_OPTS_LIST='-Xmx2g -XX:ReservedCodeCacheSize=512m'
+ [[ -n java ]]
++ java -version
++ awk -F '"' '/version/ {print $2}'
+ version=11.0.8
+ [[ 11.0.8 < 1.7 ]]
+ echo Require a java version not lower than 1.7
Require a java version not lower than 1.7

```

**Comment by Le-Zheng** [comment]
If you would like to compile with jdk11, replace our default jdk1.8 in pom.xml with:
```
<java.version>11</java.version>
<javac.version>11</javac.version>
<maven.compiler.source>1.6</maven.compiler.source>
<maven.compiler.target>1.6</maven.compiler.target>
```

And it is required to download **Oracle jdk**. Currently, openjdk11 has a problem with maven-enforcer-plugin. What's more, Scala 2.11 can not work with jdk11. We are recommended to use jdk 11 with Scala 2.12 and Spark3.

**Comment by Le-Zheng** [comment]
Follow this guide to compile with jdk 11 https://bigdl-project.github.io/master/#ScalaUserGuide/install-build-src/#build-with-jdk-11
