### ISSUE TITLE
How to implement graph neural network 

### ISSUE THREAD

**Issue by doofin** [intel-analytics/BigDL#3103]
Hi,Is it possible to construct a computation graph dynamically to allow easy implementation of graph neural networks?

**Comment by qiuxin2012** [comment]
You can try our another project analytics-zoo https://github.com/intel-analytics/analytics-zoo who support pytorch and TF.

**Comment by helenlly** [comment]
@doofin any more questions?

**Comment by doofin** [comment]
Thanks!,closing now
