### ISSUE TITLE
How to user define keras layer use bigdl

### ISSUE THREAD

**Issue by mullerhai** [intel-analytics/BigDL#3105]
HI, I want to use bigdl  to define memoryNetWork Layer or   transformer Layer like  keras   style,
but I find the kerasLayer in bigdl is package private ,can't use for  use, is it correct ?

**Comment by jason-dai** [comment]
See the official support of the Keras API for BigDL at https://analytics-zoo.github.io/master/#KerasStyleAPIGuide/keras-api-scala/
