### ISSUE TITLE
no module named 'bigdl' after pip3 install bigdl

### ISSUE THREAD

**Issue by KimiLiuQh** [intel-analytics/BigDL#3108]
After I use `pip3 install bigdl` and try to `import bigdl` in python, the error message says `ModuleNotFoundError: No module named 'bigdl' `.
`pip3 freeze | grep BigDL` tells `BigDL==0.12.1`
`which python` tells `/home/qihong/anaconda3/envs/py36/bin/python`
`which pip3` tells `/usr/bin/pip3`
All the action are done under my conda environment `py36`

**Comment by qiuxin2012** [comment]
You can check your environment `PATH`,  it seems `/usr/bin/pip3` is in front of `/home/qihong/anaconda3/envs/py36/bin/pip3` in the `PATH`. 
BTW: when you run `pip install`,  you can see where the whl is installed, in your conda env or system python.

**Comment by Adamage** [comment]
You installed in the wrong Python. Make sure you always separate from the system installation either by using package manager like Conda, Pyenv, Venv or by usage of environmental variables and aliases.
