### ISSUE TITLE
Chronos project readme should be updated

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#3177]
https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/chronos/src/bigdl/chronos/README.md

**Comment by TheaperDeng** [comment]
I think I may just remove this readme later since nearly all (if not all, more up-to-date) information is stated in our user guide.

**Comment by jason-dai** [comment]
Yes, we may remove it; all documents should go to bigdl.readthedocs.io
