### ISSUE TITLE
Chronos user guide

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#3198]
https://github.com/intel-analytics/BigDL/blob/branch-2.0/docs/readthedocs/source/doc/Chronos/Overview/chronos.md

1) Overview
2) Install
3) Run
4) Get Started

**Comment by TheaperDeng** [comment]
> https://github.com/intel-analytics/BigDL/blob/branch-2.0/docs/readthedocs/source/doc/Chronos/Overview/chronos.md
> 
> 1. Overview
> 2. Install
> 3. Run
> 4. Get Started

What's the general content/meaning for 
3. **Run**
4. **Get Started**

So basically what I understand is 
3. **Run**: Some thing like original Initialization section https://github.com/intel-analytics/BigDL/blob/branch-2.0/docs/readthedocs/source/doc/Chronos/Overview/chronos.md#3-initialization.
4. **Get Started**: Some thing like the repo readme.md https://github.com/intel-analytics/BigDL#getting-started-with-chronos and maybe add some get started example for detection(and simulation).
