### ISSUE TITLE
Cannot build the project. Use a maven xml in a internal server(10.239.45.219).

### ISSUE THREAD

**Issue by lizhizhou** [intel-analytics/BigDL#326]
Downloading: http://10.239.45.219:8081/content/groups/public/com/intel/analytics/bigdl/native/mkl-java/0.1.0-SNAPSHOT/maven-metadata.xml

**Comment by yiheng** [comment]
We're working on publish the maven artifacts. It will come soon.

**Comment by yiheng** [comment]
Another option is do a full build: https://github.com/intel-analytics/BigDL/wiki/Build-Page#full-build , which requires MKL install on your machine. 

The default build will skip the build of native code, and try to download the pre-build package from maven.

**Comment by jason-dai** [comment]
Updated the [full build page](https://github.com/intel-analytics/BigDL/wiki/Build-Page#full-build) with a free Parallel Studio for qualified open source contributors.

**Comment by lizhizhou** [comment]
Thanks.

**Comment by kiminh** [comment]
Is the maven artifacts available on http://mvnrepository.com/? Thanks.

**Comment by sundapeng** [comment]
Hi @yiheng , I have the experience of publishing Intel Chimera (Now is Apache Commons Crypto) to oss.sonatype.org, I'd like to share with you if needed.

**Comment by yiheng** [comment]
Hi @lizhizhou and @kiminh 
We have uploaded the artifacts to SonaType(a public maven repo and also a source of maven central). The internal repo has been replaced by the public repo. So now you can pull the latest code and build it. Please refer to the build page(https://github.com/intel-analytics/BigDL/wiki/Build-Page) for details.

We want temporarily keep the snapshot suffix so haven't released it to Maven Central.

**Comment by yiheng** [comment]
Hi @sundapeng 
It's very nice of you:). Definitely very appreciate for your experience share. Let's find another channel to discussion.

**Comment by yiheng** [comment]
Let me close the issue.
