### ISSUE TITLE
`bigdl-orca[automl]`, `bigdl-chronos` and `bigdl-chronos[all]` need more thorough tests 

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/BigDL#3322]
We need to test the below dependency options with a new conda environment with only python installed and make sure corresponding tests passed.

- [x] `bigdl-orca[automl]`: all example tests

- [x] `bigdl-chronos` : all example tests and app tests (including use-case and quick start) except for
  - tensorflow based forecasters and anomaly detectors 
  - distributed forecasters with ray backend
  - `AutoTS`

- [x] `bigdl-chronos[all]`: all example tests and app tests

We could first test on local and enable Jenkins jobs later. 
We need to check both the necessary packages and their versions. We should record the missing dependencies and wrong version with comments in this issue.

**Comment by liangs6212** [comment]
Related tests and packages that need to be installed manually
bigdl-chronos\bigdl-chronos[all]:
* prophet pmdarima(forecaster)
* pytorch-lightning(simalator)
* tsfresh(tsdata)
* pyarrow(tsdata/file)
bigdl-orca:
* torch

**Comment by TheaperDeng** [comment]
> Related tests and packages that need to be installed manually bigdl-chronos\bigdl-chronos[all]:
> 
> * prophet pmdarima(forecaster)
> * pytorch-lightning(simulator)
> * tsfresh(tsdata)
> * pyarrow(tsdata/file)
> 
> bigdl-orca:
> 
> * torch

bigdl-chronos
- prophet and pmdarima will be optional and code warning to prompt users to install them if needed
- pytorch-lightning will be a required module once nano is integrated
- tsfresh will be lazily imported #3356 
- pyarrow will be optional as well since it only affect from_parquet

bigdl-orca:
- torch will be optional once logger is lazily imported #3360

**Comment by yushan111** [comment]
We need to add warnings to prompt users to install the below packages
For Chronos
- [ ] `prophet`
- [ ] `pmdarima`

For bigdl-orca

- [ ] torch 
- [ ] tensorflow
- [ ] `xgboost` should also be lazily imported and add install prompts
