### ISSUE TITLE
Remove the spark3 name in whls built on top of spark3?

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#3323]
Whether we need to differ the project names by `-spark3`.

One potential issue of doing this I can think of now is if users wrongly mix the whls built on top of spark2 and spark3, for example using the spark3 dllib and spark2 orca, there will be no way to identify this misusage right? Any suggestions on this? @yangw1234 @jason-dai  @Le-Zheng 
Using the same name is also hard to manage. I would suggest using different names. We can add some doc in python guide to assist users to install whls on spark3.

**Comment by yizerozhuang** [comment]
install step for bigdl on spark 3.1.2
```
pip install https://sourceforge.net/projects/analytics-zoo/files/orca-py/bigdl_orca-0.14.0b20211107-py3-none-manylinux1_x86_64.whl
pip install https://sourceforge.net/projects/analytics-zoo/files/dllib-py/bigdl_dllib-0.14.0b20211107-py3-none-manylinux1_x86_64.whl
pip install https://sourceforge.net/projects/analytics-zoo/files/friesian-py/bigdl_friesian-0.14.0b20211107-py3-none-manylinux1_x86_64.whl
```
