### ISSUE TITLE
Permission issue when building bigdl-tf

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#3372]
If I'm not the root, when I build bigdl-tf, I will get the following error when executing `patchelf`:
```
open: Permission denied
```
If I add sudo for the release script, the `patchelf` command can run successfully, but I will get the following error:
```
Packing python distribution: python setup.py bdist_wheel --plat-name manylinux2010_x86_64 --python-tag py3
/home/kai/BigDL/python/tflibs/dev/release.sh: line 85: python: command not found
```

One option is to add sudo to the two `patchelf` commands, but this may require users to input the password during the build process.
May need to fix this issue for the convenient of users.
@yangw1234 @leonardozcm

**Comment by yangw1234** [comment]
Should we just fixed the `tflibs` version and do not change it until necessary? I do not see the reason why we have to build it very time. 

What's your thoughts?@hkvision

**Comment by hkvision** [comment]
I think so. So we create a separate job for releasing tf and math (say 0.1.0) and fix the version dependency in orca, is it ok?

**Comment by hkvision** [comment]
Fixed. Now building bigdl don't need to build tf/math. This issue still exists when building tf, so it is low priority and may be added somewhere for guidance.

**Comment by hkvision** [comment]
Added a comment in jenkins. Closing this issue.
