### ISSUE TITLE
Typo(Duplicated) inside wiki Build Page

### ISSUE THREAD

**Issue by linbojin** [intel-analytics/BigDL#339]
https://github.com/intel-analytics/BigDL/wiki/Build-Page#full-build

Note **that the instructions above will skip the build of native library code, and pulled the corresponding library from Maven Central. That the instructions above will skip the build of native library code, and pull the corresponding library from Maven Central.** If you want to build the the native library code by yourself, follow the steps below...

**Comment by psyyz10** [comment]
Fixed. Thanks for your issue :-)
