### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#340]
The native code of BigDL is only compiled on Linux-x64 platform. This is not convenient for MacOSdeveloper to develop or test code.

Pre-build native package should be supported on MacOS platform.

**Comment by wydwww** [comment]
.jar for macOS is done.

**Comment by yiheng** [comment]
Instead of provide different jar, we can package linux so file and macOS so file into one jar and load different so based on the current OS. Somewhere might be changed: https://github.com/intel-analytics/BigDL/blob/master/native/jni/src/main/java/com/intel/analytics/bigdl/mkl/MKL.java#L20

**Comment by jason-dai** [comment]
The downside of this approach is that the resulting jar can be too big though

**Comment by wydwww** [comment]
In macOS it's actually libiomp5.dylib instead of libiomp5.so @yiheng

**Comment by jason-dai** [comment]
I don't think we need windows support at this moment, yes?
