### ISSUE TITLE
The engine need to automatically detect the number of nodes/cores used for Spark

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#352]
The engine need to automatically detect the number of nodes/cores used for Spark

**Comment by yiheng** [comment]
Currently, I find:

Assume that user run their application on Spark by using spark-submit command, the SparkSubmit class will set conf in system property.

In the Engine.init() code:
Check if "SPARK_SUBMIT" is true. If not, it's not on Spark. Set the core number to half of total cores(avoid HT) or user specified value(env vars?). Set node number = 1. Set a new flag mode to local.

if it's on Spark, then:
Check "spark.master". If it's local, parse its cores number from pattern "local[n]", set node number to 1
if it's yarn|yarn-client|yarn-cluster, check "spark.executor.instances" for node number, check "spark.executor.cores" for core number
if it start with "spark", check "spark.executor.cores" for core number, use "spark.cores.max" / core number to get node number
if it start with "mesos", same with standalone.

The question is what if user didn't set these property with spark-submit options?

**Comment by linbojin** [comment]
In our use case, we check spark cluster master ui api to get cores or nodes info, ex, http://ip:8080/json/

**Comment by jason-dai** [comment]
Fixed via #380
