### ISSUE TITLE
extra_python_lib issue

### ISSUE THREAD

**Issue by gganduu** [intel-analytics/BigDL#3549]
My pytorch-based code contains several .py files and folders:

train.py (main function)

yaml_dict.py

models

​ - model.py

When training using az-local mode with backend="torch_distributed", it works well.

But when using az-k8s mode w/o backend="torch_distributed, it can not import other .py files.

My init_orca_context is defined as :

init_orca_context(
                        cluster_mode="k8s", 
                        master="k8s://https://172.16.212.154:6443",
                        container_image="ielym/test:az-k8s-v2",
                        num_nodes=2, 
                        memory="30g", 
                        cores=8,
                        conf={
                            "spark.driver.host": "172.16.212.154",
                            "spark.driver.port": "54323",
                            "spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.options.claimName":"nfsvolumeclaim",
                            "spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.mount.path": "/zoo/data",
                            "spark.kubernetes.executor.label.aztest": "1"
                        },
                        extra_python_lib="yaml_dict.py"
            )
I have set the extra_python_lib="yaml_dict.py" in init_orca_context function. However, the execute results raised ModuleNotFoundError: No module named 'yaml_dict'

So, how to solve this issue. Besides, how to import .py files from other folders?

**Comment by glorysdj** [comment]
need to put yaml_dict.py in the docker image, or put in the persistentVolume you mounted as /zoo/data

**Comment by gganduu** [comment]
this issue has been fixed when move all to /zoo/data
