### ISSUE TITLE
decouple ray based estimator from RayContext (pytorch)

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#3560]
The first step to support ray only estimators.

**Comment by jason-dai** [comment]
What do you mean by Ray only estimator? We already have estimators built on Ray.

**Comment by yangw1234** [comment]
> What do you mean by Ray only estimator? We already have estimators built on Ray.

Currently, our estimators rely on spark. By "Ray only estimators", I mean estimator can work without spark requested by Mastercard.
