### ISSUE TITLE
Warning when running Colab notebook "Enable AutoML for PyTorch" and "Use AutoXGBoost to auto-tune XGBoost parameters"

### ISSUE THREAD

**Issue by DirkFi** [intel-analytics/BigDL#3566]
When I tried to test Colab notebook "Use AutoXGBoost to auto-tune XGBoost parameters", I got a warning when the code calls function 
AutoXGBRegressor.

> (raylet) Traceback (most recent call last):
(raylet)   File "/usr/local/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 334, in <module>
(raylet)     raise e
(raylet)   File "/usr/local/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 323, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/usr/local/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 124, in run
(raylet)     dashboard_consts.RETRY_REDIS_CONNECTION_TIMES)
(raylet)   File "/usr/local/lib/python3.7/site-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
(raylet)     return await aioredis.create_redis_pool(
> (raylet) AttributeError: module 'aioredis' has no attribute 'create_redis_pool'

The same error occurred when I ran Colab notebook "Enable AutoML for PyTorch".

I checked some information on the website. The warning may be caused by version of aioredis, but after I changed its version from 2.0 to 1.3 another error occurred.
>TypeError: init() got an unexpected keyword argument 'loop'

**Comment by Le-Zheng** [comment]
Which notebook did you run? I noticed `aioredis` that chronos specified is 1.3.1 https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/chronos/src/setup.py#L58, could you try to downgrade to `aioredis==1.1.0`.

**Comment by DirkFi** [comment]
I ran [autoestimator_pytorch_lenet_mnist](https://colab.research.google.com/github/intel-analytics/BigDL/blob/branch-2.0/python/orca/colab-notebook/quickstart/autoestimator_pytorch_lenet_mnist.ipynb) and [autoxgboost_regressor_sklearn_boston](https://colab.research.google.com/github/intel-analytics/BigDL/blob/branch-2.0/python/orca/colab-notebook/quickstart/autoxgboost_regressor_sklearn_boston.ipynb).

**Comment by DirkFi** [comment]
After downgrading to 1.1.0, this error occurred when the code tries to define \__init__(self, fc1_hidden_size=500).

> TypeError: init() got an unexpected keyword argument 'loop'

**Comment by Le-Zheng** [comment]
> After downgrading to 1.1.0, this error occurred when the code tries to define __init__(self, fc1_hidden_size=500).
> 
> > TypeError: init() got an unexpected keyword argument 'loop'

Ok, we will look into it. @yushan111

**Comment by yushan111** [comment]
Thank you for reporting the issue.

The error is caused by the latest version of `aiohttp` and `aioredis`, and we have fixed the version of these two packages in our latest nightly-built BigDL (PR #3577).

You could try the colab notebooks again, and the issue should be gone.

**Comment by DirkFi** [comment]
Thanks for all. After your update, the errors have been gone.
