### ISSUE TITLE
Nano: some env variables fails to be set by bigdl-nano-init

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#3568]
I install the latest version of bigdl-nano(0.14.0b2021112311) and run `source bigdl-nano-init` on my own dev server (i7-9700)

```bash
(nano) junweid@junweid-Z390-AORUS-ELITE:~/bug-reproduce$ source bigdl-nano-init
conda dir found: /home/junweid/miniconda3/envs/nano/bin/..
OpenMP library found...
Setting OMP_NUM_THREADS...
Setting OMP_NUM_THREADS specified for pytorch...
Setting KMP_AFFINITY...
Setting KMP_BLOCKTIME...
Setting MALLOC_CONF...
Setting LD_PRELOAD...
+++++ Env Variables +++++
LD_PRELOAD=/home/junweid/miniconda3/envs/nano/bin/../lib/libiomp5.so /home/junweid/miniconda3/envs/nano/bin/../lib/python3.7/site-packages/bigdl/nano//libs/libtcmalloc.so
MALLOC_CONF=
OMP_NUM_THREADS=0
KMP_AFFINITY=granularity=fine,compact
KMP_BLOCKTIME=1
TF_ENABLE_ONEDNN_OPTS=
+++++++++++++++++++++++++
Complete.
```
Well, clearly OMP_NUM_THREADS is not the best setting... I am not sure about the others

**Comment by yangw1234** [comment]
@charlieJ107 could you help look at this?

**Comment by charlieJ107** [comment]
This problem is due to the fact that the system language is not set to English, so that when `bigdl-nano-init` scripts get cpu information, they can not find the corresponding information directly by using `lscpu` and `grep`. 
In fact, this problem will occur in any environment where the system language is not set to English, or `lscpu` cannot find the `Core (s) per socket` and `Thread (s) per core` fields.

**Comment by TheaperDeng** [comment]
https://pypi.org/project/py-cpuinfo/
(inspired by https://github.com/intel/neural-compressor/blob/b5a84e7c3672047db7b3a13733140bc9eafe882c/neural_compressor/ux/utils/hw_info.py#L30) might be a solution

**Comment by yangw1234** [comment]
how about just copying this file 

> https://pypi.org/project/py-cpuinfo/ (inspired by https://github.com/intel/neural-compressor/blob/b5a84e7c3672047db7b3a13733140bc9eafe882c/neural_compressor/ux/utils/hw_info.py#L30) might be a solution

Does this solve the problem? py-cpuinfo cannot get the number of sockets. INC still use linux/windows cmd to get the information. (see https://github.com/intel/neural-compressor/blob/master/neural_compressor/ux/utils/hw_info.py#L121)

**Comment by TheaperDeng** [comment]
> how about just copying this file
> 
> > https://pypi.org/project/py-cpuinfo/ (inspired by https://github.com/intel/neural-compressor/blob/b5a84e7c3672047db7b3a13733140bc9eafe882c/neural_compressor/ux/utils/hw_info.py#L30) might be a solution
> 
> Does this solve the problem? py-cpuinfo cannot get the number of sockets. INC still use linux/windows cmd to get the information. (see https://github.com/intel/neural-compressor/blob/master/neural_compressor/ux/utils/hw_info.py#L121)

Just noticed this reply. Yes, use cmd to get information does not work on a CN system. When I use INC on my CN system I changed the source code in https://github.com/intel/neural-compressor/blob/master/neural_compressor/ux/utils/hw_info.py#L121. So we need other solutions...

**Comment by jason-dai** [comment]
How about `os.cpu_count()`, `multiprocessing.cpu_count()`, or https://github.com/workhorsy/py-cpuinfo?

**Comment by TheaperDeng** [comment]
> How about `os.cpu_count()`, `multiprocessing.cpu_count()`, or https://github.com/workhorsy/py-cpuinfo?

It seems that all these three can not get socket num?

**Comment by yangw1234** [comment]
does `lscpu -p=sockets,cpu` solve this problem. @charlieJ107 @TheaperDeng 

I do not have environment to experiment.

![image](https://user-images.githubusercontent.com/10561966/148359154-b39d3be0-527b-489e-b327-6a4a7b3609b2.png)

**Comment by TheaperDeng** [comment]
Oh I think that could work. @yangw1234 
![image](https://user-images.githubusercontent.com/35031544/148359453-b8cbfdb2-9987-4a8d-a80e-c73b124dbeab.png)

**Comment by TheaperDeng** [comment]
Currently it reports:
```bash
(nano-test) junweid@junweid-Z390-AORUS-ELITE:~$ bigdl-nano-init
conda dir found: /home/junweid/miniconda3/envs/nano-test/bin/../
OpenMP library found...
/home/junweid/miniconda3/envs/nano-test/bin/bigdl-nano-init: 行 134: let: cores_per_socket=8/: 语法错误: 需要操作数 (错误符号是 "/")
Setting OMP_NUM_THREADS...
Setting OMP_NUM_THREADS specified for pytorch...
Setting KMP_AFFINITY...
Setting KMP_BLOCKTIME...
Setting MALLOC_CONF...
Setting LD_PRELOAD...
+++++ Env Variables +++++
LD_PRELOAD=/home/junweid/miniconda3/envs/nano-test/bin/..//lib/libiomp5.so /home/junweid/miniconda3/envs/nano-test/bin/..//lib/python3.7/site-packages/bigdl/nano//libs/libtcmalloc.so
MALLOC_CONF=
OMP_NUM_THREADS=0
KMP_AFFINITY=granularity=fine,compact
KMP_BLOCKTIME=1
TF_ENABLE_ONEDNN_OPTS=
+++++++++++++++++++++++++
Complete.
```
I think it's a typo in the code https://github.com/intel-analytics/BigDL/pull/3851/files#r781724019

**Comment by TheaperDeng** [comment]
Thank you all for the working. It can now be successfully run on a CN Ubuntu1804 with i7-9700. I think we are good for now.

![image](https://user-images.githubusercontent.com/35031544/153818115-d8965057-df7a-435b-921b-6a7b7aa5206b.png)
