### ISSUE TITLE
A warning related to the version of tensorflow occurred when running Colab notebook

### ISSUE THREAD

**Issue by DirkFi** [intel-analytics/BigDL#3580]
I tried to run colab notebook [ncf_xshards_pandas](https://colab.research.google.com/github/intel-analytics/BigDL/blob/branch-2.0/python/orca/colab-notebook/quickstart/ncf_xshards_pandas.ipynb). But I received a warning:
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/bigdl/orca/tfpark/tfnet.py:275: simple_save (from tensorflow.python.saved_model.simple_save) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/saved_model/signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.

It seems that the use of `simple_save()` should be changed from `tf.compat.v1.saved_model.simple_save(
    session, export_dir, inputs, outputs, legacy_init_op=None
)` to `simple_save(session,
            export_dir,
            inputs={"x": x, "y": y},
            outputs={"z": z})`.

**Comment by helenlly** [comment]
@Le-Zheng  pls have a look

**Comment by Le-Zheng** [comment]
The source code https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/orca/src/bigdl/orca/tfpark/tfnet.py#L275 is aimed at supporting TF1.15. This warning seems common?

**Comment by helenlly** [comment]
can the warning be ignored? or add more details in the warning message to identify TF version should be 1.15... @Le-Zheng

**Comment by Le-Zheng** [comment]
> can the warning be ignored? or add more details in the warning message to identify TF version should be 1.15... @Le-Zheng

This is TensorFlow's warning. We have already specified the Tensorflow version in the notebook.
@yangw1234 shall we replace it with `simple_save(session, export_dir, inputs={"x": x, "y": y}, outputs={"z": z})` ?

**Comment by DirkFi** [comment]
Yes, I see in the notebook the version of Tensorflow is set to 1.15.0 by `pip install tensorflow==1.15.0`.

**Comment by Le-Zheng** [comment]
Our source code https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/orca/src/bigdl/orca/tfpark/tfnet.py#L275 is already using` tf.compat.v1.saved_model.simple_save( session, export_dir, inputs, outputs, legacy_init_op=None ) `. For tensorflow 1, it seems that the SavedModel function we can use here is only `tf.compat.v1.saved_model.simple_save` from https://www.tensorflow.org/guide/migrate/saved_model .
Thus, this is a common deprecating warning.

**Comment by DirkFi** [comment]
I tried to follow information on [simple_save](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/saved_model/simple_save) : change it from `tf.compat.v1.saved_model.simple_save(
    session, export_dir, inputs, outputs, legacy_init_op=None
)` to `simple_save(session,
            export_dir,
            inputs={"x": x, "y": y},
            outputs={"z": z})`. 
But it failed with nameerror because `simple_save(session,
            export_dir,
            inputs={"x": x, "y": y},
            outputs={"z": z})` is just a simple way of calling the saving function. So I think it's just a common warning in the version Tensorflow 1.15.0.

**Comment by Le-Zheng** [comment]
As discussed with @yangw1234 and @DirkFi, this is a common deprecated warning of TF1 SavedModel function `simple_save`. We should ignore it.
