### ISSUE TITLE
Chronos: bigdl-chronos default version package dependency

### ISSUE THREAD

**Issue by liangs6212** [intel-analytics/BigDL#3601]
There is no "tqdm" and "requests" in the default version of bigdl-chronos. This situation occurs when the user uses `TSPipeline` for inference and calls `get_public_dataset`.

**Comment by TheaperDeng** [comment]
good catch, we can discuss whether to change the code or add these two lib(I think they are not that large) to requirement.

**Comment by TheaperDeng** [comment]
Seems that these two libs are covered by `bigdl-nano[pytorch]`
