### ISSUE TITLE
Set learning rate factors of a specified layer

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#366]
If it is possible, could BigDL provide a way in the future to set multiple of the learning rate in some layers for better fine tune models? Torch has a solution https://gist.github.com/fmassa/f148df8f7c443c851a4c. Whether BigDL supports a similar way or create a more convenient method?

**Comment by yiheng** [comment]
Open for discussion. Actually we already support that method. The steps in the link can also apply to BigDL.

The method is it create a tensor as large as module parameter tensor. Then multiply the tensor with learning rate and then with the weight.

It needs another tensor, say if the parameter is 100M and then the new tensor will be 100M. It's not efficient from memory or speed.

Another way to handle this is leverage the scale factor when the model accumulate the gradient. Module will multiply new gradient with a scale factor before it accumulate it. We can let user set the scale factor. It will take same effect.

**Comment by jason-dai** [comment]
We need a better interface (maybe a wrapper) to make it easier for the users to do that.

**Comment by jenniew** [comment]
Yes, a light and direct way is better.

**Comment by shane-huang** [comment]
I think using a large tensor for this is both heavy and inconvenient. Sometimes we only need a scaling factor (defined in certain types of model layers) which will be multiplied upon the given learning rate in each iteration.

**Comment by yiheng** [comment]
This has been supported. See PR https://github.com/intel-analytics/BigDL/pull/975
