### ISSUE TITLE
Remove dllib/src/bigdl/dllib/examples

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#3679]

**Comment by dding3** [comment]
Do we need delete all files under https://github.com/intel-analytics/BigDL/tree/branch-2.0/scala/dllib/src/main/scala/com/intel/analytics/bigdl/dllib/example? Or we only delete files whose code are commented?

**Comment by jason-dai** [comment]
I meant https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/dllib/src/bigdl/dllib/examples/, not scala
