### ISSUE TITLE
Move orca related example tests from https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/dllib/examples/run-example-tests-yarn-integration.sh to orca

### ISSUE THREAD

**Issue by dding3** [intel-analytics/BigDL#3683]
Since DLlib and Orca are different projects, maybe we can move orca related example tests script from dllib folder to orca folder?

**Comment by yangw1234** [comment]
how did they end up in dllib in the first place?

**Comment by yangw1234** [comment]
These examples are checked in by https://github.com/intel-analytics/BigDL/pull/3574

@piaolaidelangman @qiuxin2012 would you mind moving your orca related examples back to orca?

**Comment by qiuxin2012** [comment]
It's TODO list in https://github.com/intel-analytics/BigDL/issues/3435
