### ISSUE TITLE
local build on Mac spark312 failed 

### ISSUE THREAD

**Issue by songhappy** [intel-analytics/BigDL#3796]
1. command: bash release_default_mac_spark312.sh 0.14.0.dev1 false true
2. error message:
    /Users/guoqiong/intelWork/git/BigDL/python/dllib/dev/release
    /Users/guoqiong/intelWork/git/BigDL/python/dllib
    sed: 1: "/Users/guoqiong/intelWo ...": extra characters at the end of g command

**Comment by Le-Zheng** [comment]
`sed` can not work on mac. You should use `gsed`.
