### ISSUE TITLE
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: null

### ISSUE THREAD

**Issue by 704572066** [intel-analytics/BigDL#3797]
get the error when starting the zoo-cluster-serving:0.9.0 with the  saved bigdl model by calling pretrainedNNModel.model.save()
![微信图片_20211224130844](https://user-images.githubusercontent.com/23404868/147318968-7e01ddee-a127-49d0-b838-1fad9d189c90.png)
![微信截图_20211224130307](https://user-images.githubusercontent.com/23404868/147318629-d09f27c9-c3d0-40e2-bfe0-c8c86a413c04.png)

**Comment by yangw1234** [comment]
@Litchilitchy @dding3 Could you help take a look? It looks like a problem bigdl's ModuleLoader.

**Comment by Litchilitchy** [comment]
seems like bigdl model loading error. If no idea for now, I suggest to use a scala program (would be better in IDE) to directly load InferenceModel for your model first. And see if it works.

usage:
```
val model = new InferenceModel()
model.doLoadBigDL(path/to/model)
```

**Comment by jason-dai** [comment]
@704572066 which version of Analytics Zoo / BigDL are you using?

**Comment by Litchilitchy** [comment]
I think the version is cluster serving docker 0.9.0?

**Comment by jason-dai** [comment]
How about `pretrainedNNModel.model.save()`? How is `pretrainedNNModel` trained? Using Analytics Zoo or BigDL?

**Comment by 704572066** [comment]
> @704572066 which version of Analytics Zoo / BigDL are you using?

![image](https://user-images.githubusercontent.com/23404868/147516910-007a9d14-ecf0-49c6-a5b8-cf8e64d98450.png)

**Comment by 704572066** [comment]
> How about `pretrainedNNModel.model.save()`? How is `pretrainedNNModel` trained? Using Analytics Zoo or BigDL?

reference the link：https://github.com/mrafayaleem/transfer-learning-bigdl

**Comment by Litchilitchy** [comment]
Could you try `pretrainedNNModel.model.saveModel()` to save?

**Comment by 704572066** [comment]
> Could you try `pretrainedNNModel.model.saveModule()` to save?

pretrainedNNModel.model.saveModule() not defined, I tried pretrainedNNModel.model.saveModel() and came across  another error in cluster-serving
![image](https://user-images.githubusercontent.com/23404868/147523993-ffb30238-338c-4369-a817-8f82a85e13d2.png)

**Comment by 704572066** [comment]
> > Could you try `pretrainedNNModel.model.saveModule()` to save?
> 
> pretrainedNNModel.model.saveModule() not defined, I tried pretrainedNNModel.model.saveModel() and came across another error in cluster-serving ![image](https://user-images.githubusercontent.com/23404868/147523993-ffb30238-338c-4369-a817-8f82a85e13d2.png)

**Comment by Litchilitchy** [comment]
@704572066 Is this solved?

**Comment by 704572066** [comment]
> @704572066 Is this solved?

sorry , I closed the issue by accident

**Comment by Litchilitchy** [comment]
@704572066 How do you install cluster-serving, by docker?

**Comment by 704572066** [comment]
> @704572066 How do you install cluster-serving, by docker?

by docker

**Comment by Litchilitchy** [comment]
The docker version may be obsolete in jar file, we are trying to upgrade. 

For now would you please try install the latest version by downloading?https://bigdl.readthedocs.io/en/latest/doc/Serving/ProgrammingGuide/serving-installation.html#manual-installation
