### ISSUE TITLE
Error on Spark 3.2 + Hadoop 3.2

### ISSUE THREAD

**Issue by ztz1989** [intel-analytics/BigDL#3824]
Dear BigDL experts,

I am having some problems running the example on the Hadoop/Yarn user guide.  In specific, when I run the following code in the python terminal: 

```
from bigdl.orca import init_orca_context
sc = init_orca_context(cluster_mode="yarn-client", cores=4, memory="10g", num_nodes=2)
```
I got the following error: 

```
py4j.protocol.Py4JJavaError: An error occurred while calling o60.initEngine.
: java.lang.NoClassDefFoundError: scala/Product$class
```
I am currently using Spark 3.2.0 with Hadoop 3.2.2. They are built on top of 4 commodity Ubuntu servers in the same subnet. I have exported the HADOOP_CONF_DIR variable as well. Could you give me some hints on this error? 

Thanks & regards,

**Comment by glorysdj** [comment]
It seems that you are missing scala library jars in your classpath, please have a check.
scala-library-X.jar should in spark jars folder, please check your classpath

**Comment by glorysdj** [comment]
BTW, could you please share how you installed spark/hadoop and bigdl?

**Comment by Tony-Feng** [comment]
That looks like an error I encountered before. Not completely sure, but when I directly installed BigDL using pip, it installed BigDL with spark 2 support, which caused the same issue here.

**Comment by ztz1989** [comment]
Hi, apologies for the late reply due to vacation. 

I manually installed Spark/Hadoop on five Linux servers in the same subnet and followed the BigDL tutorial to install using pip. 

In the end, I solved the problem by downgrading my spark cluster from spark 3.2.0 to 2.4.6. This is exactly the issue that Tony pointed out. 

Thanks for your help. I will close this thread.
