### ISSUE TITLE
Platforms for providing whl files with spark 3.x support

### ISSUE THREAD

**Issue by Tony-Feng** [intel-analytics/BigDL#3845]
Hello dev team,

Currently, the whl files compiled for spark 3.x are provided in SourceForge only. I'm wondering if there would be other stable platforms offering those whl files, such as PyPI?

If not, would there be a plan/estimation about officially releasing the support for spark 3.x, so that we can use pip to install BigDL with spark 3.x from other platforms, especially to install BigDL Orca with spark 3.x?

Thank you very much and feel free to correct anything

**Comment by hkvision** [comment]
Hi @Tony-Feng 

It is already planned :) Will release it after this PR (https://github.com/intel-analytics/BigDL/pull/3781) merge very soon.

**Comment by Tony-Feng** [comment]
Hello @hkvision,

Thank you very much for the confirmation! It's great that we can now install the new version with pip!

In addition, would the corresponding docker image in the docker hub be updated with spark 3.x support?

Again, thank you very much

**Comment by Le-Zheng** [comment]
> 

Hi @Tony-Feng,
`intelanalytics/bigdl-k8s:latest` is a built-in image that supports 3.x. You can follow the guide https://bigdl.readthedocs.io/en/latest/doc/UserGuide/k8s.html to know about the usage.

**Comment by Tony-Feng** [comment]
Hi @Le-Zheng,

Thanks a lot for pointing that out. However, the Read the Docs site doesn't work right now, it showed the corresponding page did not exist. Although I found the doc here: https://github.com/intel-analytics/BigDL/blob/branch-2.0/docs/readthedocs/source/doc/UserGuide/k8s.md, would you mind having a look at the doc site?

Thank you very much

**Comment by Le-Zheng** [comment]
> Hi @Le-Zheng,
> 
> Thanks a lot for pointing that out. However, the Read the Docs site doesn't work right now, it showed the corresponding page did not exist. Although I found the doc here: https://github.com/intel-analytics/BigDL/blob/branch-2.0/docs/readthedocs/source/doc/UserGuide/k8s.md, would you mind having a look at the doc site?
> 
> Thank you very much

Hi @Tony-Feng,
Thank you for pointing out the problem of readthedoc site. We are looking into that. 
Yes. You can read the k8s.md that is the same as readthedoc site.

**Comment by Tony-Feng** [comment]
Hi @Le-Zheng,

The doc site is back now. I believe my questions are solved for now and will wait for the new release. I'll close this issue for now.

Thank you very much

**Comment by hkvision** [comment]
Hi @Tony-Feng 

Hi, we have now released bigdl based on spark3 on pypi and you may find the instructions here: https://bigdl.readthedocs.io/en/latest/doc/UserGuide/python.html#bigdl-on-spark-3

**Comment by Tony-Feng** [comment]
Hi @hkvision,

Thanks a lot for your reminder! It's running smoothly with Spark 3.1.2 ;)

**Comment by hkvision** [comment]
> Hi @hkvision,
> 
> Thanks a lot for your reminder! It's running smoothly with Spark 3.1.2 ;)

Great!
