### ISSUE TITLE
When init_orca_context , couldn't set up Ray worker_ports and got port conflict because Ray random select worker ports from range 

### ISSUE THREAD

**Issue by jack1981** [intel-analytics/BigDL#3867]
We are testing Ray 1.9.0 with BigDL 2.0 and found this issue which made RayOnSpark job run failed randomly due to ports conflict

We did not find suitable way to control the worker_ports , the only way we can control some port was through the extra_params pairs but we did not find how to impact worker_ports 

dct = {'extra_params':{"_metrics_export_port":50005,"dashboard-port":50006}}
sc = init_orca_context(cluster_mode="spark-submit",**dct)  

Exception as below : 
File "/dfs/9/yarn/nm/usercache/dw/appcache/application_1639751979565_49761/container_e55_1639751979565_49761_01_000022/bigdl2-venv.zip/bigdl2-venv/lib/python3.7/site-packages/ray/_private/parameter.py", line 316, in update_pre_selected_port
    f"Ray component {comp} is trying to use "
ValueError: Ray component worker_ports is trying to use a port number 11679 that is used by other components.

**Comment by qiuxin2012** [comment]
I find `--worker-port-list`  to control Ray's worker ports in https://github.com/ray-project/ray/issues/18053

**Comment by qiuxin2012** [comment]
`--worker-port-list` doesn't work due to a bug of bigdl, @yushan111 will fix it.

**Comment by yushan111** [comment]
Worker ports specification (with `--worker-port-list` or `--min-worker-port` and `--max-worker-port`) **works in yarn** but doesn't work in local. 

In yarn mode, you could just add {"worker-port-list": "10002,10003,10004", "metrics-export-port": "10005"} to `extra_params` to take effect. 
In local, we currently don't support worker ports specification and will cause `RuntimeError: Unknown keyword argument(s): worker_port_list`

**Comment by jack1981** [comment]
Yes , we verified that , yarn is fine, we only need it at Production.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Yu Shan ***@***.***>
Sent: Tuesday, January 11, 2022 9:13:16 PM
To: intel-analytics/BigDL ***@***.***>
Cc: Song, Suqiang ***@***.***>; Author ***@***.***>
Subject: {EXTERNAL} Re: [intel-analytics/BigDL] When init_orca_context , couldn't set up Ray worker_ports and got port conflict because Ray random select worker ports from range (Issue #3867)


CAUTION: The message originated from an EXTERNAL SOURCE. Please use caution when opening attachments, clicking links or responding to this email.



Worker ports specification (with --worker-port-list or --min-worker-port and --max-worker-port) works in yarn but doesn't work in local.

In yarn mode, you could just add {"worker-port-list": "10002,10003,10004", "metrics-export-port": "10005"} to extra_params to take effect.
In local, we currently don't support worker ports specification and will cause RuntimeError: Unknown keyword argument(s): worker_port_list

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_intel-2Danalytics_BigDL_issues_3867-23issuecomment-2D1010642917&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=f-UxR4NBBrTCJxJCM2q7EQ_6HdOD4NB8lfUCrX9tUI4&m=GmxG5RpTj9DQNAYWOVWDTuubItiRbRgxClZTl2syecoQ8Qo_RYrkrhZNja5lNxXC&s=V9vX0daWi0tJ9bvEkGzjdZGgaJKzQKFkcN5Yp3SUSBc&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADDUJ4Y6WNJYK6UXZ3AGQ3LUVUEWZANCNFSM5LXMITYA&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=f-UxR4NBBrTCJxJCM2q7EQ_6HdOD4NB8lfUCrX9tUI4&m=GmxG5RpTj9DQNAYWOVWDTuubItiRbRgxClZTl2syecoQ8Qo_RYrkrhZNja5lNxXC&s=CKkga2W5CiqCPTqTQpmb9Bf2atjWxVmNCKQ_l_CbrRE&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=f-UxR4NBBrTCJxJCM2q7EQ_6HdOD4NB8lfUCrX9tUI4&m=GmxG5RpTj9DQNAYWOVWDTuubItiRbRgxClZTl2syecoQ8Qo_RYrkrhZNja5lNxXC&s=x-C6irGNcUEVgRpeaeMKw4tgnQccTS4NFUtwANsNMUw&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=uc5ZRXl8dGLM1RMQwf7xTCjRqXF0jmCF6SP0bDlmMmY&r=f-UxR4NBBrTCJxJCM2q7EQ_6HdOD4NB8lfUCrX9tUI4&m=GmxG5RpTj9DQNAYWOVWDTuubItiRbRgxClZTl2syecoQ8Qo_RYrkrhZNja5lNxXC&s=DOv094WNleS_K6WFz263P7r0TZHaNoxgb9tZCDLBPwo&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

CONFIDENTIALITY NOTICE This e-mail message and any attachments are only for the use of the intended recipient and may contain information that is privileged, confidential or exempt from disclosure under applicable law. If you are not the intended recipient, any disclosure, distribution or other use of this e-mail message or attachments is prohibited. If you have received this e-mail message in error, please delete and notify the sender immediately. Thank you.

**Comment by yushan111** [comment]
> Yes , we verified that , yarn is fine, we only need it at Production. Get Outlook for iOS<https://aka.ms/o0ukef>

By production, you mean yarn? Or you have other production environment?

**Comment by jack1981** [comment]
I meant the differences you mentioned about single node and cluster node. We were able to identify port range though yarn , I will close it

**Comment by yushan111** [comment]
> I meant the differences you mentioned about single node and cluster node. We were able to identify port range though yarn , I will close it

Great! Thanks.
