### ISSUE TITLE
Modify bigdl docker file?

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#3875]
https://github.com/intel-analytics/BigDL/tree/branch-2.0/docker/bigdl

1. Remove start-notebook.sh which can only start for spark local. Change to `jupyter notebook --notebook-dir=/opt/work/bigdl-0.14.0-SNAPSHOT/apps --ip=0.0.0.0 --port=12345 --no-browser --NotebookApp.token=1234qwer --allow-root` and we can call init_orca_context to start spark for different modes.
2. Do we need to install all the python packages? We may only install bigdl and leave users to install the necessary ones in the notebook?

@Le-Zheng @jason-dai

**Comment by glorysdj** [comment]
I suggest to add a start-notebook-without-spark.sh to start a jupyter notebook in your way to use init_orca_context 
keep start-notebook.sh and python env to keep all the notebook tutorials running with spark local for showcases as default

**Comment by hkvision** [comment]
> I suggest to add a start-notebook-without-spark.sh to start a jupyter notebook in your way to use init_orca_context keep start-notebook.sh and python env to keep all the notebook tutorials running with spark local for showcases as default

If you want to showcase spark local, you can directly use init_orca_context("local"). I don't think two separate scripts are handy.

**Comment by glorysdj** [comment]
> use

Does this means we should modify all the tutorials code?
And if we start jupyter notebook with spark local or spark on k8s, can we still use init_orca_context to start a spark context with different conf in specified init_orca_context?

**Comment by glorysdj** [comment]
> > I suggest to add a start-notebook-without-spark.sh to start a jupyter notebook in your way to use init_orca_context keep start-notebook.sh and python env to keep all the notebook tutorials running with spark local for showcases as default
> 
> If you want to showcase spark local, you can directly use init_orca_context("local"). I don't think two separate scripts are handy.

Does this means we should modify all the tutorials code?
And if we start jupyter notebook with spark local or spark on k8s, can we still use init_orca_context to start a spark context with different conf in specified init_orca_context?

**Comment by hkvision** [comment]
> > > I suggest to add a start-notebook-without-spark.sh to start a jupyter notebook in your way to use init_orca_context keep start-notebook.sh and python env to keep all the notebook tutorials running with spark local for showcases as default
> > 
> > 
> > If you want to showcase spark local, you can directly use init_orca_context("local"). I don't think two separate scripts are handy.
> 
> Does this means we should modify all the tutorials code? And if we start jupyter notebook with spark local or spark on k8s, can we still use init_orca_context to start a spark context with different conf in specified init_orca_context?

`sc = init_nncontext("Anomaly Detection Example")`
The code in the notebooks are like this. I don't think we need to modify anything. The default mode for init_nn/orca_context is local.

If using pyspark to start the notebook, I think the sparkcontext hasn't been created at that time, modifying the conf is possible, but not a recommended approach.

**Comment by glorysdj** [comment]
> Reference i



> > > > I suggest to add a start-notebook-without-spark.sh to start a jupyter notebook in your way to use init_orca_context keep start-notebook.sh and python env to keep all the notebook tutorials running with spark local for showcases as default
> > > 
> > > 
> > > If you want to showcase spark local, you can directly use init_orca_context("local"). I don't think two separate scripts are handy.
> > 
> > 
> > Does this means we should modify all the tutorials code? And if we start jupyter notebook with spark local or spark on k8s, can we still use init_orca_context to start a spark context with different conf in specified init_orca_context?
> 
> `sc = init_nncontext("Anomaly Detection Example")` The code in the notebooks are like this. I don't think we need to modify anything. The default mode for init_nn/orca_context is local.
> 
> If using pyspark to start the notebook, I think the sparkcontext hasn't been created at that time, modifying the conf is possible, but not a recommended approach.

If no code change is required, then I'm ok with starting jupyter notebook without any spark context.

**Comment by hkvision** [comment]
Any additional comments or inputs on this? @Le-Zheng @jason-dai

**Comment by Le-Zheng** [comment]
2. Do we need to remove python env? This image installed python env that supports all apps notebooks. The image size is 2.83 GB.

**Comment by Le-Zheng** [comment]
https://github.com/intel-analytics/BigDL/pull/3938

**Comment by hkvision** [comment]
> 2. Do we need to remove python env? This image installed python env that supports all apps notebooks. The image size is 2.83 GB.

Then we can keep these dependencies installed for now? @jason-dai
