### ISSUE TITLE
Ray object_spilling_config did not work at cluster 

### ISSUE THREAD

**Issue by jack1981** [intel-analytics/BigDL#3891]
We encountered OOM issue when run large dataset by BigDL AutoML with RayTune 
From the Ray community , it was recommended to identify the size of object_store_memory and configure object_spilling_config through --system-config
In a single node environment , it is working by below approach 

spill_dct = {"object_spilling_config": json.dumps({"type": "filesystem", "params": {"directory_path": "/dev/shm/spill"}},)}
dct = {'extra_params':{"_metrics_export_port":50005,"dashboard-port":50006,"object_store_memory":1073741824,"_system_config":spill_dct}}
sc = init_orca_context(cluster_mode="spark-submit",init_ray_on_spark=True,**dct)

But in cluster , it did not work and we got disk space issue as the default directory_path is /tmp/spill but we did not have enough space at /tmp mount , we need to configure the path dynamically.

We followed the instruction from here 
https://docs.ray.io/en/releases-1.9.1/memory-management.html

dct = {'extra_params':{"metrics-export-port":63005,"include-dashboard":"false","min-worker-port":30001,"max-worker-port":30050,"object-store-memory":42949672960,"system-config":'{"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/dev/shm/spill\"}}"}'}}

We got exception here : 

Exception: node_ip: 10.154.179.201 tag: ray-master, pgid: 251134, pids: [], returncode: 2,                 master_addr: 10.154.179.201:33213,
  Usage: ray start [OPTIONS]
Try 'ray start --help' for help.

Error: Invalid value for '--system-config': {object-spilling-config:

We try the way working at single node , got the same exception

**Comment by yushan111** [comment]
We may add different ray options for local mode and distributed mode. It will be tracked and discussed in issue #3894

For cluster mode, does `"system-config":'{"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/dev/shm/spill\"}}"}'`  work?

**Comment by jack1981** [comment]
As I noted , It did not work ... which was weird as we followed the tips from Ray community. We knew there are different ways to pass configurations to Ray in a single node or in a cluster environment but did not get the point why it mentioned the value was not correct ? 
We are ok , BigDL can figure out a unified way to pass parameters but for this particular issue we hope your guys can do the test and reproduce it , then better to dig the root of cause , make sense ?

**Comment by yushan111** [comment]
@hkvision It seems that RayOnSpark does not support the parameter `system-config` correctly, could you help have a look at it?

**Comment by hkvision** [comment]
@jack1981 
Hi Jack,

I have added an argument `system_config` in `init_orca_context` and you can pass the dict to it and follow ray's same way for rayonspark. Try it using tomorrow's nightly build and tell me if there are further issues :)
