### ISSUE TITLE
the consistency of preprocessing between NNFrame transform and customized one

### ISSUE THREAD

**Issue by 704572066** [intel-analytics/BigDL#3907]
I did  transfer learning of image classification and deployed the saved the model in cluster-serving，then I found the prediction results between pyspark pipeline transform and cluster serving http api inference are different. It turns out to be the model inputs (aka. preprocessing output) are different. The preprocessing of NNFrame is `ChainedPreprocessing` and my customized one seems the same with it. the original issue https://github.com/intel-analytics/BigDL/issues/3764

 transfer learning preprocessing code:
```python
import os.path as osp
from bigdl.dllib.nn.criterion import *
from bigdl.dllib.nn.layer import *
from bigdl.dllib.nnframes import *
from bigdl.dllib.feature.image import *


def build_transforms(params):
    from bigdl.dllib.feature.common import ChainedPreprocessing
    transformer = ChainedPreprocessing(
        [RowToImageFeature(), ImageResize(256, 256), ImageCenterCrop(224, 224),
         ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor(), ImageFeatureToTensor()])    
    return transformer

def build_classifier():
    ...

def train(task_path, dataset_path, params):
    from pyspark.ml import Pipeline
    from pyspark.ml.evaluation import MulticlassClassificationEvaluator
    from pyspark.sql.functions import udf
    from pyspark.sql.types import DoubleType, StringType

    from bigdl.dllib.nnframes import NNImageReader
    from bigdl.dllib.utils.common import redire_spark_logs

    spark_conf = SparkConf().set("spark.driver.memory", "10g") \
        .set("spark.driver.cores", 4)

    sc = init_nncontext(spark_conf, cluster_mode="local")
    # redire_spark_logs("float", osp.join(task_path, 'out.log'))

    getFileName = udf(lambda row: os.path.basename(row[0]), StringType())
    getLabel = udf(lambda row: 1.0 if 'ants' in row[0] else 2.0, DoubleType())

    trainingDF = NNImageReader.readImages(osp.join(dataset_path, 'train/*'), sc, resizeH=300, resizeW=300, image_codec=1)
    trainingDF = trainingDF.withColumn('filename', getFileName('image')).withColumn('label', getLabel('image'))

    validationDF = NNImageReader.readImages(osp.join(dataset_path, 'val/*'), sc, resizeH=300, resizeW=300, image_codec=1)
    validationDF = validationDF.withColumn('filename', getFileName('image')).withColumn('label', getLabel('image'))


    transformer = build_transforms(params)
    preTrainedNNModel = NNModel(Model.loadModel(osp.join(dataset_path,'analytics-zoo_resnet-50_imagenet_0.1.0.model')), transformer) \
        .setFeaturesCol("image") \
        .setPredictionCol("embedding")

    classifier = build_classifier()
    pipeline = Pipeline(stages=[preTrainedNNModel, classifier])

    antbeeModel = pipeline.fit(trainingDF)
    predictionDF = antbeeModel.transform(validationDF).cache()
```

customized preprocessing code:
```python
import base64
import cv2
import numpy as np
from urllib import request
import json
import matplotlib.pyplot as plt
import pylab
# import torch
def resize_img(img, target_size):
    img = cv2.resize(img, (target_size, target_size))
    return img


def center_crop_img(im, target_size):
    w, h = im.shape[0], im.shape[1]
    tw, th = target_size, target_size
    assert (w >= target_size) and (h >= target_size), \
            "image width({}) and height({}) should be larger than crop size".format(w, h, target_size)
    x1 = int(round((w - tw) / 2.))
    y1 = int(round((h - th) / 2.))
    im = im[x1:x1+tw, y1:y1+th]
    return im

def normalize_image(x, mean=(0., 0., 0.), std=(1.0, 1.0, 1.0)):
    '''Normalization.

    Args:
        x: input image.
        mean: mean value of the input image.
        std: standard deviation value of the input image.

    Returns:
        Normalized image.
    '''

    x = np.asarray(x, dtype=np.float32)
    if len(x.shape) == 4:
        for dim in range(3):
            x[:, :, :, dim] = (x[:, :, :, dim] - mean[dim]) / std[dim]
    if len(x.shape) == 3:
        for dim in range(3):
            x[:, :, dim] = (x[:, :, dim] - mean[dim]) / std[dim]
    return x

def preprocess(img):
    img = img[..., ::-1]
    image_resize = resize_img(img, 256)
    ccrop_img = center_crop_img(image_resize, 224)
    n_img = normalize_image(ccrop_img, [123.0, 117.0, 104.0])
    return n_img

if __name__ == '__main__':
    bee = cv2.imread("/root/Desktop/ws/datasets/D0002/val/bees/586041248_3032e277a9.jpg")
    t_bee = preprocess(bee)
```

result of NNFrame preprocessing:
```
-49.0	-48.0	-48.0	...	-12.0	-12.0	-11.0	
-50.0	-49.0	-49.0	...	-12.0	-12.0	-11.0	
-51.0	-50.0	-51.0	...	-12.0	-12.0	-10.0
```

result of customized preprocessing:
```
[-56., -38., -49.],
[-55., -37., -48.],
[-54., -36., -47.],
...,
```
* Image link: https://user-images.githubusercontent.com/23404868/148499487-d0b723c9-df53-4213-8779-65f1e6b8c5f3.jpg
* model link: https://github.com/704572066/online-ai-platform/raw/master/model/20220106.model

**Comment by Litchilitchy** [comment]
@704572066 
```
def preprocess(img):
    img = img[..., ::-1]
    image_resize = resize_img(bee, 256)
    ccrop_img = center_crop_img(image_resize, 224)
    n_img = normalize_image(ccrop_img, [123.0, 117.0, 104.0])
    return n_img
```
Could you help to explain the logic below
```
img = img[..., ::-1]
resize_img(bee, 256)
```

**Comment by 704572066** [comment]
> @704572066
> 
> ```
> def preprocess(img):
>     img = img[..., ::-1]
>     image_resize = resize_img(bee, 256)
>     ccrop_img = center_crop_img(image_resize, 224)
>     n_img = normalize_image(ccrop_img, [123.0, 117.0, 104.0])
>     return n_img
> ```
> 
> Could you help to explain the logic below
> 
> ```
> img = img[..., ::-1]
> resize_img(bee, 256)
> ```

I changed the code, it should be resize_img(img, 256)

**Comment by dding3** [comment]
Thank you for the code.

I think above result difference is caused by reading and processing the images logic is not consistent as:
1. customized preprocess use `cv2.imread` and the returned image will have **B G R** order while NNFrame will have **R G B** order. So the params passed to normalize_image needed to be updated to `n_img = normalize_image(ccrop_img, [104.0, 117.0, 123.0])` to keep consistent with NNFrame code
2. In above NNFrame code, there is additional resize logic while reading the images. 
`NNImageReader.readImages(osp.join(dataset_path, 'train/*'), sc, **resizeH=300, resizeW=300**, image_codec=1)`, we need remove `resizeH` and `resizeW` to be consistent with customized preprocess

**Comment by jason-dai** [comment]
> Thank you for the code.
> 
> I think above result difference is caused by reading and processing the images logic is not consistent as:
> 
> 1. customized preprocess use `cv2.imread` and the returned image will have **B G R** order while NNFrame will have **R G B** order. So the params passed to normalize_image needed to be updated to `n_img = normalize_image(ccrop_img, [104.0, 117.0, 123.0])` to keep consistent with NNFrame code
> 2. In above NNFrame code, there is additional resize logic while reading the images.
>    `NNImageReader.readImages(osp.join(dataset_path, 'train/*'), sc, **resizeH=300, resizeW=300**, image_codec=1)`, we need remove `resizeH` and `resizeW` to be consistent with customized preprocess

We need to make `NNFrame` and `cv2.imread` consistent

**Comment by dding3** [comment]
> > Thank you for the code.
> > I think above result difference is caused by reading and processing the images logic is not consistent as:
> > 
> > 1. customized preprocess use `cv2.imread` and the returned image will have **B G R** order while NNFrame will have **R G B** order. So the params passed to normalize_image needed to be updated to `n_img = normalize_image(ccrop_img, [104.0, 117.0, 123.0])` to keep consistent with NNFrame code
> > 2. In above NNFrame code, there is additional resize logic while reading the images.
> >    `NNImageReader.readImages(osp.join(dataset_path, 'train/*'), sc, **resizeH=300, resizeW=300**, image_codec=1)`, we need remove `resizeH` and `resizeW` to be consistent with customized preprocess
> 
> We need to make `NNFrame` and `cv2.imread` consistent; why does NNFrame use **R G B** order (instead of **B G R**)? How does it read the image?

`NNFrame` internally use spark api to read the image into bytes and use cv2.imdecode to read the bytes into mat, also in **B G R** order. However, our parameters for `ImageChannelNormalize` are `mean_r`, `mean_g`, `meanB_b` which makes it consistent with the customized preprocessing code.

**Comment by jason-dai** [comment]
> > > Thank you for the code.
> > > I think above result difference is caused by reading and processing the images logic is not consistent as:
> > > 
> > > 1. customized preprocess use `cv2.imread` and the returned image will have **B G R** order while NNFrame will have **R G B** order. So the params passed to normalize_image needed to be updated to `n_img = normalize_image(ccrop_img, [104.0, 117.0, 123.0])` to keep consistent with NNFrame code
> > > 2. In above NNFrame code, there is additional resize logic while reading the images.
> > >    `NNImageReader.readImages(osp.join(dataset_path, 'train/*'), sc, **resizeH=300, resizeW=300**, image_codec=1)`, we need remove `resizeH` and `resizeW` to be consistent with customized preprocess
> > 
> > 
> > We need to make `NNFrame` and `cv2.imread` consistent; why does NNFrame use **R G B** order (instead of **B G R**)? How does it read the image?
> 
> `NNFrame` internally use spark api to read the image into bytes and use cv2.imdecode to read the bytes into mat, also in **B G R** order. However, our parameters order for `ImageChannelNormalize` are `mean_r`, `mean_g`, `meanB_b` which makes it consistent with the customized preprocessing code.
> 
> If there is no concern, I will update the parameters order for `ImageChannelNormalize` to `mean_b`, `mean_g`, `meanB_r`

ok

**Comment by 704572066** [comment]
@dding3 How to change the customized preprocess code to be consistent with NNFrame，I resized the img first and then converted it to R G B order with cv2.cvtColor(image_resize , cv2.COLOR_BGR2RGB) , but result of customized preprocessing is still not consistent with NNFrame.
```
def preprocess(img):
    image_resize = resize_img(img, 300)
    img_rgb = cv2.cvtColor(image_resize , cv2.COLOR_BGR2RGB)
    image_resize = resize_img(img_rgb , 256)
    ccrop_img = center_crop_img(image_resize, 224)
    n_img = normalize_image(ccrop_img, [123.0, 117.0, 104.0])
    return n_img
```

```
preprocess_bee:  [[[-56. -38. -48.]
  [-55. -37. -48.]
  [-54. -36. -47.]
  ...
  [-23.  20. -10.]
  [-24.  19. -11.]
  [-24.  19. -12.]]
```

**Comment by Litchilitchy** [comment]
@704572066 Is this result NNFrame or your customized one?

Could you please post both?

**Comment by 704572066** [comment]
> @704572066 Is this result NNFrame or your customized one?
> 
> Could you please post both?

the result is customized one：
```
preprocess_bee:  [[[-56. -38. -48.]
  [-55. -37. -48.]
  [-54. -36. -47.]
  ...
  [-23.  20. -10.]
  [-24.  19. -11.]
  [-24.  19. -12.]]
```

**Comment by qiuxin2012** [comment]
Sorry for the late response and happy Chinese New Year.
To get the same preprocess result in cluster-serving, I think you can use local ImageSet and reuse your `ChainedPreprocessing`, like below:
```python
imgs = ImageSet.read('/home/xin/IntelAnalytics/BigDL5/python/dllib/test/bigdl/resources/pascal', None, resize_height=300, resize_width=300, image_codec=1)
def build_local_transforms():
    from bigdl.dllib.feature.common import ChainedPreprocessing
    transformer = ChainedPreprocessing(
        [ImageBytesToMat(), ImageResize(256, 256), ImageCenterCrop(224, 224),
         ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor()])    
    return transformer
t_imgs = imgs.transform(build_local_transforms())
print(t_imgs.get_image())
```
Please notice you should change the first preprocessing from `RowToImageFeature` to `ImageBytesToMat`.

**Comment by 704572066** [comment]
@qiuxin2012 
The preprocess result is still different from the NNframe result.
```
    imgs = ImageSet.read('/root/Desktop/ws/datasets/D0002/bee', None,
                         resize_height=300, resize_width=300, image_codec=1)
    def build_local_transforms():
        from bigdl.dllib.feature.common import ChainedPreprocessing
        transformer = ChainedPreprocessing(
            [ImageBytesToMat(), ImageResize(256, 256), ImageCenterCrop(224, 224),
             ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor()])
        return transformer
    t_imgs = imgs.transform(build_local_transforms())
    print(t_imgs.get_image())
```

```

[array([[[-68., -67., -67., ..., -31., -31., -30.],
        [-69., -68., -68., ..., -31., -31., -30.],
        [-70., -69., -70., ..., -31., -31., -29.],
        ...,
        [-87., -87., -88., ...,  83.,  66.,  60.],
        [-87., -87., -88., ...,  87.,  79.,  78.],
        [-88., -88., -89., ..., 104.,  95.,  92.]],

       [[-38., -37., -35., ...,  19.,  19.,  20.],
        [-39., -38., -36., ...,  19.,  19.,  20.],
        [-40., -39., -38., ...,  19.,  19.,  21.],
        ...,
        [-60., -60., -61., ..., 111.,  96.,  96.],
        [-60., -60., -61., ..., 107.,  98., 102.],
        [-61., -61., -62., ..., 118., 109., 110.]],

       [[-37., -36., -35., ...,  -5.,  -5.,  -4.],
        [-38., -37., -36., ...,  -5.,  -5.,  -4.],
        [-40., -38., -38., ...,  -5.,  -5.,  -3.],
        ...,
        [-50., -50., -51., ..., 118., 103., 100.],
        [-50., -50., -51., ..., 117., 109., 110.],
        [-51., -51., -52., ..., 131., 121., 121.]]], dtype=float32)]
```

**Comment by dding3** [comment]
> 

I think above nnframe preprocessing logic is still different with the customized one. eg. in nnframe logic, the image has been resized twice, and in customized, there is `img = img[..., ::-1]` while we don't have in nnframe code. Also 

I tried below code, and the result is the same.
nnframe code:
`
def build_transforms():
    from bigdl.dllib.feature.common import ChainedPreprocessing
    transformer = ChainedPreprocessing(
        [ImageResize(256, 256), ImageCenterCrop(224, 224),
         ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor()])

    return transformer

spark_conf = SparkConf().set("spark.driver.memory", "10g") \
    .set("spark.driver.cores", 4)

sc = init_nncontext(spark_conf, cluster_mode="local")

path = "/tmp/bee.jpg"
imageSet = ImageSet.read(path, sc)
transformer = build_transforms()
transformed = transformer(imageSet)
images = transformed.get_image()
t = images.collect()
`

customized code:
`
def resize_img(img, target_size):
    img = cv2.resize(img, (target_size, target_size))
    return img


def center_crop_img(im, target_size):
    w, h = im.shape[0], im.shape[1]
    tw, th = target_size, target_size
    assert (w >= target_size) and (h >= target_size), \
            "image width({}) and height({}) should be larger than crop size".format(w, h, target_size)
    x1 = int(round((w - tw) / 2.))
    y1 = int(round((h - th) / 2.))
    im = im[x1:x1+tw, y1:y1+th]
    return im

def normalize_image(x, mean=(0., 0., 0.), std=(1.0, 1.0, 1.0)):
    '''Normalization.

    Args:
        x: input image.
        mean: mean value of the input image.
        std: standard deviation value of the input image.

    Returns:
        Normalized image.
    '''

    x = np.asarray(x, dtype=np.float32)
    if len(x.shape) == 4:
        for dim in range(3):
            x[:, :, :, dim] = (x[:, :, :, dim] - mean[dim]) / std[dim]
    if len(x.shape) == 3:
        for dim in range(3):
            x[:, :, dim] = (x[:, :, dim] - mean[dim]) / std[dim]
    return x

def preprocess(img):
    # img = img[..., ::-1]
    image_resize = resize_img(img, 256)
    ccrop_img = center_crop_img(image_resize, 224)
    n_img = normalize_image(ccrop_img, [123.0, 117.0, 104.0])
    return n_img

if __name__ == '__main__':
    bee = cv2.imread("/home/ding/data/bee.jpg")
    t_bee = preprocess(bee)
    x = np.transpose(t_bee, (2, 0, 1))
`

And results are:
`<class 'list'>: [array([[[-68., -67., -66., ..., -29., -30., -31.],
        [-69., -69., -69., ..., -31., -30., -30.],
        [-70., -69., -69., ..., -30., -29., -29.],
        ...,
        [-87., -87., -88., ...,  85.,  67.,  55.],
        [-87., -87., -88., ...,  84.,  79.,  74.],
        [-88., -88., -87., ...,  87.,  94.,  88.]],

       [[-38., -37., -36., ...,  20.,  19.,  19.],
        [-39., -39., -39., ...,  18.,  19.,  20.],
        [-40., -39., -39., ...,  19.,  20.,  21.],
        ...,
        [-60., -60., -61., ..., 110.,  98.,  94.],
        [-60., -60., -61., ..., 102.,  99.,  98.],
        [-61., -61., -61., ..., 108., 115., 108.]],

       [[-37., -36., -35., ...,  -4.,  -5.,  -5.],
        [-38., -38., -38., ...,  -6.,  -5.,  -4.],
        [-39., -38., -38., ...,  -5.,  -4.,  -3.],
        ...,
        [-50., -50., -51., ..., 120., 106., 100.],
        [-50., -50., -51., ..., 114., 110., 108.],
        [-51., -51., -51., ..., 119., 126., 119.]]], dtype=float32)]`

**Comment by 704572066** [comment]
@dding3 You mean you have fixed the issue?

**Comment by dding3** [comment]
> @dding3 You mean you have fixed the issue?

Yes

**Comment by 704572066** [comment]
@dding3 
Why are the prediction results between nnmodel and cluster-serving not consistent？

nnmodel prediction code:

```
def build_transforms():
    from bigdl.dllib.feature.common import ChainedPreprocessing
    transformer = ChainedPreprocessing(
        [RowToImageFeature(), ImageResize(256, 256), ImageCenterCrop(224, 224),
         ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor(), ImageFeatureToTensor()])
    return transformer

def nnmodel():
    from pyspark.ml import Pipeline
    from pyspark.ml.evaluation import MulticlassClassificationEvaluator
    from pyspark.sql.functions import udf
    from pyspark.sql.types import DoubleType, StringType

    from bigdl.dllib.nnframes import NNImageReader

    spark_conf = SparkConf().set("spark.driver.memory", "10g") \
        .set("spark.driver.cores", 4)
    sc = init_nncontext(spark_conf, cluster_mode="local")
    getFileName = udf(lambda row: os.path.basename(row[0]), StringType())
    getLabel = udf(lambda row: 1.0 if 'ants' in row[0] else 2.0, DoubleType())
    validationDF = NNImageReader.readImages('/root/Desktop/ws/datasets/D0002/val/*', sc, resizeH=300, resizeW=300, image_codec=1)
    validationDF = validationDF.withColumn('filename', getFileName('image')).withColumn('label', getLabel('image'))
    transformer = build_transforms()
    preTrainedNNModel = NNModel(Model.loadModel('/root/Desktop/20220106.model'),
                                transformer) \
        .setFeaturesCol("image") \
        .setPredictionCol("embedding")
    predictionDF = preTrainedNNModel.transform(validationDF).cache()
    predictionDF.withColumn("1", predictionDF.embedding[0]).withColumn("2", predictionDF.embedding[1]).show()

nnmodel()

```  
nnmodel prediction result:
```
+--------------------+--------------------+-----+--------------------+----------+-----------+
|               image|            filename|label|           embedding|         1|          2|
+--------------------+--------------------+-----+--------------------+----------+-----------+
|[file:/root/Deskt...|512164029_c0a66b8...|  1.0|[-0.5119536, -0.9...|-0.5119536|-0.91460115|
|[file:/root/Deskt...|586041248_3032e27...|  2.0|[-0.8463575, -0.5...|-0.8463575|-0.56032157|
+--------------------+--------------------+-----+--------------------+----------+-----------+
```

cluster-serving prediction code:
```
def resize_img(img, target_size):
    img = cv2.resize(img, (target_size, target_size))
    return img


def center_crop_img(im, target_size):
    w, h = im.shape[0], im.shape[1]
    tw, th = target_size, target_size
    assert (w >= target_size) and (h >= target_size), \
            "image width({}) and height({}) should be larger than crop size".format(w, h, target_size)
    x1 = int(round((w - tw) / 2.))
    y1 = int(round((h - th) / 2.))
    im = im[x1:x1+tw, y1:y1+th]
    return im

def normalize_image(x, mean=(0., 0., 0.), std=(1.0, 1.0, 1.0)):
    '''Normalization.

    Args:
        x: input image.
        mean: mean value of the input image.
        std: standard deviation value of the input image.

    Returns:
        Normalized image.
    '''

    x = np.asarray(x, dtype=np.float32)
    if len(x.shape) == 4:
        for dim in range(3):
            x[:, :, :, dim] = (x[:, :, :, dim] - mean[dim]) / std[dim]
    if len(x.shape) == 3:
        for dim in range(3):
            x[:, :, dim] = (x[:, :, dim] - mean[dim]) / std[dim]
    return x

def preprocess(img):
    # img = img[..., ::-1]
    image_resize = resize_img(img, 256)
    ccrop_img = center_crop_img(image_resize, 224)
    n_img = normalize_image(ccrop_img, [123.0, 117.0, 104.0])
    return n_img

def tobase64(img):
    cv2.imwrite("/root/Desktop/transform.jpg", img)
    transform_img = open("/root/Desktop/transform.jpg", "rb")
    b64 = base64.b64encode(transform_img.read())
    return str(b64, 'utf-8')

def http_post(url,data_json):
    jdata = json.dumps(data_json)
    # 修改格式
    headers = {'Content-Type': 'application/json'}
    # 编码成json格式
    data = bytes(json.dumps(data_json), encoding='utf8')
    # 构造request
    req = request.Request(url=url, headers=headers, data=data, method="POST")
    # 发起请求
    response = request.urlopen(req)
    return response

if __name__ == '__main__':
    ant = cv2.imread("/root/Desktop/ws/datasets/D0002/val/ants/512164029_c0a66b8498.jpg")
    bee = cv2.imread("/root/Desktop/ws/datasets/D0002/val/bees/586041248_3032e277a9.jpg")
    t_ant = preprocess(ant)
    t_bee = preprocess(bee)
    b64_ant = tobase64(t_ant)
    b64_bee = tobase64(t_bee)
    tp_ant = np.transpose(t_ant, (2, 0, 1))
    tp_bee = np.transpose(t_bee, (2, 0, 1))
    url = 'http://192.168.70.23:10020/models/1/versions/1.0/predict'
    # data_json = {"instances": [{"img": b64_bee},{"img": b64_ant}]}
    data_json = {"instances": [{"floatTensor": tp_ant.tolist()}, {"floatTensor": tp_bee.tolist()}]}
    resp = http_post(url, data_json)
    print(json.load(resp))
```

cluster-serving prediction result without np.transpose:
```
{'predictions': ['{"value":"{\\"data\\":[-0.7722654,-0.61983234],\\"shape\\":[2]}"}', '{"value":"{\\"data\\":[-0.67473793,-0.7119017],\\"shape\\":[2]}"}']}
```

cluster-serving prediction result with np.transpose:
```
{'predictions': ['{"value":"NaN"}', '{"value":"NaN"}']}
```

**Comment by dding3** [comment]
> NNImageReader.readImages('/root/Desktop/ws/datasets/D0002/val/*', sc, resizeH=300, resizeW=300, image_codec=1)

I think in the above code, we can first remove `resizeH=300, resizeW=300, image_codec=1` to make the processing logic is the same with customized code?

**Comment by 704572066** [comment]
> > NNImageReader.readImages('/root/Desktop/ws/datasets/D0002/val/*', sc, resizeH=300, resizeW=300, image_codec=1)
> 
> I think in the above code, we can first remove `resizeH=300, resizeW=300, image_codec=1` to make the processing logic is the same with customized code?
not same after removing `resizeH=300, resizeW=300, image_codec=1`
```
validationDF = NNImageReader.readImages('/root/Desktop/ws/datasets/D0002/val/*', sc)
validationDF = validationDF.withColumn('filename', getFileName('image')).withColumn('label', getLabel('image'))
transformer = build_transforms()
preTrainedNNModel = NNModel(Model.loadModel('/root/Desktop/20220106.model'),
                            transformer) \
    .setFeaturesCol("image") \
    .setPredictionCol("embedding")
predictionDF = preTrainedNNModel.transform(validationDF).cache()
predictionDF.withColumn("1", predictionDF.embedding[0]).withColumn("2", predictionDF.embedding[1]).show()
```

```

+--------------------+--------------------+-----+--------------------+-----------+----------+
|               image|            filename|label|           embedding|          1|         2|
+--------------------+--------------------+-----+--------------------+-----------+----------+
|[file:/root/Deskt...|512164029_c0a66b8...|  1.0|[-0.5100712, -0.9...|-0.5100712|-0.9174234|
|[file:/root/Deskt...|586041248_3032e27...|  2.0|[-0.84638584, -0....|-0.84638584|-0.5603003|
+--------------------+--------------------+-----+--------------------+-----------+----------+
```

**Comment by 704572066** [comment]
> > NNImageReader.readImages('/root/Desktop/ws/datasets/D0002/val/*', sc, resizeH=300, resizeW=300, image_codec=1)
> 
> I think in the above code, we can first remove `resizeH=300, resizeW=300, image_codec=1` to make the processing logic is the same with customized code?


not same after removing `resizeH=300, resizeW=300, image_codec=1`
```
validationDF = NNImageReader.readImages('/root/Desktop/ws/datasets/D0002/val/*', sc)
validationDF = validationDF.withColumn('filename', getFileName('image')).withColumn('label', getLabel('image'))
transformer = build_transforms()
preTrainedNNModel = NNModel(Model.loadModel('/root/Desktop/20220106.model'),
                            transformer) \
    .setFeaturesCol("image") \
    .setPredictionCol("embedding")
predictionDF = preTrainedNNModel.transform(validationDF).cache()
predictionDF.withColumn("1", predictionDF.embedding[0]).withColumn("2", predictionDF.embedding[1]).show()
```

```

+--------------------+--------------------+-----+--------------------+-----------+----------+
|               image|            filename|label|           embedding|          1|         2|
+--------------------+--------------------+-----+--------------------+-----------+----------+
|[file:/root/Deskt...|512164029_c0a66b8...|  1.0|[-0.5100712, -0.9...|-0.5100712|-0.9174234|
|[file:/root/Deskt...|586041248_3032e27...|  2.0|[-0.84638584, -0....|-0.84638584|-0.5603003|
+--------------------+--------------------+-----+--------------------+-----------+----------+
```

**Comment by Litchilitchy** [comment]
@704572066 Before checking the result of NNFrame and Cluster Serving, is it confirmed that the preprocess results are the same?

**Comment by 704572066** [comment]
> @704572066 Before checking the result of NNFrame and Cluster Serving, is it confirmed that the preprocess results are the same?

@dding3 could you confirm this issue？

**Comment by dding3** [comment]
I think with above code, the preprocess results should be the same.

**Comment by Litchilitchy** [comment]
I would try to verify the consistency of the two inputs.

**Comment by Litchilitchy** [comment]
@704572066 I used `bee.jpg` to check the results of both, they are almost equal.

Cluster Serving result: `[-0.8453065, -0.5611119]`,  preprocess code 
```
img = cv2.imread("debug-user-issue/data/bee.jpg")
img = preprocess(img)
img = np.transpose(img, (2, 0, 1))
img = np.expand_dims(img, axis=0)
input_api.enqueue("bee", t=img)
```
NNFrame result: `[-0.8463613390922546, -0.560318648815155]`, preprocess code
```
def build_transforms():
    from bigdl.dllib.feature.common import ChainedPreprocessing

    transformer = ChainedPreprocessing(
        [RowToImageFeature(), ImageResize(256, 256), ImageCenterCrop(224, 224),
         ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor(), ImageFeatureToTensor()])
    return transformer
```
Please check if you have pull the latest version of BigDL, and please note, Cluster Serving fix some dimension issue, and now you have to add `img = np.expand_dims(img, axis=0)` shown above. If you did not add a dimension but the model could still predict, then you may be not running the latest version. The other parts of code (except preprocess) are the same with your code.

PS: The slight difference between the two results may due to the precision gap of the low-level of NNFrame AbstractModule and Cluster Serving InferenceModel wrapper @jason-dai

**Comment by 704572066** [comment]
@Litchilitchy 
I added `img = np.expand_dims(img, axis=0)` after transposing and got the same results with yours，thanks for your help!
