### ISSUE TITLE
If a dataset is transformed to another Dataset with more elements, the opimimiter cannot infer the correct number of elements in each Epoch.

### ISSUE THREAD

**Issue by psyyz10** [intel-analytics/BigDL#391]
If the user create an Distributed DataSet and then use transformers to transform the rdd to a rdd with more elements, then put the DataSet to a ptimizer, the optimizer can not automatically inter the correct number of elements in each epoch. Here a simple example is given as follows:

```scala
case class Tokenizer(sep: String) extends Transformer[String, Seq[String]] 

// flatten the given iterator
case class Flatten() extends Transformer[Seq[String], String] {
  override def apply(prev: Iterator[Seq[String]]): Iterator[String] =
    prev.flatten
}

val trainSet = (DataSet.rdd(sc.textFile(params.trainDataLocation)) 
     -> Tokenizer() 
     -> Flatten() 
     -> ToBatch(batchSize))

val optimizer = Optimizer(
      model = model,
      dataset = trainSet,
      criterion =  ... )
```

In the above case, assume the lines in the given input text file is 100, then it was transformed into 1000 words. However, during the training process, the optimizer still regards the size of training set is 100 in each epoch. It is better to enhance the function to meet this requirement.

For now, the solution can be that:
1. Transform the DataSet to RDD and then map the transformer
2.  Transform the result RDD to DataSet and then transform to Batch.

code example as follows:
```scala
val trainSetRDD = DataSet.rdd(sc.textFile(params.trainDataLocation)
      .toDistributed()
      .data(false)
      .mapPartitions[String]((Tokenizer() -> Flatten()).apply)

val trainSet = DataSet.rdd(trainSetRDD) -> ToBatch(batchSize)
```

**Comment by yiheng** [comment]
This has been fixed in https://github.com/intel-analytics/BigDL/pull/1417
