### ISSUE TITLE
[PPML] Occlum SparkSQL TPCH 100GB Example

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/BigDL#3926]
- [x] Occlum SparkSQL TPCH Example
- [x] Occlum SparkSQL TPCH 10GB
- [x] Occlum SparkSQL TPCH 100GB

assigned to @piaolaidelangman

**Comment by piaolaidelangman** [comment]
Occlum SparkSQL TPCH 100GB finished in this pr https://github.com/intel-analytics/BigDL/pull/3962.

**Comment by qiyuangong** [comment]
Issue addressed by @piaolaidelangman 
Closed
