### ISSUE TITLE
Add better documentation for Linear, Cosine, PairwiseDistance and Reshape

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#393]
We need to make it clear that the input samples to the Linear, Cosine and PairwiseDistance modules should be vector (or a mini-batch of vectors), and the user may add Reshape to convert multi-dimensional tensor into vectors if needed:
1) We need to add more detailed Scala  doc and comments for these modules
2) Change the error messages "input must be vector or matrix" to a more meaningful, actionable one: something like "the input to the layer needs to be a vector (or a mini-batch of vectors); please use the Reshape module to convert multi-dimensional input into vectors"

And then we need to add more detailed Scala  doc and comments for the Reshape module too.

**Comment by psyyz10** [comment]
Fixed and Merged.
