### ISSUE TITLE
Example cifar10 low accuracy

### ISSUE THREAD

**Issue by ryandoren** [intel-analytics/BigDL#3956]
After running the commands, I got an accuracy of 0.25, which is a far cry from the standard value (0.53) in README.md.

In cifar10.py, the default batch size in line 48 should be modified to 4 (without changing other parameters):
```python
parser.add_argument('--batch_size', type=int, default=4, help='The training batch size')  # change default batch size to 4
```
After that, the accuracy seems more reasonable.

**Comment by hkvision** [comment]
Caused by this PR: https://github.com/intel-analytics/BigDL/pull/3452
