### ISSUE TITLE
Chronos unittest bug in test_autogener_best_cycle_length

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#3998]
https://github.com/intel-analytics/BigDL/blob/9f8c0c08246b2e920e07dc73fd591f30284d45dd/python/chronos/test/bigdl/chronos/autots/test_autotsestimator.py#L523
should be
```python
assert 2 <= config['past_seq_len'] <= 10
```
Since the real cycle length is 5 and 5//2=2

**Comment by TheaperDeng** [comment]
@liangs6212 could you have a fix on this?

**Comment by liangs6212** [comment]
Ok, I'll fix it.
