### ISSUE TITLE
Error: when trying to run textClassifier example from intelliJ: NoClassDefFoundError: org/apache/spark/rdd/RDD

### ISSUE THREAD

**Issue by lefromage** [intel-analytics/BigDL#400]
full output:

/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Users/zz/Downloads/BigDL/dl/target/classes:/Users/zz/.m2/repository/com/twelvemonkeys/imageio/imageio-jpeg/3.2.1/imageio-jpeg-3.2.1.jar:/Users/zz/.m2/repository/com/twelvemonkeys/imageio/imageio-core/3.2.1/imageio-core-3.2.1.jar:/Users/zz/.m2/repository/com/twelvemonkeys/imageio/imageio-metadata/3.2.1/imageio-metadata-3.2.1.jar:/Users/zz/.m2/repository/com/twelvemonkeys/common/common-lang/3.2.1/common-lang-3.2.1.jar:/Users/zz/.m2/repository/com/twelvemonkeys/common/common-io/3.2.1/common-io-3.2.1.jar:/Users/zz/.m2/repository/com/twelvemonkeys/common/common-image/3.2.1/common-image-3.2.1.jar:/Users/zz/.m2/repository/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar:/Users/zz/.m2/repository/com/intel/analytics/bigdl/native/mkl-java/0.1.0-SNAPSHOT/mkl-java-0.1.0-20170119.181340-20.jar:/Users/zz/.m2/repository/junit/junit/4.11/junit-4.11.jar:/Users/zz/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/zz/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/zz/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:/Users/zz/.m2/repository/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.jar:/Users/zz/Downloads/BigDL/spark-version/1.5-plus/target/classes:/Users/zz/.m2/repository/org/scalanlp/breeze_2.10/0.11.2/breeze_2.10-0.11.2.jar:/Users/zz/.m2/repository/org/scalanlp/breeze-macros_2.10/0.11.2/breeze-macros_2.10-0.11.2.jar:/Users/zz/.m2/repository/org/scalamacros/quasiquotes_2.10/2.0.0-M8/quasiquotes_2.10-2.0.0-M8.jar:/Users/zz/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar:/Users/zz/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.jar:/Users/zz/.m2/repository/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar:/Users/zz/.m2/repository/com/github/rwl/jtransforms/2.4.0/jtransforms-2.4.0.jar:/Users/zz/.m2/repository/org/spire-math/spire_2.10/0.7.4/spire_2.10-0.7.4.jar:/Users/zz/.m2/repository/org/spire-math/spire-macros_2.10/0.7.4/spire-macros_2.10-0.7.4.jar:/Users/zz/.m2/repository/org/scala-lang/scala-reflect/2.10.5/scala-reflect-2.10.5.jar:/Users/zz/.m2/repository/com/google/guava/guava/11.0.2/guava-11.0.2.jar:/Users/zz/.m2/repository/com/github/scopt/scopt_2.10/3.2.0/scopt_2.10-3.2.0.jar:/Users/zz/.m2/repository/it/unimi/dsi/fastutil/7.0.2/fastutil-7.0.2.jar:/Users/zz/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar:/Users/zz/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain com.intel.analytics.bigdl.example.textclassification.TextClassifier
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/rdd/RDD
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:126)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.rdd.RDD
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

**Comment by jenniew** [comment]
Hi, this is the problem of IntelliJ environment. You can check the dependencies of bigDL module in project structure. The scope of Maven: org.apache.spark:spark-core_2.10:1.5.1 is Provided, which means the dependency is included in the classpath only at the compilation phase. So that's why the program cannot find class at runtime. I suggest you to set scopes of such dependencies to Runtime or Compile. Please refer to https://www.jetbrains.com/help/idea/2016.3/dependencies-tab.html to see detail information of IntelliJ.

**Comment by lefromage** [comment]
in IntelliJ: File->Project Structure->Modules->Dependencies
I tried both to replace org.apache.spark:spark-core_2.10:1.5.1 from Provided
to Compile I get the same results  missing RDD
or Runtime (then it cannot compile , because it does not have Spark Core...)
I did not find a way to set it to both Compile and Runtime, is there a way ?
Thanks
PS: Shouldn't this work out of the box correctly to facilitate developer's adoption in IntelliJ?

**Comment by dding3** [comment]
There is spark-core_2.10:1.5.1 in both 1.5-plus and bigdl modules, did you update both of them? I tried update them on my intellij and it worked.

We set the scope of spark related library as provided in pom so in IntellIJ by default it's also provided. We prefer not update it as compile as we don't want include spark related libs in bigdl library, they will make bigdl a huge jar. And generally when bigdl is invoked by spark-submit, these denpendecies will be provided by spark at runtime.

**Comment by yiheng** [comment]
Change the scope in Intellij is very easy. Just enable the all-in-one profile.

View -> Tools Windows -> Maven Projects

In the Maven Projects panel
Profiles -> click "all-in-one"

**Comment by lefromage** [comment]
Thanks @yiheng +1  ! that is the correct answer.

Specifically: View -> Tools Windows -> Maven Projects

Profiles -> clicking on all 4 below 
"1.5-plus"
"all-in-one"
"mac"
"scala_2.10"

worked for me on macbook pro.

**Comment by yiheng** [comment]
Update the wiki and close the issue.
