### ISSUE TITLE
Allow user to use RDD interface for BigDL training

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#403]
In the common case (e.g., python APIs), we should allow the users to prepare their data using RDD, and BigDL can then automatically transform these into batches for training:
1) User can simply construct an rdd of arrays and pass that rdd to Optimizer or Validator
2) Optimizer & Validator can automatically transform that into Sample and MiniBatch for training

**Comment by zhichao-li** [comment]
fixed in #429
