### ISSUE TITLE
`import bigdl.dllib.keras.layers` needs to install tensorflow

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#4033]
If we just import bigdl.dllib.keras.layers, it will invoke @keras_export and the call method here: https://github.com/intel-analytics/BigDL/blob/branch-2.0/python/dllib/src/bigdl/dllib/utils/bigdl_export.py#L54, which requires tensorflow.
If tensorflow isn't installed, will get an error.
In theory, dllib should not tightly depends on tensorflow.
Can we have some modifications for this? @dding3 (for example add a try except on the tensorflow code?)

**Comment by jason-dai** [comment]
We should remove the tf dependency

**Comment by hkvision** [comment]
lazy put import tensorflow into the `__call__` method doesn't work, will still invoke the `__call__` method, when it is used at keras Model @keras_import, need further modifications, could you help on this? @dding3

**Comment by hkvision** [comment]
@jason-dai When building conda package, conda will create a new environment to test the imports. We can detect the useless dependency after conda build is enabled.
