### ISSUE TITLE
Friesian dien preprocess failed in standalone mode.

### ISSUE THREAD

**Issue by nwang2** [intel-analytics/BigDL#4086]
Run the preprocess following the example readme:
python dien_preprocessing.py \
    --cluster_mode standalone \
    --master spark://master-url:port \
    --executor_cores 4 \
    --executor_memory 20g \
    --num_executor 20 \
    --input_meta /path/to/the/folder/of/meta_books \
    --input_transaction /path/to/the/folder/of/review_data\
    --output /path/to/the/folder/to/save/preprocessed/parquet_files 

See below error message:
py4j.protocol.Py4JJavaError: An error occurred while calling o92.generateStringIdx.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 31 in stage 8.0 failed 4 times, most recent failure: Lost task 31.3 in stage 8.0 (TID 932, 10.23.190.168, executor 13): java.lang.ClassNotFoundException: com.intel.analytics.bigdl.friesian.python.PythonFriesian$$anonfun$generateStringIdx$2$$anonfun$7

**Comment by hkvision** [comment]
Thanks for pointing out! This is a bug for setting classpath for jars. Fixing it.
