### ISSUE TITLE
Chronos: some of our unittest still rely on our deprecated API

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#4095]
Including test_mtnet.py and test_mtnet_forecaster.py.

**Comment by TheaperDeng** [comment]
@liangs6212 could you have a look on it?

**Comment by liangs6212** [comment]
> @liangs6212 could you have a look on it?


I think MTNet can be reconstructed using tf2?

**Comment by TheaperDeng** [comment]
> > @liangs6212 could you have a look on it?
> 
> I think MTNet can be reconstructed using tf2?

We will eventually do this. Still MTNet is not in our first round model migration. Currently we simply just want to replace these deprecated API usage.
e.g.
https://github.com/intel-analytics/BigDL/blob/812d4214a11b59de4d67547ffb3d63c34f16f3e9/python/chronos/test/bigdl/chronos/model/test_mtnet.py#L22

**Comment by liangs6212** [comment]
> > > @liangs6212 could you have a look on it?
> > 
> > 
> > I think MTNet can be reconstructed using tf2?
> 
> We will eventually do this. Still MTNet is not in our first round model migration. Currently we simply just want to replace these deprecated API usage. e.g.
> 
> https://github.com/intel-analytics/BigDL/blob/812d4214a11b59de4d67547ffb3d63c34f16f3e9/python/chronos/test/bigdl/chronos/model/test_mtnet.py#L22

OK, I'll replace the deprecated API.
