### ISSUE TITLE
Missing Implementation for LSTM

### ISSUE THREAD

**Issue by whitebread** [intel-analytics/BigDL#415]
Is there any support for LSTM networks?

**Comment by jason-dai** [comment]
We have been working on that, and please check back later.

**Comment by whitebread** [comment]
@jason-dai  Jason, do you think we have a broad timeframe for adding this feature?

**Comment by jason-dai** [comment]
@whitebread it's currently WIP and you may take a look at #481; let us know if you have any feedback.
