### ISSUE TITLE
Missing vdErf and vsErf jni bindings in MKL library

### ISSUE THREAD

**Issue by emartinezs44** [intel-analytics/BigDL#4164]
In the gelu implementation from the Transformer Layer the ERF function is used, I see (in BIGDL-core) that in the MKL the jni bindings for these two functions are not included and a non-MKL implementation from org.apache.commons.math3.util is being used. Is there any reason to exclude the vdErf and vsErf from the native binding that Bigdl 2.0 is using?

**Comment by qiuxin2012** [comment]
Because currently bigdl-core is using mkldnn(https://github.com/intel-analytics/BigDL-core/blob/5cb0a1947049289a447e91c6b4f59bb5d3b6ffda/mkl2017-xeon-blas/Makefile.common) to build the library.
vserf and vderf are included in MKL library but not in mkldnn library. The vserf and vderf's jni bindings are implemented in zoo-core, maybe we can merge them in the future.
```
<dependency>
                    <groupId>com.intel.analytics.zoo</groupId>
                    <artifactId>zoo-core-dist-all</artifactId>
                    <version>2.1.0-SNAPSHOT</version>
                    <type>jar</type>
</dependency>
```

**Comment by qiuxin2012** [comment]
reopen as #4181 merged by mistake.

**Comment by emartinezs44** [comment]
I included the zoo core dependency and I can use the MKL implementation. However, in the module MKLBlas.scala:

```
  def erf[T: ClassTag](tensor: Tensor[T])
    (implicit ev: TensorNumeric[T]): Unit = {
    /* uncomment below lines after zoo core merged into bigdl core
    if (BMKL.isMKLLoaded && tensor.isContiguous()) {
      ev.getType() match {
        case FloatType =>
          val value = tensor.storage().array().asInstanceOf[Array[Float]]
          vsErf(tensor.nElement(), value, tensor.storageOffset() - 1,
            value, tensor.storageOffset() - 1)
        case DoubleType =>
          val value = tensor.storage().array().asInstanceOf[Array[Double]]
          vdErf(tensor.nElement(), value, tensor.storageOffset() - 1,
            value, tensor.storageOffset() - 1)
        case _ => throw new UnsupportedOperationException(s"Only Float/Double supported")
      }
    } else {
      logger.warn("MKL is not used for erf, with mkl the performance will be much better")
      tensor.erf()
    }
    */
    tensor.erf()
  }
```

The MKL call is commented, maybe because zoo core is not included ass dependency. 

We can close the issue, I managed to update my model with the zoo dependency.
