### ISSUE TITLE
[PPML] Make Occlum more configurable

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/BigDL#4224]
Hardcoded values is not user friendly in K8S env. User need to rebuild image when they change any parameter. 

[Occlum Spark config](https://github.com/intel-analytics/BigDL/blob/main/ppml/trusted-big-data-ml/scala/docker-occlum/run_spark_on_occlum_glibc.sh#L18) 
[Occlum Flink config](https://github.com/intel-analytics/BigDL/blob/main/ppml/trusted-realtime-ml/scala/docker-occlum/init-occlum-taskmanager.sh#L14)

We can set default value for these parameters, then allow user to reset it with env (which can be passed into image with `-e` or yaml).

- [x] SGX_THREAD for max_num_of_threads, default 256
- [x] SGX_HEAP for default_heap_size, default 128MB
- [x] SGX_MMAP for default_mmap_size, default 3GB, need to be less than SGX_MEM_SIZE
- [x] SGX_KERNEL_HEAP for kernel_space_heap_size, default is 1024MB

@piaolaidelangman

**Comment by piaolaidelangman** [comment]
Occlum Spark in https://github.com/intel-analytics/BigDL/pull/4225.

**Comment by piaolaidelangman** [comment]
Occlum Flink in https://github.com/intel-analytics/BigDL/pull/4226.

**Comment by qiyuangong** [comment]
Feature completed  by @piaolaidelangman 
Issued closed
