### ISSUE TITLE
[Nano] Optional dependency management

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#4288]
# Problem
To maintain the composability of Nano, we make some of the dependencies optional if the corresponding feature is not used. 

However, code related to these optional dependencies is spread in many places in the code base, which makes it **hard to maintain what optional dependencies we currently have and hard to make sure normal code can be executed without meeting "ImportError"**.

# Proposal

## Code Structure
Each optional dependency has its own directory and all code related to this dependency should go into this directory. In addition, each dependency should have a single python file exposing all necessary interfaces to other components. This file should import its dependency lazily. 

E.g.
```
bigdl/nano/deps/inc/inc_api.py # should not import inc in the top-level or lazy import[1]
bigdl/nano/deps/inc/internal_inc_funcs.py # can import inc at the top-level
```
[1] lazy import, https://github.com/intel/neural-compressor/blob/master/neural_compressor/adaptor/tensorflow.py#L31

## Testing
Each dependency should have its own testing environment. 
Normal test cases should be executed in a environment without any of the dependencies.

## Optional Dependencies

- [x] INC
- [x] OPENVINO
- [x] ONNXRT ?
- [x] Horovod
- [x] Ray
- [x] IPEX

**Comment by yangw1234** [comment]
@TheaperDeng @zhentaocc what do you think?

**Comment by zhentaocc** [comment]
Agree on that. I was trying to refactor testing before https://github.com/intel-analytics/BigDL/issues/3919 but little progress on this.  
One note: seems onnxruntime and inc should be tested both separately and together.

**Comment by TheaperDeng** [comment]
Agree on the suggestion and I think Lazy Import might be the sliver bullet. 

BTW, for ut, Chronos recently adopt a pytest feature for different env: https://github.com/intel-analytics/BigDL/blob/main/python/chronos/test/bigdl/chronos/model/tf2/test_Seq2Seq_keras.py#L44

**Comment by TheaperDeng** [comment]
just update: working on onnxrt and onnx
