### ISSUE TITLE
[PPML] Occlum JDK change to JDK-8

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/BigDL#4293]
JDK-11 have some problem on spark 3.1.2. Need to change to JDK-8

@Forest216

**Comment by qiyuangong** [comment]
JDK 8 need to merge. Please reopen https://github.com/intel-analytics/BigDL/pull/4299

**Comment by Forest216** [comment]
![image](https://user-images.githubusercontent.com/41437440/178979581-5754b357-7e33-4d7d-941a-2b14270fb627.png)
It seems that I have no right to reopen this pull request. I can't find the reopen button.

**Comment by qiyuangong** [comment]
Seems that branch is removed. Don't worry. We can cherry-pick and reopen a new one.

**Comment by qiyuangong** [comment]
Addressed by @hzjane and @Forest216 in #5108
