### ISSUE TITLE
Failed to build with make-dist.sh (scala compile error)

### ISSUE THREAD

**Issue by shengyi-pan** [intel-analytics/BigDL#432]
when run command: **bash make-dist.sh -P spark_2.0 -P mac**

It's failed to compile scala source:

**[ERROR] BigDL/dl/src/main/scala/com/intel/analytics/bigdl/tensor/Tensor.scala:608: in object Tensor, multiple overloaded alternatives of method apply define default arguments.**
...
**[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (scala-compile-first) on project bigdl: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile failed. CompileFailed -> [Help 1]**

Please tell me how to solve the build problem, thank you in advance!

**Comment by zhichao-li** [comment]
Thanks for the report and it has been fixed by #433, pls pull the latest master and rebuild.
