### ISSUE TITLE
[PPML] Upgrade Occlum to 0.27.1

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/BigDL#4427]
Occlum 0.27.1 fixed several issues in Spark Unit test. Need to upgrade to this version for both spark and flink.

- [x] [Occlum Spark Dockerfile](https://github.com/intel-analytics/BigDL/blob/main/ppml/trusted-big-data-ml/scala/docker-occlum/Dockerfile#L161)
- [x] [Occlum Flink Dockerfile](https://github.com/intel-analytics/BigDL/blob/main/ppml/trusted-realtime-ml/scala/docker-occlum/Dockerfile#L88)

@Forest216

**Comment by Forest216** [comment]
Issue addressed with #4451 and #4452
