### ISSUE TITLE
Orca: Problem with core in RayContext

### ISSUE THREAD

**Issue by zhanglirong1999** [intel-analytics/BigDL#4428]
I used torch_distributed as my backend and found that RayContext doesn't convert cores if I pass core='*' in init_orca_context().

https://github.com/intel-analytics/BigDL/blob/main/python/orca/src/bigdl/orca/common.py#L324

https://github.com/intel-analytics/BigDL/blob/b57986b4b2702a03834656fc33cd5940e986058b/python/orca/src/bigdl/orca/ray/raycontext.py#L49

**Comment by hkvision** [comment]
@sgwhat Could you fix this?
Originally RayContext takes sparkcontext argument, and can get ray_node_cpu_cores from spark cores.
Now RayContext directly sets cores input, and in this case cores="*" is not handled, which is not friendly for spark users...

**Comment by sgwhat** [comment]
> @sgwhat Could you help fix this? Originally RayContext takes sparkcontext as argument, and can get ray_node_cpu_cores from spark cores. Now RayContext directly sets cores from init_orca_context as input, and in this case `cores="*"` is not handled, which is not friendly for spark users...

Sure, will have a look.
