### ISSUE TITLE
Chronos: Training batch_size should change automatically with the change of num_processes

### ISSUE THREAD

**Issue by Rebekk** [intel-analytics/BigDL#4475]
# What?
When I compare the speed of training TCNForecaster with and without nano, the throughputs they displays (xxx it/s) are of different standards. So the speed-up effect of nano cannot be seen intuitively.
# Why?
The nano setting of the forecaster will automatically identify the number of CPU cores, and then divide by 8 to determine the number of processes. As a result, an iteration will have different numbers of samples depending on the number of cores.
# How to change?
The training batch size should change automatically with the change of number of processes, instead of letting the user manually eliminate this difference to unify the throughput standard.

**Comment by TheaperDeng** [comment]
Not only TCNForecaster, all forecaster based on bigdl-nano[pytorch]'s transparent acceleration should all suffer this issue. 
You may change the behavior in https://github.com/intel-analytics/BigDL/blob/main/python/chronos/src/bigdl/chronos/forecaster/base_forecaster.py
