### ISSUE TITLE
[Nano] trainer.save accepts multiple types of models

### ISSUE THREAD

**Issue by zhentaocc** [intel-analytics/BigDL#4485]
# Description
Current API for model saving and loading. It can do:
1. save/export a pytorch model as openvino format 
2. save a `PytorchOpenVINOModel ` as local openvino file

**Do you think this is a bit confusing for users accepting multiple types of models?**   @jason-dai   
Otherwise we can just keep one of them.
### `trainer.save`
save from `PytorchOpenvinoModel`
```python
openvino_model = trainer.trace(model: nn.Module, x, accelerator='openvino')
trainer.save(openvino_model, 'model.xml`)
```
or save from torch model directly:
```python
trainer.save(model: nn.Module, 'model.xml`, input_sample=x, accelerator='openvino', input_sample=x)
```

### `trainer.load`
```python
openvino_model  = PytorchOpenVINOModel.load('model.xml')
```
```python
openvino_model = Trainer.load('saved_openvino_model.xml', accelerator='openvino')
```

**Comment by jason-dai** [comment]
We should have only one `save` method, which export standard model format (e.g., OpenVINO or ONNX format) that can be loaded by both nano and standard 3rd party tools (such as OpenVINO or ONNX Runtime).

**Comment by TheaperDeng** [comment]
I think for `trainer.save`, we may follow your first design (**and only support this design**), which means that our users will call `trace` or `quantize` to an accelerated model and then call `save` to dump a/multiple corresponding files(`.onnx`/`.xml`/`.state`...)

For pytorch model, the `trainer.load` could be tricky. Users could not take the dump file to a totally new runtime environment and load it(theoretically impossible). They will need a `model` instance as input. So I think we do need this model parameter. https://github.com/intel-analytics/BigDL/pull/4418#discussion_r857090273

**Comment by jason-dai** [comment]
> I think for `trainer.save`, we may follow your first design (**and only support this design**), which means that our users will call `trace` or `quantize` to an accelerated model and then call `save` to dump a/multiple corresponding files(`.onnx`/`.xml`/`.state`...)
> 
> For pytorch model, the `trainer.load` could be tricky. Users could not take the dump file to a totally new runtime environment and load it(theoretically impossible). They will need a `model` instance as input. So I think we do need this model parameter. [#4418 (comment)](https://github.com/intel-analytics/BigDL/pull/4418#discussion_r857090273)

What should the workflow look like to save/load a PyTorch model using the Nano API then?

**Comment by zhentaocc** [comment]
### For OpenVINO/ ONNX
save
```python
qmodel = trainer.quantize(model, accelerator='openvino/onnx')
trainer.save(qmodel, path)
```
load
```python
loaded_qmodel = trainer.load(path)
```
### For Pytorch
save when training finished
```python
model = resnet(..)
qmodel = trainer.quantize(model, accelerator=None)
trainer.save(qmodel, path)
```
load to run on other machine
```python
model = resnet(..)
loaded_qmodel = trainer.load(path, model)
```

**Comment by jason-dai** [comment]
LGTM
