### ISSUE TITLE
Nano quick start

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#4513]
For the quick start part of Nano's documentation, I have listed a few notebooks I think we can add.

I think it is better if we can use the same workload to train, inference, run quantization and then run automl to search for a better hyperparameter.

@jason-dai @shane-huang @TheaperDeng @zhentaocc what do you think? And do you have any suggested workload that is suitable for all these notebooks (train, inference, quantization and automl)? Train mnist?

**For pytorch:**
    
- [ ] Pytorch training quick start (candidate https://pytorch-lightning.readthedocs.io/en/stable/notebooks/lightning_examples/cifar10-baseline.html)

- [ ] Pytorch inference quick start

- [ ] Pytorch quantization quick start

- [ ] Pytorch automl quick start

**For tensorflow**

- [ ] TensorFlow training quick start

- [ ] TensorFlow quantization quick start

- [ ] Tensorflow automl quick start

**Comment by TheaperDeng** [comment]
When we talk about quick starts, we intend to run them on colab?

**Comment by yangw1234** [comment]
> When we talk about quick starts, we intend to run them on colab?



> When we talk about quick starts, we intend to run them on colab?

I think it is open for discussion.

**Comment by yangw1234** [comment]
> When we talk about quick starts, we intend to run them on colab?



> When we talk about quick starts, we intend to run them on colab?

I think it is open for discussion.
