### ISSUE TITLE
Ray get stucked while at the end of prediction

### ISSUE THREAD

**Issue by marcomeng** [intel-analytics/BigDL#4528]
I started the bigdl tensorflow job with spark-submit to deal with about 70,000,000 records, the parameters like following:
--conf spark.yarn.executor.memoryOverhead=8G \
--conf spark.executor.memoryOverhead=8G \
--master yarn-cluster \
--executor-memory 4g \
--driver-memory 4g \
--executor-cores 1 \
--num-executors 480 \

And initialize the orca context as following: 
init_orca_context(cluster_mode="spark-submit", object_store_memory='6g', init_ray_on_spark=True, exra_executor_memory_for_ray="8g",)

From the spark yarn log, it shows the prediction is nearly down, and no more new logs show up:

1764/1769 [============================>.] - ETA: 0s
[2m[36m(Worker pid=46411, ip=10.21.0.119)[0m 
1765/1769 [============================>.] - ETA: 0s
[2m[36m(Worker pid=46411, ip=10.21.0.119)[0m 
1766/1769 [============================>.] - ETA: 0s
[2m[36m(Worker pid=46411, ip=10.21.0.119)[0m 
1767/1769 [============================>.] - ETA: 0s
[2m[36m(Worker pid=46411, ip=10.21.0.119)[0m 
1768/1769 [============================>.] - ETA: 0s
1769/1769 [==============================] - ETA: 0s
1769/1769 [==============================] - 189s 103ms/step

I looked into one node, there is about 3.5G ray_pilled_objects:

ls -lh ../ray_spilled_objects/
total 3.5G
264M Apr 27 14:05 0c09ff90aa5754e2c8ffdb8fa87e50a9e64ede850100000001000000-multi-1
264M Apr 27 14:05 0e14f6c4005ab9bac8ffdb8fa87e50a9e64ede850100000001000000-multi-1
267M Apr 27 14:05 1e781fc61541185ec64037749866208b5582b4880100000001000000-multi-1
264M Apr 27 14:05 345befffd62ca062c8ffdb8fa87e50a9e64ede850100000001000000-multi-1
267M Apr 27 14:05 35277ba6e5f6ce358f27544b9fc7cb453f4bbaf80100000001000000-multi-1
267M Apr 27 14:05 3d7037496c32bfc0c64037749866208b5582b4880100000001000000-multi-1
267M Apr 27 14:05 50681e30bddf3948c64037749866208b5582b4880100000001000000-multi-1
 61M Apr 27 13:58 5416d7e73446d8b05369a0dda4ca9be260ab9ac10100000001000000-multi-18
101M Apr 27 13:58 57a916164f9be83e5369a0dda4ca9be260ab9ac10100000001000000-multi-30
3.4M Apr 27 14:01 77096e4dd9c02e2d5369a0dda4ca9be260ab9ac10100000001000000-multi-1
267M Apr 27 14:05 846392116f4a56728f27544b9fc7cb453f4bbaf80100000001000000-multi-1
267M Apr 27 14:05 8beac866e83be89ec8ffdb8fa87e50a9e64ede850100000001000000-multi-1
101M Apr 27 13:58 91b62d5f5a6570e65369a0dda4ca9be260ab9ac10100000001000000-multi-30
267M Apr 27 14:05 ad3947aa58c11b1fc64037749866208b5582b4880100000001000000-multi-1
267M Apr 27 14:05 bb5cce25eb6f45f08f27544b9fc7cb453f4bbaf80100000001000000-multi-1
267M Apr 27 14:05 d7280feca96f1ded8f27544b9fc7cb453f4bbaf80100000001000000-multi-1
101M Apr 27 13:58 e7c9c432f80bba1f5369a0dda4ca9be260ab9ac10100000001000000-multi-30

Some of the ray logs are still refreshing, I downloaded some of them, see the attachments:

[python-core-worker-734ab8a5975159cccf94ad9d20442793d3a29e4a0a34f3688a0ad20d_104188.log](https://github.com/intel-analytics/BigDL/files/8571909/python-core-worker-734ab8a5975159cccf94ad9d20442793d3a29e4a0a34f3688a0ad20d_104188.log)
[raylet.out.log](https://github.com/intel-analytics/BigDL/files/8571916/raylet.out.log)
[worker-734ab8a5975159cccf94ad9d20442793d3a29e4a0a34f3688a0ad20d-01000000-104188.err.log](https://github.com/intel-analytics/BigDL/files/8571917/worker-734ab8a5975159cccf94ad9d20442793d3a29e4a0a34f3688a0ad20d-01000000-104188.err.log)
[worker-734ab8a5975159cccf94ad9d20442793d3a29e4a0a34f3688a0ad20d-01000000-104188.out.log](https://github.com/intel-analytics/BigDL/files/8571919/worker-734ab8a5975159cccf94ad9d20442793d3a29e4a0a34f3688a0ad20d-01000000-104188.out.log)

**Comment by yushan111** [comment]
Maybe the object store memory is still insufficient. Would you mind trying allocating more memory for object store? 

Since in "raylet.out", it says `object_buffer_pool.cc:146: Not enough memory to create requested object ffffffffffffffffffffffffffffffffffffffff010000004e010000, aborting`

**Comment by marcomeng** [comment]
> 



> Maybe the object store memory is still insufficient. Would you mind trying allocating more memory for object store?
> 
> Since in "raylet.out", it says `object_buffer_pool.cc:146: Not enough memory to create requested object ffffffffffffffffffffffffffffffffffffffff010000004e010000, aborting`

I tried to increase the memory, the same error again, I noticed the object store memory is sufficient, I am thinking is it because of other memory insufficient?

Object store current usage 0.0435886 / 18 GB.

[2022-04-28 00:17:21,839 I 4756 4780] object_store.cc:35: Object store current usage 0.0435886 / 18 GB.
[2022-04-28 00:17:22,471 I 4756 4756] worker_pool.cc:418: Started worker process of 1 worker(s) with pid 9986
[2022-04-28 00:17:22,477 I 4756 4756] object_buffer_pool.cc:146: Not enough memory to create requested object ffffffffffffffffffffffffffffffffffffffff010000002e000000, aborting
[2022-04-28 00:17:22,477 I 4756 4756] object_buffer_pool.cc:146: Not enough memory to create requested object ffffffffffffffffffffffffffffffffffffffff0100000026000000, aborting
[2022-04-28 00:17:22,486 I 4756 4783] object_manager.cc:716: Received duplicate or cancelled chunk at index 7 of object ffffffffffffffffffffffffffffffffffffffff010000002e000000: overall 1/19 failed

**Comment by marcomeng** [comment]
I found a similar issue here:
https://github.com/ray-project/ray/issues/21883

**Comment by marcomeng** [comment]
Any plan to update to the ray new version?

**Comment by yushan111** [comment]
It might relate to the issue. Great findings! Thanks!

> Any plan to update to the ray new version?

it seems the PR for the fix has not been merged to Ray's official version. And we could only update to ray's official releases.

Although we have mainly tested BigDL on ray 1.9.2, it might work on a newer version of ray without any code changes. So I guess you could try BigDL with the latest ray (following Ray daily release installation docs [here](https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies)) and let us know if you meet any issues due to the version upgrade.  And then you could see whether a larger `RAY_CLIENT_MAX_BLOCKING_OPERATION_TIME_S` value helps.
