### ISSUE TITLE
Doc for more arguments for init_orca_context

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#4538]
Raised by customer: on the document pages, only some typical arguments are listed. They want a full list of other arguments. Need to think of how to arrange such kind of complicated doc in a good way for users to understand.

**Comment by jason-dai** [comment]
Do we have Python doc?

**Comment by hkvision** [comment]
Currenly no in the Python API Orca section.
But even it can be generated, in our implementation, we use **kwargs, which still needs to write the doc manually? Any better ideas?
