### ISSUE TITLE
Problem in Running bigdl.sh

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#455]
Hello

I have an error while running
spark-submit --class com.intel.analytics.bigdl.models.vgg.Train \
dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar \
--core 1 \
--node 1 \
--env spark \
-f cifar10_folder/ \
-b 4

I get the error  **java.lang.OutofMemoryError: Java heap space.**

I am using an Intel Xeon KNL machine and openjdk version 1.8.0_121, scala  version 2.11.6 and Spark 1.6 on CentOS

ANy help would be appreciated.

Thanks
Jay Mahalingam
Calligo Technologies

**Comment by jaymahesh** [comment]
this got solved by adding --driver memory 12g !
Any other comment welcome on my configuration

**Comment by jason-dai** [comment]
Yes - you need to set the memory used for Spark tasks (using spark.driver.memory or spark.executor.memory depending whether your are running in spark local mode or distributed mode).
