### ISSUE TITLE
Which IDE for Tutorials page programs?

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#456]
Hello

I would like to know if the programs shown in this link (LeNet, Text and Image classifications) are to be run after installing Scala IDE. What are the typical BIOS and IDE settings to be  entered?
https://github.com/intel-analytics/BigDL/wiki/Tutorials

Should we expect any issues?

THanks
Jay Mahalingam
Calligo Technology

**Comment by jason-dai** [comment]
Closing this issue; if there are further questions, please send them to BigDL user group (https://groups.google.com/forum/#!forum/bigdl-user-group).
