### ISSUE TITLE
VGG training: How many max number of Cores/ Nodes

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#457]
In the BigDL.sh, for running the VCG training, how many max number of cores can I specify, My machine is Intel KNL and wanted to check if all 68 cores can be specified and then performance boost can be expected (i.e time taken to train can be reduced)

Similarly how many Nodes max can be specified?

Thanks
Jay Mahalingam
Calligo Technologies

**Comment by jaymahesh** [comment]
If I specify 64 cores, is the training model written in a way to take advantage of all cores in parallel?

**Comment by jason-dai** [comment]
it is recommended to set the number of cores to the number of physical cores (not logical processors) on the machine.

**Comment by jason-dai** [comment]
And yes, BigDl will take advantage of all cores in parallel.

**Comment by jason-dai** [comment]
Closing this issue; if there are further questions, please send them to BigDL user group (https://groups.google.com/forum/#!forum/bigdl-user-group).
