### ISSUE TITLE
upgrade pytorch and ipex version in Nano to 1.11

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#4571]
- [x] Chronos Jenkins switch to dynamically create conda environment so that we can test new PyTorch without effecting current tests https://github.com/analytics-zoo/cicd/issues/80
- [x] upgrade INC version to 1.11.0 #4575
- [x] change nano code (overriding `pl.Trainer`'s `fit` and inject `ipex.optimize`) (https://github.com/intel-analytics/BigDL/pull/4574)
- [x] verify other nano components and chronos works on pytorch 1.11 (pass all tests should suffice)

**Comment by yangw1234** [comment]
@TheaperDeng do we have plans to update the Chronos testing environment (the first point)?

**Comment by TheaperDeng** [comment]
> @TheaperDeng do we have plans to update the Chronos testing environment (the first point)?

We have a issue recorded here https://github.com/intel-analytics/arda-docker/issues/619#issuecomment-1107683938

We don't have plan for now but we can start to plan it from now @liangs6212

**Comment by yangw1234** [comment]
@TheaperDeng how about we first fix the nano version to the current nightly version, so that the nano upgrade will not affect Chronos.

**Comment by liangs6212** [comment]
> > @TheaperDeng do we have plans to update the Chronos testing environment (the first point)?
> 
> We have a issue recorded here [intel-analytics/arda-docker#619 (comment)](https://github.com/intel-analytics/arda-docker/issues/619#issuecomment-1107683938)
> 
> We don't have plan for now but we can start to plan it from now @liangs6212

Ok, I'll test the new version locally on Chronos,

**Comment by TheaperDeng** [comment]
> @TheaperDeng how about we first fix the nano version to the current nightly version, so that the nano upgrade will not affect Chronos.
> 
> Then Chronos can periodically bump nano version as needed.

We talked about this and find some issue may happens if we do this https://github.com/intel-analytics/BigDL/issues/4583
Currently we will stick to the dynamic installation of chronos's jenkins test env. We may have some discussions in #4853 for this decouple proposal.
