### ISSUE TITLE
Nano: torchmetrics version problem

### ISSUE THREAD

**Issue by rnwang04** [intel-analytics/BigDL#4581]
After I run the following install command :
```
pip install bigdl-nano[pytorch]
source bigdl-nano-init
```
An error occurred in **python pl-finetune.py**，the cause is "cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'"
Is there may any unresolved version conflict ?

**Comment by rnwang04** [comment]
I solved this problem by pip install torchmetrics==0.6.0 additionly.

**Comment by jason-dai** [comment]
@yangw1234 please take a look

**Comment by yangw1234** [comment]
pl-finetune.py is a PyTorch application, right? 

Maybe you should try `pip install bigdl-nano[pytorch]`
`

**Comment by yangw1234** [comment]
sync offline. `pip install bigdl-nano[pytorch]` will have an version issue because `torch_metrics` released their new version recently. This issue has been fixed on our main branch.

**Comment by shane-huang** [comment]
shall we backport a hotfix to bigdl 2.0 branch and release a new PyPI package? Our cvpr audiences might want to install a stable version to have a try.

**Comment by jason-dai** [comment]
> shall we backport a hotfix to bigdl 2.0 branch and release a new PyPI package? Our cvpr audiences might want to install a stable version to have a try. @jason-dai @yangw1234

v2.0 is pretty old; the demo can be based on our nightly, or we may release v2.1 in June.

**Comment by jason-dai** [comment]
Is this issue fixed? @yangw1234

**Comment by yangw1234** [comment]
> Is this issue fixed? @yangw1234

In the current main branch: yes, it is fixed. 

But, if user use v2.0, he/she will still meet this error.
