### ISSUE TITLE
[TBD] Should we decouple Chronos and Nano in nightly release

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#4583]
Nano is envolving quickly including
- New API and functionalities
- More advanced library(different version/more dependencies) support

These will all reflect on Chronos's source code and dependencies since we are now matching Chronos and Nano's daily release.
![2022-05-10-22-50-49-image](https://user-images.githubusercontent.com/35031544/167753374-6633dbbb-0545-4498-bd7e-d5c12698581a.png)

We are talking about decouple Chronos and Nano's nightly release. This means that we will maintain a supported version of nano in Chronos, and our users and developers for chronos will install this supported nano version.

I have talked about this with @liangs6212 and @yangw1234 , and here are pro and cons.

PRO:
1. Now Nano developers don't need to worry their changes might break Chronos's code, which will make life easier.

CON:
1. Chronos needs to adopt all changes in nano in a period once it need to support a new version.
2. There will be a time gap between nano's bug fix and chronos's bug fix

![2022-05-11-09-38-43-image](https://user-images.githubusercontent.com/35031544/167753451-800252bc-20b0-419e-b734-d0b5fbf657a7.png)

**Comment by jason-dai** [comment]
Having one single release is much easier to maintain in the long run. I wonder if you can elaborate what current changes in Nano that make it difficult to keep Chronos in sync with Nano?

**Comment by TheaperDeng** [comment]
> Having one single release is much easier to maintain in the long run. I wonder if you can elaborate what current changes in Nano that make it difficult to keep Chronos in sync with Nano?

Well currently I still prefer to make chronos and nano's nightly release unchanged.

We will:
1. Make sure new APIs in Nano being adopted in Chronos asap, working on this myself.
2. Change pr validation to dynamic env (create, install, remove a conda env every time) https://github.com/analytics-zoo/cicd/issues/80 working on this with @liangs6212
