### ISSUE TITLE
InvalidArgumentError: Cannot assign a device for operation PyFunc when run nano.tf.keras pseudo-distributed training

### ISSUE THREAD

**Issue by y199387** [intel-analytics/BigDL#4636]
I'm using use keras ImageDataGenerator to do data augmentation and ImageDataGenerator.flow(...) return a Iterator. So I create tf.data.Dataset with tf.data.Dataset.from_generator(...). Everything goes well when running single process training. But when I call model.fit(..., num_processes=1, backend="multiprocessing") I get an error:

tensorflow.python.framework.errors_impl.InvalidArgumentError:  Cannot assign a device for operation PyFunc: {{node PyFunc}} was explicitly assigned to /job:localhost/replica:0/task:0 but available devices are [ /job:worker/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[PyFunc]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]] [Op:__inference_train_function_18532]

After I gave up on data augmentation and created tf.data.Dataset with tf.data.Dataset.from_tensor_slices() . I run the pseudo-distributed training again, this error disappear.

**Comment by yangw1234** [comment]
This is a known issue. Nano tensorflow multi-processing does support from generators.
