### ISSUE TITLE
Nano：some problems and maybe more friendly and clear tips

### ISSUE THREAD

**Issue by rnwang04** [intel-analytics/BigDL#4641]
1. protobuf version
Sometimes after I "pip install --pre bigdl-nano[pytorch]", it produces "AttributeError: module 'distutils' has no attribute 'version'".
I fix this problem by pip install setuptools==58.0.4, maybe we should add some specifications to the version of protobuf?

2. quantize with onnxruntime's method
In the trainer.quantize() method, when the user enters accelerator="onnxruntime", we can check the method parameter by means such as assert, to remind the user to modify the method parameter. It maybe avoid the user taking a long time like I did yesterday to find that the bug was caused by the method parameter.

3. if not input_sample: in trainer.quantize() method
When I pass in a batch of data, an error is reported “RuntimeError: Boolean value of Tensor with more than one value is ambiguous”. Maybe it should be change as:
`if input_sample is None:`

4. post_training_quantize's collate_fn
In quantizer.post_training_quantize(), **calib_dataloader.collate_fn = func** will produce bug in wrong data type if the user specifies their own collate_fn function. May it can be changed as：
``if calib_dataloader.collate_fn is None: 
     calib_dataloader.collate_fn = func``

5. check_pytorch_dataloaders in Train.quantize
Maybe we don't need to _check_data_type(y) when we don't tunning ?

**Comment by yangw1234** [comment]
hi @rnwang04 for each of these problems, would you mind creating separate issues so that we can easily track each of them.

**Comment by rnwang04** [comment]
@yangw1234 ok, I will update it later~

**Comment by jason-dai** [comment]
Are all the issues fixed or reported elsewhere?

**Comment by rnwang04** [comment]
1, 4 have been fixed, and I report 2, 3, and 5 in separate issues.
