### ISSUE TITLE
ray.init will return ray's RayContext object in the latest versions

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#4653]
Reported by the customer.
https://github.com/ray-project/ray/blob/5964a58d84b8fe60163dc50a94e275d31a11413b/python/ray/worker.py#L618
In the latest version of Ray, Ray adds the `RayContext` itself and will return the RayContext object that contains the address_info for ray.init.
Previously the return result address_info is a dict.

After upgrading ray to a newer version, user may confuse ray's RayContext and our RayContext, do we have plan to distinguish them or modify the API?

cc @jason-dai @yushan111

**Comment by jason-dai** [comment]
Maybe `OrcaRayContext`? @sgwhat

**Comment by sgwhat** [comment]
> Maybe `OrcaRayContext`? @sgwhat

Sure.

**Comment by sgwhat** [comment]
Solved in https://github.com/intel-analytics/BigDL/pull/4661.
