### ISSUE TITLE
bigdl-nano-init slows down tcn forecaster with multiple processing

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/BigDL#4689]
### To produce: 
1. `source bigdl-nano-init`
2. run `fit` in https://github.com/intel-analytics/BigDL/blob/main/python/chronos/use-case/network_traffic/network_traffic_multivariate_multistep_tcnforecaster.ipynb

### More info

18 physical cores, run `num_processes=2` with nano pytorch trainer  
Intel(R) Core(TM) i9-9980XE CPU @ 3.00GHz

**Comment by TheaperDeng** [comment]
please have a try @liangs6212 to reproduce this. thx

**Comment by liangs6212** [comment]
The problem still exists when `forecaster.numprocess` is not 1. I tried two solutions,
* unset `KMP_INIT_AT_FORK`
* Make sure `TCNForecaster` is initialized before `sklearn`.

I ensure correctness by restarting the kernel multiple times when testing in the notebook.

TestInfo
* Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
* 10 physical cores (set magic_num to 4)
* forecaster.num_processes is 2
* network_traffic_multivariate_multistep_tcnforecaster

**Comment by TheaperDeng** [comment]
same issue to #4590
