### ISSUE TITLE
Chronos: KMP_AFFINITY error without bigdl-nano-init in forecasters

### ISSUE THREAD

**Issue by yushan111** [intel-analytics/BigDL#4692]
**to reproduce**
Run on a machine with >= 16 cores
Chronos automatedly set `num_processes = max(1, current_num_threads//8)`, e.ge in [tcn_forecaster](https://github.com/intel-analytics/BigDL/blob/main/python/chronos/src/bigdl/chronos/forecaster/tcn_forecaster.py#L134)

Without bigdl-nano-init first, before running `forecaster.fit`

There will be an error reported by nano

```
~/anaconda3/envs/chronos/lib/python3.7/site-packages/bigdl/nano/pytorch/plugins/ddp_spawn.py in start_processes_new(fn, args, nprocs, join, daemon, start_method, cpu_procs)
     88         pass
     89 
---> 90     os.environ["KMP_AFFINITY"] = init_KMP_AFFINITY
     91     os.environ["OMP_NUM_THREADS"] = init_OMP_NUM_THREADS
...    
str expected, not NoneType
```

**Comment by TheaperDeng** [comment]
related issue: https://github.com/intel-analytics/BigDL/issues/4592
