### ISSUE TITLE
Nano: torchvision version problem when use ipex.

### ISSUE THREAD

**Issue by y199387** [intel-analytics/BigDL#4727]
I try to import pytorch-lightning when I use **ipex 1.9.0** and **openvino-dev 2022.1.0**, an error is reported "Segmentation fault (core dumped)".
I found ipex change the version of torch to "torch 1.9.0+cpu", but the version of torchvision is still "torchvision 0.10.0", the error may be caused by this.
This error did disappear after I manually replaced the torchvision version with "torchvision 0.10.0+CPU".

**Comment by yangw1234** [comment]
Could you add a line in the IPEX section in our [document](https://github.com/intel-analytics/BigDL/blob/main/docs/readthedocs/source/doc/Nano/QuickStart/pytorch_train.md) to ask users to also install `torchvision 0.10.0+CPU`.

**Comment by y199387** [comment]
Done

**Comment by y199387** [comment]
https://github.com/intel-analytics/BigDL/pull/4786
