### ISSUE TITLE
Nano: Need to add unit tests to check whether setting use_ipex takes effect

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#4810]
Implementation:

Maybe using pytorch-lightning callbacks, implement `CheckIPEXCallabck` and `CheckNonIPEXCallback`.

For ipex 1.9, checkout the models' device, for ipex 1.10 and 1.11, check if the model contains ipex layers (e.g. _ipex_conv)

**Comment by yangw1234** [comment]
@y199387 could you take a look at this issue?

**Comment by y199387** [comment]
CheckIPEXCallback added #4839
