### ISSUE TITLE
Exception on saving BasePytorchForecaster after to_local conversion

### ISSUE THREAD

**Issue by Dnnd** [intel-analytics/BigDL#4816]
Consider the following snippet:

```python3
from bigdl.orca.data import XShards
import numpy as np
from bigdl.chronos.forecaster import LSTMForecaster
from bigdl.chronos.data import TSDataset
from bigdl.orca import init_orca_context

sc = init_orca_context(cluster_mode='local', cores=2, memory="4g", init_ray_on_spark=True)

x = np.random.rand(1000, 400, 2).astype(np.float32)
y = np.random.rand(1000, 400, 2).astype(np.float32)


def transform_to_dict(train_data):
    return {"x": train_data[0], "y": train_data[1]}

train_shards = XShards.partition((x , y)).transform_shard(transform_to_dict)

forecaster = LSTMForecaster(
    past_seq_len=24,
    input_feature_num=2,
    output_feature_num=2,
    loss="mae",
    lr=0.01,
    distributed=True
)

forecaster.fit(train_shards)

forecaster.to_local()

forecaster.save("forecaster.checkpoint")
```
I'm fitting an LSTMForecaster with `distributed=True`, converting it to local forecaster and then trying to save it.

I'm getting the following error:

```
Traceback (most recent call last):
  File "issue.py", line 33, in <module>
    forecaster.save("forecaster.checkpoint")
  File "***/lib/python3.7/site-packages/bigdl/chronos/forecaster/base_forecaster.py", line 420, in save
    self.trainer.save_checkpoint(checkpoint_file)  # save current status
AttributeError: 'LSTMForecaster' object has no attribute 'trainer'
```

It seems like `.save()` method in the `BasePytorchForecaster` requires the presence of the `trainer` field for local forecaster. But this field is only being set when forecaster [is fitted in the non-distributed mode](https://github.com/intel-analytics/BigDL/blob/ffcfc648a13bc1fd5fbbe2592c3bc82881da0c8e/python/chronos/src/bigdl/chronos/forecaster/base_forecaster.py#L158) and `to_local()` method doesn't set the `trainer` field.

**Comment by TheaperDeng** [comment]
Hi, thanks for the feedback. It seems to be an issue during the `to_local()` method, where a trainer should be created for saving or other operations. We will fix it soon.

**Comment by Dnnd** [comment]
Thank you for the quick fix!
I can verify that I'm no longer getting the error with `bigdl-chronos-spark3==2.1.0b20220613`

**Comment by TheaperDeng** [comment]
happy to know is has been resolved 😄

**Comment by Dnnd** [comment]
Can I close the issue now or you want to keep it open for some time?

**Comment by TheaperDeng** [comment]
I close this issue for now. If there is any bug or feature request, you may open another issue. Thanks for the feedback.
