### ISSUE TITLE
Nano : TestImageFolder test_resnet18_quantitrain_image_folder_pngze failed

### ISSUE THREAD

**Issue by rnwang04** [intel-analytics/BigDL#4832]
Here are my steps : 
1. pip install --pre --upgrade bigdl-nano[pytorch]
2. set environment variables
export PYTHONPATH=/home/cpx/ruonanw/BigDL/python/chronos/src:/home/cpx/ruonanw/BigDL/python/dllib/src:/home/cpx/ruonanw/BigDL/python/orca/src:/home/cpx/ruonanw/BigDL/scala/dllib/src/main/resources/spark-bigdl.conf:/home/cpx/ruonanw/BigDL/python/nano/src
export FTP_URI=ftp://zoo:1234qwer@10.112.231.51
export ANALYTICS_ZOO_ROOT=/home/cpx/ruonanw/BigDL
3. under BigDL dir, bash python/nano/test/run-nano-pytorch-tests.sh

then https://github.com/intel-analytics/BigDL/blob/bece7b73a75114d99c6eb6e3013811566f87ff59/python/nano/test/pytorch/tests/vision/test_imagefolder.py#L37 failed, the error message is "RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually. e.g. jpeg = TurboJPEG(lib_path)"
and in my server, I can't find this path and corresponding libs dir https://github.com/intel-analytics/BigDL/blob/bece7b73a75114d99c6eb6e3013811566f87ff59/python/nano/src/bigdl/nano/pytorch/vision/datasets/datasets.py#L30

**Comment by yangw1234** [comment]
you should either use local bigdl-nano in your PYTHONPATH and download the required files specified in `setup.py` or use the bigdl-nano installed in `site-packages`

**Comment by rnwang04** [comment]
thanks @yangw1234
