### ISSUE TITLE
Does the Bigdl.sh work with Hadoop?

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#486]
If the Spark is setup on Hadoop, can we point 'cifar' dataset from a HDFS system?

**Comment by jason-dai** [comment]
The Spark program need to read from HDFS (bigdl.sh just launches the Spark program); for instance, see the image classification example (https://github.com/intel-analytics/BigDL/tree/master/dl/src/main/scala/com/intel/analytics/bigdl/example/imageclassification).

**Comment by jason-dai** [comment]
Closing this issue; if there are further questions, please send them to BigDL user group (https://groups.google.com/forum/#!forum/bigdl-user-group).
