### ISSUE TITLE
Cluster mode for BigDL

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#487]
1) Can I put the KNL system in SNC4 mode and then specify nodes 2 within the same machine?

2) If I want to cluster (to increase the node numbers), can use KNL cluster with 2 modes intercconnected and then specify node numbers as 2? Would I have to setup the Bigdl.sh in the secondary or data node also?

Any documentation would be welcome..

**Comment by jason-dai** [comment]
To run BigDL in a distributed fashion (i.e., more than one node), you need to first set up a Yarn or Spark cluster, and then specify appropriate parameters using bigdl.sh (which runs on the Spark driver node). See the example of running vgg on Spark cluster mode at https://github.com/intel-analytics/BigDL/blob/master/dl/src/main/scala/com/intel/analytics/bigdl/models/vgg/README.md#train-model-on-spark

**Comment by jaymahesh** [comment]
1) Did you mean for cluster I need to setup Hadoop/YARN?

2) Lets say I have total of two nodes, one of them is the Master(node#1), what SW components should be loaded on the 2nd node? Should I have 'bigdl.sh' running on Node#2 as well?

3) I am planning to input the Cifar data to Master node thru HDFS instead of a local drive, hope thats fine

4) I am also planning to change the memory mode of the KNL machine --driver-mem 32g so that it uses the MCDRAM. WIll this be faster (as it will be 16g MCDRAM and 16g RAM)

THanks

**Comment by jason-dai** [comment]
@jaymahesh For 1) - you may use either a YARN cluster or Spark standalone cluster; please refer to http://spark.apache.org/docs/1.6.0/cluster-overview.html for more details.

For 2), "bigdl.sh" is just a script to launch BigDL program, both of which need to be on the Spark driver node; again, you may refer to http://spark.apache.org/docs/1.6.0/cluster-overview.html for more details.

For 3), yes, you may put the Cifar data on the same node with the BigDL program (and "bigdl.sh")

For 4), yes, it works; in addition, you may want to increase the memory of executor for better performance.

**Comment by jaymahesh** [comment]
1) Then should we not be specifying somewhere is the bighdl.sh 
--master spark://<IP address> \ 

2) How do we specify the client Node IP Address in the bigdl.sh?

3) and where exactly do we specify nodes as 2, is it
--node 2 \ # this appears in Train mode
or --nodeNumber <number> \ # this appears in Test mode

**Comment by jason-dai** [comment]
There is no need to specify the client or master address for bidl.sh; instead, when running on Spark, one should use bigdl.sh to invoke spark-submit, and need to provide appropriate parameters (including master address) to spark-submit; see http://spark.apache.org/docs/latest/submitting-applications.html#launching-applications-with-spark-submit for more details on spark-submit.

And yes, it seems that the VGG example uses different arguments in the train and test modes; we will try to fix that by using the same arguments.

**Comment by jaymahesh** [comment]
Hello @jason-dai 
It is not clear what you meant by "instead, when running on Spark, one should use bigdl.sh to invoke spark-submit, and need to provide appropriate parameters (including master address) to spark-submit;" Is it different from editing bigdl.sh for --master, --deploy, --executor-memory etc and then running it?

Can you pls show in command how this is to be run?. I have one master and one slave and would like to know where master's IP needs to be  @specified.

**Comment by jaymahesh** [comment]
What I mean is the below command (a reproduction of bigdl.sh) works on it own
spark-submit --class com.intel.analytics.bigdl.models.vgg.Train --driver-memory 32g /root/BigDL/dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar --core 64 --node 1 --env spark  -f /root/cifar-10-batches-bin

 but if I add 
-master spark://192.168.1.202:7077 --deploy-mode cluster --executor-memory 20G to the same command
it fails saying unknown option and argument

**Comment by yiheng** [comment]
Hi @jaymahesh 

The command may looks like this
./dist/bin/bigdl.sh -- \
spark-submit --master spark://192.168.1.202:7077 \
--deploy-mode cluster \
--executor-memory 20G \
--class com.intel.analytics.bigdl.models.vgg.Train \
dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar \
--core physical_core_number \
--node node_number \
--env spark \
-f Cifar-folder \
-b batchsize \
--checkpoint ~/model

**Comment by jaymahesh** [comment]
Hi @yiheng 

I substituted this below in bigdl.sh  and the program executes within 2 seconds- with no error or any other output !!

**spark-submit --master spark://192.168.1.202:7077 --deploy-mode cluster --executor-memory 20g --class com.intel.analytics.bigdl.models.vgg.Train --driver-memory 32g /root/BigDL/dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar --core 64 --node 1 -b 256 --env spark -f /root/cifar-10-batches-bin --checkpoint ~/model**

Can you pls check and tell mw what is wrong? FYI... i have /root/BigDL/dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar path & file in both master and worker nodes.

**Comment by yiheng** [comment]
I can see you use a cluster deploy-mode. Please try --deploy-mode client

**Comment by jaymahesh** [comment]
I tried this, but got the error msg as below (remember on standalone local everything worked fine)
spark-submit --master spark://192.168.1.202:7077 --deploy-mode client --executor-memory 20g --class com.intel.analytics.bigdl.models.vgg.Train --driver-memory 32g /root/BigDL/dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar --core 64 --node 1 -b 256 --env spark -f /root/cifar-10-batches-bin --checkpoint ~/model

17/02/27 17:17:50 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.1.202:49243]
[Stage 0:>                                                         (0 + 8) / 64]17/02/27 17:18:08 ERROR scheduler.TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, storage.calligotech.com): java.io.InvalidClassException: org.apache.spark.rdd.MapPartitionsRDD; local class incompatible: stream classdesc serialVersionUI

**Comment by yiheng** [comment]
Looks like your local spark version is not compatible with your cluster...

java.io.InvalidClassException: org.apache.spark.rdd.MapPartitionsRDD; local class incompatible: stream classdesc serialVersionUI

**Comment by jaymahesh** [comment]
Hello @jason-dai @yiheng 

I tried this command and I keep getting 'Master is unresponsive' although I am able to invoke spark-shell --master <IP>:7077 to scala prompt. I have one Master and one worker. Master has 64 cores and worker has 48 cores, FYI. The program runs well as a single node (without worker) machine and completes both Train and Test.

**Pls help throw some light**, thanks

./bin/spark-submit \
  --class <vggTrainPrgram> \
  --master spark://<MasterIP>:7077 \
  --executor-memory 20G \
  --total-executor-cores 40 \
  /dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar \
--core 48 \
--node 1 \
--env spark \
-f Cifar-folder \
-b 256 \
--checkpoint ~/model

**Comment by psyyz10** [comment]
Hi @jaymahesh ,

It seem there are some problems on the cluster.
Could you run the following code successfully?

"""
./bin/spark-submit \
 --class org.apache.spark.examples.SparkPi \
 --master yarn-client  \
 --deploy-mode client  \
 --driver-memory 4g    \
 --executor-memory 2g   \
 --executor-cores 48    \
lib/spark-examples*.jar 
"""

**Comment by jason-dai** [comment]
Closing this issue; if there are further questions, please send them to BigDL user group (https://groups.google.com/forum/#!forum/bigdl-user-group).
