### ISSUE TITLE
Nano : openvino version error

### ISSUE THREAD

**Issue by rnwang04** [intel-analytics/BigDL#4899]
Here is my setup step:
```
conda create -p /mnt/disk1/nano python=3.7
source activate /mnt/disk1/nano
pip install --pre bigdl-nano[pytorch]
pip install openvino-dev
```
and the installed openvino is openvino-dev-2021.4.2, which will report "ModuleNotFoundError: No module named 'opvino.tools.pot' " in Trainer.trace().
I have tried update pip, pip install --no-cache-dir openvino-dev, pip install openvino-dev==2022.1.0. All failed.

**Comment by TheaperDeng** [comment]
This could be some dependency conflict between default installation of bigdl-nano[pytorch] and openvino==2022.1.0

**Comment by rnwang04** [comment]
Unfortunately "CentOS" is not supported anymore in openvino==2022.1.0 .
See: https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes-2021.html
We may add some hints about it ?
