### ISSUE TITLE
Jenkins fails when update Nano PyTorch version to 1.11.0

### ISSUE THREAD

**Issue by y199387** [intel-analytics/BigDL#4911]
Jenkins job need to be changed accordingly when set Nano default PyTorch version to 1.11.0.
Currently only neural-compressor versions >= 1.11 support PyTorch 1.11+，and they only support onnxruntime >= 1.8.0. This makes tests related to onnxruntime on Jenkins fail.

related output：
torch 1.11.0 neural-compressor 1.8.1 onnxruntime 1.6.0
http://10.112.231.51:18888/job/BigDL-PRVN-chronos-Python-Spark-2.4-py37-ray-part1/1095/consoleFull
torch 1.11.0 neural-compressor 1.11 onnxruntime 1.6.0 onnxruntime-extensions

torch 1.11.0 neural-compressor 1.11 onnxruntime 1.10.0 onnxruntime-extensions
http://10.112.231.51:18888/job/BigDL-PRVN-chronos-Python-Spark-2.4-py37-ray-part1/1097/consoleFull

**Comment by TheaperDeng** [comment]
I think this issue should go to https://github.com/intel-analytics/arda-docker/issues

**Comment by y199387** [comment]
Ok, I will close this issue.
