### ISSUE TITLE
MethodNotFound - Urgent Issue, kindly help!

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#499]
At the end of a succeful Train, I am getting this error of Method Not found
**java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.tryOrIOException**
Can someone tell me what is **wrong**? 
My scala version 2.11.8
Java version 1.8.0_121; Spark version 1.6.3
Here is my bigdl.sh.. I built with 'make-dist.sh'

spark-submit --class com.intel.analytics.bigdl.models.vgg.Train --driver-memory 32g \
/root/BigDL-master/dl/target/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies-and-spark.jar \
--maxEpoch 1 \
--core 64 \
--node 1 \
--env spark \
-f /root/cifar-10-batches-bin/ \
-b 256 \
--checkpoint ~/model

**Comment by linbojin** [comment]
If you use spark-submit i think you should use bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar  rather than bigdl-0.1.0-SNAPSHOT-jar-with-dependencies-and-spark.jar

**Comment by jaymahesh** [comment]
Thanks. I changed it to bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar

I still get this error below, kindly help, thanks
Exception in thread "dispatcher-event-loop-7" java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.tryOrIOException(Lscala/Function0;)V

**Comment by jaymahesh** [comment]
I solved this by rebuilding from the source.
