### ISSUE TITLE
Support MKL2017 DNN API

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#5]
Intel MKL release 2017 version and it contains a DNN API, which provide DNN operation optimized for IA architecture. We will add new layers which leverage these new APIs to get a better performance on CPU.

**Comment by bhack** [comment]
Can Intel finally clarify relation roadmap against this and https://github.com/intel-analytics/BigDL/pull/363? At "marketing" level is quite confusional.

**Comment by i8run** [comment]
#363 is the same as this issue. @bhack

**Comment by bhack** [comment]
But is mkl-dnn https://github.com/01org/mkl-dnn?

**Comment by jason-dai** [comment]
Here mkl-dnn actually refers to the DNN primitives in Intel MKL 2017 (https://software.intel.com/en-us/articles/introducing-dnn-primitives-in-intelr-mkl)

**Comment by bhack** [comment]
There will be a disambiguation between the two?

**Comment by bhack** [comment]
Cause mkl dnn api and mkl-dnn api have a very similar marketing name.

**Comment by bhack** [comment]
Ok probably it is still not clear the roadmap also if one is opensource and the other one is closed:

> Intel MKL-DNN includes functionality similar to Intel(R) Math Kernel Library (Intel(R) MKL) 2017, but is not API compatible. We are investigating how to unify the APIs in future Intel MKL releases.

**Comment by jason-dai** [comment]
We plan to support the DNN primitives in Intel MKL 2017 at this moment; no plan for the https://github.com/01org/mkl-dnn support yet.
