### ISSUE TITLE
multi-task run on one Executor/Container

### ISSUE THREAD

**Issue by nikenj** [intel-analytics/BigDL#500]
i have successed runing the java vgg example,but when runing the spark example,it failed,the submit is follow:
./dist/bin/bigdl.sh -- spark-submit --class com.intel.analytics.bigdl.models.vgg.Train dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar --core 3 --node 8 --env spark -f ../cifar-10-batches-bin -b 24

the error is ：
java.lang.IllegalArgumentException: requirement failed: Detect multi-task run on one Executor/Container. Please disable singleton check or repartition data

when i set the cores to 2 and node 3 ,there will be good; but my cluster have 17 nodes ,how can i use them fullly? thks

**Comment by jason-dai** [comment]
You may refer to the discussions in our user group (https://groups.google.com/d/msg/bigdl-user-group/LNd3NNPSJv0/Oz-d3p1jBQAJ) for some workarounds; we are currently working on a fix to remove this constraint.
