### ISSUE TITLE
Architecture Diagram for BigDL

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#501]
Is there an architectural diagram for the full stack, showing all the SW omponents, VGG/Lenet etc and the outputs (what is being attempted).

A pictorial or a tex document form would be fine too..

Thanks

**Comment by jason-dai** [comment]
For some details on BigDL, you may refer to an article from O'Reilly (https://www.oreilly.com/ideas/deep-learning-for-apache-spark), and our talks in Spark Summit East in February 2016 (https://spark-summit.org/east-2017/events/bigdl-a-distributed-deep-learning-library-on-spark/ and https://spark-summit.org/east-2017/events/building-deep-learning-powered-big-data/).

**Comment by jason-dai** [comment]
Closing this issue; if there are further questions, please send them to BigDL user group (https://groups.google.com/forum/#!forum/bigdl-user-group).
