### ISSUE TITLE
json4s jars version is different in bigdl-2.1.0-SNAPSHOT and spark-3.1.2 

### ISSUE THREAD

**Issue by PatrickkZ** [intel-analytics/BigDL#5153]
The json4s jars in bigdl-2.1.0-SNAPSHOT/jars are

- json4s-ast_2.12-3.5.3.jar
- json4s-core_2.12-3.5.3.jar
- json4s-jackson_2.12-3.5.3.jar
- json4s-scalap_2.12-3.5.3.jar

in spark-3.1.2/jars are
- json4s-ast_2.12-3.7.0-M5.jar
- json4s-core_2.12-3.7.0-M5.jar
- json4s-jackson_2.12-3.7.0-M5.jar
- json4s-scalap_2.12-3.7.0-M5.jar

the different version may cause NoSuchMethodError

**Comment by glorysdj** [comment]
this is imported by bigdl-serving

[INFO] com.intel.analytics.bigdl:bigdl-assembly-spark_3.1.2:pom:2.1.0-SNAPSHOT
[INFO] \- com.intel.analytics.bigdl:bigdl-serving-spark_3.1.2:jar:2.1.0-SNAPSHOT:compile
[INFO]    \- org.json4s:json4s-jackson_2.12:jar:3.5.3:compile

we should fix this

**Comment by glorysdj** [comment]
https://github.com/intel-analytics/BigDL/blob/main/scala/serving/pom.xml#L44

**Comment by glorysdj** [comment]
@PatrickkZ  please fix this
