### ISSUE TITLE
Orca: Training process is stuck for a long time then executors connect timed out

### ISSUE THREAD

**Issue by lalalapotter** [intel-analytics/BigDL#5192]
**Describe the bug**
The training process stuck and executors show connect timed out when I run [example](https://github.com/intel-analytics/BigDL/tree/main/python/orca/example/learn/pytorch/fashion_mnist) on yarn cluster.

```
[E socket.cpp:793] [c10d] The client socket has timed out after 1800s while trying to connect to (172.16.0.152, 34771).
Traceback (most recent call last):
  File "fashion_mnist.py", line 207, in <module>
2022-07-25 15:59:11,173 WARNING worker.py:1245 -- (ip=172.16.0.107) The agent on node Almaren-Node-107 failed to be restarted 5 times. There are 3 possible problems if you see this error.
  1. The dashboard might not display correct information on this node.
  2. Metrics on this node won't be reported.
  3. runtime_env APIs won't work.
Check out the `dashboard_agent.log` to see the detailed failure messages.
    main()
  File "fashion_mnist.py", line 190, in main
    backend=args.backend)
  File "/home/kai/anaconda3/envs/orca-zcg/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/estimator.py", line 95, in from_torch
    log_level=log_level)
  File "/home/kai/anaconda3/envs/orca-zcg/lib/python3.7/site-packages/bigdl/orca/learn/pytorch/pytorch_ray_estimator.py", line 173, in __init__
    dist.constants.default_pg_timeout)
TimeoutError: The client socket has timed out after 1800s while trying to connect to (172.16.0.152, 34771).
```

**To reproduce**

- Environment
  - bigdl-orca[ray]>=2.1.0b20220707
- Scripts

```
export HADOOP_CONF_DIR=the directory of the hadoop and yarn configurations

python fashion_mnist.py --cluster_mode yarn --backend ray
```

**Comment by lalalapotter** [comment]
@sgwhat Maybe you can refer to this PR #4858

**Comment by yushan111** [comment]
@sgwhat 
I have also reproduced the issue. Could you try testing on yarn-client mode again?

**Comment by sgwhat** [comment]
> 

Sure.

**Comment by sgwhat** [comment]
> @sgwhat I have also reproduced the issue. Could you try testing on yarn-client mode again?

Sure.

**Comment by yushan111** [comment]
https://github.com/intel-analytics/BigDL/blob/06ea403518ce7cd62337f2a3e980e22b421e09de/python/orca/src/bigdl/orca/learn/pytorch/pytorch_ray_estimator.py#L170-L173

It seems that you use the ip and port of the **head** node as the **driver** ip and port, where head node is one of the worker node.

**Comment by sgwhat** [comment]
> https://github.com/intel-analytics/BigDL/blob/06ea403518ce7cd62337f2a3e980e22b421e09de/python/orca/src/bigdl/orca/learn/pytorch/pytorch_ray_estimator.py#L170-L173
> 
> It seems that you use the ip and port of the **head** node as the **driver** ip and port, where head node is one of the worker node.

That should be an error caused by `ray._private.services.get_node_ip_address()`, it get `redis_address` but not `node_ip_address`, I am looking into if that's relevant with the version of ray and find other APIs to solve it.
