### ISSUE TITLE
yarn-cluster: Cannot load libpython3.7.so

### ISSUE THREAD

**Issue by bestfleer** [intel-analytics/BigDL#5205]
I use the  following code to init a spark:
 init_orca_context(cluster_mode="yarn-cluster", num_nodes=2, penv_archive=args.archive_path, hadoop_user_name=args.hadoop_user_name)
but got error:
Exception message: ERROR: ld.so: object 'python_env/lib/libpython3.7m.so' from LD_PRELOAD cannot be preloaded: ignored.
I find that code will set preload_so = executor_python_env + "/lib/libpython" + py_version + "m.so" in bigdl/dllib/utils/spark.py at line 190. However, there is no file named "libpython3.7m.so" in python_env/lib/     
My python_env is pack by conda with python=3.7. Can you help me figure out how to fix this bug. Thanks for your help

**Comment by bestfleer** [comment]
There has two similar file in python_env/lib: libpython3.7m.a      libpython3.7m.dylib

**Comment by jason-dai** [comment]
@sgwhat please take a look

**Comment by sgwhat** [comment]
Hi, sorry for the late reply, I have tried to reproduce your problem, but I didn't meet it. I think that's caused by the way you prepare environment, maybe you could follow the steps below (recommended by BigDL team) to prepare the environment and re-run your programs.

## Prepare Environment
### 1. Install Conda
```
wget -P /tmp https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh

# Execute the script to install conda
bash /tmp/Anaconda3-2020.02-Linux-x86_64.sh

# Please type this command in your terminal to activate Conda environment
source ~/.bashrc
```

### 2. Create Conda Environment
```bash
conda create -n env python=3.7 
conda activate env
```

### 3. Use Conda to Install BigDL and Other Python Libraries (if needed)
```bash
# the latest nightly build
pip install --pre --upgrade bigdl
```

### 4. Pack the Activate Conda Environment to an Archive
Please note you need to executor the command below in your activate Conda environment.
```bash
conda pack -o environment.tar.gz
```

**Comment by bestfleer** [comment]
> Hi, sorry for the late reply, I have tried to reproduce your problem, but I didn't meet it. I think that's caused by the way you prepare environment, maybe you could follow the steps below (recommended by BigDL team) to prepare the environment and re-run your programs.
> 
> ## Prepare Environment
> ### 1. Install Conda
> ```
> wget -P /tmp https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
> 
> # Execute the script to install conda
> bash /tmp/Anaconda3-2020.02-Linux-x86_64.sh
> 
> # Please type this command in your terminal to activate Conda environment
> source ~/.bashrc
> ```
> 
> ### 2. Create Conda Environment
> ```shell
> conda create -n env python=3.7 
> conda activate env
> ```
> 
> ### 3. Use Conda to Install BigDL and Other Python Libraries (if needed)
> ```shell
> # the latest nightly build
> pip install --pre --upgrade bigdl
> ```
> 
> ### 4. Pack the Activate Conda Environment to an Archive
> Please note you need to executor the command below in your activate Conda environment.
> 
> ```shell
> conda pack -o environment.tar.gz
> ```
> 
> By the way, could you please provide the `spark-submit` script (which would be shown when you init orca context), it could help a lot to solve your problem.


My spark-submit args:
spark-submit --master yarn --deploy-mode cluster --archives hdfs://hzxs-bi-hadoop-ds/user/liwx/bigdl.tar.gz#python_env --driver-cores 4 --driver-memory 2g --num-executors 2 --executor-cores 2 --executor-memory 2g --jars /tmp/bigdl/lib/python3.7/site-packages/bigdl/share/orca/lib/bigdl-orca-spark_3.1.2-2.0.0-jar-with-dependencies.jar,/tmp/bigdl/lib/python3.7/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-2.0.0-jar-with-dependencies.jar,/tmp/bigdl/lib/python3.7/site-packages/bigdl/share/friesian/lib/bigdl-friesian-spark_3.1.2-2.0.0-jar-with-dependencies.jar  --conf spark.driver.cores=4 --conf spark.driver.memory=2g --conf spark.executor.instances=2 --conf spark.executor.cores=2 --conf spark.executor.memory=2g --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=python_env/bin/python --conf spark.yarn.appMasterEnv.OnAppMaster=True --conf spark.yarn.appMasterEnv.PYTHONHOME=python_env --conf spark.executorEnv.PYSPARK_PYTHON=python_env/bin/python --conf spark.scheduler.minRegisteredResourcesRatio=1.0 --conf spark.executorEnv.PYTHONHOME=python_env --conf spark.executor.extraLibraryPath=python_env/lib:python_env/lib/python3.7/lib-dynload --conf spark.executorEnv.LD_PRELOAD=python_env/lib/libpython3.7m.so --conf spark.yarn.appMasterEnv.LD_PRELOAD=python_env/lib/libpython3.7m.so --conf spark.executor.extraClassPath=python_env/lib/python3.7/site-packages//bigdl/share/orca/lib/bigdl-orca-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/friesian/lib/bigdl-friesian-spark_3.1.2-2.0.0-jar-with-dependencies.jar --conf spark.driver.extraClassPath=python_env/lib/python3.7/site-packages//bigdl/share/orca/lib/bigdl-orca-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/friesian/lib/bigdl-friesian-spark_3.1.2-2.0.0-jar-with-dependencies.jar bigdl_demo.py --raw_data hdfs://hzxs-bi-hadoop-ds/user/liwx/0816_lamer_sample.csv --archive_path hdfs://hzxs-bi-hadoop-ds/user/liwx/bigdl.tar.gz --inference_data hdfs://hzxs-bi-hadoop-ds/user/liwx/0816_lamer_sample.csv --model_save model.pth --hadoop_user_name getui_gdf

**Comment by sgwhat** [comment]
> > Hi, sorry for the late reply, I have tried to reproduce your problem, but I didn't meet it. I think that's caused by the way you prepare environment, maybe you could follow the steps below (recommended by BigDL team) to prepare the environment and re-run your programs.
> > ## Prepare Environment
> > ### 1. Install Conda
> > ```
> > wget -P /tmp https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
> > 
> > # Execute the script to install conda
> > bash /tmp/Anaconda3-2020.02-Linux-x86_64.sh
> > 
> > # Please type this command in your terminal to activate Conda environment
> > source ~/.bashrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 2. Create Conda Environment
> > ```shell
> > conda create -n env python=3.7 
> > conda activate env
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 3. Use Conda to Install BigDL and Other Python Libraries (if needed)
> > ```shell
> > # the latest nightly build
> > pip install --pre --upgrade bigdl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 4. Pack the Activate Conda Environment to an Archive
> > Please note you need to executor the command below in your activate Conda environment.
> > ```shell
> > conda pack -o environment.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > By the way, could you please provide the `spark-submit` script (which would be shown when you init orca context), it could help a lot to solve your problem.
> 
> My spark-submit args: spark-submit --master yarn --deploy-mode cluster --archives hdfs://hzxs-bi-hadoop-ds/user/liwx/bigdl.tar.gz#python_env --driver-cores 4 --driver-memory 2g --num-executors 2 --executor-cores 2 --executor-memory 2g --jars /tmp/bigdl/lib/python3.7/site-packages/bigdl/share/orca/lib/bigdl-orca-spark_3.1.2-2.0.0-jar-with-dependencies.jar,/tmp/bigdl/lib/python3.7/site-packages/bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-2.0.0-jar-with-dependencies.jar,/tmp/bigdl/lib/python3.7/site-packages/bigdl/share/friesian/lib/bigdl-friesian-spark_3.1.2-2.0.0-jar-with-dependencies.jar --conf spark.driver.cores=4 --conf spark.driver.memory=2g --conf spark.executor.instances=2 --conf spark.executor.cores=2 --conf spark.executor.memory=2g --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=python_env/bin/python --conf spark.yarn.appMasterEnv.OnAppMaster=True --conf spark.yarn.appMasterEnv.PYTHONHOME=python_env --conf spark.executorEnv.PYSPARK_PYTHON=python_env/bin/python --conf spark.scheduler.minRegisteredResourcesRatio=1.0 --conf spark.executorEnv.PYTHONHOME=python_env --conf spark.executor.extraLibraryPath=python_env/lib:python_env/lib/python3.7/lib-dynload --conf spark.executorEnv.LD_PRELOAD=python_env/lib/libpython3.7m.so --conf spark.yarn.appMasterEnv.LD_PRELOAD=python_env/lib/libpython3.7m.so --conf spark.executor.extraClassPath=python_env/lib/python3.7/site-packages//bigdl/share/orca/lib/bigdl-orca-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/friesian/lib/bigdl-friesian-spark_3.1.2-2.0.0-jar-with-dependencies.jar --conf spark.driver.extraClassPath=python_env/lib/python3.7/site-packages//bigdl/share/orca/lib/bigdl-orca-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/dllib/lib/bigdl-dllib-spark_3.1.2-2.0.0-jar-with-dependencies.jar:python_env/lib/python3.7/site-packages//bigdl/share/friesian/lib/bigdl-friesian-spark_3.1.2-2.0.0-jar-with-dependencies.jar bigdl_demo.py --raw_data hdfs://hzxs-bi-hadoop-ds/user/liwx/0816_lamer_sample.csv --archive_path hdfs://hzxs-bi-hadoop-ds/user/liwx/bigdl.tar.gz --inference_data hdfs://hzxs-bi-hadoop-ds/user/liwx/0816_lamer_sample.csv --model_save model.pth --hadoop_user_name getui_gdf

Can it run successfully after you try the environment preparation steps? Since I could see `spark.executorEnv.LD_PRELOAD` and `spark.yarn.appMasterEnv.LD_PRELOAD` could be correctly set up.

**Comment by bestfleer** [comment]
This issue can be closed. The error is caused by multiple spark version in one machine. Therefore system will use spark-submit by other version first.  I set export PATH=/tmp/bigdl/bin:${PATH} and the error solved. Thanks for your help.
