### ISSUE TITLE
[ReadtheDocs] Improvements on ipynb Files Integration

### ISSUE THREAD

**Issue by Oscilloscope98** [intel-analytics/BigDL#5248]
Based on PR #5222, realize the following improvements:
- [x] Adding ipynb files through DIRECTLY LINKING to where they are, without copying them https://github.com/intel-analytics/BigDL/pull/5596
- [ ] Hiding outputs with the help of nbsphinx extension, without deleting them manually: hide input/output of code cell is currently not supported by nbsphinx
- [x] Showing the interactive plots in the web pages generated by the ipynb files (helpful resources: plotly, datapane) https://github.com/intel-analytics/BigDL/pull/5596

**Comment by TheaperDeng** [comment]
Open in Colab button is invalid（e.g. https://bigdl.readthedocs.io/en/latest/doc/Nano/Tutorials/seq_and_func.html)

**Comment by Oscilloscope98** [comment]
> Open in Colab button is invalid（e.g. https://bigdl.readthedocs.io/en/latest/doc/Nano/Tutorials/seq_and_func.html)

Have found a way to fix this in https://github.com/intel-analytics/BigDL/pull/5452

**Comment by Oscilloscope98** [comment]
> * [ ]  Hiding outputs with the help of nbsphinx extension, without deleting them manually: hide input/output of code cell is currently not supported by nbsphinx

Close this issue for now. Will create a new issue if we strongly need the feature to hide/toggle the input/output of code cells in rendered notebooks.
