### ISSUE TITLE
[Nano] Enable both ipex 1.11 and bf16 will raise AttributeError

### ISSUE THREAD

**Issue by peirain** [intel-analytics/BigDL#5288]
## Description
Run Trainer.fit with both ipex 1.11 and bf16 enabled will get the error below:

![error-message](https://user-images.githubusercontent.com/96048273/182382897-2e47b461-05b6-42ac-85a6-55483961f7b0.png)

## Environment
```
Python=3.7.13
torch=1.11.0
pytorch_lightning=1.6.4
ipex=1.11.0
bigdl-nano=2.1.0b20220801
```

**Comment by y199387** [comment]
I tried enabling both ipex and bf16, but get different error message `the input and weight need have same data type`.
Can you share the code so that i can reproduce this issue?
