### ISSUE TITLE
Understanding of compressing float32 to float16

### ISSUE THREAD

**Issue by Ytinifni-zc** [intel-analytics/BigDL#533]
https://www.youtube.com/watch?v=j0ewLYecTsY&feature=youtu.be 
This video shows that BigDL has 3 excellent features of optimizing PS structure. It's really awesome. When I read code about compressing float, it shows `toFP16` method and `fromFP16` method.
In `toFP16` method, I found that code discards the last 16 bits of float32 in using method `truncate`, and keep the first 8 bits and second 8 bits of float32. While `deCompress` method use `fromFP16` and `toFloat` methods, does the program get only first 16 bits of the float32? 
```
  private def truncate(value: Float): Int = {
    java.lang.Float.floatToRawIntBits(value) & 0xffff0000
  }

  private def toFloat(byte1: Byte, byte2: Byte): Float = {
    java.lang.Float.intBitsToFloat(byte1 << 24 | byte2 << 16 & 0x00ff0000)
  }
```

Did I misunderstand of this program?

**Comment by psyyz10** [comment]
Yes, that's how it works. Discarding last 16 bits when update parameters does not make any obvious side-effect to model convergence according to our experiments.

**Comment by Ytinifni-zc** [comment]
Thank you, may be I forgot the format of float. 
https://zh.wikipedia.org/wiki/IEEE_754
So, discarding last 16 bits doesn't produce so much impact of float, because first 16 bits contain enough message of float. Many thanks.
