### ISSUE TITLE
BigDL does not seem to use all Cores (Top Command)

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#534]
Attached is what I got as results, from putting on Client Deployment. Worker nodes has 48 cores and specified executor-memory 120GB. But when I issue the 'top' command on Linux (from where BigDL- Train is running), I find that that %CPUn utilization very little and many of them seem to be sleeping. 
Is the program really parallelized or loading the CPU enough or am I missing something? Thanks

**Comment by jaymahesh** [comment]
Attaching the file now
[ClientDep_BigDL_48Core_120GB.docx](https://github.com/intel-analytics/BigDL/files/813156/ClientDep_BigDL_48Core_120GB.docx)

**Comment by jason-dai** [comment]
Closing this issue; if there are further questions, please send them to BigDL user group (https://groups.google.com/forum/#!forum/bigdl-user-group).
