### ISSUE TITLE
Chronos: installation panel enhancement

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#5387]
1. Some UI bugs still remain.
![image](https://user-images.githubusercontent.com/35031544/184466626-37262f6d-317b-4f4b-af39-29cecc989feb.png)

2. Some word can be changed a little to make it easier to be understood
   
   1. Auto Tuning: No need -> No, Needed -> Yes
   
   2. Build -> Version
   
   3. Release -> Package

3. Change some rows to eliminate misunderstanding or confusion
   
   **Functionality**: Forecasting | Anomaly Detection | Simulation
   
   **Model**:
   
   (when Forecasting is chosen): Deep learning models | Prophet | ARIMA
   
   (when Anomaly Detection is chosen): Deep learning models | Machine learning models
   
   (when Simulation is chosen): Deep learning models
   
   **Deep learning framework** (only available when Deep learning models is selected): Pytorch(Recommended) | Tensorflow
   
   **OS, Auto Tuning, Hardware, Release, Package, Install CMD**: No changing

**Comment by AndyLuo1029** [comment]
I just opened a pull request here: [#5588](https://github.com/intel-analytics/BigDL/pull/5588).
