### ISSUE TITLE
GitAction orca-tutorial-xshards: No such file ‘pima-indians-diabetes-test.csv’.

### ISSUE THREAD

**Issue by leonardozcm** [intel-analytics/BigDL#5586]
https://github.com/intel-analytics/BigDL/runs/8087695465?check_suite_focus=true#step:9:3142

**Comment by leonardozcm** [comment]
hi @dding3 , would you mind taking a look at this?

**Comment by dding3** [comment]
> hi @dding3 , would you mind taking a look at this?

It should be already fixed by https://github.com/intel-analytics/BigDL/commit/50d6f0d7b31d0529da01bddd17c7b0694186285e ?

**Comment by leonardozcm** [comment]
> > hi @dding3 , would you mind taking a look at this?
> 
> It should be already fixed by [50d6f0d](https://github.com/intel-analytics/BigDL/commit/50d6f0d7b31d0529da01bddd17c7b0694186285e) ?

https://github.com/intel-analytics/BigDL/runs/8105759047?check_suite_focus=true
Yes it is, thanks to ding ding
