### ISSUE TITLE
Nano: trace to openvino inference engine need a thread(core) num control option

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#5608]
For onnxruntime, users could control how many cores their accelerated model could use, while we don't have such option for openvino right now.

**Comment by rnwang04** [comment]
Currently, no matter what the number of intra_op_num_threads and inter_op_num_threads is, only one core is used. 
And more threads, inference is slower.

**Comment by jason-dai** [comment]
> Currently, no matter what the number of intra_op_num_threads and inter_op_num_threads is, only one core is used. And more threads, inference is slower.
> 
> ![image](https://user-images.githubusercontent.com/105281011/187829459-91776040-e5e7-4d2f-b86d-71147fd31f7d.png) ![image](https://user-images.githubusercontent.com/105281011/187829470-1a9aa5b7-339e-4a29-8efd-9414d4bac584.png)

@qiyuangong Is this behavior expected?

**Comment by TheaperDeng** [comment]
> > Currently, no matter what the number of intra_op_num_threads and inter_op_num_threads is, only one core is used. And more threads, inference is slower.
> > ![image](https://user-images.githubusercontent.com/105281011/187829459-91776040-e5e7-4d2f-b86d-71147fd31f7d.png) ![image](https://user-images.githubusercontent.com/105281011/187829470-1a9aa5b7-339e-4a29-8efd-9414d4bac584.png)
> 
> @qiyuangong Is this behavior expected?

After huge amount of experiment and feedback from team members and customers I found

**ONNXRuntime's core num control is completely fragile and useless, it may not respect user's input randomly**

For fp32:
- some hardware (e.g. i7-9700), the control is stable and follows the setting
- some hardware (e.g. cpx), the control is useless, and the core usage might change randomly even on same SKU.

For int8
- some hardware (e.g. i7-9700), no matter how many cores you set, it will only use 1 core
- some hardware (e.g. icx), it will use 16 cores if you set < 16 cores, and respect your input if you set > 16 cores

We are contacting onnxruntime support team (MS and Intel) to find some solution.

**Comment by rnwang04** [comment]
After `unset KMP_AFFINITY`, onnxruntimie works fine.
