### ISSUE TITLE
Chronos:  Syntax error in Evaluator API documentation

### ISSUE THREAD

**Issue by liangs6212** [intel-analytics/BigDL#5638]
Related Link: https://bigdl.readthedocs.io/en/latest/doc/PythonAPI/Chronos/evaluator.html#
`.. math`: cannot be rendered.

**Comment by TheaperDeng** [comment]
there might be some syntax issue (e.g. white space, tab...), https://bigdl.readthedocs.io/en/latest/doc/PythonAPI/Orca/automl.html#orca-automl-metrics this can be a good example for reference.
