### ISSUE TITLE
Document: format display missing when rendering notebooks after execution

### ISSUE THREAD

**Issue by plusbang** [intel-analytics/BigDL#5734]
In Chronos How-to Guides, color of comments in code boxes is not correct while in colab is okay.
example: https://bigdl.readthedocs.io/en/latest/doc/Chronos/Howto/how_to_create_forecaster.html#Prepare-Environments

**Comment by Oscilloscope98** [comment]
This format missing problem not only occurs in Chronos how-to guides, but also occur in several notebooks rendered in readthedocs directly.

All the problematic notebooks are after execution, which will additionally save pygment lexer info into them. such as:
```json
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
```
This will cause Pygments lexer to use `ipython3` to highlight code blocks. As we do not have `ipython` installed for our readthedocs project, problems occur.

Based on [this](https://github.com/spatialaudio/nbsphinx/issues/24#issuecomment-271611531), we could add `ipython` dependency to our readthedocs project to solve this problem.
