### ISSUE TITLE
Nano: openvino related fundamental examples

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#5773]
- [ ] need fundamental examples to `python/nano/tutorial/inference/openvino` and show how to directly load an openvino model and use it as `model(x)`. 2 examples for `async_predict`, `model(x)` respectively.

- [ ] need save/load examples to `/python/nano/tutorial/notebook/inference/pytorch` and show how to save(export)/load an optimized model.

**Comment by hjzin** [comment]
I think we may also need a fundamental example to `python/nano/tutorial/inference/pytorch` to show the usage of `async_predict` on optimized pytorch model.

**Comment by TheaperDeng** [comment]
> I think we may also need a fundamental example to `python/nano/tutorial/inference/pytorch` to show the usage of `async_predict` on optimized pytorch model.

Yeah I think we do, but maybe we can start a thread to first add the save(export) fundamental example first.

**Comment by hjzin** [comment]
> > I think we may also need a fundamental example to `python/nano/tutorial/inference/pytorch` to show the usage of `async_predict` on optimized pytorch model.
> 
> Yeah I think we do, but maybe we can start a thread to first add the save(export) fundamental example first.

OK, I wil work on it.
