### ISSUE TITLE
Reduce PPML Occlum image size (9.3GB)

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/BigDL#5807]
Due to large occlum base image (6.22GB), PPML occlum image is close 9.3GB.  It's too large for external developer to pull from dockerhub. Need to reduce size.

- [x] [Reduce occlum image size](https://github.com/occlum/occlum/issues/1007)
- [x] Reduce PPML content
    - [x] Remove unnecessary package
    - [x] Remove unnecessary layer
    - [x] Remove unnecessary source

**Comment by guzongmin** [comment]
In the PPML docker image, only a tiny subset of Occlum binaries is used:
+ Occlum runtime 
+ copy_bom
+ SEFS CLI tool
+ Occlum Glibc/musl libc

All of these things totally should be smaller than 500MB.

**Comment by qiyuangong** [comment]
> In the PPML docker image, only a tiny subset of Occlum binaries is used:
> 
> * Occlum runtime
> * copy_bom
> * SEFS CLI tool
> * Occlum Glibc/musl libc
> 
> All of these things totally should be smaller than 500MB.

Yes. We plan to make a minimal basic image based on Occlum's image. We will try occlum installer first.

**Comment by qiyuangong** [comment]
Issue resolved by #5989
