### ISSUE TITLE
Trigger the data transorm and caching logic to optimize() function if possible. 

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#581]
1.	Optimizer settings is a little bit slow
When running lenet demo https://github.com/shane-huang/BigDL/blob/notebookdemo/dl/src/main/python/models/lenet/lenet5.ipynb
Line (8) needs 1 mins+ to finish. 
 When people run demo they might notice this is unexpectedly longer, is there any explanation about what part of initializations take so long?

It’s due to Optimizer would transform and cached all the batches in memory while initializing. 

The logic of Scala API need to move that part to optimize() function if possible.

**Comment by zhichao-li** [comment]
cc @yiheng @jason-dai @shane-huang

**Comment by dding3** [comment]
Duplicate with issue 621
