### ISSUE TITLE
Orca tf2 tf_runner import copy conflict

### ISSUE THREAD

**Issue by cyita** [intel-analytics/BigDL#5885]
Need to fix in both main branch and branch-2.1

PR [#5731](https://github.com/intel-analytics/BigDL/pull/5731) `from copy import copy` conflict with `import copy`

http://10.112.231.51:18888/job/BigDL-PRVN-tf2-rayonspark/365/console

**Comment by leonardozcm** [comment]
branch 2.1: https://github.com/intel-analytics/BigDL/pull/5886
main: https://github.com/intel-analytics/BigDL/pull/5887
