### ISSUE TITLE
support resume training in python

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#589]
Currently optimizer does not support resume training, because state cannot be initialized from snapshot file. Need to support this.

**Comment by zhichao-li** [comment]
we should wrap the bellowing code and provide a resuming api:
val m = model.load
val o = optmMethod.load
new optimizer(m, o)
.optimize()

**Comment by zhichao-li** [comment]
@zhangxiaoli73 should we close this?
