### ISSUE TITLE
Nano: InferenceOptimizer outputs a `lack dependency` when `openvino-dev` is installed already

### ISSUE THREAD

**Issue by y199387** [intel-analytics/BigDL#5902]
## Optimization Results
![image](https://user-images.githubusercontent.com/49382651/191643092-35f5c553-89d0-49c5-b088-dabfe2f335a4.png)
## Environments
![image](https://user-images.githubusercontent.com/49382651/191643192-e1ec86bf-b93d-4df4-bdd5-7af3edf20b0a.png)
## Test script
```python
from bigdl.nano.pytorch.inference.optimizer import _openvino_checker
print(_openvino_checker())
from importlib.util import find_spec
print(find_spec("openvino-spec"))
```
Output
![image](https://user-images.githubusercontent.com/49382651/191644150-73bc9b61-deb2-487f-a5de-829036c2cd42.png)

**Comment by rnwang04** [comment]
I and yishuo meet this problem before. https://github.com/intel-analytics/BigDL/pull/5891 has modify _openvino_checker() from `openvino-dev` to `openvino`.

**Comment by y199387** [comment]
The latest bigdl-nano works just fine.
close the issue
