### ISSUE TITLE
Nano : Performance test of ONNX Simplifier on some models and design for integrating with Nano

### ISSUE THREAD

**Issue by rnwang04** [intel-analytics/BigDL#5975]
# Background

[ONNX Simplifier](https://github.com/daquexian/onnx-simplifier) is presented to simplify the ONNX model. It infers the whole computation graph and then replaces the redundant operators with their constant outputs (a.k.a. constant folding).
Some projects like YOLOv5 have adpoted ONNX Simplifier as a supplement to ONNX Runtime.

We are considering integrating ONNX Simplifier into Nano's InferenceOptimizer. First and foremost , have to do some performance test of ONNX Simplifier.

# Performance
| -     | ResNet50  |  TCNForecaster  |  LSTMForecaster  |  efficientnet_b7 | swin |
| ----------- | ----------- |  ----------- |  ----------- |  ----------- |  ----------- | 
| onnx latency  |  9.2ms   |   0.42ms   |  0.215ms |  121.6ms |  111.2ms |  95.8ms | 
|  onnxsim latency |  9.2ms   |     **0.35ms**   | **0.117ms** |  **101.3ms** |   95.5ms |
| onnx size |  97.4M  |   151.7K  |  2.5K |  252.4M |  339M |
| onnxsim size |   97.4M   |    149.9k  | 1.4K | 252.4M |  339M |

#  Conclusion and Design
ONNX Simplifier does improve some models,  especially for LSTM-style model.
What's more, it's easy to integrate ONNX Simplifier.  We can make it as a default choice.

Only problem is this will introduce additional dependency `onnxsim` and modify corresponding workflow. `onnxsim` depends on `onnx` and `onnxruntime`.
So it should be considered if we should support onnxsim in openvino as it will increase three additional dependencies : `onnx`, `onnxruntime`, `onnxsim`
For onnxruntime, it will increase only one additional dependency `onnxsim`.

## Design 1
Apply onnxsim on both onnxruntime and openvino compulsively
```
from bigdl.nano.deps.onnxsim.onnxsim_api import onnx_simplify
onnx_simplify(onnx_path)
```
will be put at the end of https://github.com/intel-analytics/BigDL/blob/13a08a1eb103c9fe21224c646b1920155cc16494/python/nano/src/bigdl/nano/utils/inference/pytorch/model_utils.py#L98

## Design 2
Only apply onnxsim on onnxruntime compulsively
```
from bigdl.nano.deps.onnxsim.onnxsim_api import onnx_simplify
onnx_simplify(onnx_path)
```
will be put at the end of https://github.com/intel-analytics/BigDL/blob/13a08a1eb103c9fe21224c646b1920155cc16494/python/nano/src/bigdl/nano/deps/onnxruntime/pytorch/pytorch_onnxruntime_model.py#L53

## Design 3
Only apply onnxsim on onnxruntime, add a flag to decide whether use onnxsim, default value is True

## Design 4
Apply onnxsim on onnxruntime and openvino, add a flag to decide whether use onnxsim.
Default value for onnxruntime is True, and default value for openvino is False.

**I prefer Design 4**. By default, users only need to install openvino-dev. When they want to enable onnxsim, they can install additional dependencies themselves.

# Implementation
Design 3 is in progress : #5977

**Comment by rnwang04** [comment]
@jason-dai  any concern or comments about this? Do you think we should support onnxsim for openvino?

**Comment by jason-dai** [comment]
> @jason-dai any concern or comments about this? Do you think we should support onnxsim for openvino?

Can we simply add onnxsim to Nano's dependency? @TheaperDeng @yangw1234

**Comment by TheaperDeng** [comment]
> > @jason-dai any concern or comments about this? Do you think we should support onnxsim for openvino?
> 
> Can we simply add onnxsim to Nano's dependency? @TheaperDeng @yangw1234

neither onnx or onnxruntime is now in nano's dependency, we may add more installation options to nano?
[onnx]: onnx, onnxruntime, onnxsim, ONNX Runtime Extensions
[openvino]: openvino-dev
...
