### ISSUE TITLE
enable IPEX even when avx512 disabled 

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#6010]
`WARNING: avx512 disabled, fall back to non-ipex mode.`

We have disabled IPEX  when AVX512 is disabled because earlier version of IPEX has bugs.  Newer IPEX version has fixed this issue https://github.com/intel/intel-extension-for-pytorch/releases/tag/v1.12.100.  Maybe we need to upgrade IPEX and allow using IPEX even when avx512 is disabled.

**Comment by jason-dai** [comment]
Which version are you using? We already supported latest ipex.

**Comment by jason-dai** [comment]
then it's already the latest ipex version? is this expected @yangw1234 ?

**Comment by yangw1234** [comment]
@jason-dai we will disable avx-512 if we detect the torch version is less than 1.11.

@aixideng can you provide code to reproduce?

**Comment by yangw1234** [comment]
This is actually a wrong message, it will be printed as long as there are no avx-512. 

Opened a pr to remove it. https://github.com/intel-analytics/BigDL/pull/6038

**Comment by yangw1234** [comment]
> This is actually a wrong message, it will be printed as long as there are no avx-512.
> 
> Opened a pr to remove it. #6038

merged
