### ISSUE TITLE
[PPML] [Scala] jar package failure due to object/member missing

### ISSUE THREAD

**Issue by Uxito-Ada** [intel-analytics/BigDL#6037]
Always encounter errors like below when using maven to package ppml scala jars:

```
/BigDL/scala/ppml# mvn package -Pspark_3.x -DskipTests

[ERROR] /BigDL/scala/ppml/src/main/scala/com/intel/analytics/bigdl/ppml/fl/fgboost/FGBoostModel.scala:27: object ObjectSizeCalculator is not a member of package jdk.nashorn.internal.ir.debug
[ERROR] import jdk.nashorn.internal.ir.debug.ObjectSizeCalculator
[ERROR]        ^
[ERROR] /BigDL/scala/ppml/src/main/scala/com/intel/analytics/bigdl/ppml/fl/fgboost/FGBoostModel.scala:187: not found: value ObjectSizeCalculator
[ERROR]     val perMsgSize = ObjectSizeCalculator.getObjectSize(boostEvals.head)
```

In order to package jars successfully, I have to remove codes of ppml/fl now. It seems to be possibly related to the JDK version.

My environment:
```
$ java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

@Litchilitchy

**Comment by glorysdj** [comment]
ObjectSizeCalculator no longer exists in jdk11, please refer to https://github.com/openjdk/jdk11/tree/37115c8ea4aff13a8148ee2b8832b20888a5d880/src/jdk.scripting.nashorn/share/classes/jdk/nashorn/internal/ir/debug
You may need to use jdk 8.
@Litchilitchy 
objectsizecalculator only supported on hotspot vm, to support openjdk, please try other methods to get the size.

**Comment by Uxito-Ada** [comment]
Fixed and closed now.
