### ISSUE TITLE
Use other format to save Model instead of Java serialization

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#608]
Use other format to save Model instead of Java serialization, otherwise the serialVersionUID  would restrict the model loading. 
i.e If there's new function added to the DenseTensor:

: java.io.InvalidClassException: com.intel.analytics.bigdl.tensor.DenseTensor; local class incompatible: stream classdesc serialVersionUID = -5574015350443049520, local class serialVersionUID = 5876322619614900645
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1630)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)

**Comment by zhichao-li** [comment]
Protobuf might be an option just like Caffe or Tensorflow. cc @yiheng @jason-dai

**Comment by yiheng** [comment]
I think this problem is not related with Java serialization. If you change the layer, e.g. add a new field without a default value. You can't load old model even it is saved as protobuf.

The advantage of protobuf is its size is smaller. But it's not critical in model persistent scenario.

**Comment by zhichao-li** [comment]
For this specific issue, it's due to there's no fix serialVersionUID for ```DenseTensor```  which would make it vulnerable from classes changes.
We need to check and ensure the related classes appended with a fix serialVersionUID if still stick with the Java serialization mode. 
cc @zhangxiaoli73

**Comment by SeaOfOcean** [comment]
If use different scala version, it will also throw serialVersionUID error

**Comment by srowen** [comment]
I would _avoid_ adding `serialVersionUID` to "fix" class incompatibility. It creates a potentially worse problem, that you update the class and don't change the ID and then are willing to load data that could be written by a different class version. It could actually succeed while having invalid data. It doesn't actually resolve the problem of loading different versions of a serialization automatically.

**Comment by wzhongyuan** [comment]
Protobuf provides very good backward compatibility, we shall make newly added field "optional" to avoid loading failure of old version-ed layer with new layer definition.

@jason-dai  @zhichao-li @yiheng  I am trying to write some prototype now and will discuss further with you afterward with the details

**Comment by wzhongyuan** [comment]
@zhichao-li   can this issue be closed ?
