### ISSUE TITLE
Nano: bf16 seems don't work on cpx

### ISSUE THREAD

**Issue by rnwang04** [intel-analytics/BigDL#6087]
During lots of demo writing, we find bf16 always fail to forward on cpx.

**Comment by TheaperDeng** [comment]
Could be a missing isa indicator (`avx512_bf16`) here:
https://github.com/intel-analytics/BigDL/blob/c2d6ec8e40bd0d5506b6be09acaf0f6289e221c5/python/nano/src/bigdl/nano/pytorch/amp/bfloat16.py#L92-L96

@yaxinchen666 is working on this
