### ISSUE TITLE
Nano: Can torchNano support computing resource control like Trainer do

### ISSUE THREAD

**Issue by Siritao** [intel-analytics/BigDL#6103]
For __bigdl.nano.pytorch.Trainer__, there exists a parameter that can specify the CPUs that will be used by each process, namely, _cpu_for_each_process_.
I doubt whether __torchNano__ can also support this.

**Comment by yangw1234** [comment]
Hi @MeouSker77 can you help look at this issue?

**Comment by MeouSker77** [comment]
> Hi @MeouSker77 can you help look at this issue?

sure

**Comment by MeouSker77** [comment]
fix it in #6108

**Comment by Siritao** [comment]
> fix it in #6108

thanks very much
