### ISSUE TITLE
Chronos: some chronos examples' installation guide should be updated

### ISSUE THREAD

**Issue by TheaperDeng** [intel-analytics/BigDL#6118]
We could make them consistent and linked to some pages like: https://testbigdldocshane.readthedocs.io/en/rddocs-toc/doc/Chronos/Overview/install.html . So that we don't need to update the installation guide every time.

@Oscilloscope98 If we will have new theme soon, I will update these readme after new theme is online.

https://github.com/intel-analytics/BigDL/tree/main/python/chronos/example/

**Comment by Oscilloscope98** [comment]
@TheaperDeng Yes, we could do it after the theme is online. The theme is planned to be updated very soon :D

**Comment by TheaperDeng** [comment]
> @TheaperDeng The new theme has been applied.

Great to know! I will start to work on this.
