### ISSUE TITLE
Nano: `InferenceOptimizer.optimize` does not support `torchmetrics.functional` API as input metrics

### ISSUE THREAD

**Issue by liangs6212** [intel-analytics/BigDL#6170]
## Details:
The torchmetrics interface consists of two types, class and functional.
```python
from torchmetrics import MeanSquaredError
mean_squared_error = MeanSquaredError()

from torchmetrics.functional import mean_squared_error # not support function API
```
Currently we only support the first type, maybe we can add support for the function API.

**Comment by rnwang04** [comment]
Support this by #6196. You can validate this with tomorrow's nb vesion.

**Comment by liangs6212** [comment]
> Support this by #6196. You can validate this with tomorrow's nb vesion.

Ok，thanks.
