### ISSUE TITLE
[Log] log4Error cannot completely replace throw, may cause Scala compilation error

### ISSUE THREAD

**Issue by hoshibara** [intel-analytics/BigDL#6237]
## Description
Log4error is not a complete replacement for throw. Using it in an if or switch may result in a type mismatch error.

## Reproduction

```scala
import com.intel.analytics.bigdl.dllib.utils.Log4Error
import scala.util.Random
class ReproductionSepc extends ZooSpecHelper {
  def addDouble(item: Double): Unit = {
    logger.info(item)
  }
  "Reproduction" should "work properly" in {
    val a = {
      if (Random.nextFloat() > 0.5) {
        0.4
      } else {
        Log4Error.invalidInputError(false, "a", "a")
        //must add: throw new Exception("a") or a double number
      }
    }
    addDouble(a)
    //type mismatch;
    // found   : AnyVal
    // required: Double
  }
}
```

**Comment by dding3** [comment]
In current implementation, Log4Error.invalidInputError doesn't have returns as it's used to check if condition is true (if false throw exception, and if true simple pass.) seems like there is no type that are able to cover above 2 cases?

 For the mentioned type mismatch error, one fix can be add a value after use Log4Error.invalidInputError to make the compile pass. eg.
`    val a = {
      if (Random.nextFloat() > 0.5) {
        0.4
      } else {
        Log4Error.invalidInputError(false, "a", "a")
        0.0
      }
    }`

One better way may be pass the check logic to Log4Error.invalidInputError, eg.
`   
Log4Error.invalidInputError(Random.nextFloat() > 0.5, "a", "a")
val a = 0.4
`
