### ISSUE TITLE
DLlib: script `start-worker-with-numactl.sh` does not start workers correctly

### ISSUE THREAD

**Issue by CharleneHu94** [intel-analytics/BigDL#6285]
If init orca context with standalone mode with `enable_numa_binding=true`,  the script `<conda-env>/lib/python3.x/site-packages/bigdl/share/dllib/bin/standalone/sbin/start-worker-with-numactl.sh` cannot generate correct core ranges for each worker and fails when `num_executors`  is larger than socket numer. 

Modify [line 106](https://github.com/intel-analytics/BigDL/blob/main/scripts/standalone/sbin/start-worker-with-numactl.sh#L106) to below should fix this issue:
```
core_start=$(( i * _PER_WORKER_LENGTH ))
```

**Comment by hkvision** [comment]
@yangw1234 @cyita Could you take a look at this issue?

**Comment by helenlly** [comment]
@CharleneHu94 

the fix is merged. pls let us know if more questions or close the issue, thanks!

**Comment by CharleneHu94** [comment]
> @CharleneHu94
> 
> the fix is merged. pls let us know if more questions or close the issue, thanks!

Thanks for the fix, the issue can be closed :)

**Comment by helenlly** [comment]
synced with yabai about the fixing, and the issue can be closed now.
