### ISSUE TITLE
Chronos: evaluate results are different when dataloader is shuffled or not

### ISSUE THREAD

**Issue by plusbang** [intel-analytics/BigDL#6308]
When generate two dataloaders with `shuffle=True` and `shuffle=False`, the evaluate results are different:
```python
test_loader_1 = tsdata_test.to_torch_data_loader(batch_size=1, lookback=6, horizon=2, shuffle=False)
test_loader_2 = tsdata_test.to_torch_data_loader(batch_size=1, lookback=6, horizon=2)
```
![image](https://user-images.githubusercontent.com/108676127/197992440-c89039ad-28be-46a7-8225-772c47038928.png)

**Comment by liangs6212** [comment]
This result seems to be as expected? What if both datasets have shuffle=False set?
