### ISSUE TITLE
support L1 regularization

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#634]
L2 is supported thru weight decay.  L1 is not supported right now.

**Comment by shane-huang** [comment]
seems Zhang, Yao's work of #648 covers this issue.

**Comment by yangw1234** [comment]
Zhang, Yao's work is to support L1/L2 regularizer **per layer**, but to do **global** regularization we still have to (or at least is eazier to) use the "weightDecay" in SGD/Adagrad, (which does not support L1), right? @shane-huang @psyyz10

**Comment by yiheng** [comment]
I think it's not conflict.
