### ISSUE TITLE
InferenceOptimizer thread_num cannot control openvino threads

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#6392]
The InferenceOptimizer is configured to use only one core, but openvino will try to use all the cores. 

![image](https://user-images.githubusercontent.com/10561966/199351300-54fae90d-cdc0-4eee-95c0-71e000c11caa.png)

**Comment by yangw1234** [comment]
@rnwang04 could you help take a look at this issue?

**Comment by rnwang04** [comment]
> @rnwang04 could you help take a look at this issue?

Sure. I have tested this locally, and I don't meet this problem.
![image](https://user-images.githubusercontent.com/105281011/199377542-32316033-e1ad-4bfc-b9ff-c43900e4d07b.png)
There are two possible causes:
1. Do you set some environment variables manually ?  like KMP_AFFINITY (https://github.com/intel-analytics/BigDL/issues/6371)
2. The whole pipeline for an acceleration model includes three parts : Model Conversion， Latency calculation and Accuracy Calculation(optional). You should observe cpu activity in the second phase, and you may set a very large value for `latency_sample_num` for convenient observation.

**Comment by rnwang04** [comment]
Thanks for raising this issue! After my further verification，only openvino_int8 has this problem. I have put forward a PR(https://github.com/intel-analytics/BigDL/pull/6400) for this problem.

**Comment by yangw1234** [comment]
fixed by #6400
