### ISSUE TITLE
Upgrade pyspark to version 3.1.3

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/BigDL#6393]
[#1503](https://github.com/intel-analytics/BigDL/security/dependabot/1503)
[ #701](https://github.com/intel-analytics/BigDL/security/dependabot/701)
.github/actions/python-requirements/requirements-ppml-python-ut-spark3.txt
python/dllib/src/setup.py

**Comment by Le-Zheng** [comment]
[#701](https://github.com/intel-analytics/BigDL/security/dependabot/701) may not be fixed, [python/dllib/src/setup.py](https://github.com/intel-analytics/BigDL/blob/-/python/dllib/src/setup.py) defines the default pyspark version we support is 2.4.6

**Comment by Le-Zheng** [comment]
[#1503](https://github.com/intel-analytics/BigDL/security/dependabot/1503) has been fixed.
