### ISSUE TITLE
some links on main page are 404 not found

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#6426]
See RayOnSpark [user guide](https://bigdl.readthedocs.io/en/latest/doc/Ray/Overview/ray.html) and [quickstart](https://bigdl.readthedocs.io/en/latest/doc/Ray/QuickStart/ray-quickstart.html) for more details. in https://github.com/intel-analytics/BigDL#orca

See Chronos [user guide](https://bigdl.readthedocs.io/en/latest/doc/Chronos/Overview/chronos.html) and [quick start](https://bigdl.readthedocs.io/en/latest/doc/Chronos/QuickStart/chronos-autotsest-quickstart.html) for more details. in https://github.com/intel-analytics/BigDL#chronos

**Comment by jason-dai** [comment]
I think we renamed the original pages @Oscilloscope98

**Comment by Oscilloscope98** [comment]
> I think we renamed the original pages @Oscilloscope98

Yes, we restructured the ToC of the documentation a lot, some failed link may occurred if we are using the original link. We need to update them based on our current doc structure.

I will raise a PR to fix it :D
