### ISSUE TITLE
A randomly broken unittest

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#646]
/job/BigDL-PR-Validation-2.11-validation-parallel/388/testReport/junit/com.intel.analytics.bigdl.models/InceptionSpec/Inception_bn_should_generate_correct_output/

Jenkins can be passed if we re-run it.

**Comment by SeaOfOcean** [comment]
I met the same error

/job/BigDL-PR-Validation-2.10-validation-parallel/586/testReport/com.intel.analytics.bigdl.torch/LSTMPeepholeSpec/A_LSTMPeepwhole_should_has_same_loss_as_torch_rnn/

**Comment by SeaOfOcean** [comment]
Jenkins can be passed if we re-run it.

**Comment by yiheng** [comment]
Looks like the torch relate unit test can't be parallelized. For this case, let's change the unit test type of LSTM Peephole to serial. Open another issue to track the unit test parallelization problem.
