### ISSUE TITLE
Orca: KMP related environment variable takes no effect for PyTorch with ray on spark

### ISSUE THREAD

**Issue by CharleneHu94** [intel-analytics/BigDL#6492]
Environment variables including `KMP_AFFINITY`, `KMP_BLOCKTIME` has no effect when using PyTorch Ray on Spark. The reason should be that KMP related environment variables only take effect after switching to Intel OpenMP with `export LD_PRELOAD=<path>/libiomp5.so` for PyTorch, and currently `LD_PRELOAD` is not passed to Spark executors. So should there be a parameter or method for user to pass `LD_PRELOAD` or other user-defined environment variables to executors?

**Comment by sgwhat** [comment]
May I ask which cluster mode you set when calling `init_orca_context(...)`?

**Comment by sgwhat** [comment]
> > May I ask which cluster mode you set when calling `init_orca_context(...)`?
> 
> We tried YARN client mode and standalone mode, both show the same behaviour.

Are you running with `spark-submit` command or `init_orca_context(cluster_mode="yarn-cluster")`?

**Comment by CharleneHu94** [comment]
> > > May I ask which cluster mode you set when calling `init_orca_context(...)`?
> > 
> > 
> > We tried YARN client mode and standalone mode, both show the same behaviour.
> 
> Are you running with `spark-submit` command or `init_orca_context(cluster_mode="yarn-cluster")`?

`init_orca_context(...)` is used. Sorry there was a typo, actually we used YARN **client** mode, although I think the issue would also exist for YARN cluster mode..

**Comment by sgwhat** [comment]
try set it through `env` arguments:
```python
env = {"LD_PRELOAD" : "<path>/libiomp5.so"}

init_orca_context(cluster_mode="yarn-client", env=env)
```

**Comment by hkvision** [comment]
> try set it through `env` arguments:
> 
> ```python
> env = {"LD_PRELOAD" : "<path>/libiomp5.so"}
> 
> init_orca_context(cluster_mode="yarn-client", env=env)
> ```

Seems this can't work, @leonardozcm Please take a look at this.

Setting spark.executorEnv.LD_PRELOAD for pyspark backend can work.

**Comment by leonardozcm** [comment]
1. Ray passes environment variables across processes on ray cluster, and these variables are shown in `os.environ` instead of spark executor container, and that is why **LD_PRELOAD** is not displayed in **Spark WebUI**. But it does be passed.
```
(PytorchRayWorker pid=75588) Detect PRELOAD infos: python_env/lib/libiomp5.so
(PytorchRayWorker pid=75588) Detect OMP infos: 1
(PytorchRayWorker pid=75588) Detect KMP_AFFINITY infos: granularity=fine,verbose,compact,1,0
```

2. Following workaround does working, but user needs to know where conda env achieve locates in executors(python_env/), so It's a bit high bar but we can intetgrade in `init_orca_context`
```python
    env ={"LD_PRELOAD":"python_env/lib/libiomp5.so:python_env/lib/libpython3.7m.so", "OMP_NUM_THREADS":"8", "KMP_AFFINITY":"granularity=fine,compact,1,0"}
    init_orca_context(cluster_mode="yarn-client", env=env})
```

3. It seems KMP is not working on slowfast benchmark, we just disable it as default.

**Comment by leonardozcm** [comment]
closed this issue.
