### ISSUE TITLE
Orca: init_orca_context function for the cores setting parameters didn't take effect .

### ISSUE THREAD

**Issue by bihuanxu** [intel-analytics/BigDL#6500]
for AutoTSEstimator, if we set the thread limit on pythorch level for 4 , 
 os.environ['OMP_NUM_THREADS'] = "4"  # cores
 torch.set_num_threads(4)  # please revise this according to the hardware you have

and when call init_orca_context ,  set the cores=4.
init_orca_context(address="localhost:6379", runtime="ray", cores=4)
ray_ctx = OrcaContext.get_ray_context()
ray_ctx.is_local = True

then when set cpus_per_trial=1 for AutoTSEstimator, it show that the cpu cores used for tuning and training is far more than 4 cpu cores. it seem it is not really take effect at all for cores limitation.
auto_estimator = AutoTSEstimator(model='tcn',
                                 search_space="normal",
                                  past_seq_len=look_back,
                                  future_seq_len=horizon,
                                 metric="mse",
                                  cpus_per_trial=1)
if we use htop to see the cpu status, it show that far more than 4 cpu cores are used.

**Comment by liangs6212** [comment]
hi, how did you start the ray service? 

> for AutoTSEstimator, if we set the thread limit on pythorch level for 4 , os.environ['OMP_NUM_THREADS'] = "4" # cores torch.set_num_threads(4) # please revise this according to the hardware you have
> 
> and when call init_orca_context , set the cores=4. init_orca_context(address="localhost:6379", runtime="ray", cores=4) ray_ctx = OrcaContext.get_ray_context() ray_ctx.is_local = True
> 
> then when set cpus_per_trial=1 for AutoTSEstimator, it show that the cpu cores used for tuning and training is far more than 4 cpu cores. it seem it is not really take effect at all for cores limitation. auto_estimator = AutoTSEstimator(model='tcn', search_space="normal", past_seq_len=look_back, future_seq_len=horizon, metric="mse", cpus_per_trial=1) if we use htop to see the cpu status, it show that far more than 4 cpu cores are used.

**Comment by bihuanxu** [comment]
use the following command to launch the ray server.
ray start --head

**Comment by liangs6212** [comment]
> use the following command to launch the ray server. ray start --head

There are many parameters available for "ray start", have you tried "num-cpus"? Like this ray start --head --num-cpus 4, more info, please run ray start --help.

**Comment by TheaperDeng** [comment]
> > use the following command to launch the ray server. ray start --head
> 
> There are many parameters available for "ray start", have you tried "num-cpus"? Like this ray start --head --num-cpus 4, more info, please run ray start --help.

We have validated this workaround should work. @sgwhat

**Comment by bihuanxu** [comment]
> > use the following command to launch the ray server. ray start --head
> 
> There are many parameters available for "ray start", have you tried "num-cpus"? Like this ray start --head --num-cpus 4, more info, please run ray start --help.

> > use the following command to launch the ray server. ray start --head
> 
> There are many parameters available for "ray start", have you tried "num-cpus"? Like this ray start --head --num-cpus 4, more info, please run ray start --help.

**Comment by bihuanxu** [comment]
> > use the following command to launch the ray server. ray start --head
> 
> There are many parameters available for "ray start", have you tried "num-cpus"? Like this ray start --head --num-cpus 4, more info, please run ray start --help.

I had tested with num-cpus parameters, it can work. 
So for "cores" parameter of function init_orca_context , do you plan to fix it or we only can use the paramters in ray ?

**Comment by sgwhat** [comment]
Issue fixed.

**Comment by hkvision** [comment]
Can we close this issue? @sgwhat

**Comment by TheaperDeng** [comment]
> Can we close this issue? @sgwhat

I think we can

**Comment by sgwhat** [comment]
> Can we close this issue? @sgwhat

Sure.
