### ISSUE TITLE
Orca TF and PyTorch Estimator has different meanings for batch_size

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#6798]
Seems for tf batch_size is the global_batch for all workers while for pytorch it means the batch for each single worker.

**Comment by hkvision** [comment]
@jason-dai What's your opinion on this? Seems the global_batch is more reasonable?

**Comment by jason-dai** [comment]
> @jason-dai What's your opinion on this? Seems the global_batch is more reasonable?

Yes, I think we should use global batch size

**Comment by hkvision** [comment]
> > @jason-dai What's your opinion on this? Seems the global_batch is more reasonable?
> 
> Yes, I think we should use global batch size

Sure, will update for pytorch.
