### ISSUE TITLE
optim state has no clear specifications and prone to errors

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#682]
This is an issue for both scala and python. 
Use python as example:
```python
state = {"batchSize": batch_size,
         "learningRate": lr,
         "learningRateDecay": lrd}
    #configure optimizer
    optimizer = Optimizer(
        model=model,
        training_rdd=train_rdd,
        criterion=ClassNLLCriterion(),
        end_trigger=MaxEpoch(max_epoch),
        batch_size=batch_size,
        optim_method=optim,
        state=state) 
```
Problems include:
1) User can set any (key,value) into state without receiving any warning or error message. Our program just silently ignore any illegal states. If user misspelled the name of a key, he won't know that it never takes effect (unless the state is tracked in tensorboard or somewhere). 
1) Different optim method may just enable a subset of state parameters, and some of the parameters may override each other or take effects together. e.g. learningRateDecay and Step. Need more clear specifications of which params are enabled and how they take effect for each optim method. 

Need a checking for illegal params, and docs about the params in optim method.

**Comment by yiheng** [comment]
As discussion, in scala side the state contains hyper parameter should be a case class instead of a hashmap

**Comment by shane-huang** [comment]
added some documents about optimizer hyper parameters on wiki. https://github.com/intel-analytics/BigDL/wiki/Optimization-Algorithms

**Comment by shane-huang** [comment]
submitted in pr #802
