### ISSUE TITLE
bigdl-nano training error

### ISSUE THREAD

**Issue by Zjq9409** [intel-analytics/BigDL#6830]
hist = Trainer(args.yaml, use_ipex=True, channels_last=True, num_processes=4).train()
operating system: centos

<img width="789" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/62974595/204978994-cd59086a-4553-433f-a5aa-cab579d8ad8c.png">

**Comment by MeouSker77** [comment]
This is a known issue: `bigdl-nano` will try to find physical CPU cores automatically, which will cause error on centos.
We'll fix this issue as soon as possible.
Now a quick fix is using `cpu_for_each_process` parameter to specify the CPU cores for each processes, e.g. if you have 72 physical cores, you can write:
```
hist = Trainer(args.yaml, use_ipex=True, channels_last=True, num_processes=4,
               cpu_for_each_process=[list(range(0, 18)), list(range(18, 36)), list(range(36, 54)), list(range(54, 72))])
```

**Comment by MeouSker77** [comment]
We have fixed this issue yesterday, you can use `pip install --pre --upgrade bigdl-nano[pytorch]` to install the nightly-built bigdl-nano and try it again. This error should no longer occur
