### ISSUE TITLE
Request for a test_config file inorder to generate 'bigdl-ppml-trusted-big-data-ml-python-gramine-base' image

### ISSUE THREAD

**Issue by TejaswineeL** [intel-analytics/BigDL#6856]
I have been trying to generate a base image (bigdl-ppml-trusted-big-data-ml-python-gramine-base) so that i can configure some of the bash manifest options and generate a base image out of it.
i configured all the requested parameters in build-base-image.sh
I encountered some errors because of few snippets of the Dockerfile.
If I solve an error, I would encounter another error on the way.
Currently facing below error

[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
[ERROR] Caused by: Exception com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2d127a61 [in thread "main"]
The command '/bin/sh -c cd /opt &&     apt-get install -y build-essential &&     wget https://github.com/protocolbuffers/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.bz2 &&     tar jxvf protobuf-2.5.0.tar.bz2 &&     cd protobuf-2.5.0 &&     ./configure &&     make &&     make check &&     export LD_LIBRARY_PATH=/usr/local/lib &&     make install &&     protoc --version &&     cd /opt &&     git clone https://github.com/analytics-zoo/hadoop.git &&     cd hadoop &&     git checkout branch-3.2.0-ppml &&     cd hadoop-common-project/hadoop-common &&     export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m         -Dhttp.proxyHost=$HTTP_PROXY_HOST         -Dhttp.proxyPort=$HTTP_PROXY_PORT         -Dhttps.proxyHost=$HTTPS_PROXY_HOST         -Dhttps.proxyPort=$HTTPS_PROXY_PORT" &&     mvn -T 16 -DskipTests=true clean package &&     mv /opt/hadoop/hadoop-common-project/hadoop-common/target/hadoop-common-3.2.0.jar /opt/spark-${SPARK_VERSION}/jars/hadoop-common-3.2.0.jar' returned a non-zero code: 1

Instead, I am requesting some test_config file, which has most basic configurations already included as a part of Dockerfile, so that i can build the base image without debugging errors of Dockerfile

Config parameters are as follows
i have set my http and https proxy and port (works well)
export JDK_URL=https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.tar.gz
export SPARK_JAR_REPO_URL=https://repo1.maven.org/maven2/org/apache/spark
export LOCAL_IP=localhost

**Comment by glorysdj** [comment]
You need to use JDK8 and a modified spark to build bigdl-ppml-trusted-big-data-ml-python-gramine-base.
You can download the base image from Dockerhub: 
https://hub.docker.com/layers/intelanalytics/bigdl-ppml-trusted-big-data-ml-python-gramine-base/2.2.0-SNAPSHOT/images/sha256-67b7294d613cb969af35ee4852fe218138a574d0f7b3b2c8327b8d775e7a170d?context=repo
```docker pull intelanalytics/bigdl-ppml-trusted-big-data-ml-python-gramine-base:2.2.0-SNAPSHOT```

**Comment by glorysdj** [comment]
Hi [TejaswineeL](https://github.com/TejaswineeL)
```so that i can configure some of the bash manifest options and generate a base image out of it.```
You can list the features you need, we can have a review and try to add them to the manifest, and publish a new base image for that.

**Comment by glorysdj** [comment]
Hi Tejaswinee, please try the base image: intelanalytics/bigdl-ppml-trusted-big-data-ml-python-gramine-base:2.2.0-SNAPSHOT
We are refactoring the image hierarchy of BigDL PPML. To build/refine this base image, we can help to improve/adjust the bash.manifest for you, please let us know what are the requirements. Thanks.

**Comment by TejaswineeL** [comment]
Yes, I could run spark_SGX example with the base image.
Thanks for the suggestion.

Another hurdle i am facing is that
when i try to execute my spark code with command 
./bigdl-ppml-submit.sh work/YOUR_PROMGRAM.py | tee YOUR_PROGRAM-sgx.log
as specified in the README 
https://github.com/intel-analytics/BigDL/tree/d941a9f884e39eb26b158f966077752ded362ea7/ppml/trusted-big-data-ml/python/docker-gramine

I witness errors from bigdl-ppml-submit.sh file like
1. ${RUNTIME_DRIVER_MEMORY} not defined
2. spark-examples.jars version not matching 
3. java.lang.IllegalArgumentException: spark.driver.port should be int, but was...
(the execution does not reach to my spark code) 

Could you please clarify if this method of execution is deprecated. 
Kindly, guide me for accurate steps.

**Comment by TejaswineeL** [comment]
Also, I want to execute  work/spark-3.1.3/sbin/start-master.sh on SGX so that I can run spark examples in a standalone cluster (master -slave) mode.

I tried the below command with the base image

![image](https://user-images.githubusercontent.com/56070200/206690788-3c13d35d-1c0b-4616-a153-aff541b3be39.png)
getting continuous errors seeking for extra arguments 

without SGX ./start-master.sh works

I could use your suggestions/ commands here.
Thanks in advance.

**Comment by glorysdj** [comment]
> Yes, I could run spark_SGX example with the base image. Thanks for the suggestion.
> 
> Another hurdle i am facing is that when i try to execute my spark code with command ./bigdl-ppml-submit.sh work/YOUR_PROMGRAM.py | tee YOUR_PROGRAM-sgx.log as specified in the README https://github.com/intel-analytics/BigDL/tree/d941a9f884e39eb26b158f966077752ded362ea7/ppml/trusted-big-data-ml/python/docker-gramine
> 
> I witness errors from bigdl-ppml-submit.sh file like
> 
> 1. ${RUNTIME_DRIVER_MEMORY} not defined
> 2. spark-examples.jars version not matching
> 3. java.lang.IllegalArgumentException: spark.driver.port should be int, but was...
>    (the execution does not reach to my spark code)
> 
> Could you please clarify if this method of execution is deprecated. Kindly, guide me for accurate steps.

Could you please paste the command you run, and the exception details?
For 1. RUNTIME_DRIVER_MEMORY should be defined before you run bigdl-ppml-submit.sh.
For 2 and 3, we may need the exception details.

**Comment by glorysdj** [comment]
> Also, I want to execute work/spark-3.1.3/sbin/start-master.sh on SGX so that I can run spark examples in a standalone cluster (master -slave) mode.
> 
> I tried the below command with the base image
> 
> ![image](https://user-images.githubusercontent.com/56070200/206690788-3c13d35d-1c0b-4616-a153-aff541b3be39.png) getting continuous errors seeking for extra arguments
> 
> without SGX ./start-master.sh works
> 
> I could use your suggestions/ commands here. Thanks in advance.

Spark standalone mode is deprecated in bigdl ppml. 
Please run the examples with spark local or spark on k8s mode.
Please refer to https://github.com/intel-analytics/BigDL/tree/main/ppml#step-5-submit-job

**Comment by TejaswineeL** [comment]
Team,
I need help with the values of parameters used in build_base_image.sh to generate a base image.

When I use the pre-built image 'intelanalytics/bigdl-ppml-trusted-big-data-ml-python-gramine-base' and run the spark example ![image](https://user-images.githubusercontent.com/56070200/213708457-b3b8768d-b967-466c-8640-b24f6ac1725d.png), it executes fine.

However, when I generate the base image from scratch with a dockerfile at location- ppml/trusted-big-data-ml/python/docker-gramine/base and with below parameters in the build_base_image.sh file
export JDK_URL=url for /jdk8/jdk-8u341-linux-x64.tar.gz
export SPARK_JAR_REPO_URL=https://repo1.maven.org/maven2/org/apache/spark
export LOCAL_IP=localhost, 
I encounter below errors  for ![image](https://user-images.githubusercontent.com/56070200/213714557-f8ac2116-d4cb-436b-b645-c67eed7eb03b.png)
1. error: failed sending PAL handles as part of checkpoint (ret = -22)
    error: process creation failed
2. Failed to delete: /tmp/blockmgr-b4654905-75bc-433a-80ad-b7f985b99d7b
    Failed to list files for dir: /tmp/blockmgr-b4654905-75bc-433a-80ad-b7f985b99d7b

in both the cases (with pre-built image and newly built image) the workload executes. I observe the result Pi is roughly 3.135760
    
So, could you please share the values which BigDL used to generate the pre-built image for below parameters which are used in the generation of a base image:
JDK_URL=
SPARK_JAR_REPO_URL=
BIGDL_VERSION=
SPARK_VERSION=
TINI_VERSION=
JDK_VERSION=

**Comment by qiuxin2012** [comment]
@TejaswineeL Our settings:
```
JDK_URL=http://[internal nexus ip]:8081/repository/raw/jdk/jdk-8u192-linux-x64.tar.gz
SPARK_JAR_REPO_URL=http://[internal nexus ip]:8081/repository/raw/spark
```
The spark jar files contains our optimization for gramine, it's not open sourced right now. You can copy them from our released gramine images.
The files list on our nexus:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/4495653/215301757-0357bc6f-7c05-4cb1-87fb-f4425c90eb63.png">

**Comment by glorysdj** [comment]
@TejaswineeL Hi Tejaswinee, please try the base image: [intelanalytics/bigdl-ppml-trusted-bigdata-gramine-reference-32g:2.3.0-SNAPSHOT](https://hub.docker.com/layers/intelanalytics/bigdl-ppml-trusted-bigdata-gramine-reference-32g/2.3.0-SNAPSHOT/images/sha256-61c17efd39ba9eacaf9959debed66f5491de525225826754425a047a74c37aca?context=repo)

**Comment by TejaswineeL** [comment]
Thank you so much
