### ISSUE TITLE
Orca: Pack outputs

### ISSUE THREAD

**Issue by leonardozcm** [intel-analytics/BigDL#7021]
https://github.com/intel-analytics/BigDL/blob/main/python/orca/src/bigdl/orca/learn/pytorch/torch_runner.py#L500-L504

Related issue: https://github.com/analytics-zoo/Telecom-CTC-E2E/pull/16#issuecomment-1311676360

**Comment by hkvision** [comment]
https://github.com/analytics-zoo/Telecom-CTC-E2E/issues/19
