### ISSUE TITLE
Couldn't change spark_log_level in BigDL image 

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/BigDL#7026]
[BigDL image](https://hub.docker.com/layers/intelanalytics/bigdl/2.1.0/images/sha256-97edcd292ab5d234a80a569a220c2739e986b157851d010b42dd85463bfc8909?context=explore ) couldn't change spark_log_level, using
`sc = init_spark_on_local(cores=1, spark_log_level="ERROR")` in python. 
See for details, https://github.com/intel-analytics/BigDL/issues/6873#issuecomment-1354336109

**Comment by qiuxin2012** [comment]
after create container
start a python
type in
```
from bigdl.dllib.nncontext import *
sc = init_spark_on_local(cores=1, spark_log_level="ERROR")
sc.range(0, 100).collect()
```

**Comment by qiuxin2012** [comment]
```
from bigdl.dllib.nncontext import *
sc = init_spark_on_local(cores=1, spark_log_level="ERROR")

from bigdl.dllib.keras.layers import *
from bigdl.dllib.keras.models import *
hidden_size=100
col=94
_action_size=4
model = Sequential()
# Add imput layer
model.add(Dense(hidden_size, input_dim=col,name='input'))

# Add hidden layers
for layers in range(3):
    model.add(Dense(hidden_size, activation='relu'))

# Add output layer    
model.add(Dense(_action_size, activation='softmax',name='output'))



model.compile(loss='categorical_crossentropy', optimizer='SGD')

state = np.random.rand(1, 94)
error_state = np.random.rand(1, 4)

model.fit(state, error_state, 1)
```

**Comment by qiuxin2012** [comment]
add `spark.driver.defaultJavaOptions    -Dlog4j.configuration=/opt/work/spark-3.1.2/conf/log4j2.xml` to `/opt/work/spark-3.1.2/conf/spark-defaults.conf`

**Comment by glorysdj** [comment]
need to specify log4j2 conf to spark driver and executor

**Comment by Le-Zheng** [comment]
fix in https://github.com/intel-analytics/BigDL/pull/7038
