### ISSUE TITLE
[PPML] Missing secure_argvs file in bigdl-ppml-gramine-base image

### ISSUE THREAD

**Issue by Uxito-Ada** [intel-analytics/BigDL#7110]
Encounter a SGX compiling  error when I want to build custom image on top of **intelanalytics/bigdl-ppml-gramine-base:2.2.0-SNAPSHOT**:

```
Step 16/38 : RUN cd /ppml &&     chmod a+x make-sgx.sh &&     ./make-sgx.sh
---> Running in 1684a70da9ca
......
  File "/usr/local/lib/python3.7/dist-packages/graminelibos/manifest.py", line 56, in append_trusted_dir_or_file
    raise ManifestError(f'Cannot resolve {path}')
graminelibos.manifest.ManifestError: Cannot resolve /ppml/secured_argvs
make: *** [Makefile:44: bash.manifest.sgx] Error 1
```

The sign file /ppml/secured_argvs does not exist in the base image.
Should it be created in /ppml/base/Dockfile like [trusted-big-data-ml](https://github.com/intel-analytics/BigDL/blob/main/ppml/trusted-big-data-ml/python/docker-gramine/base/Dockerfile#L273)?

@gc-fu @glorysdj

**Comment by gc-fu** [comment]
The `/ppml/secured_argvs` is created in all the second-level images.
Do you mean that we should move this to the bigdl-ppml-gramine-base image?

**Comment by Uxito-Ada** [comment]
> The `/ppml/secured_argvs` is created in all the second-level images. Do you mean that we should move this to the bigdl-ppml-gramine-base image?

I think so, if all the child images need to create secured_argvs.

**Comment by gc-fu** [comment]
Yeah, this can be put in the first-level image.
Didn't find any strong dependencies which makes it must stay at second level.

**Comment by glorysdj** [comment]
we should leave this to sub-images, each sub module of ppml should specify this file, do not need to put in base image
