### ISSUE TITLE
allow set weight and bias per layer

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#724]
Similar functionality of Keras layer.set_weights(). This is used to initialize certain layers from pre-trained layers from another model.

**Comment by zhichao-li** [comment]
How about we put this API in AbstractModule? @yiheng

**Comment by shane-huang** [comment]
# MF embeddings
    gmf_user_embeddings = gmf_model.get_layer('user_embedding').get_weights()
    gmf_item_embeddings = gmf_model.get_layer('item_embedding').get_weights()
    model.get_layer('mf_embedding_user').set_weights(gmf_user_embeddings)
    model.get_layer('mf_embedding_item').set_weights(gmf_item_embeddings)
