### ISSUE TITLE
Check the return stats consistency between different backends

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#7257]
TensorFlow
- fit should return a single dict (the values is a list containing stats of different epochs)
- evaluate should return a single dict

PyTorch
- fit should return a list of dict, each dict in the list corresponds to the stats of one epoch
- evaluate should return a single dict

TODO List:
TensorFlow
- [x] ray backend
- [x] spark backend
- [ ] Remove "train_" from keys?

PyTorch
- [x] ray backend
- [x] spark backend

@hamham223

**Comment by hkvision** [comment]
Related previous fix: https://github.com/intel-analytics/BigDL/pull/7006

**Comment by hamham223** [comment]
pytorch already satisfy all the requirements
