### ISSUE TITLE
A Quick Check is needed in bigdl-attestation-service document and for other PPML services

### ISSUE THREAD

**Issue by Uxito-Ada** [intel-analytics/BigDL#7330]
We need to provide a Quick Check method for users to validate whether the service is ready after deployment, such as a REST API at root URL path that responses some welcome message, and append the method in bigdl-attestation-service READMEs. @xiangyuT 

Additionally, we need a `check-services.sh`  containing validations of all PPML services, to test whether these components are ready in current environment like what we do in trusted-real-time. @SEULiyao 

- [x] bigdl-attestation-service deployment validation
- [x] check-services.sh for all PPML services

**Comment by Uxito-Ada** [comment]
link to #7332

**Comment by SEULiyao** [comment]
link to #7340
