### ISSUE TITLE
Need to manually downgrade protobuf after installing ray?

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#7347]
File "/root/anaconda3/envs/orca/lib/python3.7/site-packages/bigdl/orca/data/ray_xshards.py", line 19, in <module>
    import ray
  File "/root/anaconda3/envs/orca/lib/python3.7/site-packages/ray/__init__.py", line 91, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 104, in init ray._raylet
  File "/root/anaconda3/envs/orca/lib/python3.7/site-packages/ray/exceptions.py", line 5, in <module>
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  File "/root/anaconda3/envs/orca/lib/python3.7/site-packages/ray/core/generated/common_pb2.py", line 37, in <module>
    create_key=_descriptor._internal_create_key),
  File "/root/anaconda3/envs/orca/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by hkvision** [comment]
@hamham223 Please take a look.

**Comment by hamham223** [comment]
https://bigdl.readthedocs.io/en/latest/doc/Nano/Overview/known_issues.html#protobuf-version-error

A similar problem in nano:

> protobuf version error
Now pip install ray[default]==1.11.0 will install google-api-core>=2.10.0, which depends on protobuf>=3.20.1. However, nano depends on protobuf==3.19.4, so you will meet this error if you install ray after bigdl-nano. The solution is pip install google-api-core==2.8.2 before installing ray.

dependency:

+ `bigdl-orca` does not require `protobuf`
+ `bigdl-orca[ray]` requires `ray[default]==1.9.2`, which in turn requires `protobuf>=3.15.3`. If protobuf is not installed yet, it will install the newest version 4.21.12 by default, and the user need to down-grade the version.
+ `bigdl-nano` and `bigdl` require `protobuf==3.19.5`  https://github.com/intel-analytics/BigDL/blob/main/python/nano/setup.py#L163

**Comment by hkvision** [comment]
Seems this is the issue of the current ray 1.9.2. When installing ray 1.9.2, will automatically install the latest protobuf, which is not compatible with ray. (Probably at the release time of ray 1.9.2, the latest protobuf worked, but now it doesn't).

We can add protobuf version dependency to ray.
