### ISSUE TITLE
Failed to compile BigDL project

### ISSUE THREAD

**Issue by dding3** [intel-analytics/BigDL#737]
I tried both master and branch 0.1, they failed to compile bigdl and the failure is failed to find com.intel.analytics.bigdl.native:mkl-java:jar (please clean mkl-java-xxx.jar in local maven repository before compile).
Error for master branch:
Failure to find com.intel.analytics.bigdl.native:mkl-java:jar:0.2.0-SNAPSHOT in https://oss.sonatype.org/content/groups/public/ was cached in the local repository
Error for barnch 0.1:
Could not find artifact com.intel.analytics.bigdl.native:mkl-java:jar:0.1.0 in central in https://repo1.maven.org/maven2 was cached in the local repository

It's werid the exception is not catched by pr-validation

**Comment by yiheng** [comment]
This has been fixed
