### ISSUE TITLE
why does label add one ?

### ISSUE THREAD

**Issue by jhkkhtd** [intel-analytics/BigDL#744]
hello ,,, i am reading the code ,  there is one problem i can't understand .  why should the  labe been added 1.0f .?????   like these code:    the last line (  https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/models/lenet/Utils.scala)    "ByteRecord(img, label + 1.0f) ""    o r  "  ByteRecord(img, labelBuffer.get().toFloat + 1.0f)  "

**Comment by yiheng** [comment]
We assume that the classId in the label starts from 1.

**Comment by shane-huang** [comment]
@yiheng I also think classId better starts from 0. The predicted results returns an array of class probability, it's a common practice to perform argmax on the prob array to get the classId - it starts from 0 as array index starts from 0.  So we also need to +1 for each predicted class to get conforming label? This +1 behavior does look confusing to me.

**Comment by srowen** [comment]
Is this the kind of thing that should be moved to https://groups.google.com/forum/#!forum/bigdl-user-group ? it doesn't sound like an issue.
