### ISSUE TITLE
version.txt for Python is not changed

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#7481]
https://github.com/intel-analytics/BigDL/blob/main/python/version.txt
Why this is not changed?
Also for branch2.2 it is unchanged.

For the release job, we should change this file instead of manually input the version to the script. @pinggao18

**Comment by Le-Zheng** [comment]
Shall we remove this file since it seems not be use anywhere?

**Comment by hkvision** [comment]
I don't think we can remove it.
We do need to have some place in the code to identify the version, instead of always manually input it in our Jenkins jobs.

**Comment by hkvision** [comment]
@hamham223 Please help fix this.

**Comment by hkvision** [comment]
Also work with @Le-Zheng and @liu-shaojun to make sure when we release, we use the version in version.txt instead of manually input the version.
