### ISSUE TITLE
Issues Integrating forecaster tune with Nbeats

### ISSUE THREAD

**Issue by pankajr141** [intel-analytics/BigDL#7560]
When trying to integrate forecaster tune with NBeats it seems it is forcefully disabled in code

<pre>
from bigdl.chronos.forecaster.nbeats_forecaster import NBeatsForecaster
import bigdl.nano.automl.hpo.space as space

model = NBeatsForecaster(past_seq_len=timesteps_x,  # number of steps to look back
                         future_seq_len=timesteps_y,  # number of steps to predict
                         stack_types=space.Categorical(('generic', 'generic')),
                         nb_blocks_per_stack=space.Categorical(5),
                         share_weights_in_stack=space.Categorical(False),
                         hidden_layer_units=space.Categorical(256))
</pre>

Getting error as mentioned below, 

<pre>
lobal seed set to 347276960

****************************Usage Error************************
Found search spaces in arguments but HPO is disabled.Enable HPO or remove search spaces in arguments to use.

****************************Call Stack*************************
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[17], line 4
      1 from bigdl.chronos.forecaster.nbeats_forecaster import NBeatsForecaster
      2 import bigdl.nano.automl.hpo.space as space
----> 4 model = NBeatsForecaster(past_seq_len=timesteps_x,  # number of steps to look back
      5                          future_seq_len=timesteps_y,  # number of steps to predict
      6                          stack_types=space.Categorical(('generic', 'generic')),
      7                          nb_blocks_per_stack=space.Categorical(5),
      8                          share_weights_in_stack=space.Categorical(False),
      9                          hidden_layer_units=space.Categorical(256))

File ~/env/lib/python3.8/site-packages/bigdl/chronos/forecaster/nbeats_forecaster.py:172, in NBeatsForecaster.__init__(self, past_seq_len, future_seq_len, stack_types, nb_blocks_per_stack, thetas_dim, share_weights_in_stack, hidden_layer_units, nb_harmonics, optimizer, loss, lr, metrics, seed, distributed, workers_per_node, distributed_backend)
    169 self.checkpoint_callback = True
    170 self.use_hpo = False
--> 172 super().__init__()

File ~/env/lib/python3.8/site-packages/bigdl/chronos/forecaster/base_forecaster.py:78, in BasePytorchForecaster.__init__(self, **kwargs)
     73 has_space = _config_has_search_space(
     74     config={**self.model_config, **self.optim_config,
     75             **self.loss_config, **self.data_config})
     77 if not self.use_hpo and has_space:
---> 78     invalidInputError(False, "Found search spaces in arguments but HPO is disabled."
     79                              "Enable HPO or remove search spaces in arguments to use.")
     81 if not has_space:
     82     self.use_hpo = False

File ~/env/lib/python3.8/site-packages/bigdl/nano/utils/log4Error.py:32, in invalidInputError(condition, errMsg, fixMsg)
     30 if not condition:
     31     outputUserMessage(errMsg, fixMsg)
---> 32     raise RuntimeError(errMsg)

RuntimeError: Found search spaces in arguments but HPO is disabled.Enable HPO or remove search spaces in arguments to use.
</pre>

The issue is  <pre>self.use_hpo = False</pre> is forcefully disabled in code (https://github.com/intel-analytics/BigDL/blob/main/python/chronos/src/bigdl/chronos/forecaster/nbeats_forecaster.py
) and it cannot be enabled due to absence of any argument in constructor.

But as per documentation - https://bigdl.readthedocs.io/en/latest/doc/PythonAPI/Chronos/forecasters.html#nbeatsforecaster
<pre>tune</pre> function is present which is for  hyper parameter search

**Comment by TheaperDeng** [comment]
Users could enable the hpo function by
```python
forecaster.use_hpo = True  # after initializing the forecaster
```
Still, we disable the hpo function for NbeatsForecaster since we have not carried out enough test on it, you may meet some issues during the usage. Feel free to put it here for further discussion

**Comment by pankajr141** [comment]
Thanks for the revert, the issue is i am unable to instantiate an object, as you can see from above snapshot

I will not be able to set object property if i am unable to instantiate it.

**Comment by TheaperDeng** [comment]
> Thanks for the revert, the issue is i am unable to instantiate an object, as you can see from above snapshot
> 
> I will not be able to set object property if i am unable to instantiate it.

Yeah, you are right. I am raising a PR to support NBeatsForecaster in Chronos and it will be reflected in nightly version.

I understand you may willing to use stable version (since it is easier for integration in a product), please try following methods:

```python
forecaster = NBeatsForecaster(past_seq_len=24,
                              future_seq_len=5,
                              loss="mae",
                              metrics=['mae', 'mse', 'mape'])  # don't put any space when initializing the forecaster
forecaster.use_hpo = True
forecaster.optim_config.update({"lr": space.Real(0.001, 0.01, log=True)})  # different parameters may lies in different attributes (e.g., optim_config, model_config), please refer to https://github.com/intel-analytics/BigDL/blob/main/python/chronos/src/bigdl/chronos/forecaster/nbeats_forecaster.py

# after these, you may call tune method
forecaster.tune(train_data, validation_data=val_data,
                n_trials=2, target_metric=['mse', 'latency'],
                direction=None,
                directions=["minimize", "minimize"])

```

**Comment by pankajr141** [comment]
Thanks it helped
