### ISSUE TITLE
Orca: Yarn/Hadoop cluster tutorial Enhancement && Issue Summary

### ISSUE THREAD

**Issue by hamham223** [intel-analytics/BigDL#7561]
This PR summaries all the issues in the [yarn/Hadoop cluster tutorial](https://github.com/intel-analytics/BigDL/blob/main/docs/readthedocs/source/doc/Orca/Tutorial/yarn.md) and some possible improvements.

1. Replace `/path/to/python` by `$( which python )`, make it easier for users to copy and paste in the terminal. **Highlight** other **`/path/to/`** (if possible) to aware users to change them according to their environments.

2. For `spark-submit` 

+ in step 2 setup
 ```
Download the requirement file from [here]. and install the required Python libraries of BigDL Orca according to your needs.
```
Better to add one line “In the FashionMNIST example, you only need to install the basic requirements.txt” and `them torch torchvision`”

+ in step 5 download spark, seems pyspark==3.1.3 cannot work?

+ Currently, if the user downloads BigDL <= 2.2.0, they need to install `pyarrow` to run the FashionMNIST example. This bug is fixed in PR:  https://github.com/intel-analytics/BigDL/pull/7269

3. Perhaps mark the conf `--conf spark.executorEnv.PYSPARK_PYTHON` to be bold? So users can be aware of the difference between client mode and cluster mode.

@hkvision  could you please help me add the label `orca`?

**Comment by hkvision** [comment]
1. We can replace with `which python`
2. install torch already specified in the environment preparation section.
3. For spark submit users, they have no awareness of pyspark.
4. Ignore
5. Not necessary.

**Comment by hkvision** [comment]
For the first issue, can we directly use python?

**Comment by hamham223** [comment]
> For the first issue, can we directly use python?

Yes, test success for both spark-submit/bigdl-submit for `yarn-client` mode.
