### ISSUE TITLE
Comparison to deeplearning4j 

### ISSUE THREAD

**Issue by geoHeil** [intel-analytics/BigDL#757]
Especially if using deeplearning4js netlib blas backend with mkl support what is the benefit of using big-dl?

**Comment by srowen** [comment]
This doesn't sound like an issue. Better to ask a more specific question at https://groups.google.com/forum/#!forum/bigdl-user-group ?

**Comment by geoHeil** [comment]
will do that

**Comment by geoHeil** [comment]
The post is https://groups.google.com/forum/#!topic/bigdl-user-group/gBLbadb1cM4
