### ISSUE TITLE
Issue in saving and loading AutoFormer for inference

### ISSUE THREAD

**Issue by pankajr141** [intel-analytics/BigDL#7615]
Most of the other models LSTM, TCNN, Seq2Seq support onnx export, which allows model loading extremely easy in inference environment, but autoformer doesn't support
<pre>
export_onnx_file
</pre>

The example present in https://github.com/intel-analytics/BigDL/blob/main/python/chronos/use-case/electricity/autoformer.py
showcase save and load functionality, but its only fit for in memory objects, or maybe if we initiate another object with same params and then load. But for inference environment this isn't optimal, because it needs model details. 

<b>Can you please let me know if their is a way in which we can use trained model separately like other previous model (tcn etc)</b>

As a debugging step i have tried below approaches 

### Approach 1- Directly export autoformer pytorch model to onnx.

<pre>
    model.get_model().to_onnx(filepath, input_sample, export_params=True)
</pre>

But i am getting some onnx error, which is a known pytorch issue  (https://github.com/pytorch/pytorch/issues/44822)

<img width="629" alt="image" src="https://user-images.githubusercontent.com/2833859/220013075-eceede1b-2786-4ca4-ba8f-57ae875462ed.png">

### Approach 2- Pickle the autoformer object and load at client side.
<pre>
import pickle
model_chronos_file = "chronos_model_forecaster"
with open(model_chronos_file, 'wb') as fp:
    pickle.dump(model, fp)

model_pickle = pickle.load(open(model_chronos_file, 'rb'))
model_pickle.predict(data_train)
</pre>
Got below error
<img width="627" alt="image" src="https://user-images.githubusercontent.com/2833859/220013621-0c75da30-041e-4def-b7fb-0e843a61d6c7.png">

### Approach 3 - directly via torch save

<img width="625" alt="image" src="https://user-images.githubusercontent.com/2833859/220014007-f66500a2-60f4-4b12-849c-7ee63b3b248b.png">

**Comment by TheaperDeng** [comment]
This is really a good point, forecaster's loading for autoformer has really become a problem. I recommend using following method in stable 2.2.0.

```python
# saving
with open("test.fxt", "wb") as f:
    pickle.dump(forecaster.internal, f)

# loading
with open("test.fxt", "rb") as f:
    model_load = pickle.load(f)

# then you could use model_load  for prediction
model_load(x1, x2, x3, x4)
```

We will try to find some easy way for forecaster loading and it will be reflected in nightly version.

**Comment by pankajr141** [comment]
Thnx above worked for Autoformer which doesnt use forecaster.tune

<pre>
import numpy as np
import torch

# train_x: (1794, 5, 1), train_y: (1794, 2, 1), train_x_enc: (1794, 2, 4), train_y_enc: (1794, 4, 4)
timesteps_x = 10
timesteps_y = 2
label_len = 5

N = 1000
train_x = np.random.rand(N, timesteps_x, 1)
train_y = np.random.rand(N, label_len + timesteps_y, 1)
train_x_enc = np.random.rand(N, timesteps_x, 4)
train_y_enc = np.random.rand(N, label_len + timesteps_y, 4)

print("train_x: {}, train_y: {}, train_x_enc: {}, train_y_enc: {}".format(train_x.shape, train_y.shape, train_x_enc.shape, train_y_enc.shape))

import bigdl.nano.automl.hpo.space as space
from bigdl.nano.automl.hpo.backend import SamplerType

from bigdl.chronos.forecaster.autoformer_forecaster import AutoformerForecaster
model = AutoformerForecaster(past_seq_len=timesteps_x,  # number of steps to look back
                               future_seq_len=timesteps_y,
                               label_len=label_len,       # number of steps to predict
                               input_feature_num=train_x.shape[-1],      # number of feature to use
                               output_feature_num=train_y.shape[-1],     # number of feature to predict
                               d_model=space.Categorical(128),
                               e_layers=space.Categorical(2, 3),
                               d_layers=1,
                               d_ff=256,
                               freq='h',
            )


import time
from bigdl.nano.automl.hpo.backend import SamplerType
model.num_processes = 1
name = f"mo_latency_{time.time()}"
storage = "sqlite:///mo_latency.db"


trials = model.tune(data=(train_x, train_y, train_x_enc, train_y_enc),
                    validation_data=(train_x, train_y, train_x_enc, train_y_enc),
                    target_metric=['mse', 'latency'],
                    direction=None,
                    directions=['minimize', 'minimize'],
                    n_trials=1,
                    n_parallels=1,
                    sampler=SamplerType.Grid,
                    epochs=2,
                    batch_size=32,
                    study_name=name,
                    storage=storage)


model.fit((train_x.astype(np.float32), 
          train_y.astype(np.float32), 
          train_x_enc.astype(np.float32), 
          train_y_enc.astype(np.float32)), batch_size=2, epochs=1, use_trial_id=trials[0].number)


import pickle
model_chronos_file = "chronos_model_forecaster"
with open(model_chronos_file, 'wb') as fp:
    pickle.dump(model.internal, fp)
</pre>

Model is successfully trained, but i am unable to save it as mentioned above.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/2833859/220645372-25d2c00c-3245-46a1-bc09-f1f924809ab7.png">

The same thing work if i train a autoformer normally, without hyperparameter optimization

**Comment by TheaperDeng** [comment]
> Thnx above worked for Autoformer which doesnt use forecaster.tune
> 
> However when i try to use forecaster tune to train a autoformer model and then try to save it, it doesnt work, below is sample code for the sam.e
> 
> import numpy as np
> import torch
> 
> # train_x: (1794, 5, 1), train_y: (1794, 2, 1), train_x_enc: (1794, 2, 4), train_y_enc: (1794, 4, 4)
> timesteps_x = 10
> timesteps_y = 2
> label_len = 5
> 
> N = 1000
> train_x = np.random.rand(N, timesteps_x, 1)
> train_y = np.random.rand(N, label_len + timesteps_y, 1)
> train_x_enc = np.random.rand(N, timesteps_x, 4)
> train_y_enc = np.random.rand(N, label_len + timesteps_y, 4)
> 
> print("train_x: {}, train_y: {}, train_x_enc: {}, train_y_enc: {}".format(train_x.shape, train_y.shape, train_x_enc.shape, train_y_enc.shape))
> 
> import bigdl.nano.automl.hpo.space as space
> from bigdl.nano.automl.hpo.backend import SamplerType
> 
> from bigdl.chronos.forecaster.autoformer_forecaster import AutoformerForecaster
> model = AutoformerForecaster(past_seq_len=timesteps_x,  # number of steps to look back
>                                future_seq_len=timesteps_y,
>                                label_len=label_len,       # number of steps to predict
>                                input_feature_num=train_x.shape[-1],      # number of feature to use
>                                output_feature_num=train_y.shape[-1],     # number of feature to predict
>                                d_model=space.Categorical(128),
>                                e_layers=space.Categorical(2, 3),
>                                d_layers=1,
>                                d_ff=256,
>                                freq='h',
>             )
> 
> 
> import time
> from bigdl.nano.automl.hpo.backend import SamplerType
> model.num_processes = 1
> name = f"mo_latency_{time.time()}"
> storage = "sqlite:///mo_latency.db"
> 
> 
> trials = model.tune(data=(train_x, train_y, train_x_enc, train_y_enc),
>                     validation_data=(train_x, train_y, train_x_enc, train_y_enc),
>                     target_metric=['mse', 'latency'],
>                     direction=None,
>                     directions=['minimize', 'minimize'],
>                     n_trials=1,
>                     n_parallels=1,
>                     sampler=SamplerType.Grid,
>                     epochs=2,
>                     batch_size=32,
>                     study_name=name,
>                     storage=storage)
> 
> 
> model.fit((train_x.astype(np.float32), 
>           train_y.astype(np.float32), 
>           train_x_enc.astype(np.float32), 
>           train_y_enc.astype(np.float32)), batch_size=2, epochs=1, use_trial_id=trials[0].number)
> 
> 
> import pickle
> model_chronos_file = "chronos_model_forecaster"
> with open(model_chronos_file, 'wb') as fp:
>     pickle.dump(model.internal, fp)
> The error which i am getting is
> 
> <img alt="image" width="626" src="https://user-images.githubusercontent.com/2833859/220645372-25d2c00c-3245-46a1-bc09-f1f924809ab7.png">
> 
> The same thing work if i train a autoformer normally, without hyperparameter optimization

Since this is a workaround method so it might be a little hacking, for a tunned model, you may use

```python
with open(model_chronos_file, 'wb') as fp:
    pickle.dump(model.internal.model, fp)
```

We are working on a better save/load API for users who could not use `forecaster.load` and it will be reflected in next release.

**Comment by pankajr141** [comment]
Thnx it worked
