### ISSUE TITLE
Databricks Tutorial Update

### ISSUE THREAD

**Issue by sgwhat** [intel-analytics/BigDL#7659]
When creating a databricks cluster, I always get an error when running the init script, which I basically follow the script as below (to generate script):

```bash
init_script = """
#!/bin/bash

# install bigdl-orca, add other bigdl modules if you need
/databricks/python/bin/pip install pip install --pre --upgrade bigdl-orca-spark3[ray]

# install other necessary libraries, here we install libraries needed in this tutorial
/databricks/python/bin/pip install tensorflow==2.9.1
/databricks/python/bin/pip install tqdm
/databricks/python/bin/pip install torch==1.11.0+cpu torchvision==0.12.0+cpu tensorboard -f https://download.pytorch.org/whl/torch_stable.html

# copy bigdl jars to databricks
cp /databricks/python/lib/python3.8/site-packages/bigdl/share/*/lib/*.jar /databricks/jars
"""

# Change the first parameter to your DBFS path
dbutils.fs.put("dbfs:/FileStore/scripts/init.sh", init_script, True)
```

The reason has been found that `/databricks/python/lib/python3.8/site-packages/bigdl` no longer exists. 

To solve the issue, we need to switch `python3.8` to `python3.9`, which could run the init script successfully as usual. @hkvision @PatrickkZ

**Comment by hkvision** [comment]
@PatrickkZ Take a look at this.

**Comment by sgwhat** [comment]
Is it fine for us to change `python3.8` to `python3.9` directly?

**Comment by hkvision** [comment]
Will the environment always be 3.8 or 3.9? Maybe need to check how previously we used 3.8?

**Comment by sgwhat** [comment]
> Will the environment always be 3.8 or 3.9? Maybe need to check how previously we used 3.8?

Databricks has released runtime 12.x, and python version has been switched to 3.9, maybe we should look into how to use runtime 10.x for python 3.8 using？

**Comment by hkvision** [comment]
So maybe we can update the tutorial:
- Highly recommend users not to use runtime 12.x, since 3,9 is not fully tested by us
- Add a remark that if they use 12.x, they need to change the python version/path accordingly
