### ISSUE TITLE
Documentation has broken links

### ISSUE THREAD

**Issue by jlefman** [intel-analytics/BigDL#767]
In [this page](https://software.intel.com/en-us/articles/bigdl-distributed-deep-learning-on-apache-spark) there are broken links to the following

- https://github.com/intel-analytics/BigDL/tree/master/dl/src/main/scala/com/intel/analytics/bigdl/models
- https://github.com/intel-analytics/BigDL/tree/master/dl/src/main/scala/com/intel/analytics/bigdl/nn

**Comment by qiuxin2012** [comment]
Thanks very much for your reply. We will update the links in https://software.intel.com/en-us/articles/bigdl-distributed-deep-learning-on-apache-spark as soon as possible.
