### ISSUE TITLE
validate in DistriOptimizer cannot support metrics like mean average precision

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#770]
validate in DistriOptimizer cannot support metrics like MAP in object detection,
it need some global information in order to get the final map

Can we support a user defined validate method in Optimizer?

**Comment by whatbeg** [comment]
it's seem that there is no train accuracy info when training models, only loss info, but sometimes we need train acc.

**Comment by SeaOfOcean** [comment]
Optimizer will validate the model and output train accuracy when the validation trigger is met, e.g. everyEpoch

**Comment by qiuxin2012** [comment]
Override ValidationResult and ValidationMethod can support mAP.
