### ISSUE TITLE
Error: Unable to initialize main class com.intel.analytics.bigdl.ppml.kms.frontend.BigDLKMSFrontend

### ISSUE THREAD

**Issue by FFinchR** [intel-analytics/BigDL#7783]
I’m trying to install BigDL PPML services through Docker, using images below:
> docker pull intelanalytics/bigdl-attestation-service:2.2.0-SNAPSHOT
> docker pull intelanalytics/bigdl-kms:2.2.0-SNAPSHOT
> docker pull intelanalytics/kms-utils:0.3.0-SNAPSHOT
> docker pull intelanalytics/pccs:0.3.0-SNAPSHOT

Now, I have successfully installed pccs and bigdl-attestation-service, but I encountered difficulties in installing kms.
Here are my installed containers, i installed pccs on my own WSL, because this server can't connect to the internet:
![image](https://user-images.githubusercontent.com/61258341/223295763-eb93a93f-fcc7-41ed-a28a-244f376ceb05.png)

I started keywhiz container:

> [root@localhost ~]# docker logs keywhiz
> INFO  [2023-03-06 11:52:35,242] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@54780c40{/,null,AVAILABLE}
> INFO  [2023-03-06 11:52:35,248] org.eclipse.jetty.server.AbstractConnector: Started application@74b7497b{SSL, (ssl, http/1.1)}{0.0.0.0:4444}
> INFO  [2023-03-06 11:52:35,250] org.eclipse.jetty.server.AbstractConnector: Started admin@74f649a7{HTTP/1.1, (http/1.1)}{localhost:8085}
> INFO  [2023-03-06 11:52:35,250] org.eclipse.jetty.server.Server: Started @3559ms

Then I ran start-https-frontend.sh in keywhiz container, got the following error:

![image](https://user-images.githubusercontent.com/61258341/223303462-f65ebfc9-9ab7-4bc2-ad66-fb160734ccc5.png)

What caused this error?
thx.

**Comment by Uxito-Ada** [comment]
Hi @FFinchR ,

There are some clues about your issue:

1. It seems a snapshot image (and jar) is used, and some basic dependencies like sjf4j and scala are missing. I recommend to download a [stable release](https://repo1.maven.org/maven2/com/intel/analytics/bigdl/bigdl-ppml-spark_3.1.3/2.2.0/bigdl-ppml-spark_3.1.3-2.2.0-jar-with-dependencies.jar), and modify the `-cp` argument in `start-https-frontend.sh` to as below:
```
...
-cp <PATH_TO_DOWNLOAD_JAR>/bigdl-ppml-spark_3.1.3-2.2.0-jar-with-dependencies.jar
...
```
Then execute the script again and the frontend will start.

2. It is a wrong usage to run frontend process in the keywhiz backend container, although they share the same image. The architecture of BigDL-KMS can be seen [here](https://github.com/intel-analytics/BigDL/tree/main/ppml/services/bigdl-kms/kubernetes#bigdl-kms-architecture).

3. If a K8S dependency is not available in your environment, you can run you application with a [SimpleKeyManageService](https://github.com/intel-analytics/BigDL/tree/main/ppml#41-create-ppmlcontext), which does not require any infrastructure.


Hope these can help you.

**Comment by FFinchR** [comment]
Thank you for your help, I turned to eHSM deployed on K8s, which is easier for me to use.
