### ISSUE TITLE
[Random Fail]`test_checkpoint_model` No such file or directory: '/tmp/tmp1_5cj3yc/best'

### ISSUE THREAD

**Issue by hamham223** [intel-analytics/BigDL#7811]
As title, the ut `test_checkpoint_model` fails randomly due to file not found.

Failed job: https://github.com/intel-analytics/BigDL/actions/runs/4362058791/jobs/7626552200

**Comment by hkvision** [comment]
@sgwhat Please take a look.

**Comment by sgwhat** [comment]
Maybe we could modify the ut into: 
```
trainer = Estimator.from_keras(...)
trainer.fit(..., callbacks)
trainer.shutdown()

est = Estimator.from_keras(...)
est.fit(..., callbacks)
est.shutdown()
```

**Comment by hamham223** [comment]
https://github.com/intel-analytics/BigDL/actions/runs/4443221028/jobs/7800278399?pr=7895

sad... failed again
