### ISSUE TITLE
No module named bigdl.ppml when calling ehsm kms client

### ISSUE THREAD

**Issue by Uxito-Ada** [intel-analytics/BigDL#7834]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/60865256/224210083-403693e0-2fc5-4abd-8d18-6130099ac5bb.png)
It occurs in both gramine container and host.
Pls make sure correct python path is set and imported, or append the correct usage of this lib in [doc](https://github.com/intel-analytics/BigDL/tree/main/python/ppml/src/bigdl/ppml/kms/ehsm#ehsm-kms-client-api). @gc-fu

**Comment by gc-fu** [comment]
Will fix

**Comment by Uxito-Ada** [comment]
Have a look whether it has been fixed by #7830 ? @gc-fu @ShanSimu

**Comment by gc-fu** [comment]
I think it has been fixed by #7830, I will go check the documents usage

**Comment by ShanSimu** [comment]
i have test the function of generatekey. it works well
