### ISSUE TITLE
Retire env vars, System properties?

### ISSUE THREAD

**Issue by srowen** [intel-analytics/BigDL#788]
I am working on fixing calls to the deprecated `Engine.init` from tests. The only thing making it somewhat difficult is that configuration is passed around via system properties, not a config object (like the Spark config), which makes testing hard in the new code path.

More generally, there are some instances where BigDL takes input from environment vars, and some where it uses System properties, and some where it uses Spark config. I think it is generally bad practice to use env vars or System properties; just makes things difficult to test and encapsulate. At least, seems unnecessary to use env vars and properties separately.

Is any non-Spark usage actually supported? could config actually just use the Spark config object alone? that is can "local" mode go away?

It seems early enough in the project that changes like this are easy to make so wanted to raise it.

**Comment by jason-dai** [comment]
There are three sets of env variables used in BigDL:
1. MKL related, including KMP_BLOCKTIME, OMP_NUM_THREADS, etc. We need to set them properly using env variables (for both driver and executors), as these are expected by MKL.

2. "Local" mode related including "BIGDL_LOCAL_MODE" and "DL_CORE_NUMBER". These are supposed to be used for internal testing only, and shouldn't be used by the users. (Currently "DL_CORE_NUMBER" is also used when Spark running with local[*]; we can eliminate that and just use all the available cores on the local node).

3. "DL_ENGINE_TYPE". I think we should change this to a Java property.

**Comment by srowen** [comment]
Thanks @jason-dai -- yes the MKL env variables must remain of course. Internal-only env variables aren't a big deal. I was wondering whether those env variables can even go away, but that's secondary.

The issue is really using Java System properties instead of a config system. I think this causes problems eventually. Right now, it makes it hard to rewrite the tests that all call the deprecated `Engine.init` method. Updating them to use the version that takes an existing SparkConf doesn't work because the code expects certain Spark props to be set as global system properties, and won't read them from the conf. This happens to work when the app is run with spark-submit but not necessarily otherwise.

That's really the motivation for wanting to reduce or eliminate them. Maybe I can work on a prototype that narrowly addresses that problem.

**Comment by srowen** [comment]
@jason-dai as a particular example of envs though, why is `DL_ENGINE_TYPE` an env variable? seems like simple user-land config.

**Comment by jason-dai** [comment]
Yes, as mentioned above, we should change "DL_ENGINE_TYPE" to a config.

**Comment by srowen** [comment]
Sorry yeah I really meant go all the way to make it a (Spark) conf. I'll work on this one along with the others.

**Comment by srowen** [comment]
I'm going to re-propose parts of this later as a step in getting rid of calls to the deprecated Engine.init method (https://github.com/intel-analytics/BigDL/pull/814) A bit of this should go in with https://github.com/intel-analytics/BigDL/pull/827
