### ISSUE TITLE
default to user 'root' when init_nncontext with yarn-cluster and yarn-local modes

### ISSUE THREAD

**Issue by yuwgit** [intel-analytics/BigDL#7905]
I just noticed that bigdl seems to default to 'root' when init_nncontext is called with yarn-cluster and yarn-local modes. That leads to be permission errors if the actual user is not root. This does not happen when using 'local' or 'spark-submit' for init_nncontext(). 

Along with the same context, what is the proper configuration place to change application settings, such as the username, the working path, the number of executors, executor memory, driver memory, and the number of slaves used in Spark/Yarn.

**Comment by qiuxin2012** [comment]
Yes, it's really not good to use `root` as default. We will fix it.

**Comment by hkvision** [comment]
Hi @yuwgit Thanks for pointing out, we will fix it.
As a current workaround, you can specify the hadoop_user_name argument in init_orca_context to be your current user (which is default to be root...)
```
init_orca_context(..., hadoop_user_name="...")
```

**Comment by sgwhat** [comment]
You may also see [Orca Yarn Tutorial](https://bigdl.readthedocs.io/en/latest/doc/Orca/Tutorial/yarn.html#) to learn how to use `init_orca_context` as a workaround currently.
