### ISSUE TITLE
DistriOptimizer.optimize() failed silently when batchSize is not correctly set

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#792]
When batchSize is not correct, calling DistriOptimizer.optimize() will fail silently. It seems optimizer only catches and logs the optimizer but did not throw that exception to caller. [https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala#L744](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala#L744)

**Comment by yiheng** [comment]
@dding3 I think for IllegualArgumentException, we should not retry but just throw it.

**Comment by dding3** [comment]
Sure, make sense.
