### ISSUE TITLE
When trainning ResNet20 on CIFAR10 and validating the model after a epoch, loss can be negative

### ISSUE THREAD

**Issue by whatbeg** [intel-analytics/BigDL#797]
I downloaded the BigDL release 0.1.0, and modify com/intel/analytics/bigdl/models/resnet/Train.scala Line95, add validateMethod "Loss"
```
optimizer
        .setState(state)
        .setValidation(Trigger.everyEpoch,
          validateSet, Array(new Top1Accuracy[Float], new Loss[Float]))
        .setEndWhen(Trigger.maxEpoch(maxEpoch))
        .optimize()
```
and training the resnet model on cifar10, with following command:
```
dist/bin/bigdl.sh -- spark-submit \
--master yarn \
--driver-memory 6g --executor-memory 6g \
--num-executors 3 --executor-cores 8 \
--class com.intel.analytics.bigdl.models.resnet.Train \
dist/lib/bigdl-0.1.0-jar-with-dependencies.jar \
-f cifar-10/ --batchSize 480 --optnet true --depth 20 --classes 10 \
--shortcutType A --nEpochs 156 --learningRate 0.1 --cache model
```

Unfortunately, when every epoch finished and validating the model on test data(10000 pictures)，the Loss info appeared Negative values, 
like `Loss is (Loss: -5091.451, count: 336, Average Loss: -15.153129)`
so is this a bug ? or my fault on running ?

**Comment by JerryYanWan** [comment]
Please use the following command. The Loss class will use ClassNLLCriterion as a default criterion, which is not a suitable criterion for ResNet on Cifar-10.

```
optimizer
        .setState(state)
        .setValidation(Trigger.everyEpoch,
          validateSet, Array(new Top1Accuracy[Float], new Loss[Float](CrossEntropyCriterion[Float]())))
        .setEndWhen(Trigger.maxEpoch(maxEpoch))
        .optimize()
```

**Comment by whatbeg** [comment]
@JerryYanWan OK, thank you.
