### ISSUE TITLE
colab TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by Le-Zheng** [intel-analytics/BigDL#8056]
```
# import necesary libraries and modules
import argparse

from bigdl.orca import init_orca_context, stop_orca_context
from bigdl.orca import OrcaContext
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-3-193ecba601f3>](https://localhost:8080/#) in <cell line: 4>()
      2 import argparse
      3 
----> 4 from bigdl.orca import init_orca_context, stop_orca_context
      5 from bigdl.orca import OrcaContext

10 frames
[/usr/local/lib/python3.9/dist-packages/pyspark/cloudpickle.py](https://localhost:8080/#) in _make_cell_set_template_code()
    124         )
    125     else:
--> 126         return types.CodeType(
    127             co.co_argcount,
    128             co.co_kwonlyargcount,

TypeError: an integer is required (got type bytes)

**Comment by Le-Zheng** [comment]
https://colab.research.google.com/github/intel-analytics/BigDL/blob/main/python/orca/colab-notebook/quickstart/tf2_keras_lenet_mnist.ipynb#scrollTo=RDPt2XTsT-Gv

**Comment by qiuxin2012** [comment]
I have met this last week, `TypeError: an integer is required (got type bytes)` .  you can check the python version and spark version, spark 2.4.6 only support python <=3.7.
If you are using python 3.8 and above, you should update spark to 3.x

**Comment by Le-Zheng** [comment]
This issue is solved.
