### ISSUE TITLE
The default code won't compile in IDEA because of structure streaming

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#807]
The default version in BigDL is Spark 1.5. There is some spark structure streaming code. They won't compile until changing the profile to spark 2.0/2.1.

**Comment by srowen** [comment]
@yiheng I wonder if there's value in deprecating and removing support for 1.x? it'll be a little hard to maintain both going forward, because you run into lowest-common denominator problems trying to support both. 2.x has been out for a while and this project is in an early phase.

**Comment by jason-dai** [comment]
@srowen As a matter of fact, many of BigDL users are still running on Spark 1.6; I think for now Spark 1.6 and 2.1 support are still both needed for BigDL.

**Comment by yiheng** [comment]
@jason-dai should we move the structure streaming example to the analytics-zoo project?
