### ISSUE TITLE
multistep learning rate decay policy

### ISSUE THREAD

**Issue by SeaOfOcean** [intel-analytics/BigDL#817]
multistep learning rate decay policy
similar to step but it allows non uniform steps defined by stepvalue

https://github.com/BVLC/caffe/wiki/Solver-Prototxt

**Comment by SeaOfOcean** [comment]
here is a torch implementation
https://github.com/NVIDIA/DIGITS/blob/master/digits/tools/torch/LRPolicy.lua

**Comment by yiheng** [comment]
I think it should be implemented as a subclass of LearningRateSchedule https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/SGD.scala#L154
