### ISSUE TITLE
llama API fails due to import error

### ISSUE THREAD

**Issue by shane-huang** [intel-analytics/BigDL#8290]
How to replicate:

```python
from bigdl.llm.ggml.model.llama import Llama

model = Llama("model/ggml/gpt4all-model-q4_0.bin")
response=model("what is ai")
print(response)
```
It fails because of below error. We'd better add such simple tests into UTs once CI/CD is ready.

ImportError: cannot import name 'GenerationMixin' from partially initialized module 'bigdl.llm.ggml.model.generation' (most likely due to a circular import) (/home/cpx/miniconda3/envs/llm-langchain/lib/python3.9/site-packages/bigdl_llm-2.4.0.dev0-py3.9.egg/bigdl/llm/ggml/model/generation/__init__.py)

**Comment by cyita** [comment]
Will be fixed in: https://github.com/intel-analytics/BigDL/pull/8293
