### ISSUE TITLE
Failed to decrypt stream due to the wrong header parser at BigDLEncrypt::decryptStream

### ISSUE THREAD

**Issue by sixiaoming** [intel-analytics/BigDL#8309]
https://github.com/intel-analytics/BigDL/blob/main/scala/ppml/src/main/scala/com/intel/analytics/bigdl/ppml/crypto/BigDLEncrypt.scala#L282

I think it should read the whole header bytes including 400 bytes, and extract the Initialization Vector(IV) simultaneously；
like:
` val iv = read(inputStream, 400).slice(8, 24)`

**Comment by Uxito-Ada** [comment]
Hi Xiaoming，

Yep it seems 400 is the right number for the length of bytes reading, and we are going to have an exploration to fix it.

In addition, however, this potential would not harm the usability of PPMLContext and CryptoCodec, as it is a deprecated API to support big-content-bytes users handling streams directly, and the Spark ones call the another method here with 400: https://github.com/intel-analytics/BigDL/blob/main/scala/ppml/src/main/scala/com/intel/analytics/bigdl/ppml/crypto/BigDLEncrypt.scala#L139


Best

**Comment by Uxito-Ada** [comment]
Fixed in #8393
