### ISSUE TITLE
LLM: strange error when set nthreads>available cores

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#8390]
On my laptop with 8 logical cores, if I set nthreads=24, I get the following error:
![image](https://github.com/intel-analytics/BigDL/assets/21994046/9ae5d7c6-e1e1-4203-a298-11a4df2a6979)
The error message is not user-friendly and unclear.

**Comment by MeouSker77** [comment]
Fix it, now setting n_threads > core_num will automatically change n_threads to core_num

<https://github.com/intel-analytics/llm.cpp/commit/61c6847be52d7012e29b05a5dd5c7b8bf7db6477>

The binary files used by bigdl-llm need to be rebuilt again, you can try it after rebuilding.
