### ISSUE TITLE
Confusing steps in Inception examples

### ISSUE THREAD

**Issue by jzhusc** [intel-analytics/BigDL#840]
In the inception example and data preparation part, this two lines of code are confusing
```
cat classes.lst | while read CLASS_NAME; do mkdir -p ${CLASS_NAME}; done
cat img_class.lst | while read PARAM; do mv ${PARAM/ n[0-9]*/} ${PARAM/ILSVRC*JPEG /}; done
```
Since I downloaded the `ILSVRC2012_img_val .tar`, there's no two lst files mentioned above.

**Comment by yiheng** [comment]
It's at

https://github.com/intel-analytics/BigDL/blob/master/scripts/classes.lst

and

https://github.com/intel-analytics/BigDL/blob/master/scripts/img_class.lst

**Comment by yiheng** [comment]
Let me add the links to the Readme
