### ISSUE TITLE
Tensor.apply() behaves differently when the dimension of Tensor is different.

### ISSUE THREAD

**Issue by JerryYanWan** [intel-analytics/BigDL#854]
val a = Tensor(3).randn
val b = Tensor(3)

b(1).copy(a(1)) will not copy a(1) to b(1). b(1) will return a new storage.

**Comment by yiheng** [comment]
This is expected behavior. You should use b.select(...) instead.

**Comment by yiheng** [comment]
We should emphasize this in the document.
