### ISSUE TITLE
AutoTSEstimator is giving runtime error saying that ray.init called twice

### ISSUE THREAD

**Issue by Madhustat** [intel-analytics/BigDL#8606]
from bigdl.orca import init_orca_context
from bigdl.orca import OrcaContext
from bigdl.orca import init_orca_context
init_orca_context(cluster_mode="local", cores=1)

import bigdl.orca.automl.hp as hp
from bigdl.chronos.autots import AutoTSEstimator
auto_estimator = AutoTSEstimator(model='lstm', # the model name used for training
                                 search_space='normal', # a default hyper parameter search space
                                 past_seq_len=hp.randint(1, 10)) 

with the above code having below error.
_______________________________________________________
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[44], line 3
      1 import bigdl.orca.automl.hp as hp
      2 from bigdl.chronos.autots import AutoTSEstimator
----> 3 auto_estimator = AutoTSEstimator(model='lstm', # the model name used for training
      4                                  search_space='normal', # a default hyper parameter search space
      5                                  past_seq_len=hp.randint(1, 10)) 

File ~/.local/lib/python3.9/site-packages/bigdl/chronos/utils.py:93, in LazyImport.__call__(self, *args, **kwargs)
     91 module = importlib.import_module(module_name, package=self.pkg)
     92 function = getattr(module, function_name)
---> 93 return function(*args, **kwargs)

File ~/.local/lib/python3.9/site-packages/bigdl/chronos/autots/autotsestimator.py:184, in AutoTSEstimator.__init__(self, model, search_space, metric, metric_mode, loss, optimizer, past_seq_len, future_seq_len, input_feature_num, output_target_num, selected_features, backend, logs_dir, cpus_per_trial, name, remote_dir)
    170     search_space.update({"past_seq_len": past_seq_len,
    171                          "future_seq_len": future_seq_len,
    172                          "input_feature_num": input_feature_num,
   (...)
    180                          "cpus_per_trial": cpus_per_trial,
    181                          "name": name})
    183     # create auto model from name
--> 184     self.model = AutoModelFactory.create_auto_model(name=model,
    185                                                     search_space=search_space)
    187 # save selected features setting for data creator generation
    188 self.selected_features = selected_features

File ~/.local/lib/python3.9/site-packages/bigdl/chronos/autots/model/__init__.py:81, in AutoModelFactory.create_auto_model(name, search_space)
     78     invalidInputError(revised_search_space["future_seq_len"] == 1,
     79                       "future_seq_len should be set to 1 if you choose lstm model.")
     80     del revised_search_space["future_seq_len"]  # future_seq_len should always be 1
---> 81     return AutoLSTM(**revised_search_space)
     82 if name == "tcn":
     83     from .auto_tcn import AutoTCN

File ~/.local/lib/python3.9/site-packages/bigdl/chronos/autots/model/auto_lstm.py:108, in AutoLSTM.__init__(self, input_feature_num, output_target_num, past_seq_len, optimizer, loss, metric, metric_mode, hidden_dim, layer_num, lr, dropout, backend, logs_dir, cpus_per_trial, name, remote_dir)
    103     invalidInputError(False,
    104                       f"We only support keras and torch as backend,"
    105                       f" but got {self.backend}")
    106 self._model_creator = model_creator
--> 108 super().__init__()

File ~/.local/lib/python3.9/site-packages/bigdl/chronos/autots/model/base_automodel.py:42, in BaseAutomodel.__init__(self, **kwargs)
     39     self._DEFAULT_BEST_CONFIG_DIR = "best_keras_config.json"
     41 from bigdl.orca.automl.auto_estimator import AutoEstimator
---> 42 self.auto_est = AutoEstimator(model_builder, **self._auto_est_config)
     43 self.best_model = None

File ~/.local/lib/python3.9/site-packages/bigdl/orca/automl/auto_estimator.py:53, in AutoEstimator.__init__(self, model_builder, logs_dir, resources_per_trial, remote_dir, name)
     46 def __init__(self,
     47              model_builder: "ModelBuilder",
     48              logs_dir: str="/tmp/auto_estimator_logs",
     49              resources_per_trial: Optional[Dict[str, int]]=None,
     50              remote_dir: Optional[str]=None,
     51              name: Optional[str]=None) -> None:
     52     self.model_builder = model_builder
---> 53     self.searcher = SearchEngineFactory.create_engine(
     54         backend="ray",
     55         logs_dir=logs_dir,
     56         resources_per_trial=resources_per_trial,
     57         remote_dir=remote_dir,
     58         name=name)
     59     self._fitted = False
     60     self.best_trial = None

File ~/.local/lib/python3.9/site-packages/bigdl/orca/automl/search/__init__.py:25, in SearchEngineFactory.create_engine(backend, *args, **kwargs)
     23 if backend == "ray":
     24     from bigdl.orca.automl.search.ray_tune import RayTuneSearchEngine
---> 25     return RayTuneSearchEngine(*args, **kwargs)

File ~/.local/lib/python3.9/site-packages/bigdl/orca/automl/search/ray_tune/ray_tune_search_engine.py:53, in RayTuneSearchEngine.__init__(self, logs_dir, resources_per_trial, name, remote_dir)
     51 self.trials = None
     52 self.name = name
---> 53 self.remote_dir = remote_dir or RayTuneSearchEngine.get_default_remote_dir(name)
     54 self.logs_dir = os.path.abspath(os.path.expanduser(logs_dir))

File ~/.local/lib/python3.9/site-packages/bigdl/orca/automl/search/ray_tune/ray_tune_search_engine.py:60, in RayTuneSearchEngine.get_default_remote_dir(name)
     58 from bigdl.orca.ray import OrcaRayContext
     59 from bigdl.orca.automl.search.utils import process
---> 60 ray_ctx = OrcaRayContext.get()
     61 if ray_ctx.is_local:
     62     return None

File ~/.local/lib/python3.9/site-packages/bigdl/orca/ray/raycontext.py:103, in OrcaRayContext.get(cls, initialize)
    101     ray_ctx = OrcaRayContext._active_ray_context
    102     if initialize and not ray_ctx.initialized:
--> 103         ray_ctx.init()
    104     return ray_ctx
    105 else:

File ~/.local/lib/python3.9/site-packages/bigdl/orca/ray/raycontext.py:77, in OrcaRayContext.init(self, driver_cores)
     75         results = ray.init(**self.ray_args)
     76 else:
---> 77     results = self._ray_on_spark_context.init(driver_cores=driver_cores)
     78     self.num_ray_nodes = self._ray_on_spark_context.num_ray_nodes  # type: ignore
     79     self.ray_node_cpu_cores = self._ray_on_spark_context.ray_node_cpu_cores  # type: ignore

File ~/.local/lib/python3.9/site-packages/bigdl/orca/ray/ray_on_spark_context.py:593, in RayOnSparkContext.init(self, driver_cores)
    591         init_params["_redis_password"] = self.redis_password
    592     init_params.update(kwargs)
--> 593     self._address_info = ray.init(**init_params)
    594 else:
    595     self.cluster_ips = self._gather_cluster_ips()

File ~/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/.local/lib/python3.9/site-packages/ray/worker.py:856, in init(address, num_cpus, num_gpus, resources, object_store_memory, local_mode, ignore_reinit_error, include_dashboard, dashboard_host, dashboard_port, job_config, configure_logging, logging_level, logging_format, log_to_driver, namespace, runtime_env, _enable_object_reconstruction, _redis_max_memory, _plasma_directory, _node_ip_address, _driver_object_store_memory, _memory, _redis_password, _temp_dir, _metrics_export_port, _system_config, _tracing_startup_hook, **kwargs)
    854         return
    855     else:
--> 856         raise RuntimeError("Maybe you called ray.init twice by accident? "
    857                            "This error can be suppressed by passing in "
    858                            "'ignore_reinit_error=True' or by calling "
    859                            "'ray.shutdown()' prior to 'ray.init()'.")
    861 _system_config = _system_config or {}
    862 if not isinstance(_system_config, dict):

RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

**Comment by lalalapotter** [comment]
Hi @Madhustat,

We have tried to reproduce your issue, yet your example code can run normally on BigDL 2.3.0. Could you please provide more information about your BigDL version and other related environment information. Moreover, please also check if you have start a ray cluster before running the example code.

**Comment by Madhustat** [comment]
Hi This is what my code 
i tried to run the code twice 
from bigdl.orca import init_orca_context
from bigdl.orca import OrcaContext
from bigdl.orca import init_orca_context
init_orca_context(cluster_mode="local", cores=1)

from bigdl.chronos.autots.model.auto_prophet import AutoProphet
from bigdl.chronos.autots.model.auto_prophet import AutoProphet
auto_prophet = AutoProphet()
auto_prophet.fit(data=train_data,
                 cross_validation=False,
                 freq="1D")

print("Training completed.")

import bigdl.orca.automl.hp as hp
from bigdl.chronos.autots import AutoTSEstimator
auto_estimator = AutoTSEstimator(model='lstm', # the model name used for training
                                 search_space='normal', # a default hyper parameter search space
                                 past_seq_len=hp.randint(1, 10)) 

________________________________________
below is my libraries version
bigdl-chronos            2.4.0b20230721
bigdl-chronos-spark3     2.3.0
bigdl-core               2.3.0
bigdl-dllib-spark3       2.3.0
bigdl-friesian-spark3    2.3.0
bigdl-math               2.3.0
bigdl-nano               2.3.0
bigdl-orca-spark3        2.3.0
bigdl-serving            2.3.0
bigdl-spark3             2.3.0
bigdl-tf                 2.3.0

**Comment by lalalapotter** [comment]
Call `ray.shutdown()` before init orca, and resolved on user's server. Maybe environment issue.
