### ISSUE TITLE
The decryptStream method should first getHeader(inputStream) instead of read(inputStream,400).

### ISSUE THREAD

**Issue by GLei16** [intel-analytics/BigDL#8694]
protected def decryptStream(
        inputStream: DataInputStream,
        outputStream: DataOutputStream): Unit = {
    val header = read(inputStream, 400)
    verifyHeader(header)
    while (inputStream.available() != 0) {
      val decrypted = decryptPart(inputStream, byteBuffer)
      outputStream.write(decrypted)
    }
    outputStream.flush()
  }

**Comment by Uxito-Ada** [comment]
Fixed in #8764
