### ISSUE TITLE
chatglm2 Native INT4 can't print performance data

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#8704]
Chatglm2 can convert to native INT4:
>llm-convert "D:/llm-models/chatglm2-6b/" --model-format pth --model-family "chatglm" --outfile “./bigdl_chatglm2_6b_q4_0.bin"

But it didn't print performance data about 1st token latency, 2nd + Avg latency ms/token 
>llm-cli -t 20 -x chatglm -m "ggml-chatglm2-6b-q4_0.bin" -p "Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun" --no-mmap -n 32

C:\Users\BigDL-LLM\miniconda3\envs\ui_llm\lib\site-packages\bigdl\llm\libs/main-chatglm_vnni.exe -t 20 -n 32 '-m' 'ggml-chatglm2-6b-q4_0.bin' '-p' 'Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun' '--no-mmap'
. One day, she heard about a magical kingdom far, far away. The kingdom was said to be filled with talking animals, enchanted forests, and

OS: windows 11，bigdl-llm version 0807

**Comment by MeouSker77** [comment]
you can add `-v` argument to print performance data😊

**Comment by KiwiHana** [comment]
Yes, thank you
