### ISSUE TITLE
[BUG] TypeError: forward() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#8707]
refer to chatglm pybinding support https://github.com/intel-analytics/BigDL/pull/8672, but got error TypeError: forward() got an unexpected keyword argument 'stream'

bigdl-llm version 0808 or 0807

```
model = ChatGLM(model_all_local_path + "\\ggml-chatglm2-6b-q4_0.bin", use_mmap=True, n_threads=20, n_ctx=512)
for chunk in model(prompt, stream=True):
    print(chunk)
```

  File "D:\PC_LLM_UI\LLM_demo_v0.63.py", line 190, in predict
    for chunk in model(prompt, stream=True):
  File "C:\Users\BigDL-LLM\miniconda3\envs\ui_llm\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'stream'

**Comment by shane-huang** [comment]
@MeouSker77

**Comment by shane-huang** [comment]
We cannot reproduce this issue with latest version. Please make sure you have installed the latest BigDL-LLM

**Comment by MeouSker77** [comment]
This error message is a little strange, `bigdl.llm.ggml.model.chatglm.chatglm.ChatGLM` is not a subclass of `torch.nn.Module`, but the error message shows it tries to call `forward_call` of `torch.nn.Module`:
![image](https://github.com/intel-analytics/BigDL/assets/34214113/2589707d-cdd2-49f6-a170-99e1457d9323)

I guess the two `model` variables in your examples are not the same one?

**Comment by KiwiHana** [comment]
Sorry load the wrong model path, It is not a bug
