### ISSUE TITLE
Add maven artifacts for other spark platforms and use dependency only module to manage them

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#874]
BigDL support running on Spark 1.5, 1.6, 2.0 and 2.1, but only artifacts for 1.6 and 2.0 are released to maven. The artifacts for other Spark platforms are expected.

**How to distinguish artifacts for different spark platforms?**
Currently, the artifacts are distinguished by names, e.g. bigdl is for Spark 1.6 and bigdl_Spark2.0 is for Spark 2.0. We can keep using the name conversions but a better way is to use classifier.

**Comment by yiheng** [comment]
As discussed in the [mail list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/bigdl-user-group/X6D9R3TA-1E), it's better to use a bunch of dependency only module to manage the published artifacts

**Comment by srowen** [comment]
I will take a shot at making a change like this, and will open a PR to show a proposed change when it seems ready to look at.

**Comment by srowen** [comment]
https://github.com/intel-analytics/BigDL/issues/900 _might_ make this obsolete, but probably not entirely. If we could remove the per-version dependencies we wouldn't have a need for multiple modules. Anyway, it should come before.
