### ISSUE TITLE
how to get hidden layer result

### ISSUE THREAD

**Issue by JunkangNLP** [intel-analytics/BigDL#875]
I check the official document, but cannot find the solution that get hidden layer result rather than the output layer result by forward computing, can anyone help me to solve this ? thanks.

**Comment by zhichao-li** [comment]
Could you elaborate on the  ``` hidden layer reust ``` ?  
If use optimizer.optimze() for training, the intermediate result cann't be print for now, but you can add a ``` Echo()``` layer in between the layers while debugging which would tell you the gradient or weight output size. or you can use ``` forward()``` method instead for debugging.

**Comment by JunkangNLP** [comment]
thanks for reply. Here is a detail case, I have trained an Autoencoder by copying BigDL's Autoencoder, in prediction part I just want to run the encode part  or how can I get the parameters of  encode layers(remove the decode layers) to construct a new model to predict the data? thanks

**Comment by yiheng** [comment]
I think you can set the name to the layers and then use the name to locate the layers.

Build your model like this
val model = Sequential[Float]()
    model.add(new Reshape(Array(featureSize)))
    model.add(new Linear(featureSize, classNum).setName("linear1"))
    model.add(new ReLU[Float]())
    model.add(new Linear(classNum, featureSize).setName("linear1"))
    model.add(new Sigmoid[Float]())
    model

After optmize, build the predict model
val linear1 = model("linear1")
val predictModel = Sequential[Float]().add(Reshape(Array(featureSize))).add(linear1).add(ReLU[Float]())

**Comment by JunkangNLP** [comment]
Hi, @yiheng thanks for reply, But It can't work. 
I have the error com.intel.analytics.bigdl.nn.Sequential[Float] does not take parameters, I don't know how to fix it.
here is my part of codes:
 ` val NNEncoder = Encoder(dim, featureSize).setName("encoder")
    val NNDecoder = Decoder(dim, featureSize).setName("decoder")
    val NNAutoencoder = Sequential[Float]()
    NNAutoencoder.add(NNEncoder)
    NNAutoencoder.add(NNDecoder)
    val modelDecoder = modelAutoencoder("decoder").get`

**Comment by yiheng** [comment]
Oh. Looks like you use an older code. In this way, you can use the index to locate the layer.

```scala
val NNEncoder = Encoder(dim, featureSize).setName("encoder")
val NNDecoder = Decoder(dim, featureSize).setName("decoder")
val NNAutoencoder = SequentialFloat
NNAutoencoder.add(NNEncoder)
NNAutoencoder.add(NNDecoder)
val modelAutoencoder = NNAutoencoder
val modelDecoder = modelAutoencoder.modules(1)  // For "decoder"
```
