### ISSUE TITLE
Core dump for native Bloom model with 256 input token

### ISSUE THREAD

**Issue by CharleneHu94** [intel-analytics/BigDL#8762]
When using native format Bloom model with 256 input token length, core dump occurs. The issue persists for bloom model size of 1b to 7b, and for both FP16 and INT4.
Reproduce with CLI tool:
`llm-cli -t 48 -x bloom -m bigdl_llm_bloomz_1b7_q4_0.bin -f prompt_256.txt -n 32 --no-mmap`
Output:
`ggml_new_tensor_impl: not enough space in the context's memory pool (needed 3035080064, available 2935126208)
/path/to/miniconda3/envs/llm/bin/llm-cli: line 47: 2490559 Segmentation fault      (core dumped)`

**Comment by MeouSker77** [comment]
Fixed it, you can try latest code **tomorrow**: `pip install --pre --upgrade bigdl-llm[all]`

**Comment by CharleneHu94** [comment]
> Fixed it, you can try latest code **tomorrow**: `pip install --pre --upgrade bigdl-llm[all]`

Fix has been verified with latest code, issue closed.

**Comment by CharleneHu94** [comment]
Reopen this because have found performance issue for input token 256, native INT4 shows higher latency than transformer and the upstream `bloomz.cpp`. Below is the average INT4 ms/token from 2nd token on a 2s48c SPR8475B with 48 cores/threads used, output token number is 32.
| | bloomz.cpp INT4| bigdl-llm Native INT4| bigdl-llm Transformer INT4|
|-- |------------|------------------|-----------------------|
|ms/token| 24.68      | 61.91            | 41.4                  |

Reproduce with CLI tool:
` numactl -C 0-47 -m 0 llm-cli -t 48 -x bloom -m bigdl_llm_bloomz_7b_q4_0.bin -f prompts.txt -n 32 --no-mmap`
