### ISSUE TITLE
Py4JJavaError: An error occurred while calling o42.initEngine

### ISSUE THREAD

**Issue by fatenlouati** [intel-analytics/BigDL#8772]
when i run sc=init_nncontext(), this error occurs:
`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/tmp/ipykernel_9604/3818662322.py in <module>
      2 #sc = init_spark_on_local(cores=2,spark_log_level="ERROR")
      3 
----> 4 sc=init_nncontext()

~/anaconda3/envs/pysparkenv/lib/python3.10/site-packages/bigdl/dllib/nncontext.py in init_nncontext(conf, cluster_mode, spark_log_level, redirect_spark_log, **kwargs)
    538         spark_args.update(conf.getAll())
    539     if cluster_mode == "spark-submit":
--> 540         sc = init_internal_nncontext(conf, spark_log_level, redirect_spark_log)
    541     elif cluster_mode == "local":
    542         if conf:

~/anaconda3/envs/pysparkenv/lib/python3.10/site-packages/bigdl/dllib/nncontext.py in init_internal_nncontext(conf, spark_log_level, redirect_spark_log)
    669         redire_spark_logs()
    670         show_bigdl_info_logs()
--> 671     init_engine()
    672     set_python_home()
    673     return sc

~/anaconda3/envs/pysparkenv/lib/python3.10/site-packages/bigdl/dllib/utils/common.py in init_engine(bigdl_type)
    442 
    443 def init_engine(bigdl_type="float"):
--> 444     callBigDlFunc(bigdl_type, "initEngine")
    445     # Spark context is supposed to have been created when init_engine is called
    446     get_spark_context()._jvm.org.apache.spark.bigdl.api.python.BigDLSerDe.initialize()

~/anaconda3/envs/pysparkenv/lib/python3.10/site-packages/bigdl/dllib/utils/common.py in callBigDlFunc(bigdl_type, name, *args)
    632             # if the invoked method exist but something else went wrong, throw the exception
    633             if not re.match(r'.*Method.*does not exist', str(e), flags=re.DOTALL):
--> 634                 invalidOperationError(False, str(e), cause=e)
    635         else:
    636             return result

~/anaconda3/envs/pysparkenv/lib/python3.10/site-packages/bigdl/dllib/utils/log4Error.py in invalidOperationError(condition, errMsg, fixMsg, cause)
     38         outputUserMessage(errMsg, fixMsg)
     39         if cause:
---> 40             raise cause
     41         else:
     42             raise RuntimeError(errMsg)

~/anaconda3/envs/pysparkenv/lib/python3.10/site-packages/bigdl/dllib/utils/common.py in callBigDlFunc(bigdl_type, name, *args)
    627         try:
    628             api = getattr(jinvoker, name)
--> 629             result = callJavaFunc(api, *args)
    630         except Exception as e:
    631             error = e

~/anaconda3/envs/pysparkenv/lib/python3.10/site-packages/bigdl/dllib/utils/common.py in callJavaFunc(func, *args)
    681     """ Call Java Function """
    682     gateway = _get_gateway()
--> 683     result = func(*args)
    684     return _java2py(gateway, result)
    685 

/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o42.initEngine.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<init>(Engine.scala:37)
	at com.intel.analytics.bigdl.dllib.utils.MklBlas$.<clinit>(Engine.scala)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.<init>(Engine.scala:225)
	at com.intel.analytics.bigdl.dllib.utils.Engine$.<clinit>(Engine.scala)
	at com.intel.analytics.bigdl.dllib.utils.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more`

pyspark=3.0.3
python=3.10
tensorflow=2.13.0
bigdl=2.3.0

**Comment by hkvision** [comment]
Hi @fatenlouati this error is due to the version mismatch between spark version and bigdl version. BigDL 2.3.0 should depend on pyspark 3.1.3, which is a dependency actually, maybe you change your pyspark to this version?

Also, you may check if you set SPARK_HOME to another spark version (e.g. spark2).

Similar issue: https://github.com/intel-analytics/BigDL/issues/8588

Feel free to tell us if you still have this issue after using the expected spark version.

**Comment by fatenlouati** [comment]
@hkvision  thank you for your reply. I install pyspark 3.1.3 but I face this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigdl-dllib 2.3.0 requires pyspark==2.4.6, but you have pyspark 3.1.3 which is incompatible.
```

**Comment by fatenlouati** [comment]
I uninstall bigdl and reinstall it again, those versions are installed automatically 
`Successfully installed bigdl-2.3.0 bigdl-chronos-2.3.0 bigdl-core-2.3.0 bigdl-dllib-2.3.0 bigdl-friesian-2.3.0 bigdl-math-2.3.0 bigdl-nano-2.3.0 bigdl-orca-2.3.0 bigdl-serving-2.3.0 bigdl-tf-2.3.0 py4j-0.10.7 pyspark-2.4.6`
pyspark 3.1.3 is uninstalled automatically and replaced by pyspark 2.4.6. when I rerun the code  I got the first issue. and when I install pyspark 3.1.3 I got this error 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigdl-dllib 2.3.0 requires pyspark==2.4.6, but you have pyspark 3.1.3 which is incompatible
```.
I feel stuck. how to fix this problem please

**Comment by hkvision** [comment]
Hi, sorry for making not clear. If you install `bigdl` then it will by default to be built on spark 2.4.6. If you install `bigdl-spark3` then it will be default to be built on spark 3.1.3.

![image](https://github.com/intel-analytics/BigDL/assets/21994046/79b4360d-0dc3-45c3-ae90-4edbe98033d4)
Can you check what Spark and Python environment you are using? Seems you are not using the spark and python where you install bigdl and bigdl depends. Please check your spark related environment variables, particularly SPARK_HOME; you shouldn't set it as we would use pyspark instead.

**Comment by fatenlouati** [comment]
Thank you. it works now
