### ISSUE TITLE
(bigdl-llm) Determine which instruction set is being used

### ISSUE THREAD

**Issue by hueyline** [intel-analytics/BigDL#8783]
Does bigdl-llm support AMX? How can I determine which instruction set is being used by bigdl-llm?
Can I dynamically change the instruction set that is being used?

**Comment by MeouSker77** [comment]
> Does bigdl-llm support AMX?

AMX support is still in process.

> How can I determine which instruction set is being used by bigdl-llm?

It will print some system info when loading model, e.g. `system_info: n_threads = 48 / 192 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |`, corresponding instruction will be used if it is equal to 1

> Can I dynamically change the instruction set that is being used?

This is not supported yet

**Comment by hueyline** [comment]
Does bigdl-llm always use the latest available instruction set?
And when is the estimated timeline for the integration of AMX support into bigdl-llm?

**Comment by MeouSker77** [comment]
> Does bigdl-llm always use the latest available instruction set?

yes, on client, it will use AVX-VNNI, AVX2 and AVX (if possible),
on server, it will use AMX(WIP), AVX512-VNNI and AVX512 (if possible)

> And when is the estimated timeline for the integration of AMX support into bigdl-llm?

Initial AMX support for int4 will be available next week, but AMX will only be used to accelerate the first token latency with long input, it cannot speed up the generation of rest tokens

**Comment by hueyline** [comment]
Thanks for the info!
Is there any plan to extend the AMX support to other low-bit formats like int5/int8?

**Comment by MeouSker77** [comment]
> Is there any plan to extend the AMX support to other low-bit formats like int5/int8?

yes, of course

**Comment by MeouSker77** [comment]
AMX support for int4(q4_0) is ready in both native int4 and transformer int4, it will be used automatically when input token num >= 32.

You can try it with latest bigdl-llm==2.4.0b20230830, but remember for transformer int4, it cannot be used with bf16 (i.e. torch.autocast("cpu", dtype=torch.bfloat16)) together.

**Comment by hueyline** [comment]
I do not see any performance improvement with AMX (left side panel in the screenshot), and the inference time is even slower than AVX512_VNNI (right side panel in the screenshot). I assume bigdl-llm always uses the latest available instruction set. Below with my inference code.

 
![image](https://github.com/intel-analytics/BigDL/assets/97221497/e36537b4-2bfc-4836-af7e-d21b078ddc29)

 

```
import torch
import time

 

from bigdl.llm.transformers import AutoModelForCausalLM
from transformers import LlamaTokenizer
from huggingface_hub import login

 

login(token = "your_token")

 

if __name__ == '__main__':

 

    question = "What are the ethical implications of using artificial intelligence to control autonomous weapons that can identify and target individuals based on their race, religion, or other protected characteristics, and how can we mitigate these risks?"
    model_path = "meta-llama/Llama-2-7b-chat-hf"

 

    model = AutoModelForCausalLM.from_pretrained(model_path, load_in_low_bit="sym_int4", trust_remote_code=True)

 

    tokenizer = LlamaTokenizer.from_pretrained(model_path, trust_remote_code=True)

 

    with torch.inference_mode():
        input_ids = tokenizer.encode(question, return_tensors="pt")

 

        start = time.time()
        output = model.generate(input_ids, max_new_tokens=64)
        end = time.time()

 

        output_str = tokenizer.decode(output[0], skip_special_tokens=True)

 

        inference_time = end - start

 

        print(f'Inference time: {inference_time} s')
        print('-'*20, 'Output', '-'*20)
        print(output_str)
```

**Comment by MeouSker77** [comment]
Can you try it again with numactl again? i.e. `numactl -C 0-47 -m 0 python inference.py` (assume your first socket has 48 physical cores), accessing memory from multiple sockets will cause poor performance.

The performance is inaccurate without numactl

**Comment by hueyline** [comment]
Yes, I have observed a consistent Int4 performance boost of approximately 1.03x with AMX compared to AVX512_VNNI when restricting it to the physical cores of the first socket. Is it feasible to fully utilize all the system cores across both sockets to achieve even better performance? Please note that I am using SPR 8454H.

Also, there is an unusual observation is that Int8 performance significantly outperforms Int4 and Int5 when restricted to one socket (physical cores). Please see the screenshots below.

![image](https://github.com/intel-analytics/BigDL/assets/97221497/d5333575-516a-476c-aada-67775c17de19)
![image](https://github.com/intel-analytics/BigDL/assets/97221497/57751448-64d2-4725-b592-a29bf0e70080)
![image](https://github.com/intel-analytics/BigDL/assets/97221497/c9b55024-dca5-4757-b1c5-5386fb2e9abc)

**Comment by MeouSker77** [comment]
> Yes, I have observed a consistent Int4 performance boost of approximately 1.03x with AMX compared to AVX512_VNNI when restricting it to the physical cores of the first socket

1.03X performance is a litter poor, does it supports amx_int8 ? use `lscpu | grep amx_int8` to confirm it.
And I suggest you set `max_new_tokens` to 1 to see AMX acceleration more clearly, because AMX is only used to accelerate the first token. It should achieve about 1.5~2X performance compared to AVX512_VNNI, it not, there maybe some bugs.

> Is it feasible to fully utilize all the system cores across both sockets to achieve even better performance?

For LLM, memory access is the bottleneck, accessing memory from other sockets is too slow, we have no idea about how to use multiple sockets now.

> Also, there is an unusual observation is that Int8 performance significantly outperforms Int4 and Int5 when restricted to one socket (physical cores)

And I think it's a bug, as you can see in your screenshot, int8 doesn't output anything, maybe it just crashed.

**Comment by hueyline** [comment]
Yes, AMX is supported on my platform and I have made slight modifications to my inference code as below. I have noticed a potential bug where the inference time increases for subsequent questions.

![image](https://github.com/intel-analytics/BigDL/assets/97221497/f6bedd90-9ef4-4015-b224-30a9592f9b80)


```
import time
import torch
from transformers import LlamaTokenizer
from bigdl.llm.transformers import AutoModelForCausalLM

chat_history = []
model_path = "../SYM_INT4"
model = AutoModelForCausalLM.load_low_bit(model_path)
tokenizer = LlamaTokenizer.from_pretrained(model_path, trust_remote_code=True)

def format_prompt(input_str, chat_history):
    prompt = [f'<s>[instruction]\n\n']
    do_strip = False
    for history_input, history_response in chat_history:
        history_input = history_input.strip() if do_strip else history_input
        do_strip = True
        prompt.append(f'{history_input} [/instruction] {history_response.strip()} </s><s>[instruction] ')
    input_str = input_str.strip() if do_strip else input_str
    prompt.append(f'{input_str} [/instruction]')
    return ''.join(prompt)


while True:
    with torch.inference_mode():
        user_input = input("Input: ")
        if user_input == "stop":
          print("Chat with Llama-2-7B-chat-hf stopped.")
          break

        prompt = format_prompt(user_input, chat_history)
        input_ids = tokenizer.encode(prompt, return_tensors="pt")

        start = time.time()
        output_ids = model.generate(input_ids,max_new_tokens=128)
        end = time.time()

        output_str = tokenizer.decode(output_ids[0][len(input_ids[0]):], skip_special_tokens=True)
        inference_time = end - start

        print(f"\nResponse: {output_str.strip()}")

        chat_history.append((user_input, output_str))

        print(f'\nInference time: {inference_time} s')
        print('-'*150)
```

**Comment by MeouSker77** [comment]
> I have noticed a potential bug where the inference time increases for subsequent questions

This is because the input is getting longer and longer as in the subsequent questions, longer input will cause longer first token latency, each time it must recompute all the input.

For multi-turn chat like this, you can use the `past_key_values` argument to avoid recompute the older input.
