### ISSUE TITLE
Whisper int4 audio recognition does not read the full audio file

### ISSUE THREAD

**Issue by nedo99** [intel-analytics/BigDL#8793]
Hi,

I have the following issue. Audio file is 56sec long and using a whisper model as it is (without BigDL package) everything gets recognized. With BigDL whiper optimization based on [THIS ](https://github.com/intel-analytics/BigDL/tree/4ffa012a426e0d16ed13b707b03d8787ddca6aa4/python/llm/example/transformers/transformers_int4/whisper) example only half of the text is being returned.

I am using `bigdl-llm 2.4.0b20230807` python package version. This is the code:
```
#Importing Pytube library
import pytube
# Reading the Taken movie Youtube link
video = ‘https://www.youtube.com/watch?v=-LIIf7E-qFI'
data = pytube.YouTube(video)
# Converting and downloading as 'MP4' file
audio = data.streams.get_audio_only()
audio.download()
```
```
import torch
import time
import argparse

from bigdl.llm.transformers import AutoModelForSpeechSeq2Seq
from transformers import WhisperProcessor
from datasets import load_dataset
model = AutoModelForSpeechSeq2Seq.from_pretrained(model_path,
                                                      load_in_4bit=True)
model.config.forced_decoder_ids = None

    # Load processor
processor = WhisperProcessor.from_pretrained(model_path)
forced_decoder_ids = processor.get_decoder_prompt_ids(language=language, task="transcribe")
with torch.inference_mode():
    input_features = processor(audio,
                                sampling_rate=sampling_rate,
                                return_tensors="pt").input_features 
    st = time.time()
    predicted_ids = model.generate(input_features,
                        forced_decoder_ids=forced_decoder_ids)
    end = time.time()
    output_str = processor.batch_decode(predicted_ids, skip_special_tokens=True)
    print(f'Inference time: {end-st} s')
    print('-'*20, 'Output', '-'*20)
    print(output_str)
```

Is there some default limit to the audio file length?

Regards,
Nedim

**Comment by jason-dai** [comment]
@ruobing-wang please take a look

**Comment by leonardozcm** [comment]
ok, I will check this

**Comment by leonardozcm** [comment]
@nedo99 would you mind also recording how do you get `audio.mp4` converted to the format that you feed into input_features = processor(audio, ..)?

**Comment by leonardozcm** [comment]
I suppose this issue may relate to the **sample rate** of your audio file, for I have noticed the audio extract from your video is 44100Hz and whisper requires your audio is under 16000Hz:
```log
ValueError: The model corresponding to this feature extractor: WhisperFeatureExtractor was trained using a sampling rate of 16000. Please make sure that the provided `raw_speech` input was sampled with 16000 and not 44100.
```

Here is my steps that may help:
1. download full video file:
```python
import pytube

# YouTube video URL
video_url = 'https://www.youtube.com/watch?v=-LIIf7E-qFI'

# Create a YouTube object
yt = pytube.YouTube(video_url)

# Choose the stream with the desired resolution or format
# For example, to download the highest resolution stream available
video_stream = yt.streams.get_highest_resolution()

# Define the path to save the downloaded video

# Download the video
video_stream.download(filename="audio.mp4")

print("Video downloaded successfully.")
```
2. extract audio with its original sample rate:
```python
import librosa
import soundfile as sf
from moviepy.editor import VideoFileClip
import numpy as np

# Path to the downloaded video file
video_file_path = "audio.mp4"

# Load the video clip
clip = VideoFileClip(video_file_path)

# Extract the audio as a NumPy array
audio_array = clip.audio.to_soundarray()

# Convert the audio array to mono if it's stereo
if len(audio_array.shape) > 1 and audio_array.shape[1] == 2:
    audio_array = np.mean(audio_array, axis=1)

# Path to save the extracted audio
extracted_audio_path = "extracted_audio.wav"

# Save the audio array as a temporary WAV file
print(clip.fps)
sf.write(extracted_audio_path, audio_array, 44100)
```
3. Resample audio file at 16000Hz before whisper inference:
```python
import torch
import time
import argparse

from bigdl.llm.transformers import AutoModelForSpeechSeq2Seq
from transformers import WhisperProcessor
from datasets import load_dataset

import soundfile as sf
import librosa

# Path to the .wav audio file
audio_file_path = "extracted_audio.wav"

# Load the audio using soundfile
# audio, sample_rate = sf.read(audio_file_path)
# print(audio, sample_rate)

# Load the input audio
y, sr = librosa.load(audio_file_path, sr=None)

# Downsample the audio to 16kHz
target_sr = 16000
audio = librosa.resample(y,
                         orig_sr=sr,
                         target_sr=target_sr)


model_path = "./whisper-tiny"

model = AutoModelForSpeechSeq2Seq.from_pretrained(model_path,
                                                      load_in_4bit=True)
model.config.forced_decoder_ids = None

    # Load processor
processor = WhisperProcessor.from_pretrained(model_path)
forced_decoder_ids = processor.get_decoder_prompt_ids(language="english", task="transcribe")
with torch.inference_mode():
    input_features = processor(audio,
                                sampling_rate=16000,
                                return_tensors="pt").input_features 
    st = time.time()
    predicted_ids = model.generate(input_features,
                        forced_decoder_ids=forced_decoder_ids)
    end = time.time()
    output_str = processor.batch_decode(predicted_ids, skip_special_tokens=True)
    print(f'Inference time: {end-st} s')
    print('-'*20, 'Output', '-'*20)
    print(output_str)
```

And here is how it looks like:
```log
(changmin-llm) [root@spr01 changmin]# python recognizer.py 
Inference time: 0.3899717330932617 s
-------------------- Output --------------------
[" I don't know who you are I don't know what you want If you're looking for ransom I can tell you I don't know money but what I do have I're a very particular set of skills skills I have acquired a very long career skills that make me a nightmare for people like you"]
```
@nedo99 Pls take a look?

**Comment by leonardozcm** [comment]
> I have the following issue. Audio file is 56sec long and using a whisper model as it is (without BigDL package) everything gets recognized.

**I can't repeat this with the knows now.**
I repeat this experiments without bigdl-llm and resampling,  and specify sampling_rate=16000/44100 to read this audio(original sample rate 44100), and here is what I get:
```python
    input_features = processor(audio,
                                sampling_rate=16000, # 44100
                                return_tensors="pt").input_features
```
1. For sampling rate at 16000, I think WhisperProcessor will `listen` this audio as about 3 times slower as we heard, so it can only recognize an `I`, is this what you get in your case? :
```log
(changmin-llm) [root@spr01 changmin]# python recognizer.py 
Inference time: 0.32364845275878906 s
-------------------- Output --------------------
[' I']
```
2.  For sampling rate at 44100, the whisper model fails as we expect:
```log
ValueError: The model corresponding to this feature extractor: WhisperFeatureExtractor was trained using a sampling rate of 16000. Please make sure that the provided `raw_speech` input was sampled with 16000 and not 44100.
```

@nedo99  Would you mind provide us more information like follows, so that we can better catch up with your problem here:
1. how do you process your audio data from download to feed in whisper?
2. what is your sample rate here `input_features = processor(audio, sampling_rate=16000,`  ?

Thanks,
Changmin

**Comment by nedo99** [comment]
> ```
> (changmin-llm) [root@spr01 changmin]# python recognizer.py 
> Inference time: 0.3899717330932617 s
> -------------------- Output --------------------
> [" I don't know who you are I don't know what you want If you're looking for ransom I can tell you I don't know money but what I do have I're a very particular set of skills skills I have acquired a very long career skills that make me a nightmare for people like you"]
> ```
> 
> @nedo99 Pls take a look?

You still have the issue :)
The full text in the example is:
```
I don't know who you are. I don't know what you want. If you are looking for ransom, I can tell you I don't have money. But what I do have are a very particular set of skills. Skills I have acquired over a very long career. Skills that make me a nightmare for people like you. If you let my daughter go now, that'll be the end of it. I will not look for you. I will not pursue you. But if you don't, I will look for you. I will find you. And I will kill you. Good luck.
```

What you got and what I get is only a bit more than half:
```
I don't know who you are I don't know what you want If you're looking for ransom I can tell you I don't know money but what I do have I're a very particular set of skills skills I have acquired a very long career skills that make me a nightmare for people like you
```

So this part is missing with BigDL package:
```
If you let my daughter go now, that'll be the end of it. I will not look for you. I will not pursue you. But if you don't, I will look for you. I will find you. And I will kill you. Good luck.
```

It seems like the data analyzed are only up to cca 30sec of the audio file.

I load the file in 16000 sample rate so that should not be an issue `audio, sampling_rate = librosa.load(path='liam_audio.wav', sr=16000)`

**Comment by leonardozcm** [comment]
> > ```
> > (changmin-llm) [root@spr01 changmin]# python recognizer.py 
> > Inference time: 0.3899717330932617 s
> > -------------------- Output --------------------
> > [" I don't know who you are I don't know what you want If you're looking for ransom I can tell you I don't know money but what I do have I're a very particular set of skills skills I have acquired a very long career skills that make me a nightmare for people like you"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @nedo99 Pls take a look?
> 
> You still have the issue :) The full text in the example is:
> 
> ```
> I don't know who you are. I don't know what you want. If you are looking for ransom, I can tell you I don't have money. But what I do have are a very particular set of skills. Skills I have acquired over a very long career. Skills that make me a nightmare for people like you. If you let my daughter go now, that'll be the end of it. I will not look for you. I will not pursue you. But if you don't, I will look for you. I will find you. And I will kill you. Good luck.
> ```
> 
> What you got and what I get is only a bit more than half:
 
> It seems like the data analyzed are only up to cca 30sec of the audio file.
> 
> I load the file in 16000 sample rate so that should not be an issue `audio, sampling_rate = librosa.load(path='liam_audio.wav', sr=16000)`

Ok, now I see. Any progress I will update here.

**Comment by leonardozcm** [comment]
I repeat your result again w/ and w/o bigdl, they both cut-off the length of audio into 30s.
**Actually this is the limitation of whisper itself instead of bigdl-llm**, whisper is designed to only[ access 30s of audio content](https://github.com/openai/whisper/discussions/1118#discussioncomment-5362741) :
>Too short, and you'd lack surrounding context. You'd cut sentences more often.  A lot of sentences would cease to make sense.
>  Too long, and you'll need larger and larger models to contain the complexity of the meaning you want the model to keep track of.

If you do want a long-form transcription, you may need to cut off your audio into pieces up to 30s, fed them one by one or group them a batch. Here is solution utilizing [`transformers.pipe` API](https://huggingface.co/openai/whisper-large#long-form-transcription) to help achieve this batch inference process:
```python
import torch
import time
from transformers import WhisperProcessor
from datasets import load_dataset
from transformers import pipeline

import soundfile as sf
import librosa

# Path to the .wav audio file
audio_file_path = "extracted_audio.wav"

# Load the input audio
y, sr = librosa.load(audio_file_path, sr=None)

# Downsample the audio to 16kHz
target_sr = 16000
audio = librosa.resample(y,
                         orig_sr=sr,
                         target_sr=target_sr)

model_path = "./whisper-medium" # tiny may not reach a good result here

# from transformers import AutoModelForSpeechSeq2Seq
# model = AutoModelForSpeechSeq2Seq.from_pretrained(model_path)

from bigdl.llm.transformers import AutoModelForSpeechSeq2Seq
model = AutoModelForSpeechSeq2Seq.from_pretrained(model_path, load_in_4bit=True)

model.config.forced_decoder_ids = None

processor = WhisperProcessor.from_pretrained(model_path)
forced_decoder_ids = processor.get_decoder_prompt_ids(language="english", task="transcribe")

from transformers.models.whisper import WhisperFeatureExtractor, WhisperTokenizer

pipe = pipeline(
  "automatic-speech-recognition",
  model=model,
  feature_extractor= WhisperFeatureExtractor.from_pretrained(model_path),
  tokenizer= WhisperTokenizer.from_pretrained(model_path, language="english"),
  chunk_length_s=30,
)

prediction = pipe(audio, batch_size=8)["text"]
print(prediction)
```
here is the output:
```log
(changmin-llm) [root@spr01 changmin]# python recognizer.py 
 I don't know who you are. I don't know what you want. If you're looking for ransom, I can tell you I don't have money. But what I do have are a very particular set of skills. Skills I have acquired over a very long career. Skills that make me a nightmare for people like you. If you let my daughter go now, that'll be the end of it. I will not look for you. I will not pursue you. But if you don't, I will look for you. I will find you. And I will kill you. Good luck.
```
@nedo99

**Comment by nedo99** [comment]
That is odd. If you would use whisper as it is it will do. The post you pasted is from March this year, maybe they changed it.

If you install openai.whisper package and do:
```
model = whisper.load_model('tiny')
text = model.transcribe("liam_audio.wav")
```

You will get the full version.

Whisper version:
Name: openai-whisper
Version: 20230314

**Comment by leonardozcm** [comment]
Thanks for the note, I will take a look at openai's API and see what difference between it and huggingface.
As far as I known, **both huggingface api and bigdl-llm api** can not break the limitation of 30s audio.
To clarify, did your whisper with **huggingface API** can take audio longer than 30s as the input?

**Comment by leonardozcm** [comment]
For openai-whisper, they don't feed the whole audio at once either, instead they break audio into pieces and do inference. See the logits here [decode_with_fallback](https://github.com/openai/whisper/blob/main/whisper/transcribe.py#L147) decode one segment of audio, and in the [loop](https://github.com/openai/whisper/blob/main/whisper/transcribe.py#L226-L234) they decode pieces one by one. By a slight change of your code you  can view this pipeline:
```python
result = model.transcribe("extracted_audio.wav", verbose=True, language="English")
```
here is my output:
```python
[00:00.000 --> 00:13.640]  I don't know who you are.
[00:13.640 --> 00:15.980]  I don't know what you want.
[00:15.980 --> 00:20.080]  If you are looking for ransom, I can tell you I don't have money.
[00:20.080 --> 00:25.040]  But what I do have are a very particular set of skills.
[00:25.040 --> 00:27.960]  Skills I have acquired over a very long career.
[00:28.000 --> 00:32.000]  Skills that make me a nightmare for people like you.
[00:32.000 --> 00:36.000]  If you let my daughter go now, that will be the end of it.
[00:36.000 --> 00:40.000]  I will not look for you. I will not pursue you.
[00:40.000 --> 00:44.000]  But if you don't, I will look for you.
[00:44.000 --> 00:48.000]  I will find you. And I will kill you.
[00:52.000 --> 00:54.000]  Good luck.
 I don't know who you are. I don't know what you want. If you are looking for ransom, I can tell you I don't have money. But what I do have are a very particular set of skills. Skills I have acquired over a very long career. Skills that make me a nightmare for people like you. If you let my daughter go now, that will be the end of it. I will not look for you. I will not pursue you. But if you don't, I will look for you. I will find you. And I will kill you. Good luck.
```

**Comment by nedo99** [comment]
Got it. If that is the case, will close the issue. The only thing is that I tested with the official openai whisper python version mentioned above and then with the one from BiGDL and noticed. I just thought it was an issue in the code, but since it is a limitation of the model, then it is fine. Maybe in the future just to add a note, if input audio is longer than 30sec give a warning or something that only 30secs will be decoded.

**Comment by jason-dai** [comment]
I think we may update the whisper example to use the transformer pipeline API to support long segment? @leonardozcm
