### ISSUE TITLE
LLM fine-tuning demo validation on TEE

### ISSUE THREAD

**Issue by holmastoo** [intel-analytics/BigDL#8824]
Hi, I see there is only LLM serving demo, is there any guides to fine-tuning demos?

**Comment by Uxito-Ada** [comment]
Hi holmastoo, we are working in progress on TDX fine-tuning of Llama 7b in #8775 .

**Comment by Uxito-Ada** [comment]
Hi holmastoo, we have released fine-tuning on TDX now: https://github.com/intel-analytics/BigDL/tree/main/docker/llm/finetune/lora#to-run-in-tdx-coco-and-enable-remote-attestation-api
