### ISSUE TITLE
private spark libs authorization issue

### ISSUE THREAD

**Issue by antchainmappic** [intel-analytics/BigDL#8831]
please slove private spark libs authorization issue about building docker image to ensure mappic safety review success.

**Comment by qiyuangong** [comment]
Hi @antchainmappic 
Apache Spark is open-sourced under Apache 2.0 license. That private Spark repo in PPML dockerfile is a patched Spark for SGX LibOS.

Due to legal, IP and code quality concerns, we can provide these patches under legal agreements. 

We can discuss this offline. :)
