### ISSUE TITLE
Question: Any performance loss converting gptq models to ggml format?

### ISSUE THREAD

**Issue by itechbear** [intel-analytics/BigDL#8880]
Hi authors,

Great work for running LLMs on cpu devices!

I have some knowledge about model quantization and know that it would hurt performance a little bit. Also I know that llama.cpp uses different quantization methods from gptq. However, with biglm-llm, I'm wondering **which of the two methods would produce a better 4-bit llama model, therotically.**

1. converting the original f32/f16 model to native(ggml) int4 model
2. converting the `GPTQ` version of the model to native(ggml) int 4model

Would love to get your feedback. Thank you!

**Comment by hkvision** [comment]
Hi @itechbear 

From our test result (maybe the test is not thorough), we observe that for llama-7b, gptq has little accuracy improvement against native ggml quantization.
But for llama-13b(vicuna) model, we observe that the accuracy improvement of gptq is obvious and the accuracy result against several benchmark tasks (including PIQA, WinoGrande) is almost close to the bf16 result.

Hope the above information from our side helps you!

**Comment by hkvision** [comment]
Hi @itechbear 
You are right, convert_gptq2ggml only converts gptq models to ggml format, and there is no accuracy loss in this step. I suppose the accuracy difference is from the quantize method (gptq vs ggml native) itself. Seems in the gptq paper, it also says gptq will have more benefit for larger models.
