### ISSUE TITLE
Langchain vulnerable to arbitrary code execution via the evaluate function in the numexpr library

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/BigDL#8885]
An issue in LanChain-ai Langchain v.0.0.245 allows a remote attacker to execute arbitrary code via the evaluate function in the numexpr library.

[ppml/tdx/docker/trusted-bigdl-llm/requirements.txt](https://github.com/intel-analytics/BigDL/blob/-/ppml/tdx/docker/trusted-bigdl-llm/requirements.txt)

**Comment by liu-shaojun** [comment]
fixed in https://github.com/intel-analytics/BigDL/pull/8887
