### ISSUE TITLE
Authenticated Local Privilege Escalation vulnerability in Intel Optimization for Tensorflow

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/BigDL#8886]
Improper buffer restrictions in the Intel(R) Optimization for Tensorflow software before version 2.12 may allow an authenticated user to potentially enable escalation of privilege via local access.

https://github.com/intel-analytics/BigDL/blob/main/python/requirements/nano/requirements_tensorflow.txt

**Comment by MeouSker77** [comment]
It's a hard work to upgrade intel-tensorflow to 2.12.

intel-tensorflow 2.12 requires protobuf >= 3.20.3, while onnx 1.12 requires protobuf < 3.20.1, we must also upgrade onnx to 1.13, which requires protobuf >= 3.20.2.

But another question is now pytorch and tensorflow use a common installation option `inference`(i.e. `bgidl-nano[inference]`) to install onnx, so pytorch and tensorflow are using the same onnx, but pytorch-lightning 1.6.4 requires protobuf <= 3.19.5, it is conflict with onnx 1.13's protobuf >= 3.20.2. To solve it, we have to upgrade pytorch-lightning or let pytorch and tensorflow use differenct onnx version.

If we want to let pytorch and tensorflow use different onnx, we must change our intallation options, it may be a breaking change.

And upgrading onnx to 1.13.1 and upgrading pytorch-lightning are also hard work.
