### ISSUE TITLE
1. I have a raw data file a.orc in orc format. I want to read it through spark/hadoop and calculate it with other files to generate b (spark.dataframe). b wants to encrypt and store it as b.orc. b.orc can be decrypted into plaintext again later. I personally have two ideas: 1. Perform aces encrypt on each column of b read by a.orc, and then store 2. For b (spark.dataframe), the file can be stored as c.encrypt.orc by a certain method, and this format can perform encryption and decryption similar to orc I don’t know if you have similar functions or materials for reference, thank you very much

### ISSUE THREAD

**Issue by Tringname** [intel-analytics/BigDL#8888]

**Comment by Uxito-Ada** [comment]
Hi, PPMLContext is able to [read or write dataFrames with crypto](https://github.com/intel-analytics/BigDL/tree/main/ppml#42-read-and-write-files), which supports CSV/JSON/TextFile/Parquet and four kinds of crypto mode. It works with [key management](https://github.com/intel-analytics/BigDL/tree/main/ppml#41-create-ppmlcontext) that allows a user to specify his data key in multiple ways.

You can read orc into memory first, and save ciphertext dataFrames in the above available formats with the write API of PPMLContext. After that, the ciphertext files saved can be decrypted into memory in plaintext again, by calling PPMLContext's read API.

**Comment by Uxito-Ada** [comment]
I will close this issue if no any other update

**Comment by Tringname** [comment]
Maybe it is a way to solve this problem throughout “You can read orc into memory first, and save ciphertext dataFrames in the above available formats with the write API of PPMLContext. ”，But this is not a good way,it will waste more time and space,and we can not save the encrypted dataframe to a new encrypted orc file. ---- Replied Message ----FromHeyang ***@***.***>Date09/15/2023 15:13 ***@***.***> ***@***.***>***@***.***>SubjectRe: [intel-analytics/BigDL] 1. I have a raw data file a.orc in orc format. I want to read it through spark/hadoop and calculate it with other files to generate b (spark.dataframe). b wants to encrypt and store it as b.orc. b.orc can be decrypted into plaintext again later. I personally have two ideas: 1. Perform aces encrypt on each column of b read by a.orc, and then store 2. For b (spark.dataframe), the file can be stored as c.encrypt.orc by a certain method, and this format can perform encryption and decryption similar to orc I don’t know if you have similar functions or materials for reference, thank you very much (Issue #8888)
I will close this issue if no any other update

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/intel-analytics/BigDL/issues/8888#issuecomment-1720790063",
"url": "https://github.com/intel-analytics/BigDL/issues/8888#issuecomment-1720790063",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Uxito-Ada** [comment]
@Tringname hi, sorry for a late reply. I do not get your point, could pls provide a case to illustrate what you want to achieve?
