### ISSUE TITLE
WARNING: bigdl-llm 2.4.0b20230809 does not provide the extra 'xpu'

### ISSUE THREAD

**Issue by azhuvath** [intel-analytics/BigDL#8949]
I am seeing this warning when I create a conda environment. Not remember seeing it before. Added to that it is missing accelerate and sentencepiece libraries which needs to be additionally installed.

conda create -n llm python=3.9
conda activate llm

pip install --pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu

**Comment by jason-dai** [comment]
The warning message seems to be `WARNING: bigdl-llm 2.4.0b20230809 does not provide the extra 'xpu'`

**Comment by rnwang04** [comment]
Hi @azhuvath , I have tried to reproduce your installation commands:
```bash
conda create -n llm python=3.9
conda activate llm
pip install --pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu
```
I don't see the warnings, and accelerate & sentencepiece libraries are installed, here is my log:
```bash
Installing collected packages: tokenizers, sentencepiece, safetensors, py-cpuinfo, mpmath, bigdl-llm, bigdl-core-xe, urllib3, typing-extensions, tqdm, tabulate, sympy, regex, pyyaml, psutil, protobuf, pillow, packaging, numpy, networkx, MarkupSafe, idna, fsspec, charset-normalizer, certifi, requests, jinja2, intel-extension-for-pytorch, filelock, torch, huggingface-hub, transformers, torchvision, accelerate
Successfully installed MarkupSafe-2.1.3 accelerate-0.22.0 bigdl-core-xe-2.4.0b20230911 bigdl-llm-2.4.0b20230911 certifi-2023.7.22 charset-normalizer-3.2.0 filelock-3.12.3 fsspec-2023.9.0 huggingface-hub-0.17.1 idna-3.4 intel-extension-for-pytorch-2.0.110+xpu jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.26.0rc1 packaging-23.1 pillow-10.0.0 protobuf-4.24.3 psutil-5.9.5 py-cpuinfo-9.0.0 pyyaml-6.0.1 regex-2023.8.8 requests-2.31.0 safetensors-0.3.3 sentencepiece-0.1.99 sympy-1.12 tabulate-0.9.0 tokenizers-0.13.4rc3 torch-2.0.1a0+cxx11.abi torchvision-0.15.2a0+cxx11.abi tqdm-4.66.1 transformers-4.31.0 typing-extensions-4.8.0rc1 urllib3-2.0.4
```
By the way, the warning doesn't matter at all as the extra 'xpu' option is provided from bigdl-llm 2.4.0b20230810. When you install the nightly release version, you can just ignore this warning.

**Comment by azhuvath** [comment]
> Hi @azhuvath , I have tried to reproduce your installation commands:
> 
> ```shell
> conda create -n llm python=3.9
> conda activate llm
> pip install --pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu
> ```
> 
> I don't see the warnings, and accelerate & sentencepiece libraries are installed, here is my log:
> 
> ```shell
> Installing collected packages: tokenizers, sentencepiece, safetensors, py-cpuinfo, mpmath, bigdl-llm, bigdl-core-xe, urllib3, typing-extensions, tqdm, tabulate, sympy, regex, pyyaml, psutil, protobuf, pillow, packaging, numpy, networkx, MarkupSafe, idna, fsspec, charset-normalizer, certifi, requests, jinja2, intel-extension-for-pytorch, filelock, torch, huggingface-hub, transformers, torchvision, accelerate
> Successfully installed MarkupSafe-2.1.3 accelerate-0.22.0 bigdl-core-xe-2.4.0b20230911 bigdl-llm-2.4.0b20230911 certifi-2023.7.22 charset-normalizer-3.2.0 filelock-3.12.3 fsspec-2023.9.0 huggingface-hub-0.17.1 idna-3.4 intel-extension-for-pytorch-2.0.110+xpu jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.26.0rc1 packaging-23.1 pillow-10.0.0 protobuf-4.24.3 psutil-5.9.5 py-cpuinfo-9.0.0 pyyaml-6.0.1 regex-2023.8.8 requests-2.31.0 safetensors-0.3.3 sentencepiece-0.1.99 sympy-1.12 tabulate-0.9.0 tokenizers-0.13.4rc3 torch-2.0.1a0+cxx11.abi torchvision-0.15.2a0+cxx11.abi tqdm-4.66.1 transformers-4.31.0 typing-extensions-4.8.0rc1 urllib3-2.0.4
> ```
> 
> By the way, the warning doesn't matter at all as the extra 'xpu' option is provided from bigdl-llm 2.4.0b20230810. When you install the nightly release version, you can just ignore this warning.

The machine I had has a landing node and the file system is mounted onto it. The conda environment was created in the mounted file system as opposed to the landing node. Need to see if that is the real issue. Bare meatal might be fine.

**Comment by sheikmohdimran** [comment]
pip might be loaded from the default python installation. Try replacing "pip install" with "python -m pip install"

**Comment by azhuvath** [comment]
I am closing this issue since it doesn't happen always. I tried in bare metal system, and it works fine. Will reopen it once I am able to understand the behavior better.
