### ISSUE TITLE
whisper-medium take 2.28GB peak sysytem memory when loading transformer INT4 model. 

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#8966]
whisper-medium take 2.28GB peak sysytem memory when loading transformer INT4 model. 
whisper-medium transformer INT4 model size is 499MB.

```
from transformers import WhisperProcessor
import torch
import time
import intel_extension_for_pytorch as ipex
from gpu_benchmark_util import BenchmarkWrapper
from bigdl.llm.transformers import AutoModelForSpeechSeq2Seq
from datasets import load_dataset, load_from_disk

model_path = "/home/a770/llm/whisper-medium-int4/"
dataset_path = "hf-internal-testing/librispeech_asr_dummy"

# load model and processor
ds = load_dataset(dataset_path, "clean", split="validation")
print("pass")
processor = WhisperProcessor.from_pretrained(model_path)
# load dummy dataset and read audio files
sample = ds[0]["audio"]
# for transformer == 4.30.2
input_features = processor(sample["array"], sampling_rate=sample["sampling_rate"], return_tensors="pt").input_features

input_features = input_features.half().contiguous().to('xpu')
print(input_features.shape)
print(input_features.is_contiguous())

# generate token ids
#whisper =  AutoModelForSpeechSeq2Seq.from_pretrained(model_path, load_in_4bit=True, optimize_model=False)
whisper =  AutoModelForSpeechSeq2Seq.load_low_bit(model_path, trust_remote_code=True, optimize_model=False)
whisper.config.forced_decoder_ids = None
whisper = whisper.half().to('xpu')
whisper = BenchmarkWrapper(whisper)

with torch.inference_mode():
    for i in range(10):
        torch.xpu.synchronize()
        st = time.time()
        predicted_ids = whisper.generate(input_features)
        # print(len(predicted_ids[0]))
        torch.xpu.synchronize()
        end = time.time()
        output_str = processor.batch_decode(predicted_ids, skip_special_tokens=True)
        print(f'Inference time: {end-st} s')
        print('-'*20, 'Output', '-'*20)
        print(output_str)

```

**Comment by leonardozcm** [comment]
I'm using fine-grained memory footprint tracking to monitor the memory consumption during the loading process, and I haven't been able to reproduce the peak memory usage of 2.28GB.
```log
--------------------Before load low bit--------------------

Used: 9088.54 MB
tied true 1
--------------------before load state dict--------------------

Used: 9102.50 MB
--------------------after load state dict--------------------

Used: 9699.05 MB
--------------------when loading state to model--------------------

Used: 9699.05 MB
--------------------when loading state to model--------------------

Used: 9699.05 MB

....
Used: 9700.28 MB
--------------------when loading state to model--------------------

Used: 9700.28 MB
--------------------when loading state to model--------------------

Used: 9700.28 MB
--------------------when loading state to model--------------------

Used: 9700.28 MB
--------------------after _load_pretrained_model--------------------

Used: 9770.12 MB
tied true 1
--------------------after tied--------------------

Used: 9770.12 MB
--------------------After load low bit--------------------

Used: 9770.12 MB

```
take ~680MB memory to load whisper medium int4. Library version:
```log
Name: bigdl-llm
Version: 2.4.0.dev0

Name: transformers
Version: 4.31.0

Name: accelerate
Version: 0.21.0
```

**Comment by KiwiHana** [comment]
You can use $htop

**Comment by leonardozcm** [comment]
hi @KiwiHana , thanks for your suggestion.

The default sampling rate of `htop` is one sample per second. Choosing an inappropriate sampling rate for htop may result in missing the sampling of peak memory usage, and memory footprint might be a more reasonable way to measure.

I reduced the htop sampling rate to 0.01 seconds, and below is the memory usage during my load. The peak memory usage still did not exceed 1GB. Considering the additional overhead of the inference process, it is possible to exceed 1GB. Have you accounted for the memory overhead of the inference process?
![memory_usage_plot](https://github.com/intel-analytics/BigDL/assets/26900100/7fd6261c-4916-4bd3-abd2-48ce66efbdf0)

May you send me the output file with the command line following for a raw memory usage sampling?
```shell
top -d 0.01 -b | grep "MiB Mem" > test.log
```
also here is the code to be sampled:
```python
from bigdl.llm.transformers import AutoModelForSpeechSeq2Seq

save_dir = `path/to/whisper-int4-model`
whisper =  AutoModelForSpeechSeq2Seq.load_low_bit(save_dir, optimize_model=False, trust_remote_code=True)
```

**Comment by KiwiHana** [comment]
![memory_usage_plot](https://github.com/intel-analytics/BigDL/assets/102839943/ef015276-6c2e-4659-ac34-ec8ec110337f)

**Comment by leonardozcm** [comment]
what version of bigdl-llm/transformers/accelerate are you using, would you mind show me your output of :
```shell
pip show bigdl-llm transformers accelerate
```

**Comment by KiwiHana** [comment]
Name: bigdl-llm
Version: 2.4.0b20230827
Summary: Large Language Model Develop Toolkit
Home-page: https://github.com/intel-analytics/BigDL
Author: BigDL Authors
Author-email: bigdl-user-group@googlegroups.com
License: Apache License, Version 2.0
Location: /home/a770/miniconda3/envs/llm-arc/lib/python3.9/site-packages
Requires:
Required-by:
---
Name: transformers
Version: 4.31.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/a770/miniconda3/envs/llm-arc/lib/python3.9/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by:
---
Name: accelerate
Version: 0.22.0
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: sylvain@huggingface.co
License: Apache
Location: /home/a770/miniconda3/envs/llm-arc/lib/python3.9/site-packages
Requires: numpy, packaging, psutil, pyyaml, torch
Required-by:

**Comment by leonardozcm** [comment]
Fixed with fresh bigdl-llm build(>2.4.0b20230901)

**Comment by KiwiHana** [comment]
bigdl 0913

![memory_usage_plot](https://github.com/intel-analytics/BigDL/assets/102839943/1afea883-d8ae-4c56-9928-e49788a8ff25)

**Comment by KiwiHana** [comment]
```
#whisper =  AutoModelForSpeechSeq2Seq.from_pretrained(model_path, load_in_4bit=True, optimize_model=False)
whisper =  AutoModelForSpeechSeq2Seq.load_low_bit(model_path, trust_remote_code=True, optimize_model=False,tie_word_embeddings=False)
#whisper.save_low_bit(model_path + "-int4-0913/")
#processor.save_pretrained(model_path + "-int4-0913/")
```
