### ISSUE TITLE
Building container using kaniko is skipping pip install--pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu

### ISSUE THREAD

**Issue by azhuvath** [intel-analytics/BigDL#8979]
Building container using kaniko is skipping pip install--pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu

This leads to required packages not getting installed in the path. On further investigation we are seeing the below error.

Could not fetch URL https://developer.intel.com/ipex-whl-stable-xpu: 403 Client Error: Forbidden for url: https://corpredirect.intel.com/Redirector/404Redirector.aspx?404;https://developer.intel.com/ipex-whl-stable-xpu - skipping

Some debugging lead to the additional details.

Request URL:
http://ec2-52-27-27-201.us-west-2.compute.amazonaws.com/ipex-release.php?device=xpu&repo=us&release=stable
Referrer Policy:
strict-origin-when-cross-origin

**Comment by glorysdj** [comment]
It seems that there is some network issue in your building env, could you please try to curl the url (https://developer.intel.com/ipex-whl-stable-xpu) to check if your env is ok, please run the curl in your container/pod or run it as a command in the Dockerfile.
Could you please share the Dockerfile, we will try to reproduce this? You can also try to build the image with Docker instead of kaniko.

**Comment by azhuvath** [comment]
The machine has access to internet. So, it doesn't look like network access issue. If the machine in which the build is happening has a host by name xyz as opposed to xyz.intel.com, I think this issue happens.

Not sure if anyone has tried pip install--pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu from an outside machine.

This is probably related to the warning I was seeing earlier.
WARNING: bigdl-llm 2.4.0b20230809 does not provide the extra 'xpu'
https://github.com/intel-analytics/BigDL/issues/8949

**Comment by rnwang04** [comment]
> Not sure if anyone has tried pip install--pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu from an outside machine.
> 

I tried on my outside machine, and I feel https://developer.intel.com/ipex-whl-stable-xpu can be accessed.

**Comment by glorysdj** [comment]
> The machine has access to internet. So, it doesn't look like network access issue. If the machine in which the build is happening has a host by name xyz as opposed to xyz.intel.com, I think this issue happens.
> 
> Not sure if anyone has tried pip install--pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu from an outside machine.
> 
> This is probably related to the warning I was seeing earlier. WARNING: bigdl-llm 2.4.0b20230809 does not provide the extra 'xpu' #8949

I tried on my outside machine in which hostname is xyz but without .intel.com, pip install--pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu can be successfully installed.
Please make sure your OS is Linux or Windows. Please try to curl the URL(https://developer.intel.com/ipex-whl-stable-xpu) to check if your env is blocked by the EC2 server(ec2-52-27-27-201.us-west-2.compute.amazonaws.com) which may cause 403 Client Error: Forbidden for url.

**Comment by avinash-palleti** [comment]
@glorysdj  
Yes it is blocked by EC2 server, possible reasons to get blocked is listed here, https://repost.aws/knowledge-center/api-gateway-troubleshoot-403-forbidden

But not sure which one among these could be our issue and what is the expectation from AWS EC2 side. 
Anyone has contact from the team who hosted these whl packages on AWS EC2

**Comment by rnwang04** [comment]
> Anyone has contact from the team who hosted these whl packages on AWS EC2

ipex team hosted these whl packages, and you may report this issue to them(https://github.com/intel/intel-extension-for-pytorch/issues)

**Comment by azhuvath** [comment]
Opened an issue with IPEX team. Closing it here.
https://github.com/intel/intel-extension-for-pytorch/issues/432
