### ISSUE TITLE
Error: Failed to load the llama dynamic library. Segmentation fault

### ISSUE THREAD

**Issue by fengenbao** [intel-analytics/BigDL#8984]
platform：Intel Xeon Processor (Icelake) 16cores virtual machine 
task：Baichuan2-13B-Chat 
version：2.4.0b20240810、2.4.0b20240903、2.4.0b20240911，I've tried it all before

After Loading checkpoint shards 100%, accured “Error: Failed to load the llama dynamic library. Segmentation fault” ，I am attempt to solve this problem，but unsuccessfully
![image](https://github.com/intel-analytics/BigDL/assets/57557769/8344d72c-1afe-4be7-8fc9-ecd052b5e8db)

**Comment by fengenbao** [comment]
I feel strange that I can run normally on other computing platforms with graphics cards.

**Comment by fengenbao** [comment]
I guess maybe this Intel Xeon Processor (Icelake) can not run ggml or llama.cpp?

**Comment by MeouSker77** [comment]
Can you tell me which OS are you using? Some old OS's GLIBC version is too low to run bigdl-llm

**Comment by fengenbao** [comment]
> Can you tell me which OS are you using? Some old OS's GLIBC version is too low to run bigdl-llm

![image](https://github.com/intel-analytics/BigDL/assets/57557769/17ea266b-2bdd-4db0-91f7-490c582dbea0)

**Comment by MeouSker77** [comment]
sorry, but the minimal supported GLIBC version is 2.27, CentOS 7 is not supported.
Can you try other newer OS? such as ubuntu 18.04, centos stream 8 or newer

**Comment by fengenbao** [comment]
> sorry, but the minimal supported GLIBC version is 2.27, CentOS 7 is not supported. Can you try other newer OS? such as ubuntu 18.04, centos stream 8 or newer

OK，Thank you very much for your reply. I understand
