### ISSUE TITLE
Bert with optimze_model fail on ARC770

### ISSUE THREAD

**Issue by juan-OY** [intel-analytics/BigDL#9032]
Environment: ADL + ARC770
Install bigdl-llm with below command
pip install --pre --upgrade bigdl-llm[xpu] -f https://developer.intel.com/ipex-whl-stable-xpu
bigdl-core-xe             2.4.0b20230920           pypi_0    pypi
bigdl-llm                 2.4.0b20230920           pypi_0    pypi

Run bert large model on ARC with optimze_model, it reports below error:

return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: PyTorch is not linked with support for xpu devices

---------------------------- code to reproduce---------------------------------------
```python
import time
from transformers import BertTokenizer, BertModel
from bigdl.llm import optimize_model

tokenizer = BertTokenizer.from_pretrained('bert_large_uncased')
model = BertModel.from_pretrained("bert_large_uncased")

# With only one line to enable BigDL-LLM optimization on model
model = model.to('xpu')
model = optimize_model(model)
```
---------------------------- code to reproduce---------------------------------------

the same code after removing model = model.to('xpu'), works well on CPU

Link to model card： 
https://huggingface.co/bert-base-uncased

**Comment by juan-OY** [comment]
OS: Ubuntu 22.04

**Comment by shane-huang** [comment]
@plusbang please take a look.

**Comment by plusbang** [comment]
Hi, @juan-OY .
To enable BigDL-LLM optimizations on Intel GPUs, you need to import intel_extension_for_pytorch first. Please try the following code:
```python
import intel_extension_for_pytorch as ipex
import time
from transformers import BertTokenizer, BertModel
from bigdl.llm import optimize_model

tokenizer = BertTokenizer.from_pretrained('bert_large_uncased')
model = BertModel.from_pretrained("bert_large_uncased")

# With only one line to enable BigDL-LLM optimization on model
model = optimize_model(model)
model = model.to('xpu')
```

P.S. We will add more examples about the `optimize_model` usage on ARC later.

**Comment by juan-OY** [comment]
Also need to put tokenizer on xpu
encoded_input = tokenizer(text, return_tensors='pt').to('xpu')
After these changes, bert is able to run on ARC 770 
full code:
import intel_extension_for_pytorch as ipex
from transformers import BertTokenizer, BertModel
from bigdl.llm import optimize_model

 

tokenizer = BertTokenizer.from_pretrained('bert_large_uncased')
model = BertModel.from_pretrained("bert_large_uncased")

 

# With only one line to enable BigDL-LLM optimization on model
#imodel = model.to('xpu')
model = optimize_model(model)

model = model.to('xpu:0')
text = "I want to get a hello word c++ sample."

encoded_input = tokenizer(text, return_tensors='pt').to('xpu')
t0= time.time()
output = model(**encoded_input)
