### ISSUE TITLE
llm-convert llama2 models to int4 or int8 

### ISSUE THREAD

**Issue by ernleite** [intel-analytics/BigDL#9076]
Hi team
I am searching the good parameter to ask llm-convert to use int4 or int8 quantization but can't find it in the documentation
Any idea? Is this possible already?
thanks

**Comment by jason-dai** [comment]
`llm-convert` is implemented by https://github.com/intel-analytics/BigDL/blob/main/python/llm/src/bigdl/llm/convert_model.py#L119; you may take a look. We will add more document for it later.

**Comment by ernleite** [comment]
wonderful. thanks !
