### ISSUE TITLE
Llama2-7B-4bit: First token takes 3 second to return on i7-11850H

### ISSUE THREAD

**Issue by hjmus** [intel-analytics/BigDL#9143]
Repro: 
1. Run https://github.com/intel-analytics/bigdl-llm-tutorial/blob/main/ch_5_AppDev_Intermediate/5_1_ChatBot.ipynb up to the last cell, which executes a streaming chat like the following:
```
chat_history = []

while True:
    with torch.inference_mode():
        user_input = input("Input:")
        if user_input == "stop": # let's stop the conversation when user input "stop"
          print("Stream Chat with Llama 2 (7B) stopped.")
          break
        stream_chat(model=model_in_4bit,
                    tokenizer=tokenizer,
                    input_str=user_input,
                    chat_history=chat_history)
```
2. In the input box, type in "hello" and press return.

Expected:
Because the prompt is only 1 token, the computation should take under 1 second. The flops per token in the model should be 14B. Intel's SIMD instructions should handle 64 4bit ints per instruction, so it should take 220 million instructions. If they are pipelined well, such that every instruction takes one cycle, then on a 3GHz core, the entire computation should take 220M / 3G < 0.1 seconds. The CPU I used was i7-11850H, which has 8 physical cores, which should further reduce the wall time.

Actual:
It takes about 3 seconds to see the first token. However, the subsequence tokens flows out pretty fast, about 0.1 sec per token.

**Comment by MeouSker77** [comment]
First, the model's real input is not "hello", but 
```
<s>[INST] <<SYS>>
You are a helpful, respectful and honest assistant, who always answers as helpfully as possible, while being safe.
<</SYS>>

hello [/INST]
```

These models are trained to follow instruction with some specific format, we need to add some extra tokens to create such an instruction. So its input token number is not 1, but about 30

Second, the 2nd+ token's performance bottleneck is memory bandwidth, not computation. 
A single DDR4 3200MHz DRAM's bandwidth is up to about 25GB/s, 11th intel CPU has two memory channels, so its total memory bandwidth is up to about 50GB/s (assume your machine has at least two DRAM and locates in different channel).
A 7B int4 model's parameters take up about 3.7GB memory, 3.7GB/50GB/s = 0.074s = 74ms, means just reading all parameters once will take about 74ms.

Third, I remember such streaming (i.e. use thread.Threading to achieve streaming) will affect performance, you can use non-streaming generation and set max_new_tokens to 1 to get a more accurate first token latency. If it is still too slow, feel free to tell us.

**Comment by hjmus** [comment]
Hi MeouSker77, thanks for the comment.

I tested the three factors. Yes, it's the system prompt that's in play. After I removed it, the first token was returned in 0.2 seconds instead of 3 seconds. All other two factors (74ms and streaming) didn't make a difference.

Yes, of course when the latency is 0.2 seconds, 74ms become meaningful.
