### ISSUE TITLE
IndexError with mpt-7b-chat model when the in_out_pairs is 2048-256 using transformer_int4_gpu

### ISSUE THREAD

**Issue by WeiguangHan** [intel-analytics/BigDL#9158]
@hkvision When I did benchmark tests for bigdl-llm on my local machine, I found that the indexing errors will appear when the in_out_pairs is 2048-256. The model and api interface I used is **mpt-7b-chat** and **transformer_int4_gpu**.
![MicrosoftTeams-image (3)](https://github.com/intel-analytics/BigDL/assets/109776541/ed06b4b2-5b8e-4eb5-8f72-a3ae5ba6f87e)

### **Env**
bigdl-core-xe-2.4.0b20231011
bigdl-llm-2.4.0b20231011
intel-extension-for-pytorch-2.0.110+xpu
torch-2.0.1a0+cxx11.abi
torchvision-0.15.2a0+cxx11.abi

**Comment by MeouSker77** [comment]
There should be a `config.json` in model's directory, it has a key named `max_seq_len`, you can set it to a value > 2048+256, then try again.

**Comment by WeiguangHan** [comment]
Thanks!. I will try it.
