### ISSUE TITLE
"Segmentation fault" when import Bigdl-llm

### ISSUE THREAD

**Issue by Kailuo-Lai** [intel-analytics/BigDL#9168]
I encounter a very weird problem when importing bigdl

**Code**

```python
from bigdl.llm.langchain.llms import TransformersLLM
``` 

**Output**

```
Segmentation fault
```

**Environment**
- bigdl-llm: 2.4.0b20231014
- langchain: 0.0.248
- torch: 2.0.1
- torchvision:  0.15.2a0
- transformers: 4.31.0

I have tried to reinstall bigdl, but the problem is still there

**Comment by jason-dai** [comment]
What's your OS version? bigdl-llm may not work on old linux due to glibc dependency (https://github.com/intel-analytics/BigDL/tree/main/python/llm#bigdl-llm-dependency).

**Comment by Kailuo-Lai** [comment]
My linux version
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by Romanticoseu** [comment]
> I encounter a very weird problem when importing bigdl
> 
> **Code**
> 
> ```python
> from bigdl.llm.langchain.llms import TransformersLLM
> ```
> 
> **Output**
> 
> ```
> Segmentation fault
> ```
> 
> **Environment**
> 
> * bigdl-llm: 2.4.0b20231014
> * langchain: 0.0.248
> * torch: 2.0.1
> * torchvision:  0.15.2a0
> * transformers: 4.31.0
> 
> I have tried to reinstall bigdl, but the problem is still there

Hello
I used the same system environment (debian:10 buster) and did not reproduce the issue.
![image](https://github.com/intel-analytics/BigDL/assets/47251317/5d0c7479-7414-4a9e-a335-b7748ded5dd8)
Here is my glibc version.
```bash
ldd (Debian GLIBC 2.28-10+deb10u2) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by Kailuo-Lai** [comment]
> > I encounter a very weird problem when importing bigdl
> > **Code**
> > ```
> > from bigdl.llm.langchain.llms import TransformersLLM
> > ```
> > 
> > 
> > **Output**
> > ```
> > Segmentation fault
> > ```
> > 
> > 
> > **Environment**
> > 
> > * bigdl-llm: 2.4.0b20231014
> > * langchain: 0.0.248
> > * torch: 2.0.1
> > * torchvision:  0.15.2a0
> > * transformers: 4.31.0
> > 
> > I have tried to reinstall bigdl, but the problem is still there
> 
> Hello I used the same system environment (debian:10 buster) and did not reproduce the issue. ![image](https://user-images.githubusercontent.com/47251317/275404049-5d0c7479-7414-4a9e-a335-b7748ded5dd8.png) Here is my glibc version.
> 
> ```shell
> ldd (Debian GLIBC 2.28-10+deb10u2) 2.28
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> ```

Thank you for your reply, I create a new conda environment and reinstall bigdl then the problem disappear. I think may be there are some conflicts among the different packages in my old conda environment.
