### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable when runing on databricks cluster

### ISSUE THREAD

**Issue by fatenlouati** [intel-analytics/BigDL#9169]
Im using `databricks community edition` and 
I follow this tuto [bigdl-orca in databricks](https://bigdl.readthedocs.io/en/latest/doc/UserGuide/databricks.html) ,
I install manually the packages shown in `init.sh `script:
```
%sh
/databricks/python/bin/pip install pip install --pre --upgrade bigdl-orca-spark3[ray]
/databricks/python/bin/pip install gym
cp /databricks/python/lib/python3.8/site-packages/bigdl/share/*/lib/*.jar /databricks/jars
```
then I call `init_orca_context ` 
```
from bigdl.dllib.nncontext import *

OrcaContext.log_output = True

init_orca_context(cluster_mode="spark-submit")
spark = OrcaContext.get_spark_session()
spark
```
but I got this error:
```
Initializing orca context
/databricks/python/lib/python3.9/site-packages/bigdl/orca/common.py:229: Warning: Cores not specified, using 2 cores per node by default.
  warnings.warn("Cores not specified, using 2 cores per node by default.", Warning)
TypeError: 'JavaPackage' object is not callable

```

**Comment by sgwhat** [comment]
Hi fatenlouati, we have reproduced your issue and are actively looking for a solution. Please stay tuned😄.

**Comment by fatenlouati** [comment]
@sgwhat Thank you! Please Keep me updated and  notify me as soon as you've fixed the error. It's urgent.

**Comment by sgwhat** [comment]
Hi @fatenlouati ! I think that manually installing `BigDL` in a Databricks notebook may not work as expected. As a recommendation, you may follow our tutorial to generate an `init.sh`. [ Please click here to see more details](https://bigdl.readthedocs.io/en/latest/doc/UserGuide/databricks.html#generate-initialization-script) and restart the cluster to deploy the environment on Databricks nodes. This method has been verified as reliable and effective.

**Comment by fatenlouati** [comment]
@sgwhat , I tried this method before installing manually, but I couldn't execute the init.sh script file into the cluster. it seems that this feature is not available in databricks community edtion :(

**Comment by fatenlouati** [comment]
It worked like a charm in databricks free trial
Thank you
