### ISSUE TITLE
How to inference multi-instances on 2 Arc A770

### ISSUE THREAD

**Issue by biyuehuang** [intel-analytics/BigDL#9195]
Could you provide multi-instance LLM test guide on 2 Arc A770？ For example, Chatglm2-6b, LLama2-13b.
Configuration: Ubuntu22.04, kernel 5.19, with Xeon

**Comment by gc-fu** [comment]
To run LLM inference on Arc A770, you need to install the `oneAPI-base-toolkit` first.  

If you have not yet installed the toolkit, refer to this [page](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html) to install the toolkit.

Another option is to use the image `intelanalytics/bigdl-llm-xpu:2.4.0-SNAPSHOT` provided by us. The `oneAPI-base-toolkit` and other dependencies have already been installed in the image.

To clarify, a single LLM inference instance cannot run across multiple cards using `BigDL-LLM`.  However, you can run multiple LLM inference instances across multiple cards and do card-level isolation. 


You can do this following these steps:

```bash

#/bin/bash
export DOCKER_IMAGE=intelanalytics/bigdl-llm-xpu:2.4.0-SNAPSHOT

sudo docker run -itd \
        --net=host \
        --device=/dev/dri \
        --memory="32G" \
        --name=CONTAINER_NAME \
        --shm-size="16g" \
        $DOCKER_IMAGE
```

In the container, run `sycl-ls`, you should see your multiple Arc A770 cards.

Then, you can use the environment variable `ZE_AFFINITY_MASK` to control which cards to use for a specific task.

For instance, if you set `ZE_AFFINITY_MASK` to 0, then only the 0 card will be available to the process.  Check [here](https://spec.oneapi.io/level-zero/latest/core/PROG.html#affinity-mask) for detailed information.

In your environment, it should be:

```bash
# chatglm2-chat.py is just an example of your inference instance
ZE_AFFINITY_MASK=0 python3 chatglm2-chat.py &
ZE_AFFINITY_MASK=1 python3 LLama2-13b-chat.py
```

**Comment by biyuehuang** [comment]
Hi @gc-fu , Does "ZE_AFFINITY_MASK=0 python3 chatglm2-chat.py" means inference 1-instance on the first A770?
How to inference 2-instance on the first A770 and 2-instance on the second A770 for python3 chatglm2-chat.py?

**Comment by gc-fu** [comment]
`ZE_AFFINITY_MASK=0` simply indicates that only the card with index zero will be available/seen by the processes. So in your context, simply do the following:

```bash
# Inference two-instances on the first A770
ZE_AFFINITY_MASK=0 python3 inference-instance-one.py &
ZE_AFFINITY_MASK=0 python3 inference-instance-two.py &
```

I am not very sure about what do you mean by inference 2-batch_size on the first A770.  In my view, you cannot yet run batched inference through `BigDL-LLM` in one process.

@Oscilloscope98 Can you help to check if we can run batched inference using `BigDL-LLM`?

**Comment by jason-dai** [comment]
> `ZE_AFFINITY_MASK=0` simply indicates that only the card with index zero will be available/seen by the processes. So in your context, simply do the following:
> 
> I am not very sure about what do you mean by inference 2-batch_size on the first A770. In my view, you cannot yet run batched inference through `BigDL-LLM` in one process.
> 
> @Oscilloscope98 Can you help to check if we can run batched inference using `BigDL-LLM`?

We can run batched inference using `BigDL-LLM`

**Comment by biyuehuang** [comment]
> `ZE_AFFINITY_MASK=0` simply indicates that only the card with index zero will be available/seen by the processes. So in your context, simply do the following:
> 
> ```shell
> # Inference two-instances on the first A770
> ZE_AFFINITY_MASK=0 python3 inference-instance-one.py &
> ZE_AFFINITY_MASK=0 python3 inference-instance-two.py &
> ```
> 
> I am not very sure about what do you mean by inference 2-batch_size on the first A770.
> 
> @Oscilloscope98 Can you help to check if we can run batched inference using `BigDL-LLM`?

Hi Guancheng,

[passed] It work for $ python3 test_chatglm2.py

[failed]   It will "Segmentation fault (core dumped)" for $ ZE_AFFINITY_MASK=0 python3 test_chatglm2.py
  
[passed one, failed the other]   It will "[1]+  Segmentation fault      (core dumped) ZE_AFFINITY_MASK=0 python3 test_chatglm2.py" for $ ZE_AFFINITY_MASK=0 python3 test_chatglm2.py &ZE_AFFINITY_MASK=1 python3 test_chatglm2.py

**Comment by biyuehuang** [comment]
Hi @gc-fu , multi-batch size doesn't have 4  outputs
 
[1] prompt = [prompt_32]
```
torch.Size([1, 32])
2023-10-19 18:14:54,403 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
=========First token cost 0.1158s=========
=========Rest tokens cost average 0.0218s (31 tokens in all)=========
Output: ['', '', '我', '总是在', '晚上', '失眠', ',', '这个', '症状', '已经', '持续', '很长时间', ',', '所以', '晚上', '睡不着', '到底', '应该', '怎么', '处理', ',', '请', '告诉我', '一些', '可行的', '建议', '与', '方法', ',', '越', '详细', '越好', '。', '', '首先', ',', '我', '建议', '您', '尝试', '以下', '方法', '来', '改善', '睡眠', '质量', ':', '<0x0A>', '<0x0A>', '1', '.', '', '睡前', '放松', ':', '在', '睡觉', '前', '放松', '自己', ',', '可以通过', '听', '音乐']
```

[2] prompt = [prompt_32,prompt_32,prompt_32,prompt_32]
```
torch.Size([4, 32])
2023-10-19 18:03:54,796 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
=========First token cost 0.1328s=========
=========Rest tokens cost average 0.1038s (31 tokens in all)=========
Output: ['', '', '我', '总是在', '晚上', '失眠', ',', '这个', '症状', '已经', '持续', '很长时间', ',', '所以', '晚上', '睡不着', '到底', '应该', '怎么', '处理', ',', '请', '告诉我', '一些', '可行的', '建议', '与', '方法', ',', '越', '详细', '越好', '。', '', '首先', ',', '我', '建议', '您', '尝试', '以下', '方法', '来', '改善', '睡眠', '质量', ':', '<0x0A>', '<0x0A>', '1', '.', '', '睡前', '放松', ':', '在', '睡觉', '前', '放松', '自己', ',', '可以通过', '听', '音乐']
```
attach code:
```
prompt_32 = "我总是在晚上失眠,这个症状已经持续很长时间,所以晚上睡不着到底应该怎么处理,请告诉我一些可行的建议与方法,越详细越好"
prompt = [prompt_32,prompt_32,prompt_32,prompt_32]
tokenizer = AutoTokenizer.from_pretrained(args.model_dir, trust_remote_code=True)
model =  AutoModel.load_low_bit(args.model_dir, trust_remote_code=True, optimize_model=False)
    model = model.to('xpu')
    model = BenchmarkWrapper(model)

    with torch.inference_mode():
        for i in range(5):
            torch.xpu.synchronize()
            st = time.time()
            inputs = tokenizer(prompt, return_tensors="pt").to('xpu')
            print(inputs["input_ids"].shape)
            output = model.generate(**inputs, do_sample=False, temperature=0.9, max_new_tokens=32)
            gen_ids = output[0]
            gen_text = tokenizer.batch_decode(gen_ids, skip_special_tokens=True)
            torch.xpu.synchronize()
    print('Output:', gen_text)
```

**Comment by gc-fu** [comment]
> Hi @gc-fu
> 
> $ sycl-ls
> 
> ```
> [opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.16.6.0.22_223734]
> [opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 5420+ 3.0 [2023.16.6.0.22_223734]
> [opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics 3.0 [23.17.26241.33]
> [ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.26241]
> ```
> 
> [passed] It work for $ python3 test_chatglm2.py
> 
> [failed] It will "Segmentation fault (core dumped)" for $ ZE_AFFINITY_MASK=0 python3 test_chatglm2.py
> 
> ```
>   /home/adc-a770/miniconda3/envs/llm-test/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
>   warn(
> Namespace(model_dir='/home/adc-a770/llm/chatglm2-6b-int4/', max_new_tokens=32, input_tokens='32')
> Test /home/adc-a770/llm/chatglm2-6b-int4/...
> Segmentation fault (core dumped)
> ```
> 
> [passed on one A770, failed on the other A770] It will "[1]+ Segmentation fault (core dumped) ZE_AFFINITY_MASK=0 python3 test_chatglm2.py" for $ ZE_AFFINITY_MASK=0 python3 test_chatglm2.py &ZE_AFFINITY_MASK=1 python3 test_chatglm2.py
> 
> ```
> [1] 90252
> /home/adc-a770/miniconda3/envs/llm-test/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
>   warn(
> /home/adc-a770/miniconda3/envs/llm-test/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
>   warn(
> Namespace(model_dir='/home/adc-a770/llm/chatglm2-6b-int4/', max_new_tokens=32, input_tokens='32')
> Test /home/adc-a770/llm/chatglm2-6b-int4/...
> Namespace(model_dir='/home/adc-a770/llm/chatglm2-6b-int4/', max_new_tokens=32, input_tokens='32')
> Test /home/adc-a770/llm/chatglm2-6b-int4/...
> <class 'transformers_modules.modeling_chatglm.ChatGLMForConditionalGeneration'>
> torch.float32
> torch.Size([1, 32])
> torch.Size([1, 32])
> 2023-10-19 17:51:02,399 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> /home/adc-a770/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py:374: UserWarning: IPEX XPU dedicated fusion passes are enabled in ScriptGraph non profiling execution mode. Please enable profiling execution mode to retrieve device guard.
>  (Triggered internally at /build/intel-pytorch-extension/csrc/gpu/jit/fusion_pass.cpp:826.)
>   query_layer = apply_rotary_pos_emb(query_layer, rotary_pos_emb)
> =========First token cost 1.1896s=========
> =========Rest tokens cost average 0.0230s (31 tokens in all)=========
> torch.Size([1, 32])
> 2023-10-19 17:51:04,341 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> =========First token cost 0.1159s=========
> =========Rest tokens cost average 0.0224s (31 tokens in all)=========
> torch.Size([1, 32])
> 2023-10-19 17:51:05,154 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> =========First token cost 0.1157s=========
> =========Rest tokens cost average 0.0217s (31 tokens in all)=========
> torch.Size([1, 32])
> 2023-10-19 17:51:05,946 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> =========First token cost 0.1157s=========
> =========Rest tokens cost average 0.0219s (31 tokens in all)=========
> torch.Size([1, 32])
> 2023-10-19 17:51:06,742 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> =========First token cost 0.1157s=========
> =========Rest tokens cost average 0.0225s (31 tokens in all)=========
> Inference time: 0.8151659965515137 s
> [1]+  Segmentation fault      (core dumped) ZE_AFFINITY_MASK=0 python3 test_chatglm2.py
> ```

Hi, I am working on this to see if I can reproduce this issue.

Later, I will update to this thread.  Thanks.

**Comment by cyita** [comment]
> Hi @gc-fu , multi-batch size doesn't have 4 outputs
> 
> [1] prompt = [prompt_32]
> 
> ```
> torch.Size([1, 32])
> 2023-10-19 18:14:54,403 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> =========First token cost 0.1158s=========
> =========Rest tokens cost average 0.0218s (31 tokens in all)=========
> Output: ['', '', '我', '总是在', '晚上', '失眠', ',', '这个', '症状', '已经', '持续', '很长时间', ',', '所以', '晚上', '睡不着', '到底', '应该', '怎么', '处理', ',', '请', '告诉我', '一些', '可行的', '建议', '与', '方法', ',', '越', '详细', '越好', '。', '', '首先', ',', '我', '建议', '您', '尝试', '以下', '方法', '来', '改善', '睡眠', '质量', ':', '<0x0A>', '<0x0A>', '1', '.', '', '睡前', '放松', ':', '在', '睡觉', '前', '放松', '自己', ',', '可以通过', '听', '音乐']
> ```
> 
> [2] prompt = [prompt_32,prompt_32,prompt_32,prompt_32]
> 
> ```
> torch.Size([4, 32])
> 2023-10-19 18:03:54,796 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> =========First token cost 0.1328s=========
> =========Rest tokens cost average 0.1038s (31 tokens in all)=========
> Output: ['', '', '我', '总是在', '晚上', '失眠', ',', '这个', '症状', '已经', '持续', '很长时间', ',', '所以', '晚上', '睡不着', '到底', '应该', '怎么', '处理', ',', '请', '告诉我', '一些', '可行的', '建议', '与', '方法', ',', '越', '详细', '越好', '。', '', '首先', ',', '我', '建议', '您', '尝试', '以下', '方法', '来', '改善', '睡眠', '质量', ':', '<0x0A>', '<0x0A>', '1', '.', '', '睡前', '放松', ':', '在', '睡觉', '前', '放松', '自己', ',', '可以通过', '听', '音乐']
> ```
> 
> attach code:
> 
> ```
> prompt_32 = "我总是在晚上失眠,这个症状已经持续很长时间,所以晚上睡不着到底应该怎么处理,请告诉我一些可行的建议与方法,越详细越好"
> prompt = [prompt_32,prompt_32,prompt_32,prompt_32]
> tokenizer = AutoTokenizer.from_pretrained(args.model_dir, trust_remote_code=True)
> model =  AutoModel.load_low_bit(args.model_dir, trust_remote_code=True, optimize_model=False)
>     model = model.to('xpu')
>     model = BenchmarkWrapper(model)
> 
>     with torch.inference_mode():
>         for i in range(5):
>             torch.xpu.synchronize()
>             st = time.time()
>             inputs = tokenizer(prompt, return_tensors="pt").to('xpu')
>             print(inputs["input_ids"].shape)
>             output = model.generate(**inputs, do_sample=False, temperature=0.9, max_new_tokens=32)
>             gen_ids = output[0]
>             gen_text = tokenizer.batch_decode(gen_ids, skip_special_tokens=True)
>             torch.xpu.synchronize()
>     print('Output:', gen_text)
> ```

Please try to use `gen_ids = output` instead of `gen_ids = output[0]`.

**Comment by biyuehuang** [comment]
> > Hi @gc-fu , multi-batch size doesn't have 4 outputs
> > [1] prompt = [prompt_32]
> > ```
> > torch.Size([1, 32])
> > 2023-10-19 18:14:54,403 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> > =========First token cost 0.1158s=========
> > =========Rest tokens cost average 0.0218s (31 tokens in all)=========
> > Output: ['', '', '我', '总是在', '晚上', '失眠', ',', '这个', '症状', '已经', '持续', '很长时间', ',', '所以', '晚上', '睡不着', '到底', '应该', '怎么', '处理', ',', '请', '告诉我', '一些', '可行的', '建议', '与', '方法', ',', '越', '详细', '越好', '。', '', '首先', ',', '我', '建议', '您', '尝试', '以下', '方法', '来', '改善', '睡眠', '质量', ':', '<0x0A>', '<0x0A>', '1', '.', '', '睡前', '放松', ':', '在', '睡觉', '前', '放松', '自己', ',', '可以通过', '听', '音乐']
> > ```
> > 
> > 
> > [2] prompt = [prompt_32,prompt_32,prompt_32,prompt_32]
> > ```
> > torch.Size([4, 32])
> > 2023-10-19 18:03:54,796 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> > =========First token cost 0.1328s=========
> > =========Rest tokens cost average 0.1038s (31 tokens in all)=========
> > Output: ['', '', '我', '总是在', '晚上', '失眠', ',', '这个', '症状', '已经', '持续', '很长时间', ',', '所以', '晚上', '睡不着', '到底', '应该', '怎么', '处理', ',', '请', '告诉我', '一些', '可行的', '建议', '与', '方法', ',', '越', '详细', '越好', '。', '', '首先', ',', '我', '建议', '您', '尝试', '以下', '方法', '来', '改善', '睡眠', '质量', ':', '<0x0A>', '<0x0A>', '1', '.', '', '睡前', '放松', ':', '在', '睡觉', '前', '放松', '自己', ',', '可以通过', '听', '音乐']
> > ```
> > 
> > 
> > attach code:
> > ```
> > prompt_32 = "我总是在晚上失眠,这个症状已经持续很长时间,所以晚上睡不着到底应该怎么处理,请告诉我一些可行的建议与方法,越详细越好"
> > prompt = [prompt_32,prompt_32,prompt_32,prompt_32]
> > tokenizer = AutoTokenizer.from_pretrained(args.model_dir, trust_remote_code=True)
> > model =  AutoModel.load_low_bit(args.model_dir, trust_remote_code=True, optimize_model=False)
> >     model = model.to('xpu')
> >     model = BenchmarkWrapper(model)
> > 
> >     with torch.inference_mode():
> >         for i in range(5):
> >             torch.xpu.synchronize()
> >             st = time.time()
> >             inputs = tokenizer(prompt, return_tensors="pt").to('xpu')
> >             print(inputs["input_ids"].shape)
> >             output = model.generate(**inputs, do_sample=False, temperature=0.9, max_new_tokens=32)
> >             gen_ids = output[0]
> >             gen_text = tokenizer.batch_decode(gen_ids, skip_special_tokens=True)
> >             torch.xpu.synchronize()
> >     print('Output:', gen_text)
> > ```
> 
> Please try to use `gen_ids = output` instead of `gen_ids = output[0]`.

Yes, you are right!

**Comment by biyuehuang** [comment]
> > Hi @gc-fu
> > $ sycl-ls
> > ```
> > [opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.16.6.0.22_223734]
> > [opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 5420+ 3.0 [2023.16.6.0.22_223734]
> > [opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics 3.0 [23.17.26241.33]
> > [ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.26241]
> > ```
> > 
> > 
> > [passed] It work for $ python3 test_chatglm2.py
> > [failed] It will "Segmentation fault (core dumped)" for $ ZE_AFFINITY_MASK=0 python3 test_chatglm2.py
> > ```
> >   /home/adc-a770/miniconda3/envs/llm-test/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
> >   warn(
> > Namespace(model_dir='/home/adc-a770/llm/chatglm2-6b-int4/', max_new_tokens=32, input_tokens='32')
> > Test /home/adc-a770/llm/chatglm2-6b-int4/...
> > Segmentation fault (core dumped)
> > ```
> > 
> > 
> > [passed on one A770, failed on the other A770] It will "[1]+ Segmentation fault (core dumped) ZE_AFFINITY_MASK=0 python3 test_chatglm2.py" for $ ZE_AFFINITY_MASK=0 python3 test_chatglm2.py &ZE_AFFINITY_MASK=1 python3 test_chatglm2.py
> > ```
> > [1] 90252
> > /home/adc-a770/miniconda3/envs/llm-test/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
> >   warn(
> > /home/adc-a770/miniconda3/envs/llm-test/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
> >   warn(
> > Namespace(model_dir='/home/adc-a770/llm/chatglm2-6b-int4/', max_new_tokens=32, input_tokens='32')
> > Test /home/adc-a770/llm/chatglm2-6b-int4/...
> > Namespace(model_dir='/home/adc-a770/llm/chatglm2-6b-int4/', max_new_tokens=32, input_tokens='32')
> > Test /home/adc-a770/llm/chatglm2-6b-int4/...
> > <class 'transformers_modules.modeling_chatglm.ChatGLMForConditionalGeneration'>
> > torch.float32
> > torch.Size([1, 32])
> > torch.Size([1, 32])
> > 2023-10-19 17:51:02,399 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> > /home/adc-a770/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py:374: UserWarning: IPEX XPU dedicated fusion passes are enabled in ScriptGraph non profiling execution mode. Please enable profiling execution mode to retrieve device guard.
> >  (Triggered internally at /build/intel-pytorch-extension/csrc/gpu/jit/fusion_pass.cpp:826.)
> >   query_layer = apply_rotary_pos_emb(query_layer, rotary_pos_emb)
> > =========First token cost 1.1896s=========
> > =========Rest tokens cost average 0.0230s (31 tokens in all)=========
> > torch.Size([1, 32])
> > 2023-10-19 17:51:04,341 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> > =========First token cost 0.1159s=========
> > =========Rest tokens cost average 0.0224s (31 tokens in all)=========
> > torch.Size([1, 32])
> > 2023-10-19 17:51:05,154 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> > =========First token cost 0.1157s=========
> > =========Rest tokens cost average 0.0217s (31 tokens in all)=========
> > torch.Size([1, 32])
> > 2023-10-19 17:51:05,946 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> > =========First token cost 0.1157s=========
> > =========Rest tokens cost average 0.0219s (31 tokens in all)=========
> > torch.Size([1, 32])
> > 2023-10-19 17:51:06,742 - gpu_benchmark_util - WARNING - Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
> > =========First token cost 0.1157s=========
> > =========Rest tokens cost average 0.0225s (31 tokens in all)=========
> > Inference time: 0.8151659965515137 s
> > [1]+  Segmentation fault      (core dumped) ZE_AFFINITY_MASK=0 python3 test_chatglm2.py
> > ```
> 
> Hi, I am working on this to see if I can reproduce this issue.
> 
> Later, I will update to this thread. Thanks.

Solved after update level-zero
