### ISSUE TITLE
all-in-one/run.py can't output 1024 tokens when set "1024-1024" pair in config.yaml

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#9234]
https://github.com/intel-analytics/BigDL/tree/c3e3b065e98c20d78f5b87b80ff84ac63b822b73/python/llm/dev/benchmark/all-in-one

test device: A770 
model: chatglm2-6b
test_api: 
   - "ipex_fp16_gpu" # on Intel GPU
   - "transformer_int4_gpu"  # on Intel GPU
   - "optimize_model_gpu"  # on Intel GPU

from result.csv:
input/output tokens ||||  actual input/output tokens
32-32                        ||||   32-32
1024-128                  ||||   1024-128
1024-1024                ||||   1024-191
2048-1024                ||||   2048-659

**Comment by hkvision** [comment]
@qiuxin2012 Could you please take a look? Is this related to the content of the input?

**Comment by qiuxin2012** [comment]
We can't force the model to output excepted lenght, the model will be end of text if they have nothing to say.
Our prompts are general prompts to test all the models, it's not specific prompt for chatglm2.
If you want's chatglm2 to say more words, you can try to change the prompts in https://github.com/intel-analytics/BigDL/tree/c3e3b065e98c20d78f5b87b80ff84ac63b822b73/python/llm/dev/benchmark/all-in-one/prompt

**Comment by KiwiHana** [comment]
Thanks Xin! Although chatglm2-6b can't output 1024 token with run.py and prompt/1024.txt.
I can use other script to generate 1024 token outputs.

**Comment by hkvision** [comment]
Is it ok for you to share your prompt that can let chatglm generate 1k outputs for our reference? @KiwiHana :)

**Comment by KiwiHana** [comment]
https://github.com/KiwiHana/LLM_UI_Windows_CPU/blob/main/benchmark/test_chatglm2.py

@hkvision

**Comment by hkvision** [comment]
Thank you so much!
