### ISSUE TITLE
bigdl.llm.serving.model_worker doesn't load "xxx-bigdl" model with "Customized bigdl-llm loader"

### ISSUE THREAD

**Issue by qzheng527** [intel-analytics/BigDL#9250]
I tried "python -m bigdl.llm.serving.model_worker --model-path /models/vicuna-7b-bigdl --device cpu --host 0.0.0.0" following [doc](https://github.com/intel-analytics/BigDL/tree/main/python/llm/src/bigdl/llm/serving). But it didn't load model. using BigDL-LLM.

BTW, model "chatglm2-6b-bigdl" works fine with using BigDL-LLM.

**Comment by qzheng527** [comment]
Thanks, "bigdl-7b" name works.

**Comment by gc-fu** [comment]
Closed as solved.
