### ISSUE TITLE
Unmatched tensor size of dolly-v1-6b model using transformer_int4_gpu

### ISSUE THREAD

**Issue by WeiguangHan** [intel-analytics/BigDL#9282]
@hkvision The error of unmatched tensor size will happen when I tested the **dolly-v1-6b**  model using  **transformer_int4_gpu** api. Please have a look.

![MicrosoftTeams-image (4)](https://github.com/intel-analytics/BigDL/assets/109776541/78f7f9fb-8ebd-4fad-adff-a94405083ea8)

### **Env**
bigdl-core-xe-2.4.0b20231023
bigdl-llm-2.4.0b20231023
intel-extension-for-pytorch-2.0.110+xpu
torch-2.0.1a0+cxx11.abi
torchvision-0.15.2a0+cxx11.abi

**Comment by hkvision** [comment]
@qiuxin2012 Please take a look and check if anything changes when you run this model.

**Comment by qiuxin2012** [comment]
@WeiguangHan Input/Output size?

**Comment by qiuxin2012** [comment]
32-32, 1024-128 works fine.
But 2048-256, the tokenizer will throw below warining: 
`Token indices sequence length is longer than the specified maximum sequence length for this model (2070 > 2048). Running this sequence through the model will result in indexing errors`
From this warning and upown RuntimeRror, it looks like the dolly v1 only accept input size < 2048.

**Comment by lalalapotter** [comment]
You may need to set `"n_positions"` in config.json file or set it when loading models as following:
```python
model = AutoModelForCausalLM.from_pretrained(model_path, load_in_4bit=True, low_cpu_mem_usage=True, trust_remote_code=True, n_positions=4096)
```

**Comment by WeiguangHan** [comment]
> You may need to set `"n_positions"` in config.json file or set it when loading models as following:
> 
> ```python
> model = AutoModelForCausalLM.from_pretrained(model_path, load_in_4bit=True, low_cpu_mem_usage=True, trust_remote_code=True, n_positions=4096)
> ```

Make sense. After I set `"n_positions"` in config.json file, 2048-256 works fine now. Thanks!
