### ISSUE TITLE
'QWenAttention' object has no attribute 'use cache quantization'

### ISSUE THREAD

**Issue by WeiguangHan** [intel-analytics/BigDL#9283]
@hkvision The error that `'QWenAttention' object has no attribute 'use cache quantization'` will happen when I tested the **Qwen-7B-Chat**  model using  **transformer_int4_gpu** api. Please have a look.

![MicrosoftTeams-image (5)](https://github.com/intel-analytics/BigDL/assets/109776541/62b51ba1-fe34-429c-bf73-6c3a7f7c92da)

### **Env**
bigdl-core-xe-2.4.0b20231023
bigdl-llm-2.4.0b20231023
intel-extension-for-pytorch-2.0.110+xpu
torch-2.0.1a0+cxx11.abi
torchvision-0.15.2a0+cxx11.abi

**Comment by rnwang04** [comment]
Maybe you are using old Qwen model? Qwen has updated  their modeling file (and maybe weight), and I update related file based on that.
We have uploaded new Qwen model to ftp (Qwen-7B-Chat-10-12/), could you please test with it again?

**Comment by hkvision** [comment]
Sure, we will test it.

**Comment by WeiguangHan** [comment]
> Maybe you are using old Qwen model? Qwen has updated their modeling file (and maybe weight), and I update related file based on that. We have uploaded new Qwen model to ftp (Qwen-7B-Chat-10-12/), could you please test with it again?

I have tested the new model Qwen-7B-Chat-10-12 on my side and it worked fine! Thanks a lot!
