### ISSUE TITLE
bigdl-llm-init cannot reach the optimized performance as bigdl-nano-init

### ISSUE THREAD

**Issue by Zhengjin-Wang** [intel-analytics/BigDL#9304]
I used both methods to test Llama-2-7b-chat-hf in condition of 1k-128(beam=4) transformer-int4 api.
Next token latency using bigdl-nano-init is around 170ms, but 320ms using bigdl-llm-init.
I have made a comparison of env list between two circumstances.
https://github.com/Zhengjin-Wang/BigDL/commit/1f6d524f8967a9a020f46afe941e4fbaa6b19c01?diff=split
The left side is env list in bigdl-llm-init, and right side is in bigdl-nano-init.

**Comment by hkvision** [comment]
@MeouSker77 Take a look at this?

**Comment by jason-dai** [comment]
@qiuxin2012

**Comment by MeouSker77** [comment]
installing bigdl-llm won't install intel-onenmp, tcmalloc, jemalloc automatically. So we should change bigdl-llm's `setup.py`, add `intel-openmp` as dependency, and also add tcmalloc and jemalloc in it.
