### ISSUE TITLE
Chatglm2-6B multi-batch size has unexpected performance on Arc A770

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#9326]
ChatGLM2-6B use multi-batch size by bigdl-llm[xpu] 20231016 on Arc 770 with Xeon.
batch size=2/4 has unexpected performance compared with batch size=1. 

For 32in/32out，batch size=1, rest latency is 20.5ms/token. 
batch size = 2, rest latency is 103.4ms/token. 
batch size = 4, rest latency is 103.9ms/token. 
batch size = 8, rest latency is 105.6ms/token. 
batch size=16, rest latency is 109.8ms/token.

For 1024in/1024out，batch size=1, rest latency is 29.4ms/token. 
batch size = 2, rest latency is 131.5ms/token. 
batch size = 4, rest latency is 151.1ms/token. 
batch size = 8, rest latency is 199.3.6ms/token. 

download script: https://github.com/biyuehuang/LLM_Arc_UI/blob/main/gpu_benchmark/test_chatglm2.py

```
conda activate llm-test
source /opt/intel/oneapi/setvars.sh
export USE_XETLA=OFF
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1
export LD_PRELOAD=${LD_PRELOAD}:/home/adc-a770/miniconda3/envs/llm-test/lib/libtcmalloc.so
python test_chatglm2.py --input-tokens   32 --max-new-tokens   32 --batch-size 2
python test_chatglm2.py --input-tokens   1024 --max-new-tokens   1024 --batch-size 2
```

**Comment by MeouSker77** [comment]
Cound you try the latest `bigdl-llm[xpu]==2.4.0b20231101` ? It should fix this problem.

**Comment by KiwiHana** [comment]
Thanks! Checked!
