### ISSUE TITLE
pridict() in PythonBigDL should use ModelBroadcast instead of sparkContext.broadcast

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#938]
pridict() in PythonBigDL should use ModelBroadcast instead of sparkContext.broadcast

**Comment by zhichao-li** [comment]
currently we depend on ```modelPredictRDD``` and  ``` predict``` is useless here and would be removed shortly. @zhangxiaoli73

**Comment by zhichao-li** [comment]
https://github.com/intel-analytics/BigDL/pull/939

**Comment by zhangxiaoli73** [comment]
yeah, the old one can be removed.
