### ISSUE TITLE
Segmentation fault with QLora merged model on CPU Sapphire Rapids during Inference

### ISSUE THREAD

**Issue by tsantra** [intel-analytics/BigDL#9392]
My system configuration:
Xeon Gold (2 sockets)
Memory: 128 GB
Disc Capacity : 3.8 TB
OS: 22.04.3 LTS

1. Used the CPU code provided to fine-tune using Qlora. Used the default dataset "**Abirate/english_quotes**"
Base Model : **meta-llama/Llama-2-7b-chat-hf**

Added 4 lines in the default dataset:

{"quote":"“You can install the latest version by running the command, sudo yum install openvino”","author":"OpenVINO","tags":["OpenVINO","YUM Package Manager","Linux","commands"]}
{"quote":"“You can update PIP to the highest version by running the command, python -m pip install --upgrade pip,  in the activated virtual environment.”","author":"OpenVINO","tags":["OpenVINO","OpenVINO installation using PIP","commands"]}
{"quote":"“To install GCC 8.3.1 on CENTOS 7 using devtoolset-8, run the following commands, sudo yum update -y && sudo yum install -y centos-release-scl epel-release sudo yum”","author":"OpenVIO","tags":["OpenVINO", "GCC", "CENTOS 7", "commands"]}
{"quote":"“The command to update pip and setuptools to newer version is, python3 -m pip install -U pip setuptools”","author":"OpenVINO","tags":["OpenVINO", "OpenVINO Installation"]}

2. Trained for 160 steps. 
3. Then merged the model using export_merged_model.py

4. Made one change in the training code, by following the example from GPU. So instead of training on the data['train']['predictions'], trained on data['train']['quote']. This is exactly how GPU example does it. Code snippet below: 
   
    #data = load_dataset(dataset_path)
    data = load_dataset("json", data_files=dataset_path)     
 
   # commented out this part below in the example CPU code
    '''    
    def merge(row):
        row['prediction'] = row['quote'] + ' ->: ' + str(row['tags'])
        return row
    data['train'] = data['train'].map(merge)
    data = data.map(lambda samples: tokenizer(samples["prediction"]), batched=True)
    '''
    
    # And added this line in the CPU code.
    data = data.map(lambda samples: tokenizer(samples["quote"]), batched=True)    

5. Attaching pic of the Segmentation fault:
<img width="871" alt="mergedmodel_coredump" src="https://github.com/intel-analytics/BigDL/assets/45886215/d85f655a-04ab-40b2-9c84-a75034be9771">

6. Env:
(base) ceed-user@ceed-server:~$ conda activate bigdl_cpu
Sourcing bigdl-nano-init in: /home/ceed-user/anaconda3/envs/bigdl_cpu/bin
Setting OMP_NUM_THREADS...
Setting KMP_AFFINITY...
Setting KMP_BLOCKTIME...
Setting jemalloc...
nano_vars.sh already exists
+++++ Env Variables +++++
LD_PRELOAD            = /home/ceed-user/anaconda3/envs/bigdl_cpu/lib/libiomp5.so /home/ceed-user/anaconda3/envs/bigdl_cpu/lib/python3.9/site-packages/bigdl/nano/libs/libjemalloc.so
MALLOC_CONF           = oversize_threshold:1,background_thread:false,metadata_thp:always,dirty_decay_ms:-1,muzzy_decay_ms:-1
OMP_NUM_THREADS       = 64
KMP_AFFINITY          = granularity=fine,none
KMP_BLOCKTIME         = 1
TF_ENABLE_ONEDNN_OPTS = 1
+++++++++++++++++++++++++
Complete.

Kindly help!

**Comment by liu-shaojun** [comment]
@tsantra There is an issue reported the same error: https://github.com/intel-analytics/BigDL/issues/9202, you could try the methods in comments https://github.com/intel-analytics/BigDL/issues/9202#issuecomment-1784642526 and https://github.com/intel-analytics/BigDL/issues/9202#issuecomment-1797159460

**Comment by qiyuangong** [comment]
Hi @tsantra 

Seem default nano-init added by `bigdl-nano` leads to core dump in your system. Please create a new conda env without `bigdl-nano`. 

Or uninstall `bigdl-nano` with `pip uninstall bigdl-nano`. Then, remove nano-init in conda with
```bash
/home/spr/anaconda3/envs/your_env/etc/conda/activate.d/nano_vars.sh
/home/spr/anaconda3/envs/your_enve/etc/conda/deactivate.d/nano_vars.sh
```

Please upgrade to latest bigdl-llm, and use `source bigdl-llm-init` instread of `source source bigdl-nano-init` in scripts.

**Comment by tsantra** [comment]
@qiyuangong  Issue resolved after creating new env. 
bigdl-nano-init seemed to be the problem.

**Comment by qiyuangong** [comment]
> @qiyuangong Issue resolved after creating new env. bigdl-nano-init seemed to be the problem.

Thank you for your feedback!
We have already excluded `bigdl-nano-init` from BigDL-LLM.

**Comment by qiyuangong** [comment]
Issue closed. 
Feel free to reopen if there is any further question.
