### ISSUE TITLE
inference chatglm3-6b with 2k input prompt failed

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/BigDL#9408]
When I inference chatGLM3-6B model with 2k input prompt and INT4 or FP8, the command is as below:
numactl -C 0-4 -m 0 python generate.py --repo-id-or-model-path /home/fred/LLM/text-generation/pretrained-model/chatglm3-6b/ --n-predict 1024 --prompt "xxx...", first inference is successful, then it hung.
BigDL-LLM version: 2.4.0b20231108
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:07<00:00,  1.04s/it]
2023-11-09 21:38:41,923 - bigdl.llm.transformers.utils - INFO - Converting the current model to sym_int4 format......
<class 'transformers_modules.modeling_chatglm.ChatGLMForConditionalGeneration'>
=========First token cost 6.6247 s=========
=========Rest tokens cost average 0.0282 s (517 tokens in all)=========
and GPU utilization is 0%, and memory utilization is ~10GB.
![image](https://github.com/intel-analytics/BigDL/assets/99886928/f2a0cabe-61c8-45c6-acb2-fd6f810adc35)

**Comment by hkvision** [comment]
@JinBridger Please check is this.

**Comment by JinBridger** [comment]
I tested on our device (13900K+64G DDR5, A770). For 1024 input it works fine. However, when use 2048 input, it outputs nothing.

**Comment by hkvision** [comment]
@sgwhat Take a look at this issue?

**Comment by sgwhat** [comment]
Has reproduced on user's machine.

**Comment by sgwhat** [comment]
This issue could be resolved by removing `warm up` ipex model in https://github.com/intel-analytics/BigDL/blob/e204f2591aee87febcdaf3d22fea93bb91bcdad6/python/llm/example/GPU/HF-Transformers-AutoModels/Model/chatglm3/generate.py#L61.

**Comment by shane-huang** [comment]
> This issue could be resolved by removing `warm up` ipex model in
> 
> https://github.com/intel-analytics/BigDL/blob/e204f2591aee87febcdaf3d22fea93bb91bcdad6/python/llm/example/GPU/HF-Transformers-AutoModels/Model/chatglm3/generate.py#L61
> 
> .
