### ISSUE TITLE
Refine the Spark Wrapper (DLClassifier and DLEstimator)

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/BigDL#941]
Several issues were found during the review of https://github.com/intel-analytics/BigDL/pull/745, since most of them would impact `DLClassifier`, we didn't make the change in https://github.com/intel-analytics/BigDL/pull/745. 

1.` DLClassifier` uses `HasInputCol` and `HasOutputCol` while `DLEstimator` uses `HasFeatureCol` and `HasPredictionCol`, suggest to unify to `HasFeatureCol` and `HasPredictionCol`.
2. We should implement `TransformSchema` to allow datatype check before pipeline execution and better error message.
3. Currently `DLClassifier` and `DLEstimator` implement `DLDataParams` separately which does not make sense.
4. DLClassifier and DLEstimator may not necessarily be generic, they can inference the datatype from model.
5. We can make `process` method private as I assume it may be revoked sometime in the future if we don't need to support 1.5+. 
6. Shall we rename the `DLClassifier` to `DLTransformer`? As Classification is only one type of the applications.

We can also add the `Evaluator` interface.

**Comment by hhbyyh** [comment]
Mark High priority since it's API change and probably be fixed before release. Feel free to downgrade it if necessary. cc @jason-dai @yiheng

**Comment by wzhongyuan** [comment]
sure, I will make a quick fix to DLClassifier. I thought we didn't want to touch the existing DLClassifier. 
Another thing we may need to consider is we may want to put modelTrain and batchShape into the constructor as well to keep consistent with DLEstimator @hhbyyh
