### ISSUE TITLE
Unable to use GPU for inference

### ISSUE THREAD

**Issue by prakal** [intel-analytics/BigDL#9418]
I am using an Arc A770 GPU and followed instructions for [Mistral (GPU)](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/mistral) and a few other models. I am monitoring my GPU load and it does not seem to use it at all. Inference for 64 tokens takes around 10s which makes me think it is only CPU. I am using conda env and have transformers-4.34.0, torch at 2.0.1a0+cxx11.abi and intel-extension-for-pytorch at 2.0.110+xpu.

Is there something elementary I am missing here? I tried using [mlc-llm](https://llm.mlc.ai/docs/index.html#getting-started) and it seems to use the GPU just fine, seeing very quick generation on Llama2.

**Comment by plusbang** [comment]
Hi @prakal , could you please try to use `sudo xpu-smi stats -d 0` to monitor your GPU memory usage? Then we could know exactly whether GPU is used.

According to our experience, as long as you follow https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/mistral to run the `generate.py`, the GPU is used during inference.

Moreover, as we mentioned [here](https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/mistral/generate.py#L58), a **warm-up** run is recommended before the actual generation.

**Comment by prakal** [comment]
Hi @plusbang, thanks for your response. I will install `xpu-smi` and report the stats. I am currently using [intel_gpu_top](https://manpages.ubuntu.com/manpages/trusty/man1/intel_gpu_top.1.html) to monitor my GPU and it shows no changes from background usage. Correct, the 9s time I got excludes that of the warm-up run.

**Comment by plusbang** [comment]
Hi @prakal, I also tried intel_gpu_top and could monitor the change during inference just like that:
<img width="416" alt="image" src="https://github.com/intel-analytics/BigDL/assets/108676127/57ff61f3-471f-479e-a8dc-e72af2efdf5d">

**BTW, I still suggest you to use `xpu-smi` to monitor your detailed GPU memory usage.**

And could you please provide more details about your experiment to better investigate the reason: 1) bigdl-llm version, 2) your hardware information, 3) input prompt and output token length, 4) experiment code ?

**Comment by prakal** [comment]
Thanks for following up @plusbang. Funnily enough, after reboot and installing and running mlc-llm, bigdl-llm became faster although my `intel-gpu-top` still doesn't register much change in Render/3D like your screenshot does.

I verified using `xpu-smi` that my GPU is indeed being used though - I can see the GPU Memory Used (MiB)  at 7578 and GPU Memory Util (%) at 47.

To keep things simple, I ran the generate.py at https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/mistral/generate.py as is:
```
python generate.py --prompt 'Tell me a story about a courier in a post apocalyptic world' --n-predict 128
```
Excluding the warm up run, this took 4.2s which seems a bit slow but certainly faster than CPU. Is this a reasonable speed for Mistral-7B-Instruct-v0.1? 
For context, I am using:
- AMD Ryzen 3700X
- Intel Arc A770 16 GB
- bigdl-llm at  2.4.0b20231109

I also converted the Mistral PyTorch model to int4 using https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/PyTorch-Models/Save-Load to see if that would speed things up, but it did not improve speeds by much.

**Comment by plusbang** [comment]
Hi @prakal, thanks for your update.
- According to your `GPU Memory Used (MiB)` information, the GPU is indeed used.
- During inference on Arc, one CPU core is used and the frequency of CPU also influences the inference speed. We have no performance data on AMD CPU + Arc, it's a little hard to judge whether reasonable, sorry for that. If you have set environment variables as we recommended [here](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model/mistral#3-run), the inference speed may be reasonable.
- Save/load operations are used to optimize loading process and have no improvement on inference.

**Comment by prakal** [comment]
Thanks for the benchmark details and for diving into this issue with me, @plusbang. CPU bottleneck here sounds reasonable. I will close this issue, since the GPU is being utilized.
