### ISSUE TITLE
GPU Transformers INT4 falcon-7b generates meaningless output

### ISSUE THREAD

**Issue by CharleneHu94** [intel-analytics/BigDL#9424]
With `bigdl-llm[xpu]==2.4.0b20231109`,  patched falcon-7b-instruct model with INT4 dtype generates meaningless output:

	Once upon a time, there was a young girl named Samantha who lived with her parents in a small town. Samantha had always dreamed of traveling the world and 
	experiencing>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>
	TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<>>TITLE<<

Using older version like `bigdl-llm[xpu]==2.4.0b20231026` has no such issue.

**Comment by hkvision** [comment]
@WeiguangHan Please verify this.

**Comment by WeiguangHan** [comment]
I can't produce this issue on my side.
![MicrosoftTeams-image (6)](https://github.com/intel-analytics/BigDL/assets/109776541/f263b317-4eef-4639-8d0c-096274210ddb)
You can refer to my pip list.
![image](https://github.com/intel-analytics/BigDL/assets/109776541/731ff473-a520-4ad9-b9a9-36006a24eeae)

**Comment by hkvision** [comment]
Verified, this issue only appears on Max 1100 (probably max series). Will look into it.

**Comment by hkvision** [comment]
@Ariadne330 Please verify which version of bigdl-llm/bigdl-core-xe starts to have this issue.

**Comment by Ariadne330** [comment]
It seems like` bigdl-core-xe==2.4.0b20231030` starts this issue

**Test Results**
|  ` bigdl-llm` | ` bigdl-core-xe/bigdl-core-xe-esimd` | Result |
|  --- | --- | --- |
|  1030 | 1030 | Abnormal | 
|  1029 | 1030 | Abnormal | 
|  1029 | 1029 | Normal output | 

Test with latest `bigdl-llm`
|  ` bigdl-llm` | ` bigdl-core-xe/bigdl-core-xe-esimd` | Result |
|  --- | --- | --- |
|  1115 | 1029 | Normal output | 
|  1115 | 1030 |  Abnormal  |

**Comment by hkvision** [comment]
@rnwang04 Seems only this PR is merged on 1030: https://github.com/intel-analytics/llm.cpp/pull/133
Could you check if this issue matters with it?

**Comment by rnwang04** [comment]
I will take a look.

**Comment by rnwang04** [comment]
I have fixed this issue by related PR, may test it again when new wheel release.
