### ISSUE TITLE
Use bigdl-llm-init instead of bigdl-nano-init in examples

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/BigDL#9451]

**Comment by qiyuangong** [comment]
We still have 55 `source bigdl-nano-init` in `llm/example`.

https://github.com/search?q=repo%3Aintel-analytics%2FBigDL+path%3A%2F%5Epython%5C%2Fllm%5C%2F%2F+nano-init&type=code

**Comment by qiyuangong** [comment]
Issue addressed by #9558
