### ISSUE TITLE
Spark Tuning With BigDL : Fails when there are multiple executors on same worker node

### ISSUE THREAD

**Issue by nsakar** [intel-analytics/BigDL#947]
I have a standalone spark cluster with 5 worker nodes. Total memory = 380g and 120 cores across the 5 physical workers. I have set  cores per executor = 4 and number of  nodes = 16 and memory per executor = 20 g and when I launch the VGG model [ coded in a zeppelin notebook code attached] , I see the executors working fine as long as they are working on the local  rdd partitions [ CIFAR 10 dataset partitioned into 16 partitions]. However , when an executor frees up and tries to execute on a remote RDD it throws an exception  java.lang.IllegalStateException: Engine.init: Thread engine is not initialized. Do you call Engine.init? Whole event stack trace is as below: The setup works fine if I  restrict number of nodes and max spark cores such that it is equal to nodes * cores per executor. Does bigdl expect only one executor per worker node?

2017-05-26 13:42:02 INFO  CoarseGrainedExecutorBackend:54 - Got assigned task 5255
2017-05-26 13:42:02 INFO  Executor:54 - Running task 13.0 in stage 649.0 (TID 5255)
2017-05-26 13:42:02 INFO  MapOutputTrackerWorker:54 - Updating epoch to 2 and clearing cache
2017-05-26 13:42:02 INFO  TorrentBroadcast:54 - Started reading broadcast variable 341
2017-05-26 13:42:02 INFO  TransportClientFactory:250 - Successfully created connection to /10.11.210.33:39410 after 10 ms (0 ms spent in bootstraps)
2017-05-26 13:42:02 INFO  MemoryStore:54 - Block broadcast_341_piece0 stored as bytes in memory (estimated size 4.3 KB, free 10.5 GB)
2017-05-26 13:42:02 INFO  TorrentBroadcast:54 - Reading broadcast variable 341 took 38 ms
2017-05-26 13:42:02 INFO  MemoryStore:54 - Block broadcast_341 stored as values in memory (estimated size 8.3 KB, free 10.5 GB)
2017-05-26 13:42:05 INFO  BlockManager:54 - Found block rdd_26_13 remotely
2017-05-26 13:42:06 INFO  BlockManager:54 - Found block rdd_21_13 remotely
2017-05-26 13:42:06 INFO  BlockManager:54 - Found block rdd_22_13 remotely
2017-05-26 13:42:06 INFO  BlockManager:54 - Found block rdd_23_13 remotely
2017-05-26 13:42:06 INFO  BlockManager:54 - Found block rdd_24_13 remotely
2017-05-26 13:42:06 INFO  BlockManager:54 - Found block rdd_25_13 remotely
2017-05-26 13:42:08 INFO  ThreadPool$:79 - Set mkl threads to 1 on thread 132
2017-05-26 13:42:08 ERROR Executor:91 - Exception in task 13.0 in stage 649.0 (TID 5255)
 See more at https://github.com/intel-analytics/BigDL/wiki/Programming-Guide#engine
	at com.intel.analytics.bigdl.utils.Engine$.default(Engine.scala:230)
	at java.lang.IllegalStateException: Engine.init: Thread engine is not initialized. Do you call Engine.init?com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$14$$anonfun$apply$19.apply(DistriOptimizer.scala:591)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$14$$anonfun$apply$19.apply(DistriOptimizer.scala:586)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1011)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1009)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-05-26 13:43:49 INFO  BlockManager:54 - Removing RDD 191

**Comment by zhangxiaoli73** [comment]
Hi, Did you call Engine.init in your code? According to the error message, I think Engine.init isn't called and ThreadPool is not initialized , so when calling Engine.default to invoke threadpool in DistriOptimizer, error happened.

**Comment by nsakar** [comment]
Yes I did. Enclosing Zeppelin notebook.

Regards

Nandini

**Comment by zhangxiaoli73** [comment]
Sorry, I can't find your code. Can you attach some code here?

**Comment by nsakar** [comment]
The code is in a zeppelin notebook . Each Cell contains as shown below:

#cell1
spark
import com.intel.analytics.bigdl.utils.Engine
val nodeNumber = 5
val coreNumber = 4
val mult = 30
val batchSize = nodeNumber * coreNumber * mult
Engine.init(nodeNumber, coreNumber, true /* env == "spark" */)

Cell2
import java.nio.ByteBuffer
import java.io.ByteArrayOutputStream
import java.nio.file.{Files,Path , Paths}
import com.intel.analytics.bigdl.dataset._
import com.intel.analytics.bigdl.dataset.image._
import com.intel.analytics.bigdl.utils.File
import scala.collection.mutable.ArrayBuffer

def loadBinaryFile(filePath: String): Array[Byte] = {
  val files = sc.binaryFiles(filePath)
  val bytes = files.first()._2.toArray()
  bytes
}

def load(featureFile: String, result : ArrayBuffer[ByteRecord]): Unit =
 {
    val rowNum = 32
    val colNum = 32
    val imageOffset = rowNum * colNum * 3 + 1
    val channelOffset = rowNum * colNum
    val bufferOffset = 8

    val featureBuffer =
    {
      ByteBuffer.wrap(loadBinaryFile(featureFile))
    }

    val featureArray = featureBuffer.array()
    val featureCount = featureArray.length / (rowNum * colNum * 3 + 1)

    var i = 0
    while (i < featureCount)
    {
      val img = new Array[Byte]((rowNum * colNum * 3 + bufferOffset))
      val byteBuffer = ByteBuffer.wrap(img)
      byteBuffer.putInt(rowNum)
      byteBuffer.putInt(colNum)

      val label = featureArray(i * imageOffset).toFloat
      var y = 0
      val start = i * imageOffset + 1
      while (y < rowNum)
      {
        var x = 0
        while (x < colNum)
        {
          img((x + y * colNum) * 3 + 2 + bufferOffset) =
            featureArray(start + x + y * colNum)
          img((x + y * colNum) * 3 + 1 + bufferOffset) =
            featureArray(start + x + y * colNum + channelOffset)
          img((x + y * colNum) * 3 + bufferOffset) =
            featureArray(start + x + y * colNum + 2 * channelOffset)
            x += 1
}
            y += 1
      }
       result.append(ByteRecord(img, label + 1.0f))
       i += 1
    }
}
 def loadTrain(dataFile: String): Array[ByteRecord] =
    {
      val allFiles = Array(
      dataFile + "/data_batch_1.bin",
      dataFile + "/data_batch_2.bin",
      dataFile + "/data_batch_3.bin",
      dataFile + "/data_batch_4.bin",
      dataFile + "/data_batch_5.bin"
      )
      val result = new ArrayBuffer[ByteRecord]()
      allFiles.foreach(load(_, result))
      result.toArray
    }

def loadTest(dataFile: String): Array[ByteRecord] =
{
    val result = new ArrayBuffer[ByteRecord]()
    val testFile = dataFile + "/test_batch.bin"
    load(testFile, result)
    result.toArray
}

Cell3
import java.nio.file.Paths
import com.intel.analytics.bigdl._
import com.intel.analytics.bigdl.dataset.DataSet
import com.intel.analytics.bigdl.dataset.image._
import com.intel.analytics.bigdl.nn.{ClassNLLCriterion, Module}
import com.intel.analytics.bigdl.optim._
import com.intel.analytics.bigdl.tensor.TensorNumericMath.TensorNumeric._
import com.intel.analytics.bigdl.utils.{Engine, LoggerFilter, T, Table}
import org.apache.log4j.{Level, Logger}
val dbfsDir = "/mnt/home/sctsuser/modelsexport/files/cifar10"
val trainMean = (0.4913996898739353, 0.4821584196221302, 0.44653092422369434)
val trainStd = (0.24703223517429462, 0.2434851308749409, 0.26158784442034005)
val testMean = (0.4942142913295297, 0.4851314002725445, 0.45040910258647154)
val testStd = (0.2466525177466614, 0.2428922662655766, 0.26159238066790275)


val trainDataSet = DataSet.array(loadTrain(dbfsDir), sc) -> BytesToBGRImg() -> BGRImgNormalizer(trainMean, trainStd) -> BGRImgToBatch(batchSize)
val validateSet = DataSet.array(loadTest(dbfsDir), sc) -> BytesToBGRImg() -> BGRImgNormalizer(testMean, testStd) -> BGRImgToBatch(batchSize)


Cell4
import com.intel.analytics.bigdl._
import com.intel.analytics.bigdl.dataset.DataSet
import com.intel.analytics.bigdl.dataset.image._
import com.intel.analytics.bigdl.nn.{ClassNLLCriterion, Module}
import com.intel.analytics.bigdl.optim._
import com.intel.analytics.bigdl.tensor.TensorNumericMath.TensorNumeric._
import com.intel.analytics.bigdl.utils.{Engine, LoggerFilter, T, Table}
import com.intel.analytics.bigdl.models.vgg._

val maxEpoch = 25

val initialModel = VggForCifar10(classNum = 10)  // 10 digit classes
val optimMethod =  new SGD[Float](learningRate = 0.01, learningRateDecay = 0.0, weightDecay = 0.0005, momentum = 0.9, dampening = 0.0, nesterov = false, learningRateSchedule = SGD.EpochStep(25, 0.5))


val optimizer = Optimizer(
  model = initialModel,
  dataset = trainDataSet,
  criterion = ClassNLLCriterion[Float]())

//optimizer.setCheckpoint("/mnt/home/sctsuser/modelsexport/vgg", Trigger.everyEpoch)
//optimizer.overWriteCheckpoint()

val trainedModel = optimizer.setValidation(Trigger.everyEpoch, validateSet, Array(new Top1Accuracy[Float])).setOptimMethod(optimMethod).setEndWhen(Trigger.maxEpoch(maxEpoch)).optimize()

Cell5
import com.intel.analytics.bigdl.optim.{LocalValidator, Top1Accuracy, Validator}
val validator = Validator(trainedModel, validateSet)
val result = validator.test(Array(new Top1Accuracy[Float]))
result.foreach(r => {
  println(s"${r._2} is ${r._1}")
})


Regards

Nandini

**Comment by zhichao-li** [comment]
Wondering how did you launch the notebook service? did you use pyspark to set the cores# ?

**Comment by zhangxiaoli73** [comment]
@zhichao-li  as we have discussed, please follow up.

**Comment by zhichao-li** [comment]
Just trying to understand the context. 
What do you mean by "when an executor frees up and tries to execute on a remote RDD it throws an exception"? 
Back to your last question.  bigdl do expect one executor per worker node which occupy the whole physical cores in standalone mode in respect of the performance, but this is not a must.

**Comment by zhichao-li** [comment]
The API you used is deprecated. please use  ```Engine.init``` instead.
node# or core# should be set via spark-submit parameters
i.e via executor-cores and total-executor-cores and then ```bigdl``` would infer those automatically.
``` 
 @deprecated(
    "See https://github.com/intel-analytics/BigDL/wiki/Programming-Guide#engine",
    "0.1.0")
  def init(nExecutor: Int,
           executorCores: Int,
           onSpark: Boolean): Option[SparkConf] = {
```

**Comment by nsakar** [comment]
So I find that if there are multiple executors spawned to complete a bigDL job and if one of the executors is freed up while some other executor has pending tasks, it will attempt to access a remote rdd partition to get busy again. And it encounters errors getting to that rdd partition.

Also after running successfully for several epochs, an executor fails sometimes with exceptions wrt netty connectivity and then aborts whole job: Please find enclosed one failed executor log.

Regards

Nandini

**Comment by nsakar** [comment]
After playing around with how to get optimum  number of nodes and executors per core, I find the following results:
1. Worker node : 5, Total Cores : 20, Cores/executor: 4, Executor memory: 20 g, Training result after 25 epochs: 78 % Top1Accuracy, Training result after 50 epochs: 85 % , Batch Size : 600, Training time 4 hours for 25 epochs , 8 hours for 50.

2. Worker node : 5, Total Cores : 68, Cores/executor: 4, Executor memory: 20 g, Training result after 25 epochs: 78 % Top1Accuracy, Training result after 50 epochs: 85 % , Batch Size : 680, Training time 4 hours for 25 epochs , 8 hours for 50.

3. Worker node : 5, Total Cores : 48 , Cores/executor: 4, Executor memory: 20 g, Training result after 25 epochs: 78 % Top1Accuracy, Training result after 50 epochs: 85 % , Batch Size : 600, Training time 4 hours for 25 epochs , 8 hours for 50.
 
4. Worker node : 5, Total Cores : 90 , Cores/executor: 10, Executor memory: 20 g, Training result after 25 epochs: 12 % Top1Accuracy,  Batch Size : 900, Training time 4 hours for 25 epochs 

I have the following questions:
1. Does BigDL expect 1 executor node per worker node?
2. Does BigDL  clone model for each executor even if they are multiple executors on same worker node?
3. Does Big dl partition input RDD by number of executors even if they are on same worker node? . Example if there are 12 executors distributed in 5 worker nodes, will there be 12 partions that each executor works on?
4. Do all cores of an executor work on the same data set partition and aggregate trained model results before broadcasting to BlockManager?
5. Where does the DistributedOptimizer code run? In the spark-submit job of the client in deployMode = client?
6. While doing these experiments I have encountered following issues:

--netty io issues between executors and driver
--OOM issues
--job failure when only 1 task fails [ no retry on another executor]

Can you provide  a best known configuration of spark standalone cluster for bigDL?

**Comment by yiheng** [comment]
The question is reposted in another issue #951
