### ISSUE TITLE
python kernel crashes when running conversion to int4

### ISSUE THREAD

**Issue by rairatne** [intel-analytics/BigDL#9485]
Hardware:
SPR with flex 140

Kernel: 5.15.47 with no AMX support
OS: Ubuntu 22

Issue:
When trying to run bigdl-llm.AutoModelCausalLm.from_pretrained with any model, with load_in_4bit=True, Python kernel crashes
2023-11-16 19:53:46,278 - INFO - Converting the current model to sym_int4 format......
failed to enable AMX
![MicrosoftTeams-image (7)](https://github.com/intel-analytics/BigDL/assets/81367619/d7cff19d-237f-4292-b1f2-22bf19c235a0)

Shouldn't the ISA selection be based on kernel support, instead of hardware platform?

Is there any minimum kernel requirement for big-dll??

**Comment by glorysdj** [comment]
please use export BIGDL_LLM_AMX_DISABLED=1 to disable AMX

**Comment by MeouSker77** [comment]
BigDL-LLM only supports detecting ISA based on hardware for now. You can use `export BIGDL_LLM_AMX_DISABLED=1` to disable AMX

**Comment by rairatne** [comment]
Thanks, this worked!!
