### ISSUE TITLE
want to understand bigdl metrics and timings that are being reported

### ISSUE THREAD

**Issue by tsantra** [intel-analytics/BigDL#9497]
Hi,

I want to understand these metrics and timings reported by bigdl. Can you please point me to the right documentation if there is any or could you please explain these to me 

<img width="727" alt="image" src="https://github.com/intel-analytics/BigDL/assets/45886215/fc9218b6-d6aa-4c7f-950f-7fa5d21e7e39">

**Comment by MeouSker77** [comment]
1. `load time` means the time of loading model.
2. `sample time` means the time of choosing one token based on the model's output. The `108` means total output length is `108`. It can be ignored in most cases.
3. `prompt eval time` means the time of generating the first token, it is related to the input length, The `837` means input length is 837.
4. `eval time` means the time of generating the rest tokens, it is related to the output length. The `107` is `total output length - 1`.

The calculation logic of first token and rest tokens is different, so we use two metrics to record them
