### ISSUE TITLE
ChatGLM3-6B low-bit model is failed to be loaded after saving

### ISSUE THREAD

**Issue by wangkl2** [intel-analytics/BigDL#9521]
Hi, I encountered an issue of not being able to load the converted INT4 ChatGLM3-6b model, attached below is the error log:
<img width="309" alt="image" src="https://github.com/intel-analytics/BigDL/assets/109344418/804c6354-6ceb-46d4-8355-e79e4233d37b">
The original downloaded ChatGLM3-6b model is pytorch_model.bin format, while the quantized model is saved in safetensors format. But load_low_bit is trying to fetch a pytorch_model.bin format model. 
<img width="319" alt="image" src="https://github.com/intel-analytics/BigDL/assets/109344418/285bd6bd-861d-409b-93b6-21d8b4fd3330">
<img width="286" alt="image" src="https://github.com/intel-analytics/BigDL/assets/109344418/76cc89b3-5b1f-4dba-8854-388287f38afa">

* HW: MTL iGPU

* Model saving code snippet:
```
model_path = "THUDM/chatglm3-6b"
model = AutoModel.from_pretrained(model_path, load_in_4bit=True, trust_remote_code=True, optimize_model=True)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model.save_low_bit(saved_model_path)
tokenizer.save_pretrained(saved_model_path)
```

* Model loading part:
```
model = AutoModel.load_low_bit(saved_model_path, trust_remote_code=True, optimize_model=True)
tokenizer = AutoTokenizer.from_pretrained(saved_model_path, trust_remote_code=True)
```

Thanks!

**Comment by leonardozcm** [comment]
Hi, I am afraid that I can not reproduce this issue, and my lowbit model is in `.bin`` format.
```
(igpu) arda@arda-arc16:~/changmin/baichuan2_memory_profile$ ls /mnt/disk1/models/chatglm3-6b-int4/
config.json  configuration_chatglm.py  generation_config.json  load_keys.json  modeling_chatglm.py  pytorch_model.bin  quantization.py  special_tokens_map.json  tokenization_chatglm.py  tokenizer_config.json  tokenizer.model
```
Actually I noticed that in recent transformers, they change the default value of `safe_serialization` from False to True, which means by default they will save models in safetensors format in recent version of transformers.

As our recommended version of transformers is 4.31.0, would you mind try this version of transformers?

**Comment by wangkl2** [comment]
@leonardozcm Thanks. Downgrading the transformer version to 4.31.0 fixes this issue. Much appreciated!
