### ISSUE TITLE
Qwen-7b-Chat 多次问答后，在16GB MTL机器会报错。

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#9615]
Qwen-7b-Chat 多次问答后，在16GB MTL机器会报错。
没有历史记录的功能。
bigdl1029

```
--------------------------------------------------
===============Get first token at 2023-12-06 22:11:09.933278
Prompt:  问：hi
答：

Response:  hello! how can i help you today? (你好！我今天能帮你做什么吗？)
------------------------------------------------
Prompt:  问：How are you?
答：

Response:  I'm fine, thank you. And you?（我很好，谢谢。你呢？）
故答案为：I'm fine, thank you. And you?。
--------------------------------------------------
Prompt:  问：Thanksgiving day
答：

Response:  ：Thanksgiving Day is on the fourth Thursday of November in the United States. It is a time for people to give thanks for the blessings they have received. Thanksgiving Day is also a time for families and friends to gather together and have a special meal. The traditional meal includes turkey, stuffing, mashed potatoes, cranberry sauce, and pumpkin pie. People also give thanks for their health, family, and friends. Thanksgiving Day is celebrated with parades, football games, and other activities. It is a very special day in the United States.
--------------------------------------------------
prompt:  问：小龙女说：我也想过过过儿过过的生活。依次解释一下这里的过过、过儿、过过的意思
答：

Response:  过过：指小龙女与杨过两人相依为命，共同生活。过儿：指杨过，小龙女的丈夫。过过的意思：指两人共同生活。
--------------------------------------------------
Prompt:  问：ABC
答：

Response:  （1）A
（2）B
（3）C
（4）A
（5）B
（6）C
（7）A
（8）B
（9）C
（10）A
（11）B
（12）C
（13）A
（14）B
（15）C
（16）A
（17）B
（18）C
（19）A
（20）B
（21）C
（22）A
（23）B
（24）C
（25）A
（26）B
（27）C
（28）A
（29）B
（30）C
（31）A
（32）B
（33）C
（34）A
（35）B
（36）C
（37）A
（38）B
（39）C
（40）A
（41）B
（42）C
（43）A
（44）B
（45）C
（46）A
（47）B
（48）C
（49）A
（50）B
（51）C
（52）A
（53）B
（54）C
（55）A
（56）B
（57）C
（58）A
（59）B
（60）C
（61）A
（62）B
（63）C
（64）A
（65）B
（66）C
（67）A
（68）B
（69）C
（70）A
（71）B
（72）C
（73）A
（74）B
（75）C
（76）A
（77）B
（78）C
（79）A
（80）B
（81）C
（82）A
（83）B
（84）C
（85）A
（86）B
（87）C
--------------------------------------------------
prompt:  问：大语言模型对未来的影响的论文
答：

text ouput
stream_chat-----input_ids: {'input_ids': tensor([[ 56007,   5122,  26288, 102064, 104949, 113756, 104126,   9370, 104734,
            198,  99590,  28311]], device='xpu:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], device='xpu:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='xpu:0')}
Exception in thread Thread-562:
Traceback (most recent call last):
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ZERO/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat-int4\modeling_qwen.py", line 1318, in generate
    return super().generate(
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\transformers\generation\utils.py", line 1538, in generate
    return self.greedy_search(
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\transformers\generation\utils.py", line 2405, in greedy_search
    input_ids = torch.cat([input_ids, next_tokens[:, None]], dim=-1)
RuntimeError: Native API failed. Native API returns: -997 (Command failed to enqueue/execute) -997 (Command failed to enqueue/execute)
```

**Comment by KiwiHana** [comment]
这是bigdl1206的报错

Prompt:  问：A
答：

Response:  （1）A
（2）B
（3）C
（4）D
（5）E
（6）F
（7）G
（8）H
（9）I
（10）J
（11）K
（12）L
（13）M
（14）N
（15）O
（16）P
（17）Q
（18）R
（19）S
（20）T
（21）U
（22）V
（23）W
（24）X
（25）Y
（26）Z
（27）A
（28）B
（29）C
（30）D
（31）E
（32）F
（33）G
（34）H
（35）I
（36）J
（37）K
（38）L
（39）M
（40）N
（41）O
（42）P
（43）Q
（44）R
（45）S
（46）T
（47）U
（48）V
（49）W
（50）X
（51）Y
（52）Z
（53）A
（54）B
（55）C
（56）D
（57）E
（58）F
（59）G
（60）H
（61）I
（62）J
（63）K
（64）L
（65）M
（66）N
（67）O
（68）P
（69）Q
（70）R
（71）S
（72）T
（73）U
（74）V
（75）W
（76）X
（77）Y
（78）Z
（79）A
（80）B
（81）C
（82）D
（83）E
（84）F
（85）G
（86）H
（87）I
token count input:  6
token count output:  512
LLM First token latency(ms):  2021.082878112793
LLM After token latency(ms/token):  138.0860497188601
LLM time cost(s):  72.58304047584534
--------------------------------------------------


anwser finish!
user stop start
user stop finish. will clear temp resource!
./static/audio_cache ****Folder deleted and recreated.


--------------------------------------------------
------language:  zh
prompt:  问：大语言模型对未来的影响的论文
答：

text ouput
stream_chat-----input_ids: {'input_ids': tensor([[ 56007,   5122,  26288, 102064, 104949, 113756, 104126,   9370, 104734,
            198,  99590,  28311]], device='xpu:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], device='xpu:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='xpu:0')}
===============Get first token at 2023-12-07 11:57:23.471820
2023-12-07 11:57:23,472 - INFO - 127.0.0.1 - - [07/Dec/2023 11:57:23] "POST /api/requestLLMSSE HTTP/1.1" 200 -
Prompt:  问：大语言模型对未来的影响的论文
答：

Response:  大语言模型对未来的影响的论文可以探讨以下主题：

1. 自然语言处理技术的发展：随着大语言模型的出现，自然语言处理技术的发展取得了显著的进展。这些技术可以用于文本生成、机器 翻译、问答系统、情感分析、文本摘要等任务。论文可以探讨这些技术的发展趋势，以及它们如何影响未来的自然语言处理应用。

2. 人工智能的普及：大语言模型的出现使得人工智能技术更加普及。这些技术可以用于各种应用，包括智能家居、智能医疗、智能交通 、智能教育等。论文可以探讨这些应用的发展趋势，以及它们如何影响未来的社会生活。

3. 数据隐私和安全：大语言模型的出现也带来了一些数据隐私和安全的问题。这些模型需要大量的训练数据，而这些数据可能包含敏感 信息。论文可以探讨这些问题，并提出相应的解决方案。

4. 伦理和道德问题：大语言模型的出现也引发了一些伦理和道德问题。例如，这些模型可能会被用于生成虚假信息，或者被用于进行恶 意攻击。论文可以探讨这些问题，并提出相应的解决方案。

5. 法律和政策问题：大语言模型的出现也引发了一些法律和政策问题。例如，这些模型可能会被用于侵犯版权，或者被用于进行网络欺 诈。论文可以探讨这些问题，并提出相应的解决方案。

6. 教育和培训：大语言模型的出现也对教育和培训领域产生了影响。这些模型可以用于提供个性化的学习体验，或者用于提供自动化的 评估和反馈。论文可以探讨这些应用的发展趋势，以及它们如何影响未来的教育和培训。

7. 社会和文化影响：大语言模型的出现也对社会和文化产生了影响。这些模型可以用于理解和翻译各种语言，从而促进跨文化交流。论 文可以探讨这些应用的发展趋势，以及它们如何影响未来的社会和文化。
token count input:  12
token count output:  383
LLM First token latency(ms):  568.3233737945557
LLM After token latency(ms/token):  127.05048172188951
LLM time cost(s):  49.10159468650818
--------------------------------------------------


anwser finish!
user stop start
user stop finish. will clear temp resource!
./static/audio_cache ****Folder deleted and recreated.


--------------------------------------------------
------language:  en
prompt:  问：ABC
答：

text ouput
stream_chat-----input_ids: {'input_ids': tensor([[56007,  5122, 25411,   198, 99590, 28311]], device='xpu:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0]], device='xpu:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]], device='xpu:0')}
===============Get first token at 2023-12-07 12:00:25.289749
2023-12-07 12:00:25,289 - INFO - 127.0.0.1 - - [07/Dec/2023 12:00:25] "POST /api/requestLLMSSE HTTP/1.1" 200 -
Prompt:  问：ABC
答：

Response:  ABC
token count input:  6
token count output:  1
LLM First token latency(ms):  289.8857593536377
LLM After token latency(ms/token):  -1233959.1979981828
LLM time cost(s):  0.4132816791534424
--------------------------------------------------


anwser finish!
user stop start
user stop finish. will clear temp resource!
./static/audio_cache ****Folder deleted and recreated.


--------------------------------------------------
------language:  zh
prompt:  问：小龙女说：我也想过过过儿过过的生活。依次解释一下这里的过过、过儿、过过的意思
答：

text ouput
stream_chat-----input_ids: {'input_ids': tensor([[ 56007,   5122, 103667,  57750,  36587,   5122, 104284, 108898,  38182,
          38182,  99261,  38182,  38182, 104103,   1773, 110298, 104136, 100158,
         106370,  38182,  38182,   5373,  38182,  99261,   5373,  38182, 105565,
         100313,    198,  99590,  28311]], device='xpu:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]], device='xpu:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1]], device='xpu:0')}
Exception in thread Thread-46:
Traceback (most recent call last):
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ZERO/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat-int4\modeling_qwen.py", line 1318, in generate
    return super().generate(
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\transformers\generation\utils.py", line 1538, in generate
    return self.greedy_search(
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\transformers\generation\utils.py", line 2362, in greedy_search
    outputs = self(
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ZERO/.cache\huggingface\modules\transformers_modules\Qwen-7B-Chat-int4\modeling_qwen.py", line 1125, in forward
    lm_logits = self.lm_head(hidden_states)
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ZERO\miniconda3\envs\audio\lib\site-packages\bigdl\llm\transformers\low_bit_linear.py", line 469, in forward
    result = linear_q4_0.forward_new(x_2d, self.weight.data, self.weight.qtype,
RuntimeError: Native API failed. Native API returns: -1 (PI_ERROR_DEVICE_NOT_FOUND) -1 (PI_ERROR_DEVICE_NOT_FOUND)

**Comment by qiyuangong** [comment]
For generation cannot stop, it maybe caused by latest issue for Qwen. https://github.com/QwenLM/Qwen/issues/686

Need to add stop words and quit generation when Qwen output stop words.

**Comment by KiwiHana** [comment]
更新到oneapi2024.0和bigdl1210后，机器不报错了。但是输入
A

红鲤鱼绿鲤鱼与驴

下雨天要大三吗


还是会出现以上不理想的重复的回答。

**Comment by Jasonzzt** [comment]
Different formats will lead to different outputs and stop words. Qwen use chatml format. https://huggingface.co/Qwen/Qwen-7B-Chat/blob/218aa3240fd5a5d1e80bb6c47d5d774361913706/generation_config.json#L2
After correcting qwen chat format and adding stop words list, the outputs become normal.
Related PR: https://github.com/intel-analytics/BigDL/pull/9642

**Comment by Jasonzzt** [comment]
Issue closed
