### ISSUE TITLE
chatglm3-6B当输入512token的时候，会直接卡住

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/BigDL#9634]
OS：windows11 MTL iGPU 32GB memory
bigdl1029 和 bigdl1206 都复现了，输入512 token，机器直接卡住无法操作
输入：
桌子有左中右3个抽屉；张三，李四，王五，赵六都看到桌子上有一袋巧克力。张三让李四和王五出门后，在赵六面前把这袋巧克力放进了右抽屉；王五回来后，张三让赵六出门去找李四，并在王五面前从左抽屉拿出一盒饼干放进中抽屉里；等李四和赵六返回，张三又让王五和赵六出去买酱油，等二人走后，他告诉李四刚才已将一盒饼干放进中抽屉；张三等了很久，发现王五和赵六还没回来，就派李四去寻找，可最后只有王五和李四回来了。王五告诉张三，一开始他们没有找到卖酱油的店，所以只好分头去买，后来赵六走丢了；回来的路上，王五碰上了李四，两人便先赶了回来。于是，张三让两人出门去找赵六；为防再次走丢，张三叮嘱李四和王五要时刻同行，就算酱油买不到，也要找回赵六。结果，李四和王五在外面找到了赵六，发现他已经买了酱油。三人觉得张三从来不出门跑腿，十分气愤，讨论并达成共识，回去见到张三后，不要告诉他买到了酱油的事情，并让王五把酱油藏到自己的背包里。等三人一同回来后，他们按照计划谎称没有买到酱油，并希望张三以后买东西也要一同出门，不能偷懒，张三答应了。当大家最后站在桌子前，四人分别写下自己知道的物品清单和物品所在位置。问，这四人写下的物品和位置信息是否一致，为什么？

**Comment by leonardozcm** [comment]
Consider this patch that put mm on bf16:
```
torch_mm_old_ = torch.matmul
def bf16_mm(a, b):
    if a.device.type == 'cpu':
        return torch_mm_old_(a, b)

    batch, q_len, A_rows, common = a.size()
    B_cols = b.size(3)
    if a.size(2) == 1:
        C = torch.empty((batch, q_len, A_rows, B_cols), device=a.device)
        torch_mm_old_(a, b, out=C)
    else:
        # print("mm xpu")
        C = torch.empty((batch, q_len, A_rows, B_cols), device=a.device, dtype=torch.bfloat16)
        torch_mm_old_(a.bfloat16(), b.bfloat16(), out=C)
        C = C.float()
    return C

class SafeMM:
    def __init__(self):
        self._old_mm = torch_mm_old_

    def __enter__(self):
        torch.matmul = bf16_mm

    def __exit__(self, *args, **kwargs):
        torch.matmul = self._old_mm

with SafeMM():
...
```

It works for me even when input length>1k.

**Comment by leonardozcm** [comment]
Seems oneapi 2024 solved this issue, will close this.
