### ISSUE TITLE
oneAPI 2024.0 not working and 2023.2 deprecated

### ISSUE THREAD

**Issue by nedo99** [intel-analytics/BigDL#9646]
Hello,

I updated oneAPI version to 2024.0 and BigDL GPU llama2 examples do not work. Here is the log:
```
File "/intel_extension_for_pytorch/__init__.py", line 93, in <module>
    from .utils._proxy_module import *
  File "/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: libmkl_sycl.so.3: cannot open shared object file: No such file or directory
```

The `libmkl_sycl.so.3` does not exist in the 2024 version, only in the 2023.2 version. The problem with that is that 2023.2 is deprecated ([see here](https://www.intel.com/content/www/us/en/developer/tools/oneapi/iot-toolkit.html)). 

What is the solution?

**Comment by jason-dai** [comment]
Try https://archlinux.org/packages/extra/x86_64/intel-oneapi-basekit/?

**Comment by MeouSker77** [comment]
you can download oneapi 2023.2 from <https://registrationcenter-download.intel.com/akdlm/IRC_NAS/992857b9-624c-45de-9701-f6445d845359/l_BaseKit_p_2023.2.0.49397_offline.sh>

**Comment by nedo99** [comment]
I see that readme is updated now so we can close this.
