### ISSUE TITLE
Enrich function doc for getParameters()

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/BigDL#966]
1) Add ```final``` to getParameters() to prevent overriding in subclass
2) We might need to add a checking to ensure not invoking this method multiple times but alert that in comments maybe enough as it would slightly effect the performance.
2) Enrich the comments with:

This function returns two tensors. One for the flattened learnable parameters flatParameters and another for the gradients of the energy wrt to the learnable parameters flatGradParameters.

__Custom modules should not override this function.__  They should instead override parameters(...) which is, in turn, called by the present function.

This function will go over all the weights and gradWeights and make them view into a single tensor (one for weights and one for gradWeights). Since the storage of every weight and gradWeight is changed, this function __should be called only once on a given network.__

**Comment by yiheng** [comment]
+1
