### ISSUE TITLE
Performance difference between driver versions

### ISSUE THREAD

**Issue by nedo99** [intel-analytics/BigDL#9701]
Hello,

I get different performance on the same hardware with Arc 770 but different driver versions. Here are the drivers:

- `[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770M Graphics 1.3 [1.3.26241]` - recommended driver per this [LINK](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/GPU). **llama2 with 128 tokens takes cca 3sec**
- `[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770 Graphics 1.3 [1.3.26918]` - **llama2 with 128 tokens takes min 6sec.**

How come there is such a big difference with newer drivers? Btw oneAPI version is the same -> 2023.2 and all other python packages are the same including bigdl, intel extension for pytorch, etc.

I tried installing back `1.3.26241` driver but apt cannot find it anymore. I followed the official GPU installation [LINK](https://dgpu-docs.intel.com/driver/client/overview.html), but that only installs the latest available drivers, but I cannot the ones recommended by BigDL.

**Comment by jason-dai** [comment]
Maybe try bigdl-llm with pytorch 2.1and oneAPI 2024.0 (https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#pytorch-2-1)?

**Comment by nedo99** [comment]
> Maybe try bigdl-llm with pytorch 2.1and oneAPI 2024.0 (https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#pytorch-2-1)?

Tried that, still 7sec. So not even near what I get with recommended drivers. And they are gone.

**Comment by nedo99** [comment]
After some more debugging, the issue lies in the kernel version. The best performance was as mentioned above with kernel 5.17.0-1020-oem. Kernel >= 6.2 executes min 6sec.

Are you aware of this? Is there a plan to reach the performance from previous kernel?

**Comment by tonym97** [comment]
So you're looking for the build that has the right level-zero driver which is this package.  intel-level-zero-gpu.

It is part of this build:

https://dgpu-docs.intel.com/releases/stable_647_21_20230714.html

You might be able to install them using these packages, but not sure what the interoperable dependencies are, hopefully apt can resolve for you

(base) tonym@lianli:~$ sudo apt-cache madison intel-level-zero-gpu
intel-level-zero-gpu | 1.3.26918.50-736~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages
intel-level-zero-gpu | 1.3.26690.36-704~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages
intel-level-zero-gpu | 1.3.26516.25-682~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages
intel-level-zero-gpu | 1.3.26241.33-647~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages

(base) tonym@lianli:~$ sudo apt-cache madison intel-level-zero-gpu-dev
intel-level-zero-gpu-dev | 1.3.26918.50-736~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages
intel-level-zero-gpu-dev | 1.3.26690.36-704~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages
intel-level-zero-gpu-dev | 1.3.26516.25-682~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages
intel-level-zero-gpu-dev | 1.3.26241.33-647~22.04 | https://repositories.intel.com/gpu/ubuntu jammy/client amd64 Packages

**Comment by jason-dai** [comment]
> After some more debugging, the issue lies in the kernel version. The best performance was as mentioned above with kernel 5.17.0-1020-oem. Kernel >= 6.2 executes min 6sec.
> 
> Are you aware of this? Is there a plan to reach the performance from previous kernel?

Yes, it's a know issue (https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#known-issues); you may refer to the tutorial (https://github.com/intel-analytics/bigdl-llm-tutorial/blob/main/ch_6_GPU_Acceleration/environment_setup.md) to downgrade the kernel to 5.19
