### ISSUE TITLE
BytesToGreyImg  transformer require label >=1

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#971]
For prediction image, the label cannot be set to bigger than 1.  If use this transformer, requirement would fail. We can create another transformer for prediction grey image ByteRecord, or make this transformer can process the prediction grey image ByteRecord.

**Comment by shane-huang** [comment]
I'm a little big confused why label>=1 should be checked in a transformer. If this transformer checks the label, how about others? IMO, we need either a seperate Label checker, or leave the label checking to the optimization process - this way no matter which transfomers are called, labels are always checked.

**Comment by yiheng** [comment]
The transformer just does some data validation... If the label < 1, the data should be invalid. Right?

**Comment by yiheng** [comment]
I think we can use some special value, e.g. -1, to mark no label. But this should be mentioned in the document.
