### ISSUE TITLE
[Quesion]: How is the speedup achieved for int4 inference?

### ISSUE THREAD

**Issue by llCurious** [intel-analytics/BigDL#9746]
Hi, very nice work of BigDL, especially for the support of int4 quantization.

The experiments shows about 3x faster throughput using int4 aginst bf16 on CPU. I wonder where is the performance boost?
-  In memory access or matmul?

It seems to me that the linear forward still computes fp x fp, i.e., conver the quantized weights to fp for the subsequent matmul. This should be slower instead. 

If my understanding is incorrect, could you help me solve the confusion？

**Comment by qiuxin2012** [comment]
We use a quantized int4 weight. During the linear forward, we will read the int4 weights and dequantized int4 to int8 by group. And we also convert the input to int8, too.
Then we can compute the matmul result of the int8 weight and int8 input with CPU instructions, such AVX512 and AMX...The outputs are floats, but the computing is using int8.

**Comment by llCurious** [comment]
Thanks to your quick response. 

Your explanation makes sense to me. I wonder:
1. Do you use the interface `ggml_compute_forward_mul_mat_q_fp32` to implement CPU-side integer matmul?
2. Have you benchmarked the speedup of using tailored CPU int8 matmul against fp16 matmul (using torch)?
3. Does the end-to-end speedup mainly comse from the int8 matmul computation improvement?

**Comment by jason-dai** [comment]
> Thanks to your quick response.
> 
> Your explanation makes sense to me. I wonder:
> 
> 1. Do you use the interface `ggml_compute_forward_mul_mat_q_fp32` to implement CPU-side integer matmul?
> 2. Have you benchmarked the speedup of using tailored CPU int8 matmul against fp16 matmul (using torch)?
> 3. Does the end-to-end speedup mainly comse from the int8 matmul computation improvement?

We used our own implementations.
