### ISSUE TITLE
When running the Yi-6B-Chat model, the same content will be output repeatedly

### ISSUE THREAD

**Issue by chengtx809** [intel-analytics/BigDL#9767]
<img width="865" alt="微信图片_20231223105253" src="https://github.com/intel-analytics/BigDL/assets/103792951/9bc207c7-34e4-44e0-b07a-908ed9ebd0b4">

**Comment by chengtx809** [comment]
我是使用的是来自https://modelscope.cn/models/01ai/Yi-6B-Chat 的未量化模型版本

**Comment by Jasonzzt** [comment]
PR created: https://github.com/intel-analytics/BigDL/pull/9778

It is recommended that you use `transformers==4.35.0`. https://huggingface.co/01-ai/Yi-6B-Chat/blob/36326f9bc1c8020e0cf29ea830ee5e6679a66a23/config.json#L23.
The following is run under the condition of `transformers==4.35.0`

The chat format of Yi is the same with Qwen. https://huggingface.co/01-ai/Yi-6B-Chat#31-use-the-chat-model
```
        prompt = f"""
            <|im_start|>system
            You are a helpful assistant.<|im_end|>
            <|im_start|>user
            {user_input}<|im_end|>
            <|im_start|>assistant
        """
```
After modifying chat format in chat.py, there's an error that can't stop the generation.

The following is the stop word of Yi model.
https://huggingface.co/01-ai/Yi-6B-Chat/blob/36326f9bc1c8020e0cf29ea830ee5e6679a66a23/tokenizer_config.json#L38
```
stop_words_ids = [tokenizer.encode("<|im_end|>")]
```
So far,  running Yi model in chat.py has been normal.

**Comment by Jasonzzt** [comment]
Hi @chengtx809, issue has been fixed. Please download the latest chat.py. https://github.com/intel-analytics/BigDL/blob/main/python/llm/portable-zip/chat.py
