### ISSUE TITLE
Product found on AWS Marketplace

### ISSUE THREAD

**Issue by kevinbleckmann** [intel-analytics/BigDL#9817]
Hello, I found this product on AWS Marketplace in an not approved Intel branded page.
https://aws.amazon.com/marketplace/pp/prodview-wd66puitgizw4?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

I own the official Intel AWS Marketplace and if this is a valid product It needs to be managed under the Official Intel account.
https://aws.amazon.com/marketplace/seller-profile?id=d1c6e336-5f6f-4234-82a8-a57463081a35

Can someone please contact me regarding this issue.  

Thank you

**Comment by jason-dai** [comment]
@jenniew please take a look.

**Comment by jenniew** [comment]
@kevinbleckmann, the product can be close now. No need to put it under the Official Intel account.

**Comment by kevinbleckmann** [comment]
Okay Thanks i will work with AWS to have that removed.
