### ISSUE TITLE
is_deepspeed_available error for a dir happen to be called deepspeed

### ISSUE THREAD

**Issue by xwu99** [intel-analytics/BigDL#9822]
https://github.com/intel-analytics/BigDL/blob/main/python/llm/src/bigdl/llm/transformers/convert.py#L61

Hi, our working directory happen to have a dir called deepspeed which is not the deepspeed package, then this line failed to find the correct deepspeed imports.

**Comment by hkvision** [comment]
Hi @xwu99 

It may not be a good practice to have a dir name in the currently working directory and it has the same name with some package installed in the environment. It may confuse the python interpreter to find the correct package.

@rnwang04 For our code, do we have any solution to better adapt to this issue?

**Comment by xwu99** [comment]
> Hi @xwu99
> 
> It may not be a good practice to have a dir name in the currently working directory and it has the same name with some package installed in the environment. It may confuse the python interpreter to find the correct package.

Thanks! As user code, it's hard to aware if the name is conflicted with 3rd party lib. This dir contains deepspeed backend code so it's also normal to name deepspeed. It's possible to adopt the same detection methods such as in deepspeed? 
https://github.com/microsoft/DeepSpeed/blob/master/accelerator/real_accelerator.py#L62

> 
> @rnwang04 For our code, do we have any solution to better adapt to this issue?

**Comment by rnwang04** [comment]
hi @xwu99 , we have tried to fixed this issue by https://github.com/intel-analytics/BigDL/pull/9838.
You maybe have a try again tomorrow as we have released new package.

**Comment by xwu99** [comment]
@rnwang04 cool! thanks for the fix!

**Comment by rnwang04** [comment]
We will close this issue now as this issue seems be fixed. You can reopen it again if needed.
