### ISSUE TITLE
How to install bigdl library from source code?

### ISSUE THREAD

**Issue by SjeYinTeoIntel** [intel-analytics/BigDL#9843]
I tried to follow this https://bigdl.readthedocs.io/en/latest/doc/UserGuide/develop.html
but seems content is different . 
after i run the script. it showing as below.
 
![MicrosoftTeams-image (6)](https://github.com/intel-analytics/BigDL/assets/78522263/fa7ad92a-59ce-4ff4-b5f9-abe69fed76b6)

what's the platform variable should put here?
and i didnt see the dllib/src/dist folder is generated.

**Comment by hkvision** [comment]
Hi,

For the second argument, it means quick build (you may check the documentation page for this), and you need to set it to be true to build the project. After the build is successful, you can get the dllib/src/dist folder.

**Comment by SjeYinTeoIntel** [comment]
> Hi,
> 
> For the second argument, it means quick build (you may check the documentation page for this), and you need to set it to be false to build the project. After the build is successful, you can get the dllib/src/dist folder.

Hi, 
From the document mentioned "The second argument is whether to quick build BigDL Scala dependencies. You need to set it to be ‘true’ for the first build. In later builds, if you don’t make any changes in BigDL Scala, you can set it to be ‘false’ so that the Scala dependencies would not be re-built."

it mentioned for first build, need to set it to be 'true'. I'm first time building. so should I set it to be 'false'?

**Comment by SjeYinTeoIntel** [comment]
Hi,
I tested with this command : bash release_default_linux_spark3.sh default false false false

it is working now. but there's no whl file in nano & serving folder.
![image](https://github.com/intel-analytics/BigDL/assets/78522263/94a4c028-c708-47e0-b483-fe83b7158f4a)
![image](https://github.com/intel-analytics/BigDL/assets/78522263/ee3e5a12-74b4-4b55-888d-8f11844d1193)

After installed chronos & friesian , pip list will showing all bigdl library as below.
![image](https://github.com/intel-analytics/BigDL/assets/78522263/982c7335-e156-4486-a159-7d7470a6275d)

May I know is this expected output for nano & serving folder didnt have whl file?

**Comment by hkvision** [comment]
> > Hi,
> > For the second argument, it means quick build (you may check the documentation page for this), and you need to set it to be false to build the project. After the build is successful, you can get the dllib/src/dist folder.
> 
> Hi, From the document mentioned "The second argument is whether to quick build BigDL Scala dependencies. You need to set it to be ‘true’ for the first build. In later builds, if you don’t make any changes in BigDL Scala, you can set it to be ‘false’ so that the Scala dependencies would not be re-built."
> 
> it mentioned for first build, need to set it to be 'true'. I'm first time building. so should I set it to be 'false'?

Sorry that this is a typo. Should be the opposite values. Fixed in https://github.com/intel-analytics/BigDL/pull/9853

**Comment by hkvision** [comment]
> Hi, I tested with this command : bash release_default_linux_spark3.sh default false false false
> 
> it is working now. but there's no whl file in nano & serving folder. ![image](https://private-user-images.githubusercontent.com/78522263/294803525-94a4c028-c708-47e0-b483-fe83b7158f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTg2MDIsIm5iZiI6MTcwNDY5ODMwMiwicGF0aCI6Ii83ODUyMjI2My8yOTQ4MDM1MjUtOTRhNGMwMjgtYzcwOC00N2UwLWI0ODMtZmU4M2I3MTU4ZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYmMxYzM0ZGE4MzI5YjFiMDk1MjI1NzE1MDk5MTRmMzJlMDc4ZTY4YjRlNzhmYTg1ZDQ0MzRiMzI4NWRmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mwm5s_8uuR-QDurxd7BVKV6TQkCuAl4G-0TUIagjeSc) ![image](https://private-user-images.githubusercontent.com/78522263/294803788-ee3e5a12-74b4-4b55-888d-8f11844d1193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTg2MDIsIm5iZiI6MTcwNDY5ODMwMiwicGF0aCI6Ii83ODUyMjI2My8yOTQ4MDM3ODgtZWUzZTVhMTItNzRiNC00YjU1LTg4OGQtOGYxMTg0NGQxMTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjY2VmNmI2N2M4MTdkOTQzNjNmNmJkNGMwNDM3ZDcyNmYwZDQ1ZDY5NjQ0Y2E0Yjk0YWNiZDU1NjI0YzQzMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L64LrA1kW8B7HNIgnLS36KkHTAR_9vXOg7NkKmVk_l8)
> 
> After installed chronos & friesian , pip list will showing all bigdl library as below. ![image](https://private-user-images.githubusercontent.com/78522263/294804088-982c7335-e156-4486-a159-7d7470a6275d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTg2MDIsIm5iZiI6MTcwNDY5ODMwMiwicGF0aCI6Ii83ODUyMjI2My8yOTQ4MDQwODgtOTgyYzczMzUtZTE1Ni00NDg2LWExNTktN2Q3NDcwYTYyNzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjlhOTY4ZDVjMzNiZjAzZmQwNzliNjQwM2YzNTFhZWY5NjM3NjdlMzJmOTcwNWJkNDJmNjFjNTE3ZjI3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wbEox82Sd8BZs70gVqzS3vL-Yfuv-apR4rbkuPBmjg)
> 
> May I know is this expected output for nano & serving folder didnt have whl file?

Since you are running the script for spark3 and nano/serving is independent of the spark version, so they are not included in this script.

They are released here FYI :) You may comment out other lines in this file and run release nano/serving only.
https://github.com/intel-analytics/BigDL/blob/main/python/dev/release_default_linux.sh#L39-L41
https://github.com/intel-analytics/BigDL/blob/main/python/dev/release_default_linux.sh#L47-L49

**Comment by SjeYinTeoIntel** [comment]
ok noted and thanks!

**Comment by hkvision** [comment]
Closing this issue. Feel free to reopen it if it is still unresolved :)
