### ISSUE TITLE
BigDL-LLM Container can't support Qwen-14B-Chat

### ISSUE THREAD

**Issue by darshanhuang1** [intel-analytics/BigDL#9905]
I run python chat.py /llm/models/models--Qwen--Qwen-14B-Chat/snapshots/cdaff792392504e679496a9f386acf3c1e4333a5/ in BigDL-LLM container (intelanalytics/bigdl-llm-xpu:2.5.0-SNAPSHOT) in NUC (12Gen i7 + A770M). The error message is

 /usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python exision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did yfrom source?
  warn(
Sorry, the model you entered is not supported in installer.

**Comment by liu-shaojun** [comment]
Hi @darshanhuang1, it seems the error message you provided is not complete, and I cannot reproduce the issue from my side with the latest docker image.

You can have a try with the latest docker image
```
docker pull intelanalytics/bigdl-llm-xpu:2.5.0-SNAPSHOT

export DOCKER_IMAGE=intelanalytics/bigdl-llm-xpu:2.5.0-SNAPSHOT
export MODEL_PATH=/xxx/xxx/models/path

sudo docker run -itd  --net=host  --device=/dev/dri   --memory="64G" --name=llm_container --shm-size="16g" -v $MODEL_PATH:/models  $DOCKER_IMAGE

docker exec -it llm_container bash

cd /llm
python chat.py --model-path /models/Qwen-14B-Chat/
python chat.py --model-path /models/chatglm2-6b/
```

**Comment by darshanhuang1** [comment]
it works now, thanks.
