### ISSUE TITLE
Check size when adding module to container

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#992]
If user put the following two modules together
```scala
Sequential[Float]()
    .add(Linear(3, 4))
    .add(Linear(3, 4))
```
Although the sizes do not match, the exception will be thrown till runtime. It's better if there's a way to report errors when defining the model.

Each module may need to tell how to map an input size to output. The container may have an input shape, and if it's set, when some modules are added to the container, the shape will check.

```scala
Sequential[Float]().setInputShape([-1, 3])  // -1 means batch
    .add(Linear(3, 4))
    .add(Linear(3, 4))  // throw an shape mismatch error
```

**Comment by zhichao-li** [comment]
Each layer should have methods/fields like: `get_output_shape`, `get_input_shape`, then we can inference the shape easily.

**Comment by yiheng** [comment]
There's a Keras style API. Users can use that if they want to check shape info
