### ISSUE TITLE
Output of GGUF Mixtral model on SPR01 is incorrect

### ISSUE THREAD

**Issue by liu-shaojun** [intel-analytics/BigDL#9929]
## Issue description

bigdl-llm==2.5.0b20240117, the output of GGUF Mixtral model is incorrect. 

<img width="360" alt="image" src="https://github.com/intel-analytics/BigDL/assets/61072813/4256ef8f-f7f4-4371-9673-4c9fa5d102a2">

## To reproduce

I followed this README to reproduce it:

https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/CPU/HF-Transformers-AutoModels/Advanced-Quantizations/GGUF/README.md

On SPR01

```bash
conda create -n llm python=3.9 # recommend to use Python 3.9
conda activate llm

pip install --pre --upgrade bigdl-llm[all] # install the latest bigdl-llm nightly build with 'all' option
pip install transformers==4.36.0  # upgrade transformers

python ./generate.py --model '/home/llm/models/gguf/mixtral-8x7b-v0.1.Q4_0.gguf' --prompt 'I believe the meaning of life is'
```

**Comment by Uxito-Ada** [comment]
Fixed in #9930
<img width="743" alt="image" src="https://github.com/intel-analytics/BigDL/assets/60865256/992a3af6-1490-4629-b7ac-42acb074daba">
