### ISSUE TITLE
how to judge the model is on xpu

### ISSUE THREAD

**Issue by K-Alex13** [intel-analytics/BigDL#9958]
我当前遇到了问题，就是将model 与input放到xpu上结果还是说俩个不在同一个上，不确定怎么做。
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, xpu:0 and cpu! (when checking argument for argument index in method wrapper_XPU__index_select)

**Comment by rnwang04** [comment]
Hi @K-Alex13 , could you please share your test code with us so that we can try it and see whether we can reproduce your error : )

**Comment by K-Alex13** [comment]
I fix this problem by change the mode url.  The original problem seems that it will download file from HuggingFace and use the dowloaded file as modeling Baichuan file.  That is why inputs id not on cpu.

**Comment by rnwang04** [comment]
Glad to hear you have solved it, then I will merge this issue first : )
